### ISSUE TITLE
Lieferschein erstellen

### ISSUE THREAD

**Issue by Lars-Mue** [selectline-software/selectline-api#100]
Hallo zusammen, 

des weiteren habe ich beim erstellen eines Lieferscheines das Problem, dass das beim erstellen der Belegpositionen ich einen Fehler bekomme wenn ich mehr als 1 Stück des Artikels in der Position verwenden möchte. 
Mit der Menge 1 funktioniert aber alles. 
Der Artikel ist auch auf Bestand, sodass auch eine Menge von 2 / 3.. kein Problem darstellen sollte. 
`{
	"calculationPrice":0,
	"articleNumber":"DIV",
	"orderNumber":null,
	"quantityUnit":null,
	"CustomText1":"Be1",
	"Name":"Kohlen",
	"storeInformation":[
		{
			"Quantity":2,
			"ArticleNumber":"DIV",
			"Warehouse":"Laden"
		}
	],
	"unitPrice":4.2,
	"discountPercent":0,
	"discountPercent2":0,
	"totalPrice":0.0,
	"taxRate":0
}`

Erhaltene Fehlermeldung : 

`{
  "StatusCode": "BadRequest",
  "ResponseCode": "42-036",
  "Message": "CreateDocumentErrorException",
  "Details": {
    "ResponseDetails": "Fehler beim Lagern. Offene Menge: 2,00",
    "ResponseType": "CreateDocumentError",
    "ErrorCode": -1
  }
}`

Vielen Dank für eine baldige Antwort. 

Grüße

**Comment by MatthiasGuse** [comment]
Hallo,

bitte geben Sie "CalculatedQuantityValue" mit der Gesamtmenge mit an. Dann wird es funktionieren. Weshalb das so ist bzw. ob die Pflicht in der Doku fehlt, muss ich noch klären. Sicherlich macht es an der Stelle auch Sinn die wikrliche Mengeneinheit statt "null" zu übergeben, damit das Feld in der Wawi nicht leer ist. 

Beste Grüße

**Comment by Lars-Mue** [comment]
Hallo Herr Guse, 

super dass hat So funktioniert. 
Vielen Dank
