### ISSUE TITLE
Fehler: Belegpositionen Abrufen

### ISSUE THREAD

**Issue by Grewamor** [selectline-software/selectline-api#101]
Version: 21.1.1
Request URL: https://sql02/slmobileApi/Documents/FAU20000020/Positions

```
{
  "StatusCode": "InternalServerError",
  "ResponseCode": "42-000",
  "Message": "ArticleKind.FromValue()\r\nParametername: value\r\nDer tatsächliche Wert war .",
  "Details": null
}
````

Was sagt dieser Fehler? Wo kann ich ansetzen?

**Comment by MatthiasGuse** [comment]
Ich vermute, dass das am Inhalt des Belegs liegt. Welche Zeilentypen verwenden Sie im betroffenen Beleg? Welche Stücklistentypen haben die Artikel dahinter?

Evtl. lässt sich der betroffene Artikel besser ermitteln indem Sie den Beleg kopieren, erneut per API abfragen und eine Position nach der anderen testhalber löschen, bis der Fehler nicht mehr auftritt.

Viele Grüße

**Comment by Grewamor** [comment]
Vielen Dank für die Hilfestellung. Beim Artikel stand bei Stückliste nichts drin. Nun klappt es.
