### ISSUE TITLE
vermisse Geschäftspartner Nummern

### ISSUE THREAD

**Issue by srotter** [selectline-software/selectline-api#102]
Sehr geehrte Damen und Herren,

bei der Abfrage von allen Kunden\Lieferanten\Interessenten ist mir aufgefallen, dass bei der Abfrage kein Feld mit der Kundennummer, Lieferantennummer oder Interessentennummer zurückgegeben wird.
In meinen Projekt benötige ich die Funktion einen Kunden (erkennbar anhand der Kundennummer) zum Datensatz zu verknüpfen. Hierzu soll der Nutzer eine Auflistung der Kunden bekommen um selbst wählen zu können. Übersehe ich hier einfach die Möglichkeit per GET Customers die Kundennummern zu bekommen?
 
Das Feld FinancialAccountId ist übrigens keine Lösung für mich, da die FIBU-Kontennummer von der tatsächlichen Kundennummer abweichen kann (bei Lieferanten und Interessenten ebenfalls)

Ich bedanke mich im Voraus, freue mich auf Ihre Antwort und verbleibe...

Mit freundlichen Grüßen
Sebastian Rotter

**Comment by MatthiasGuse** [comment]
Hallo,

die Information ist im Element "Number" zu finden.

Viele Grüße

**Comment by srotter** [comment]
Hallo,

vielen Dank für die schnelle Antwort. Ich habe mir meinen Quelltext noch einmal angesehen, da bei mir das Feld Number immer leer blieb. Es wurde durch das Feld Number der PostOfficeBox immer mit NULL überschrieben. Nun funktioniert alles wunderbar.
