### ISSUE TITLE
Übertrag Kunde / Lieferant 

### ISSUE THREAD

**Issue by Torchok19081986** [selectline-software/selectline-api#103]
Hallo, ich habe ein Problem beim Übertrag der Kunden / Lieferanten von einem Mandanten auf den anderen.
bis jetzt wars es so, dass wenn man den Customer / Supplier übergeben hat, so wurde nur die felder neuübertragen oder aktualisiert. Seit der Version 20.3.10 wird das Ziel Kunde / Lieferant in seiner Gesamtheit überschrieben. Wenn z.B. ein Kunde 
als Quelle Telefonnummer2 wert nicht hatte oder leer ist.  und das Ziel mit selben Nummer hat, so wird das übertrag von 1. Kunden das Wert vom Feld Telefonummer2 überschreiben.  Gibt es die Möglichkeit dieses Verhalten irgendwie zu ändern oder so anzupassen, dass es die bestehende Werte nicht auf NULL oder leer aktualisiert werden? Vielen Dank schon mal im Voraus.

**Comment by MatthiasGuse** [comment]
Hallo,

hier ein paar Fragen um das nachvollziehen zu können. Mit welcher Version vergleichen Sie die 20.3.10? Welche Routen benutzen Sie? Bitte schicken Sie ein Beispiel JSON des Inhalts, den Sie zum Update der Adresse benutzen.

Grüße

**Comment by Torchok19081986** [comment]
Hallo, bis jetzt war im Einsatz Version 19.X und 20.3.X . Hier ist das Verhalten sagen wir normal. Die Daten werde nicht überschrieben. Nach dem Update von 20.3.X auf 20.3.10 ist dieses Verhalten nicht mehr vorhanden.
Wenn Sie mit "Routen" die Adressen meinen, dann sind es folgende  -  Customers/{customernumber} mit PUT oder POST und selben sind für das Supplier. 
[JsonBsp.txt](https://github.com/selectline-software/selectline-api/files/6284246/JsonBsp.txt)
So schaut das Json Bsp output bei uns beim Serialisieren der Kunden daten nach dem Einloggen der 2. Benutzer ins ziel Mandanten aus.

**Comment by MatthiasGuse** [comment]
Schicken Sie den Inhalt der angehangenen JSON als Post zur Aktualierung einer Adresse?
Falls ja, dürfen Sie nur die Elemente übermitteln, die Sie auch wirklich aktualisieren möchten. 

Viele Grüße

**Comment by Torchok19081986** [comment]
Hallo, das sind die Daten aus Muster Mandaten , welche ich zum einen anderen , zuvor gewechselten Mandanten, übertragen möchte. Wie man im Json bzw. Text Datei sieht, so ist dort die Telefonnummer2 nicht belegt bzw hat der Wert "null". Ist  das Wert  im Ziel Telefonnummer2 Feldes nicht leer, so wird es derzeit überschrieben, Heute noch mal genaust nachvollzogen. Kann sein, dass der PUT Anforderungen IMMER das gesamt object von Customer überschreibt?

**Comment by MatthiasGuse** [comment]
Es ist korrekt, dass der vorhandene Inhalt geleert wird, wenn Sie NULL übermitteln. Es ist gewünscht, dass Werte auch auf NULL gesetzt werden können. Anhand der Änderungshistorie kann ich keine Änderung an diesem Verhalten nachvollziehen.

Sie dürfen nur die Werte übermitteln, die Sie auch wirklich verändern wollen.

Viele Grüße

**Comment by Torchok19081986** [comment]
Guten Morgen , danke für die ausführliche Information.  
Gibt es info in der API wie man einzelne Werte ans Zielmandanten beim Kundennummer übermittelt? Bis jetzt haben wir das ausgesuchten Kunden / Lieferanten anhand von Nummer via Json als Customer object desserialisiert via JsonConvert.DeserliaseObject(Kunden oder Lieferaten object), und dann via Put aktualisiert oder via Post angelegt.

**Comment by VivienSchuboth** [comment]
Guten Tag,

Beispiele zu einzelnen Funktionalitäten befinden sich in der Postman Collection für die SelectLine API.
Diese sind ebenfalls hier im GitHub-Forum zu finden.

Ein Beispiel für das Anlegen von einem Kunden wäre:
```
POST {{url}}/Customers
{
    "FirstName": "Wilhelm Tölke UNiversität",
    "City": "Stenkelfeld",
    "InternationalLocationNumber": "GerümpelLieferNummer"
}
```

Sie können natürlich auch gerne zuerst Ihre bisherigen Daten auslesen und damit Ihr Objekt befüllen.
Doch nutzen Sie wirklich nur die Properties und deren Werte, die Sie auch wirklich aktualisieren wollen.
Jedes Property, welches Sie in Ihrem Objekt explizit setzen, wird in der SelectLine API als bearbeitet gekennzeichnet und daher aktualisiert.
Wenn Sie ein Property nicht aktualisieren wollen, setzen Sie es nicht. Lassen Sie es einfach weg.

Beste Grüße,
Vivien Schuboth
