### ISSUE TITLE
Passwort des API Benutzers über API ändern

### ISSUE THREAD

**Issue by chucky2002** [selectline-software/selectline-api#104]
Wie kann ein Nutzer über die SL.API sein Passwort ändern?

Wie entwickeln gerade eine App und wollen dazu die Nutzerverwaltung der SL.API nutzen. Dazu bekommt jeder Nutzer der App einen eigenen SL.API -Nutzer angelegt mit dem er sich anmelden kann und der mit seinem SelectLine Nutzer verknüpft ist. 
Wie kann der Nutzer sein eigenes SL.API Passwort ändern? Ich habe dazu keinen passenden REST-Call gefunden und ein Login über SL.Moible Oberfläche ist auch nicht möglich.

**Comment by MatthiasGuse** [comment]
Hallo,

so eine Funktion steht bisher nicht zur Verfügung.

Viele Grüße
