### ISSUE TITLE
Error bei Abfrage von Extra Tabellen mithilfe der API 

### ISSUE THREAD

**Issue by fb199** [selectline-software/selectline-api#105]
API Version:  20.3.10
Programmiersprachen: PHP 

Beim Abruf von Daten aus den ExtraTabellen mit der auto-generierten Funktion "extraTableRead" kommt es zu Problemen. Der Abruf scheint zu funktionieren gibt aber kein Array sondern einen String zurück.  Ist dieses Problem auch schon bei anderen Partnern aufgetreten?

**Comment by VivienSchuboth** [comment]
Guten Morgen,

bislang ist dieses Problem noch nicht aufgetreten bzw. zu uns getragen wurden.
Kann die Rückgabe als String vielleicht mit dem Tool zusammenhängen, welches Ihnen diese Funktion automatisch generiert?

Beste Grüße,
Vivien Schuboth

**Comment by VivienSchuboth** [comment]
Guten Tag,
hat sich die Problematik für Sie bereits erledigt?

Wenn ja, würde ich Sie bitten den Issue zu schließen.
Ansonsten melden Sie sich gerne zurück.

Beste Grüße
