### ISSUE TITLE
Belegübergabe/Zusammenführen von Belegen

### ISSUE THREAD

**Issue by aameyer** [selectline-software/selectline-api#106]
Hallo,
ich habe hier eine Kundenanforderung, bei der ich nicht sicher bin, inwieweit die API dies abbilden kann:

Zu bereits bestehenden Wareneingängen sollen über die API Eingangsrechnungen angelegt werden. Dabei sollen sowohl Teilmengen aus den einzelnen Wareneingängen übernommen werden als auch mehrere Wareneingänge in einer Rechnung zusammengefasst werden. Die Belegkette muss dabei erhalten bleiben. Wir benötigen also über die API die Funktion "Beleg übernehmen von" aus der WaWi-Oberfläche für das Zusammenführen, "Beleg übergeben" reicht hier nicht aus.

Soweit ich dies sehe, bildet die Route POST /Documents/{documentKey}/Successors jedoch nur die Funktion "Beleg übergeben" ab, da hier als Parameter nur der Belegtyp des Zielbeleges übergeben werden kann, nicht aber die Belegnummer des Zielbelegs - daher können so auch keine Belege zusammengeführt werden.

Habe ich hier noch eine andere Route übersehen, oder existieren hier ggf. noch weitere undokumentierte Parameter, um Positionen aus verschiedenen Belegen in einen gemeinsamen Zielbeleg zu übergeben? 

Vielen Dank und freundliche Grüße

**Comment by VivienSchuboth** [comment]
Guten Morgen,

diese Funktionalität ist leider noch kein Bestandteil der SelectLine API. 
Sie können diesen Wunsch jedoch gerne in das UserVoice-Forum stellen.

Mit freundlichen Grüßen
