### ISSUE TITLE
Memo-Feld in Extradialog setzen

### ISSUE THREAD

**Issue by LandoWalter** [selectline-software/selectline-api#107]
Hallo zusammen,

ich versuche ein Memo-Feld in einem Extradialog zu setzen, bekomme es allerdings nicht gefüllt.
Meine Felder im Extradialog (Tabellenname: „LagerLog“ bzw. „XLagerLog“):
![image](https://user-images.githubusercontent.com/82435968/114887833-12121000-9e09-11eb-9be2-0f6b88e4e159.png)
 

API-Aufruf:
https://xxx/ExtraTable/XLagerLog 
```
{
    "IdentifierName": "Id",
    "Fields": {
        "_KUERZEL": "xx",
        "_METHODE": "POST",
        "_URL": "https://xxx/ExtraTable/XLagerLog",
        "_REQUEST": "HIER MEMOFELDTEXT"
    }
}
```

Allerdings finde ich in meinem Memo-Feld _REQUEST keine Daten.
![image](https://user-images.githubusercontent.com/82435968/114887904-1d653b80-9e09-11eb-8cb3-9ff18e5d2154.png)

 
Auch mit dem Pfad: https://xxx/ExtraTable/XLagerLog_Extra bekomme ich nicht mein gewünschtes Ergebnis, sondern folgende Fehlermeldung:
```
{
    "StatusCode": "InternalServerError",
    "ResponseCode": "05-000",
    "Message": "Ungültiger Spaltenname \"AngelegtAm\".\r\nUngültiger Spaltenname \"AngelegtVon\".",
    "Details": null
}
```

SelectLine: 20.3.12
SL-Mobile: 20.3.10

**Comment by VivienSchuboth** [comment]
Guten Morgen,

das Problem konnte ich nachvollziehen. 
Zur Version 21.2 können Sie die Fehlerbehebung erwarten.

Mit freundlichen Grüßen
