### ISSUE TITLE
Erstellen eines neuen Auftrages

### ISSUE THREAD

**Issue by ws-doubleus** [selectline-software/selectline-api#11]
Warum wird beim Erstellen einer neuen Belegposition (/Documents/{documentKey}/ArticleItem) nicht auch der Einzelpreis und die Artikelbezeichnung automatisch im Beleg ausgefüllt, wenn man beim Request nur die Artikelnummer übergibt (so wie es auch in der SelectLine-Software ist)?
Mache ich etwas falsch, oder MUSS ich wirklich alle Informationen (Einzelpreis, Artikelbezeichnung, ...) im Request bereitstellen?

**Comment by SteveSteglitz** [comment]
Was bedeutet denn "nur die Artikelnummer"? Wie sieht denn der Body bei Ihnen aus? 

Folgender POST legt eine Artikelposition an, analog der Positionsanlage in der Warenwirtschaft. Hier wird auch der Einzelpreis und die Artikelbezeichnung automatisch übernommen. 
`
POST 'http://localhost:9000/Documents/FAU532/ArticleItem' 
{
  "CalculatedQuantityValue": 3,
  "ArticleNumber": "100001"
}`

Wenn Sie natürlich andere Eigenschaften mit einem Wert (auch Leerstring oder 0) senden, werde diese für die Position verwendet.

Ich hoffe ich konnte Ihnen helfen. Falls das Problem weiterbesteht, benötigen wir einmal den Body Ihres Beispiels.

**Comment by ws-doubleus** [comment]
Vielen Dank für den Hinweis.
Der Fehler lag bei mir: ich hatte in meiner Klasse auch die Properties UnitPrice und Name definiert - deshalb wurde sie mit den Standard-Werten "" und 0 befüllt!
