### ISSUE TITLE
Doku / Response verbessern

### ISSUE THREAD

**Issue by Logic-Bits** [selectline-software/selectline-api#111]
Hallo,

bitte schreibt doch in die Details rein dass der Login Fehlschlägt via API wenn der Appkey nicht passt (z.B. durch Demoinstallation).

Danke!

**Comment by VivienSchuboth** [comment]
Guten Morgen,

meinen Sie hierbei die SelectLine API Hilfeseite oder die Response des Logins?
Wo fehlen Ihnen diese Informationen?

Vorab noch eine Info dazu:
 
Aus sicherheitstechnischen Gründen werden genaue Fehlerursachen bei einem Login nicht mehr in den Details ausgegeben. Stattdessen nutzen Sie bitte die zurückgesendeten Response Codes, zu denen Sie Näheres auf unserer [Hilfeseite](https://demo.slmobile.de/demoApi/Help/ResponseCodes) finden:
Dort entdecken Sie dann auch auf den ResponseCode für invalide Appkeys:
> 039 | AppKeyInvalidException | Der verwendete AppKey ist nicht gültig.

Beste Grüße,
Vivien

**Comment by Logic-Bits** [comment]
Guten Morgen,

ist jetzt schon wieder eine Zeit her, ich war der Meinung bei einer Demo Installation der SL und API wurden keine Fehlercodes zurückgegeben. Falls das jetzt doch funktioniert dann kann des Ticket geschlossen werden.

Danke
