### ISSUE TITLE
Belegübergabe, "TCP-Anbieter: Eine vorhandene Verbindung wurde vom Remotehost geschlossen."

### ISSUE THREAD

**Issue by Benziner** [selectline-software/selectline-api#112]
Hallo zusammen,

https://x.x.x.x:413/slmobileApi/Documents/F14/Successors

Ich wollte einen Beleg übergeben von Auftrag (F) Beleg 14 an eine Rechnung (R). 

### Hier die JSON zur Übergabe: 
{"documentKindDestination":"R","Positions":[{"identifier":"60D8E36D-4AB1-46E
E-B1E3-5CFEB8376AE5","articleNumber":"DAL-KIM-Basic","quantity":1},{"identif
ier":"D126C265-6C79-44F6-9644-018268EEFAEF"}]}

In den meisten Fällen erhalte ich diese Response, dann wurde die Position korrekt übergeben.
### RESPONSE
{
  "documentKind": "R",
  "documentNumber": "RE2021/008"
}

### In manchen seltenen Fällen erhalte ich allerdings diese Response: 
Fehler 400
TCP-Anbieter: Eine vorhandene Verbindung wurde vom Remotehost geschlossen.

Wenn ich den POST dann genau gleich erneut ausführe, funktioniert es meistens. 
Aus welchem Grund wird dieser 400er-Fehler ausgegeben und wie kann ich das abfangen? Sind evtl. zu viele Verbindungen offen o.ä.?

**Comment by Benziner** [comment]
Version 20.3.6

**Comment by MatthiasGuse** [comment]
Aktuell ist die Version 21.1.4 verfügbar. Im Verlauf sind mehrere Fehlerbehebungen enthalten, bei denen es denkbar ist, dass Ihr beschriebenes Verhalten behoben wurde.

Sofern es Ihnen möglich ist, aktualisieren Sie bitte auf die aktuellste Version und testen das Verhalten erneut.

**Comment by Benziner** [comment]
`Details: {"StatusCode": "BadRequest",  "ResponseCode": "42-036",  "Message": "CreateDocumentErrorException",  "Details": {    "ResponseDetails": "Shared Memory-Anbieter: Kein Prozess ist am anderen Ende der Pipe.",    "ResponseType": "CreateDocumentError",    "ErrorCode": -1 }}`

Dieser Fehler tritt mittlerweile auch gehäuft auf. Könnte das auch mit einem Update gelöst werden oder gibt es hier eine andere Ursache? Der Kunde wollte momentan noch kein Update aufspielen, um einen langwierigen Testprozess zunächst zu vermeiden.

**Comment by MatthiasGuse** [comment]
Hallo, ja das ist korrekt. Auch dieses Problem wird höchst wahrscheinlich durch ein Update behoben. Mittlerweile ist die Version 21.2.1 aktuell.

**Comment by Benziner** [comment]
Guten Morgen, wir haben das Update durchgeführt auf 21.2.1, leider bleibt das Problem bestehen. Immer wieder kommt die Fehlermeldung 400, Shared Memory-Anbieter: Kein Prozess ist am anderen Ende der Pipe.

**Comment by MatthiasGuse** [comment]
Hallo,

bitte prüfen Sie ob alle Tests im Mobile Manager grün sind. Falls ja, schicken Sie bitte die Logfiles aus dem Verzeichnis `C:\ProgramData\SelectLine Software\logs\` unter Angabe des Zeitpunkts des Auftretens des Fehlers an support@selectline.de
Wir schauen uns das im Detail dann an.

Viele Grüße

**Comment by VivienSchuboth** [comment]
Guten Tag,

ich wollte mich erkundigen, ob sich dieses Problem inzwischen gelöst hat?
Falls ja, würde ich Sie bitten den Issue zu schließen.

Falls das Problem noch besteht, freue ich mich von Ihnen zu hören.

Danke im Voraus!

Beste Grüße,
Vivien Schuboth

**Comment by Benziner** [comment]
Guten Tag,

Das Problem besteht weiterhin. 
Vom Support habe ich damals folgende Rückmeldung bekommen: 

```
Sehr geehrter Herr Schrodt,

die Fehlermeldung ist uns nicht weiter bekannt.
Wir vermuten, dass die Verbindung mit dem Server gestört ist/war.
https://docs.microsoft.com/de-de/sql/relational-databases/errors-events/mssqlserver-233-database-engine-error?view=sql-server-ver15

Diese Fehlermeldung wurde u. a. in einem anderen Zusammenhang gemeldet und
kommt nicht aus der SelectLine sondern direkt vom SQL-Server.

Ein Client, der eine Verbindung mit SQL Server herstellt, kann mit diesem Named Pipe-Fehler konfrontiert werden, wenn eine Verbindung mit SQL Server hergestellt wird und der Server keine Unterstützung für Named Pipes aktiviert hat, auch wenn andere Protokolle wie z. B. TCP/IP verfügbar sind.

Wenn Named Pipes auf dem Server nicht aktiviert sind, werden Clientverbindungsversuche, die Named Pipes verwenden, zurückgewiesen. Dieser Fehler kann in zwei Varianten auftreten:

- Der Client versucht, ausschließlich mit Named Pipes eine Verbindung herzustellen, und das Named Pipes-Protokoll ist auf dem Server nicht aktiviert.

- Der Client versucht, mit einem beliebigen verfügbaren Protokoll eine Verbindung herzustellen, Named Pipes werden jedoch vor TCP in der Clientprotokollreihenfolge aufgelistet.

..."

Vielleicht hilft das ja irgendwie weiter. Zu der ähnlichen Anfrage erhielten wir leider kein Feedback vom Fachhändler.
```

Die Lösung im oben genannten Link haben wir versucht, der SQL Server war auch entsprechend schon eingestellt. Das Problem ist ja aber auch, dass es bei allen REST API Funktionen, die wir sonst so verwenden bei dem Kunden, problemlos funktioniert, nur bei der Belegübergabe funktioniert es eben nur ca. zu 50%. 

Die hauptsächliche Fehlermeldung ist mittlerweile: 
`400, Shared > Memory-Anbieter: Kein Prozess ist am anderen Ende der Pipe.`

WIr haben auch noch 2, 3 Dinge versucht, die wir im Internet dazu gefunden haben, leider ohne Erfolg bisher. (SQL Server 2016). Leider ist mir nicht ganz klar, ob die SelectLine REST API vielleicht eine bestimmte Konfiguration des SQL Servers benötigt und wenn ja welche. Vielleicht wissen Sie hierzu noch etwas? 

Viele Grüße

Jens Schrodt

**Comment by Micha-Richter** [comment]
Ich habe heute aus heiterem Himmel heraus genau dasselbe Problem wie oben beschrieben gehabt (TCP-Anbieter: Eine vorhandene Verbindung wurde vom Remotehost geschlossen.).

Nach dem Deaktivieren der im o.a. MS-Artikel (https://docs.microsoft.com/de-de/troubleshoot/windows-server/identity/apps-forcibly-closed-tls-connection-errors) angesprochenen Verschlüsselungssuiten lief derselbe Aufruf wieder sauber durch.
Kann natürlich Zufall gewesen sein, einen Versuch ist es aber vielleicht wert.
