### ISSUE TITLE
Response POST ./ExtraTable/{tableName}

### ISSUE THREAD

**Issue by ThePholph** [selectline-software/selectline-api#116]
Hallo,

ich habe da mal eine wichtige Anregung: Es wäre gut, wenn man beim POST den Identifier des neuen Datensatzes zurückgeliefert bekommen würde. Dies würde bei der Entwicklung vieles vereinfachen!

Danke.

**Comment by VivienSchuboth** [comment]
Guten Tag,
danke für das Feedback!
Das "Feature" bzw. die Fehlerbehebung wurde mit der V21.2 behoben.

Beste Grüße
