### ISSUE TITLE
Beleg erstellen per API

### ISSUE THREAD

**Issue by Lars-Mue** [selectline-software/selectline-api#119]
Hallo zusammen, 

seit der neuen Version ist es nicht mehr möglich selbst generierte Belege per API (z.b Belegtyp J) 
zu erstellen. 
Ist schon bekannt wann dies wieder Möglich ist,
da wir ansonsten bei vielen Kunden kein Update der Version durchführen können.  

Das ganze hat für uns wirklich höchste Priorität .

Viele Grüße

**Comment by davidhommel** [comment]
Wir haben das gleiche Problem auch. Der DocumentCreate-Aufruf schlägt gänzlich fehl und wirft undefinierbare Fehlermeldungen zurück... 😞

**Comment by MatthiasGuse** [comment]
Hallo,

das beschribene Verhalten ist bei mir nicht nachvollziehbar (Version 21.1.0 / 21.1.4). Welche Version setzen Sie ein?

Mit der Version 21.1.2 wurde ein Fehler behoben, der undefinierte Abbrüche zur Folge haben konnte. Aktuell ist die Version 21.1.4 verfügbar.

Sofern es Ihnen möglich ist, aktualisieren Sie bitte auf die aktuellste Version und testen das Verhalten erneut.

Sollte das Verhalten mit der aktuellen Version weiterhin bestehen, stellen Sie bitte die Einstellungen des Belegs (Screenshot Belegedefinition) zur Verfügung bei dem es bei Ihnen nicht funktioniert.

Viele Grüße
