### ISSUE TITLE
Error Message while using Post../documents/.../Print

### ISSUE THREAD

**Issue by Lars-Mue** [selectline-software/selectline-api#12]
I want to print a document to a file. 
I'm trying to call the API from my client with the following body:

{
NumberOfCopies:1,
"MasterName":"APack"
"PrintTarget":"File"
}

It doesn't matter which print target I choose, I always get an error response.

{
  "StatusCode": "InternalServerError"
  "ResponseCode": "42-000""
  "Message": "Client.Send failed. See InnerException,"
  Details: null 
}
I think my header is  correct . The document number exists and the document type is also correct.                     How do I define the Print Target correctly to print the receipt on my client into a file.

Request:  https://...../slmobileapi/Documents/F20-00201/Print

**Comment by VivienSchuboth** [comment]
Hello,
you must enclose the key NumberOfCopies within quotations marks:   
```
{
"NumberOfCopies":1,
"MasterName":"APack"
"PrintTarget":"File"
}
```
And make sure the name of the printing template is "APack".

If there are still any errors, please write back and we get right back to you.

Best regards,
Vivien

**Comment by Lars-Mue** [comment]
Hello, i already got that. The name of the printing template  is correct.
```
 {
"NumberOfCopies":1,
"MasterName":"APack",
"PrintTarget":"File"
}
```

**Comment by SteveSteglitz** [comment]
Hello, 

have you set up the print template. The file name must be inserted in the print template. The file name cannot be given via the API.

For example:  [V:0::DateiPDF:2:0::"test.pdf"] 

If the print out of the Wawi works, without an opening window, it should also work via the API.


Best regards,
Steve

**Comment by Lars-Mue** [comment]
Thank you that works now. 
But is it possible that factory orders with document type W are not supported? I always get the following error response here:

https://.../slmobileapi/Documents/W14000005/Print
 
``
{
  "StatusCode": "InternalServerError",
  "ResponseCode": "42-000",
  "Message": "[EBelegDruckMitVorlageException] Nicht unterstützter Belegtyp",
  "Details": null
}
``

**Comment by SteveSteglitz** [comment]
Yes, thats right. The document type "W" will not be supported via the SelectLine API in the future either.

Best regards,
Steve
