### ISSUE TITLE
DocumentCreate schlägt mit neuer API-Version fehl

### ISSUE THREAD

**Issue by davidhommel** [selectline-software/selectline-api#120]
Hallo zusammen,

Seit dem Update auf die API-Version 21.1.1 funktioniert mein DocumentCreate-Aufruf nicht mehr. Die Fehlermeldung ist leider sehr spärlich - Mache ich etwas falsch? 

Postman-Ansicht meines Aufrufes inkl. Antwort:
![grafik](https://user-images.githubusercontent.com/72391062/117964672-2bcc4780-b322-11eb-8141-e3ef22079314.png)

**Comment by MatthiasGuse** [comment]
Aktuell ist die Version 21.1.4 verfügbar. Im Verlauf sind mehrere Fehlerbehebungen enthalten, bei denen es denkbar ist, dass Ihr beschriebenes Verhalten behoben wurde.

Sofern es Ihnen möglich ist, aktualisieren Sie bitte auf die aktuellste Version und testen das Verhalten erneut.

**Comment by davidhommel** [comment]
Hallo,
Danke - das hat das Problem beseitigt
