### ISSUE TITLE
ContactPersons: Feld Priorität

### ISSUE THREAD

**Issue by webworkerAPI** [selectline-software/selectline-api#121]
Guten Tag miteinander

Könnte man das Feld Priorität bei den Kontaktpersonen (Endpunkt: ContactPersons) aufnehmen, sodass man dieses auslesen und auch beschreiben kann?

Danke für ein Feedback.

Viele Grüße

**Comment by VivienSchuboth** [comment]
Guten Tag,

ich nehme Ihren Wunsch gerne erst einmal auf.
Wann diese Erweiterung zur Verfügung stehen wird, kann ich Ihnen jedoch noch nicht sagen.

Beste Grüße
