### ISSUE TITLE
Aktualisierung EDI-Status eines Dokuments funktioniert nicht

### ISSUE THREAD

**Issue by davidhommel** [selectline-software/selectline-api#122]
Hallo zusammen,

Wenn ich über einen PUT-Aufruf den EDI-Status eines Dokuments verändern will bekomme ich von der API (21.1.4) eine Fehlermeldung. Ich hänge einen Screenshot des Postman an.

![grafik](https://user-images.githubusercontent.com/72391062/119097630-433bbc80-ba15-11eb-9a3b-aec810185da9.png)

**Comment by MatthiasGuse** [comment]
Bitte einmal an der API abmelden und erneut anmelden oder den Backendmanager neustarten und erneut testen. Bitte prüfen Sie auch die Tests im Mobile-Manager.

Grundsätzlich ist diese gegeben und bei mir erfolgreich mit der genannten Version getestet.

**Comment by VivienSchuboth** [comment]
Guten Tag,

hat Ihnen der Ratschlag von Herrn Guse bei der Fehlerbehebung geholfen?
Falls ja, würde ich Sie bitten, diesen Issue zu schließen. 

Falls das Problem weiterhin besteht, melden Sie sich gerne zurück.

Danke im Voraus!

Beste Grüße,
Vivien Schuboth
