### ISSUE TITLE
.GET /Documents/{documentKey}/Positions - Falscher Wert in OutstandingAbsorptionAmount 

### ISSUE THREAD

**Issue by ThePholph** [selectline-software/selectline-api#124]
Version 21.1.2 Build 308084

Hallo SelectLine-Team,

im Response von .GET /Documents/{documentKey}/Positions wird bei der Eigenschaft OutstandingAbsorptionAmount nicht die offene Menge, wie dokumentiert unter ./slmobileApi/Help/Api/GET-Documents-documentKey-Positions zurückgegeben, sondern der offene Gesamtwert (Währung) und dies sogar negativ.

Dies führt leider dazu, das ich eine geplante Umsetzung für einen Kunden nicht über die API abbilden kann, da ich hier die offene Menge zwingend benötige!

Bsp. Auszug aus Response (siehe OutstandingAbsorptionAmount, Quantity und NetAmount):

````
  "SerialOrChargeLabel": "None",
  "AbsorptionAmountPredecessor": 0.0,
  "AbsorptionAmountSuccessor": 0.0,
  "OutstandingAbsorptionAmount": -6408.0,
  "ProjectId": 0,
  "ProjectLabel": null,
  "ReferenceAddressNumber": "70001",
  "ActualQuantity": 0.0,
  "Quantity": 400.0,
  "ArticleKindFlag": "K",
  "ArticleKindLabel": "Default",
  "PlanningKindLabel": "None",
  "DoExplodeSetArticle": false,
  "RejectArticleNumber": "",
  "RejectArticleLabel": null,
  "SurchargeRefersToArticleIdentifier": null,
  "CalculationPriceInEuro": 16.02,
  "CalculationPriceInObsoleteCurrency": 0.0,
  "NetAmount": 6408.0,
  "NetAmountInEuro": 6408.0,
  "NetAmountInObsoleteCurrency": 0.0,
  "NetAmountLessDiscount": -6408.0,
  "NetAmountLessDiscountInEuro": -6408.0,
````

Vielen Dank.

VG Daniel

**Comment by MatthiasGuse** [comment]
Hallo,

die Übersetzungen und zugehörigen Beschreibungen der Elemente sind eher "gewöhnungsbedürftig" ;-)
"OutstandingAbsorptionAmount" beschreibt die noch offene Übernahmesumme (Währungswert). Hier ist die Beschreibung falsch, was ich zur Korrektur mit aufnehme. Da Sie scheinbar 100% Rabatt gegeben haben, wäre der negative Wert aber korrekt.

Ihre Anforderung ist grundsätzlich schon abbildbar.

Allerdings müssen Sie dazu in den Vorgängerbeleg gucken. Ein Beispiel: Auftrag "A" und Lieferschein "L"

Um in "L" nur die offene Menge der Positionen "A" zu erfassen, müssen Sie aus der Position in "A" das Feld "AbsorptionAmountSuccessor" auswerten mit von der Gesamtmenge der Position in "A" abziehen. Das ergibt dann sozusagen die offenen Menge in "A" die noch in "L" ausgelagert werden darf um nicht zu überlagern. 
Am Folgebeleg selbst ("L") sieht man nicht die offenen Mengen des Vorgängers ("A"), da der Auftrag "A" ja bspw. in mehrere Lieferscheine aufgeteilt werden kann. Man sieht im Feld "AbsorptionAmountSuccessor" immer die Menge, die in Folgebelege übergeben wurde, das immer aus Sicht des eigenen Belegs (der Position).

Ich hoffen Sie kommen so weiter.

Viele Grüße!
Matthias

**Comment by ThePholph** [comment]
Hallo Matthias,

danke dir die Auskunft. Es ist an der Stelle wiedermal unschlüssig was sich der Softwareingenieur hier bei der Benennung gedacht hat oder welches Tool zur Übersetzung eingesetzt wurde. Jedoch sollte es schon geradlinig sein, wenn "AbsorptionAmountSuccessor" die übernommene Menge Zurückliefert, dann sollte "OutstandingAbsorptionAmount" auch die offene Menge und nicht den Wert enthalten. Na ja, viele Wege führen ja bekanntlich nach Rom.

Ich werde es nun mit "AbsorptionAmountSuccessor" gegen rechnen, funktioniert auch.

Viele Grüße

Daniel
