### ISSUE TITLE
Document BelegTyp 'K'

### ISSUE THREAD

**Issue by itsieber** [selectline-software/selectline-api#127]
Guten Morgen zusammen

Wenn ich einen 'K' Beleg lesen oder schreiben möchte, bekomme ich immer einen Fehler dass dies nicht möglich ist.
Gemäss Doku geht das aber?!

Grüsse 
Andreas

**Comment by VivienSchuboth** [comment]
Guten Tag,

Kassenbelege werden leider nicht über die SelectLine API unterstützt.
Obwohl wir versucht haben, diese Information über die API-Hilfe generell sichtbar zu machen, ist uns uns das anscheinend nicht ganz gelungen.  

Daher verweise ich im Folgenden explizit auf die Seiten mit den Informationen über nicht-unterstützte Belegtypen:
[API-Hilfe, Überblick](https://demo.slmobile.de/demoApi/Help/ApiFunctions)
[API-Hilfe, Bereich für Belege](https://demo.slmobile.de/demoApi/Help/ApiGroup?controllerName=Document)

Die Ursache für dieses Missverständnis scheint wohl die Information über Kassenbelege > "K" - Kassenbelege < zu sein, welche noch an dem Property "KindFlag" zu sehen ist.
Diese Fehlinformation werden wir umgehend entfernen, um solchen Missverständnissen zukünftig vorzubeugen.

Entschuldigen Sie dieses Missverständnis und beste Grüße,
Vivien
