### ISSUE TITLE
Macro

### ISSUE THREAD

**Issue by itsieber** [selectline-software/selectline-api#129]
Guten Tag

Kann es sein, dass das Macro immer einen String mitgibt?

**Macro:**
`select [BILD].Blobkey,[BILD].Bild, Substring(Blobkey,3,100) as ArtikelNr, Dateiname,Beschreibung,Ordnung
from [BILD]
LEFT JOIN ART ON
ART.Artikelnummer=SUBSTRING([BILD].[Blobkey],3,100)
where [BILD].[Blobkey] Like 'AR%'
  and [BILD].AngelegtAm > '01.01.2021'
ORDER BY BILD_ID
  OFFSET 5 ROWS
FETCH NEXT 5 ROWS ONLY;`

**json:**
`[{"Name": "DT","Value": "2000-01-01 00:00:00"},{"Name": "Offset","Value": 0},{"Name": "Rows","Value": 50}]`

**Fehler:**
`"LogLevel":"Error",
"Message":"Die für den Rowcount-Parameter einer TOP-Klausel oder FETCH-Klausel angegebene Zeilenanzahl muss einer ganzen Zahl entsprechen.",
"Exception":{
"Message":"Die für den Rowcount-Parameter einer TOP-Klausel oder FETCH-Klausel angegebene Zeilenanzahl muss einer ganzen Zahl entsprechen.",
"StackTrace":`

**Comment by VivienSchuboth** [comment]
Guten Tag,
welche Version setzen Sie derzeit ein?

Beste Grüße

**Comment by VivienSchuboth** [comment]
Guten Tag,

konnten Sie dieses Problem bereits lösen oder ist dieser Issue noch gültig?

Ich würde mich über eine Rückmeldung freuen.

Beste Grüße,
Vivien Schuboth
