### ISSUE TITLE
../Macros is not working 

### ISSUE THREAD

**Issue by Lars-Mue** [selectline-software/selectline-api#13]
Hello,

I i trying to Run a Macro through the API.  I dont get a Error Response. 
Seemingly it works fine. 

`````````````
{
  "ResponseDetails": "AffectedRows: 10448992",
  "ResponseType": "Ok",
  "ErrorCode": 0
}
```````````````
I want to print a simple Example.
The Header of the Macro:

[V:300::DateiPDF:2:0::"C:\..\MakroTest.pdf"] +".pdf"]
[3T:0::Test][P:0::.Belegtyp] 

If i run this Macro from the "Wawi" it works and it prints the file.

But if I run it through the API nothing happen's.

``````````````
{
    "macroName": "Test",
    "parameters": [
        {
            "name": "Belegtyp",
            "value": "\"F\""
        },
        {
            "name": "Belegnummer",
            "value": "\"20-00201\""
        }
    ]
}
``````````````````
 
The result of the Macro is printed.

Is it possible to write in German?

**Comment by ThePholph** [comment]
Hallo Lars,

hast du schon den Backend-Manager neugestartet auf dem Server? Makros werden erst nach einem Neustart der WaWi und somit auch der Backend-Instanz (SelectLine.API.Backend) verfügbar. Hatte das gleiche Problem am Anfang.

Belege kannst du auch über ./Documents/{documentKey}/Print drucken. Die Hilfe findest du unter  ./slmobileApi/Help/Api/POST-Documents-documentKey-Print.

Hoffe, ich konnte dir helfen.
