### ISSUE TITLE
ArticleItem per API

### ISSUE THREAD

**Issue by pahlgrimm** [selectline-software/selectline-api#130]
Moin, ich bastele gerade eine Schnittstelle für TANSS und Selectline. Ich komme gut voran habe jedoch das Problem, dass beim Anlegen eines Artikels per /documents/R123456/ArticleItem unter StoreInformation die "Quantity" ignoriert wird. Egal ob ich 0.5, 2 oder irgendetwas anderes angebe im Beleg steht immer 1,00. ICh sehe meinen Fehler nicht. Alle Felder passen nur die Menge nicht.
Ich setze im Moment Version 21.1.1.0 der API ein.

**Comment by VivienSchuboth** [comment]
Guten Abend,
da kann ich auf die Antwort zu dem Issue #58 verweisen. Dieses Feld sollte auch bei Ihrem Problem helfen. 
Falls nicht, melden Sie sich gerne zurück.

Beste Grüße,
Vivien Schuboth

**Comment by pahlgrimm** [comment]
Moin Frau Schuboth, das war's! Jetzt klappt es!

Danke für die schnelle Antwort!
