### ISSUE TITLE
ExtraFelder bei Seriennummern

### ISSUE THREAD

**Issue by timothy3001** [selectline-software/selectline-api#131]
Hallo *,

wir versuchen momentan die Extrafelder bei Seriennummern zu füllen via REST API. 

Laut API Beschreibung, kann man diese ExtraFelder scheinbar weder auslesen, noch via POST oder PUT beschreiben:
https://demo.slmobile.de/demoApi/Help/Api/GET-SerialNumbers-serialNumberId (GET)
https://demo.slmobile.de/demoApi/Help/Api/PUT-SerialNumbers-serialNumberId (PUT)
https://demo.slmobile.de/demoApi/Help/Api/POST-SerialNumber (POST)

Von den Belegen kenne ich die Modelerweiterungen "...WithExtraFields': `DocumentReadModelWithExtraFields`. 

Gibt es so etwas für die Seriennummern-Objekte auch? Bzw. ist dort etwas geplant? Oder komme ich da nur über die Datenbank ran zum jetzigen Zeitpunkt?

Viele Grüße
Timo

**Comment by VivienSchuboth** [comment]
Guten Tag,

derzeit gibt es für Seriennummern noch keine Erweiterung hinsichtlich der Extrafelder.
Bisher ist nur geplant, dass das Schreiben, Bearbeiten und Lesen der Extrafelder über einen einheitlichen Weg möglich ist.
Erst danach werden wir neue Routen um Extrafelder erweitern können.

Nichtsdestotrotz werde ich Ihren Wunsch erst einmal aufnehmen.

Beste Grüße,
Vivien
