### ISSUE TITLE
Begrenzte Zahl Positionen GET

### ISSUE THREAD

**Issue by Benziner** [selectline-software/selectline-api#132]
SelectLine Version 21.1.7 (auch Mobile). 
Bei Aufruf von 

`Communication.GetApiUrl() + "Documents/RR21-0001/Positions`

werden maximal 10 Positionen angezeigt, auch wenn im SelectLine Beleg mehr Positionen drin sind. 
Dasselbe habe ich auch über Swagger ausprobiert, selbes Ergebnis, max. 10 Positionen. 

Wenn ich filtere, bspw. so: 

`Communication.GetApiUrl() + "Documents/RR21-0001/Positions?documentPositionListFilter.filter=(PositionKind EQ 'H') OR (PositionKind EQ 'A')"`

erhalte ich zwar andere Positionen (Zeilentyp Artikel und Handelsstückliste) aber auch hier erhalte ich maximal 10 Positionen. Hängt das damit zusammen, dass ich für den Aufruf einen developer - APIkey benutze? Ist der API Key evtl. auf 10 Positionen beschränkt?

**Comment by VivienSchuboth** [comment]
Guten Tag,
nein, das hängt nicht damit zusammen.
Aus Performancegründen werden standardmäßig immer nur 10 Einträge ausgelesen.
Scheinbar wurde das in der SelectLine API Hilfe bisher noch nicht erwähnt. Das werden wir mit der nächsten Version nachholen!

Falls Sie die nächsten 10 Einträge lesen wollen, setzen Sie die Page in Ihrem Filter hoch. Andernfalls können Sie die Anzahl der ausgegebenen Einträge erhöhen, indem Sie die Filterung nutzen. Dabei spielt das Feld "Items" die Hauptrolle. 
Auf dieses und noch weitere spannende Infos wird übrigens in unseren SelectLine API Schulungen eingegangen. Falls Sie also mehr erfahren wollen, besuchen Sie gerne eine unserer Schulungen.

Beste Grüße
