### ISSUE TITLE
ExtraFelder bei Artikel

### ISSUE THREAD

**Issue by bengadola** [selectline-software/selectline-api#133]
Guten Tag

Habe keine Möglichkeit gefunden, die Extrafelder auf dem Artikel abzufragen.

Wie kann man auf diese zugreifen?

Bei den Belegen gibt es "DocumentReadModelWithExtraFields", gibt es so etwas auch bei den Artikeln?

Vielen Dank.

Freundliche Grüsse

Beni

**Comment by VivienSchuboth** [comment]
Guten Tag,
derzeit ist das Abrufen von Extrafeldern an Artikeln noch nicht möglich.
Jedoch können Sie Ihren Wunsch gerne in das UserVoice-Forum einstellen bzw. für einen eventuell Vorhandenen voten.

Beste Grüße,
Vivien
