### ISSUE TITLE
Feld Dimension auf Artikel

### ISSUE THREAD

**Issue by bengadola** [selectline-software/selectline-api#134]
Guten Tag

Gibt es eine Möglichkeit das Feld Dimension aus der Artikeltabelle abzufragen?

Habe dies nirgends gefunden.

Vielen Dank.

Freundliche Grüsse

Beni

**Comment by VivienSchuboth** [comment]
Guten Tag,

das Feld Dimension wird derzeit nur bei der Abfrage von Artikelbeständen zurückgegeben.
Diese Route finden Sie [hier](https://demo.slmobile.de/demoApi/Help/Api/GET-Articles-articleNumber-Stocks).

Beste Grüße,
Vivien
