### ISSUE TITLE
Aktionspreise und Preisgruppen Preise

### ISSUE THREAD

**Issue by bengadola** [selectline-software/selectline-api#135]
Guten Tag

Habe zwar gesehen, dass die Preisgruppenstammdaten abgefragt werden können, habe aber keine Möglichkeit gesehen den Aktionspreis oder andere Preisgruppen zu einem Artikel abzufragen.

Vielen Dank für die Unterstützung.

Freundliche Grüsse

Beni

**Comment by VivienSchuboth** [comment]
Hallo,
die Abfrage von Informationen zu Preisen ist bei uns im System, jedoch noch nicht eingetaktet.
Stellen Sie doch gerne Ihren Wunsch in das UserVoice-Forum ein. Anhand der dort vergebenen Stimmen wird über die Priorisierung der Themen entschieden. 

Beste Grüße,
Vivien

**Comment by MatthiasGuse** [comment]
Wir freuen uns Ihnen mitteilen zu können, dass wir mit der Version 23.1 zwei neue API Routen zur Verfügung gestellt haben, mit der Ihre Anforderung erfüllt werden kann. Es gibt zwei neue API-Routen, mit der die Verkaufspreise und Einkaufspreise eines Artikels für einen Kunden bzw. Lieferanten abgefragt werden können.

Beste Grüße

**Comment by pietzschke** [comment]
> Wir freuen uns Ihnen mitteilen zu können, dass wir mit der Version 23.1 zwei neue API Routen zur Verfügung gestellt haben, mit der Ihre Anforderung erfüllt werden kann. Es gibt zwei neue API-Routen, mit der die Verkaufspreise und Einkaufspreise eines Artikels für einen Kunden bzw. Lieferanten abgefragt werden können.
> 
> Beste Grüße

Danke für die Info. Das heißt der Weg an die Informationen aus einer Preisgruppe zu kommen wäre für jede Preisgruppe einen Dummykunden anzulegen und dann darüber an einen Preis zu kommen?

**Comment by MatthiasGuse** [comment]
Hallo,

wenn die Preisgruppe das Kriterium ist, wäre das der richtige Ansatz. Wobei man aber anmerken muss, dass die API Funktion nicht nur die Preisgruppen berücksichtigt, sondern auch Aktionspreise und Staffeln. Ebenso werden die Mandanteneinstellungen zur Preisfindung berücksichtigt. Der Preis, den diese Funktion ermittelt, gleicht dem, was der Beleg beim Einfügen einer Position in einem Beleg ermittelt. D.h. der hier ermittelte Preis, kann aufgrund der genannten Faktoren auch von dem der Preisgruppe abweichen. Die Funktion gibt allerdings auch zurück, woher der Preis stammt.

Viele Grüße
