### ISSUE TITLE
Manuelle Lagerung - "Belegtyp M wird nicht unterstützt."

### ISSUE THREAD

**Issue by LukWlbr** [selectline-software/selectline-api#137]
Hallo zusammen,

ich habe aktuell ein großes Problem mit meinen manuellen Lagerungen nach dem Update von Version 20.3 auf Version 21.2. 

Mein Aufruf über "/Documents/{documentKey}/Positions/Store" läuft seit dem Update auf folgenden Fehler: 
`  
"StatusCode": "NotFound",
"ResponseCode": "42-017",
"Message": "Der übermittelte Parameterwert wird nicht unterstützt: documentKey",
"Details": {
"message": "Belegtyp M wird nicht unterstützt."
`

Das Erstellen des Beleges mit Belegtyp M funktioniert, das Erstellen einer Position auf diesem allerdings nicht mehr...

Vielen Dank im Voraus!

Gruß,
Luk

**Comment by VivienSchuboth** [comment]
Guten Tag,

das Lagern von Positionen für manuelle Lagerungsbelege können Sie über folgende Route abwickeln:
[Lagern von manuellen Lagerungsbelegen](https://demo.slmobile.de/demoApi/Help/Api/POST-ManualStorages-manualStorageNumber-Positions-Store)

Ein entsprechendes Beispiel finden Sie in der Postman-Collection.

Beste Grüße,
Vivien

**Comment by LukWlbr** [comment]
Hallo,

Vielen Dank für die schnelle Rückmeldung! 

Wurde dies denn in einem aktuellen Update geändert? Mit der Version 20.3 funktionierte dies noch...
In der Dokumentation der API und in dem Update-Helfer finde ich diesbzgl. keine Änderungen.

Beste Grüße,
Luk

**Comment by VivienSchuboth** [comment]
Guten Tag,

ich konnte dementsprechend auch keinen Hinweis finden.
Das sollte natürlich nicht vorkommen, scheint uns aber doch passiert zu sein.
Es tut uns leid für die Umstände.

Beste Grüße,
Vivien

**Comment by LukWlbr** [comment]
Hallo, 

vielen Dank nochmal für die Rückmeldung. 
Ich passe entsprechend meinen Code auf den von Ihnen genannten Endpoint um und schließe hiermit das Issue. 

Gruß,
Luk
