### ISSUE TITLE
Kunden Extrafelder

### ISSUE THREAD

**Issue by Logic-Bits** [selectline-software/selectline-api#138]
Hallo,

ich bin leider zu blöd in der Doku oder Rest API die Extrafelder für den Kunden zu finden... brauche bitte Hilfe.

Danke

**Comment by VivienSchuboth** [comment]
Hallo,
da diese Route seit Existenzbeginn der API existiert, sind Extrafelder damals in diesem Bereich nicht umgesetzt wurden.
Stellen Sie doch gerne Ihren Wunsch in das UserVoice-Forum ein. Anhand der dort vergebenen Stimmen wird über die Priorisierung entschieden.

Beste Grüße,
Vivien
