### ISSUE TITLE
Wartungsvertrag anlegen

### ISSUE THREAD

**Issue by Benziner** [selectline-software/selectline-api#139]
Hallo, 
gibt es eine Möglichkeit einen Wartungsvertrag anzulegen? 
Über 
POST /Document hatte ich keinen Erfolg (Version 21.1.2):

```
{
  "KindFlag": "V",
  "BusinessPartner": {
    "Address": {
      "Number": "11606"
    }
  }
}
```

Response:

`{
  "StatusCode": "NotFound",
  "ResponseCode": "42-017",
  "Message": "Der übermittelte Parameterwert wird nicht unterstützt: documentKind",
  "Details": {
    "message": "Belegtyp V wird nicht unterstützt."
  }
}`

**Comment by VivienSchuboth** [comment]
Guten Tag,

wie die Fehlermeldung bereits aussagt, unterstützen wir die Verwaltung von Wartungsverträgen nicht über die SelectLine API.
Darauf verweisen wir ebenfalls auf den gängigen Hilfeseiten zu der SelectLine API, wie z.B. [hier](https://demo.slmobile.de/demoApi/Help/ApiGroup?controllerName=Document)

Beste Grüße

**Comment by Benziner** [comment]
Sprich es gibt keine Möglichkeit? Ist so etwas denn angedacht?

**Comment by VivienSchuboth** [comment]
Genau. Derzeit ist die Verwaltung von Wartungsaufträgen über die SelectLine API auch nicht angedacht.
Trotz dessen haben Sie die Möglichkeit Ihren Wunsch in das UserVoice Forum der SelectLine einzustellen.

Beste Grüße
