### ISSUE TITLE
Infrequent Error with ./Documents/{documentKey}/Print 

### ISSUE THREAD

**Issue by ThePholph** [selectline-software/selectline-api#14]
**API Version: 20.1.2.0**

Guten Morgen,

ich hoffe es ist OK, dass ich Fehler in Deutsch aufgebe, da ich es unnötig finde, dass die Meldungen zweimal übersetzt werden müssten 😃?

Es treten immer wieder Probleme beim Druck über die API auf, die ich nicht klar spezifizieren kann. In unregelmäßigen abständen bekomme ich folgenden Response:

`{
    "StatusCode": "InternalServerError",
    "ResponseCode": "42-000",
    "Message": "[EBelegDruckMitVorlageException] Ungültiger Parameter",
    "Details": null
}`

Nachdem der Fehler aufgetreten ist, funktioniert der Druck ohne notwendige Anpassungsmaßnahmen wieder tadellos.

Ich hoffe, Ihr könnt trotz der wenigen Information etwas damit anfangen.

Vielen Dank.

**Comment by jprause1234** [comment]
Hallo,

ich glaube um mehr zu diesem Fehler herauszufinden, müssen wir in die Logs schauen. Die liegen normalerweise unter "C:\ProgramData\SelectLine Software\logs". Dort sollten in den Ordnern "SelectLine.API.Backend" und "SelectLine.API" Logs liegen. Diese entweder selbst durchschauen oder uns bereitstellen. Wichtig wäre dann aber der ungefähre Zeitpunkt, wann der Fehler aufgetreten ist.

Viele Grüße
Jan

**Comment by ThePholph** [comment]
Hallo,

der Fehler ist heute aufgetreten, aus den Logs kann ich jedoch nichts entnehmen. Für "SelectLine.API.Backend" wurde für heute kein Log angelegt. Die Zeitpunkte wann der Fehler aufgetreten ist, kannst du meinem aktuellen Log entnehmen.

[Logfile_08052020_svc_dien.log](https://github.com/selectline-software/selectline-api/files/4597951/Logfile_08052020_svc_dien.log)
[SelectLine.Erp.WebApi.WebHost.log](https://github.com/selectline-software/selectline-api/files/4597952/SelectLine.Erp.WebApi.WebHost.log)

Danke und viele Grüße

Daniel

**Comment by jprause1234** [comment]
Welche Version der API ist da im Einsatz?

**Comment by ThePholph** [comment]
Hallo,

wie oben im ersten Post angegeben: API Version: 20.1.2.0

Viele Grüße

Daniel

**Comment by jprause1234** [comment]
Oh, sorry, hatte ich übersehen.
Ich war verwundert, weil die Endung der Log Files nicht "slog" war.
In den Logs steht, dass sowohl bei der Wawi als auch bei Mobile die Version 19.3 ermittelt wurde.

Viele Grüße
Jan

**Comment by ThePholph** [comment]
Hallo,

ich musste es umbenennen, da ".slog" nicht von GitHub unterstützt wird beim Upload. 

Die 19.3 ist im Logfile richtig, da es vom Kunden stammt. Ich konnte den gleichen Fehler auch unter 20.1.2.0 in unserem System reproduzieren.

Viele Grüße
Daniel

**Comment by jprause1234** [comment]
Ich bräuchte auch noch die Logs aus dem Ordner "SelectLine.API.Backend".
Da es aber hier auch um Logs eines Kunden geht, würde ich alles weitere gern per HelpDesk klären und nicht hier im öffentlichen GitHub Forum. 
Ich habe dazu bereits einen Vorgang mit der Nummer 109345 angelegt, über den dann bitte alles weitere laufen soll.
Die weiteren Log Files also bitte per Mail an den HelpDesk schicken. Danke.

Viele Grüße
Jan

**Comment by ThePholph** [comment]
Guten Morgen,

ich habe alle Logs gepackt und auf HiDrive zur Verfügung gestellt. Die Mail dazu inkl. Verweis auf die Servicenummer ist unterwegs.

Viele Grüße

Daniel

**Comment by VivienSchuboth** [comment]
Guten Tag,
wir haben das Handling der Anfragen an die SelectLine API optimiert.
Damit lösen sich hoffentlich auch die Probleme in #7, #8 und #22.
Die Fehlerbehebung steht Ihnen mit der V21.1 zur Verfügung.

Mit freundlichen Grüßen,
Vivien Schuboth
