### ISSUE TITLE
GET /Inventories nutzt keinen Status-Filter

### ISSUE THREAD

**Issue by LandoWalter** [selectline-software/selectline-api#140]
Hallo zusammen,

wenn ich alle aktiven (nicht abgeschlossenen) Inventuren mit _/Inventories?inventoryListFilter.status=1&inventoryListFilter.items=100_ abfrage, bekomme ich immer alle Inventuren angezeigt.
![image](https://user-images.githubusercontent.com/82435968/125264712-62afe100-e304-11eb-8dfc-5ce5102c67f4.png)

Bei mir greift hier die Filterung nach Status gar nicht. Mir werden hier auch abgeschlossene Inventuren mit zurückgeschickt.
Die Filterung nach Elementanzahl wird mir allerdings richtig gemacht, da bekomme ich maximal 100 Inventuren pro Seite angezeigt.

Sind hier Fehler bekannt oder erkennen Sie etwas falsches an meiner Abfrage?

SelectLine: 21.2.0
SL-Mobile: 21.2.0

**Comment by MatthiasGuse** [comment]
Hallo!
Das sieht so aus, als wäre der Filter kaputt. Ich nehme das als Fehler auf.

Um Ihre Abfrag zu realisieren, können Sie den auch "inventoryListFilter.filter" nutzen.
![grafik](https://user-images.githubusercontent.com/31447000/125408104-d3193980-e3ba-11eb-988c-13e1f736d815.png)

Viele Grüße

**Comment by MatthiasGuse** [comment]
Der Fehler wurde mit der kürzlich veröffentlichten Version 23.1.0 behoben.

Beste Grüße
