### ISSUE TITLE
API-Pfad für Leistungserfassung ?

### ISSUE THREAD

**Issue by kagithd** [selectline-software/selectline-api#141]
Hallo ich suche die möglichkeit Einträge in der Leistungserfassung zu ersellen. Gibt es hierzu einen API-Aufruf ?

**Comment by MatthiasGuse** [comment]
Hierfür gibt es leider bisher ebenfalls keine Funktion. Gerne nutzen Sie auch hier die Möglichkeit Ihren Wunsch in das UserVoice Forum der SelectLine einzustellen.
