### ISSUE TITLE
Api-Pfad für Kundenpreise 

### ISSUE THREAD

**Issue by kagithd** [selectline-software/selectline-api#142]
Hallo, 
ich würde gerne die Kundenpreise / Rabate eines Kunden zu einem bestimten Artikel herausbekommen finde for lauter wald aber die Pfade dahin nicht

**Comment by MatthiasGuse** [comment]
Diese Funktion steht aktuell in der API noch nicht zur Verfügung. Gerne nutzen Sie die Möglichkeit Ihren Wunsch in das UserVoice Forum der SelectLine einzustellen.
