### ISSUE TITLE
Aktualisieren der Artikel via Makro

### ISSUE THREAD

**Issue by Torchok19081986** [selectline-software/selectline-api#144]
Hallo, ich würde gern ein Artikel, welche ich aus der Mobile API bekomme, von einem Mandanten in einem anderen aktualisieren. 
Das Makro habe ich angelegt, aber leider habe ich für das Angabe der Parameter beim Makroaufruf in der Hilfe nichts gefunden.  Marko wurde wie gefolgt ansehen :  Update ART set Feld = Wert ... where Artikelnummer =: Artikelnummer.  
Ich habe an dieser Stelle ein paar Fragen: 
1. Wie übergebe ich das Parameter an das Makro z.B. Artikelnummer ? 
2.  Gibt es irgendwelche Einschränkungen bei den Artikel Anlegen / Aktualisieren ?

**Comment by MatthiasGuse** [comment]
Hallo,

welche Makro-Funktionalität nutzen Sie? 
In der API sind zwei verschiedene Makro-Funktionalitäten enthalten. 
1. POST /Macros/{macroFileName}
2. POST /Macros

Die Beschreibung für 1. finden Sie hier: [https://demo.slmobile.de/demoApi/Help/HowToMacro](https://demo.slmobile.de/demoApi/Help/HowToMacro)

**Comment by Torchok19081986** [comment]
Hallo, danke für die Antwort und das Link. Ich würde gern das 1. Verwenden, da es, laut Beschreibung die gespeicherte Makro in der SL WaWi benutzt.

**Comment by MatthiasGuse** [comment]
Wenn Sie ein Makro verwenden möchten, welche Sie in der Warenwirtschaft anlegen und benutzen können, müssen Sie 2. "POST /Macros" verwenden und als Namen den Dateinamen des Makros angeben. Der Name steht im Makroassistenen unten links in der Ecke, wenn Sie ein Makro ausgewählt haben + ".qvl"

Hier das Beispiel aus Swagger:
`{
  "MacroName": "MDE-Beleg-Druck.qvl",
  "Parameters": [
    {
      "Name": "Belegtyp",
      "Value": "\"R\""
    },
    {
      "Name": "Belegnummer",
      "Value": "\"AR030\""
    }
  ]
}`

**Comment by Torchok19081986** [comment]
Moin, vielen Dank für Antwort. Braucht man dafür MDE Lizenz und wie kann ich das Ausführen von Makro für bestimmte Benutzer erlauben?

**Comment by MatthiasGuse** [comment]
Hallo,

ein normaler API User reicht aus (lizenz natürlich vorausgesetzt). Mir sind soweit kein Einschränkungen / Berechtigungen für das Ausführen von Makros bekannt. Theoretisch kann jeder API Benutzer Makros ausführen.

Kleine Wiederholung von oben:

> In der API sind zwei verschiedene Makro-Funktionalitäten enthalten.
> 
> 1. POST /Macros/{macroFileName}
> 2. POST /Macros
> 
> Die Beschreibung für 1. finden Sie hier: https://demo.slmobile.de/demoApi/Help/HowToMacro

Bei 2. wird ein Makro nur ausgeführt und Sie erhalten nur die Rückmeldung, ob das Makro ausgeführt wurde oder nicht. Nur bei 1. erhalten Sie die Ergebnismenge per API zurück. Beschreibung siehe Link oben oder hier: https://demo.slmobile.de/demoApi/swagger/ui/index#/Macro/Macro_ExecuteMacro

**Comment by Torchok19081986** [comment]
ok, vielen Dank für die Aufklärung.  Ich habe es soweit implementiert, wie es beschrieben wurde, leider bekomme ich nach der Ausführung des 1. POST entweder InternalserverError oder BadRequest. 
 ```csharp

public void ExecuteWaWiMakro(string artnummer)
        {
            try
            {
                ServicePointManager.ServerCertificateValidationCallback = (_, __, ____, ___) => true;

                //ToolConfiguration t = new ToolConfiguration();

                Commonfunctions common = new Commonfunctions();
                Userconfig profile = common.LoadXmlFile();
                
                WawiMacroTaskParameter wawiparameter = new WawiMacroTaskParameter
                {
                    Name = "ArtNr",
                    Value = "\"" + artnummer + "\""
                };
                List<WawiMacroTaskParameter> wawiMacros = new List<WawiMacroTaskParameter>
                {
                    wawiparameter
                };

                WawiMacroTask macroTask = new WawiMacroTask
                {
                    MacroName = "Suchebynummer.qvl",  //SQL1008.qvl
                    Parameters = wawiMacros                 
                };

                using (HttpClient httpclient = new HttpClient())
                {
                    string macronamemitext = macroTask.MacroName.Replace(".qvl","");

                    requestUriMacros = string.Format("{0}Macros/{1}", profile.Zielurl, macronamemitext);

                    requestUri = requestUriMacros;

                    SetClientDefaults(httpclient, requestUri);

                    //1. Benutzer führt das Macro aus.
                    SetClientAuthorization(httpclient, 1); //1

                    Log4NetClass.WriteInfo("WaWi Makro Request Url: " + requestUri);

                    string macro = JsonConvert.SerializeObject(macroTask);

                    Log4NetClass.WriteInfo("SerializeObject: " + macro);

                    StringContent httpcontent = new StringContent(macro);
                    
                    Log4NetClass.WriteInfo("Content: " + httpcontent.ReadAsStringAsync().Result);

                    HttpResponseMessage httpresponse = httpclient.PostAsJsonAsync(requestUri, httpcontent).Result;

                    _ = MessageBox.Show(httpresponse.StatusCode.ToString(), "Info", MessageBoxButton.OK, MessageBoxImage.Information);

                    if (httpresponse.IsSuccessStatusCode)
                    {
                       Task<MacroResult> task = httpresponse.Content.ReadAsAsync<MacroResult>();
                       _ = MessageBox.Show(task.Result.ToString(), "Info", MessageBoxButton.OK, MessageBoxImage.Information);
                    }
                    else
                    {
                      _ = MessageBox.Show("No successfull Execute WaWi Macro", "Info", MessageBoxButton.OK, MessageBoxImage.Information);
                    }
                }
            }
            catch(Exception e)
            {
                Log4NetClass.WriteError(e.ToString(), e);
                Application.Current.Shutdown(0);
            }

```

das macro, dass ich ausführen möchte lautet  SELECT COUNT(*) FROM ART WHERE Artikelnummer =: ArtNr . 
Kann es sein, dasss man keinen SQL Scalarfunktionen in der macro ausführen kann?

**Comment by MatthiasGuse** [comment]
Hallo,

Ihre gesendeten Daten haben den falschen Aufbau. Sie verwenden die Struktur von "POST /Macros".

Das JSON, was Sie bei der Verwendung von "POST /Macros/{macroFileName}" absenden müssen, sieht exemplarisch so aus:
`[{"Name":"Artikelnummer","Value":"120001"},{"Name":"SerieCharge","Value":""}]`

**Comment by Torchok19081986** [comment]
Guten Morgen, danke für den Hinweis. Ich habe dies im meinen APP verändert, es kommt zwar keine InternalServerError, sondern es kommt jetzt NotFound. Macro existiert aber mit diesem Namen in WaWi.  Gesendete Json sieht jetzt wie Sie es beschrieben haben. Jetzt funktioniert, nur bekome ich das Error 
System.Net.Http.UnsupportedMediaTypeException: No MediaTypeFormatter is available to read an object of type 'MacroResult' from content with media type 'application/octet-stream'.

**Comment by MatthiasGuse** [comment]
Bitte lesen Sie die Beschreibung der API Makros noch einmal genau durch. https://demo.slmobile.de/demoApi/Help/HowToMacro

Ein API Makro ist ein Makro, was als Datensatz in der Tabelle APIMACRO angelegt werden muss.

Das geht zum Beispiel per Managementstudio oder Makroassistenten so (ungetestet):

INSERT [APIMACRO] (Name, Text)
VALUES(N'Suchebynummer', 
 ' SELECT COUNT(*) FROM ART WHERE Artikelnummer =: ArtNr');

**Comment by Torchok19081986** [comment]
Ok. Das Makro wurde mit Hilfe der SSMS (Sql Server Management Studio )  in der Tabelle APIMACRO erstellt, via Insert eingepfelgt.
Makro läuft ja, nur ich kann keinen Erbenis davon auswerten, weder mit MacroResult noch mit MacroResultRow kann ich httpresponse.Content.ReadAsStringAsync().Result / httpresponse.Content.ReadAsAsync<MacroResult>().Result kann ich das lesen. 
Es kommt entweder Fehlermeldung oder das ganze HTML Document zurück. 
![SL Macro Tabelle APIMacro](https://user-images.githubusercontent.com/25432729/128321038-71901f08-df68-4b73-abd3-5d2ca757863b.JPG)

**Comment by MatthiasGuse** [comment]
Das Ausführen des Mkros per Swagger funktioniert und liefert das gewünschte Ergebnis zurück.
![grafik](https://user-images.githubusercontent.com/31447000/128454545-64bf53c3-1d5e-4088-b8ce-6da4412eaad9.png)

Ich habe festgestellt, dass Sie in Ihrem Makro ein Leerzeichen zwischen dem Doppelpunkt und dem Parameter in Ihrem Makro eingefügt haben.
![grafik](https://user-images.githubusercontent.com/31447000/128454775-28a9997a-3ec1-4d8f-b5b9-dbe33ea19a67.png)
Das darf da natürlich nicht stehen. Denke somit wird es dann auch funktionieren.

Viele Grüße

**Comment by Torchok19081986** [comment]
Morgen, Vielen dank an der Stelle. Ich habe noch mla das ganze überprüfen können. Die Leerzeichen ist wohl falsch an der Stelle. 
Letzte Frage hier : 
Wann soll ich die Klasse WawiMacroTask verwenden und wann die Macro Klasse.

**Comment by MatthiasGuse** [comment]
Hallo,

    POST /Macros/{macroFileName} --> "MacroParameter"
    POST /Macros --> "WawiMacroTask"

Wie Sie schreiben funktioniert das Ausführen des Makros per Swagger. Bitte haben Sie Verständnis dafür, dass ich Ihnen darüber hinaus hier nicht weiterhelfen kann.

Viel Erfolg weiterhin!
