### ISSUE TITLE
API-Function für Werkaufträge

### ISSUE THREAD

**Issue by diekloope** [selectline-software/selectline-api#145]
Ich möchte API-Functionen von 19.2.8 auf 21.2 anpassen.
Jetzt habe ich gesehen das Werkaufträge nicht mehr mit der Function /Documents/{documentKey} unterstützt werden.
Wie kann ich die in der Version 21.2 die Werkauftragdaten laden?

**Comment by diekloope** [comment]
Bisher haben wir den Werkauftrag genutzt um die Adressnummer auszulesen. Der Kunde hat die Werkauftragsnummer kombiniert mit anderen Werten auf den Fertigungsaufträges in einem Barcode. Der Barcode wird gescannt und in einem Teilschritt wird mit der Werkauftragsnummer der Kunde ermittelt.

**Comment by MatthiasGuse** [comment]
In den Belegrouten sind "Werkaufträge" als ausgeschlossen genannt, da gewisse Felder in der Belegtabelle anders genutzt werden, als der Name sagt. Um die Funktionalität in der API durchgängig zu gestalten und Fehler zu vermeiden, wurde der Werkauftrag in allen Aktionen der Route "/Documents/{documentKey}" ausgeschlossen.
Das Auslesen von Werkaufträgen ist in der aktuellen Version dennoch möglich per GET ​/Documents. Mit einem Filter auf Typ und Belegnummer sollten Sie das gleiche Ergebnis erhalten. 

Ich hoffe Sie kommen so weiter. Viele Grüße

**Comment by MatthiasGuse** [comment]
An dieser Stelle nochmal ausdrücklich der Hinweis, dass Werkaufträge in den Routen der Belege offiziell nicht unterstützt werden. D.h. die oben geschilderte Lösung kann also zukünftig auch entfallen. Hier bliebe dann nur noch der Weg ein Makro zu benutzen.

Viele Grüße

**Comment by diekloope** [comment]
Danke für die Infos. Finde es schade, dass der Werkauftrag nicht mehr unterstützt wird, gerade da er ja weiterhin in SelectLine nutzbar ist. Ich habe es über SQL-Function gelöst.
