### ISSUE TITLE
PaymentTerm setzt nicht neu PaymentPeriod

### ISSUE THREAD

**Issue by Logic-Bits** [selectline-software/selectline-api#146]
Payment.PaymentTerm wird gesetzt, überschreibt aber nicht den Standard Zahlungsziel in Tagen im Beleg.

**Comment by MatthiasGuse** [comment]
Hallo,

wo befinden wir uns in Ihrem Beispiel? Beleganlage "POST" oder Update "PUT"?

**Comment by Logic-Bits** [comment]
Hallo, bei Post

**Comment by MatthiasGuse** [comment]
Das beschriebene Verhalten kann ich nicht nachvollziehen. Bei Angabe einer vorhandenen Zahlungsbedingung im Post, werden die Zahlungsziele entsprechende der angegebenen Bedingung gesetzt.

Falls das Problem bei Ihnen nachstellbar ist, schildern Sie es bitte mit entsprechendem Beispiel und Screenshots.

**Comment by Logic-Bits** [comment]
Hallo Herr Guse, ich kann es jetzt auf meinem Testsystem auch nicht mehr nachvollziehen. Beim Kunde habe ich es jetzt direkt angegeben.
Danke trotzdem.
