### ISSUE TITLE
API Key nach dem Update ist nicht mehr gültig.

### ISSUE THREAD

**Issue by Torchok19081986** [selectline-software/selectline-api#147]
Hallo, wir haben bei uns auf unseren Testsystem die SL mit Mobile von 20.3 auf 21.2.3 aktualisiert. Nun wollten wir uns mit neuen Sachen in 21.2.3 ansehen. Nur leider können wir uns nicht mehr mit unseren APIKey anmelden. Es erscheint eine Fehlermeldung mit 02-039. APIKey ist in der WaWi unter liezenzsierung vorhanden.  das VM wurde umgezogen von alten Hardware auf ein Neues.
Müssen wir noch was zusätzlich andern? Momentan ist da nur die Benezeichnung Developer-XYZ.

**Comment by MatthiasGuse** [comment]
Hallo,

ist der Appkey auch in der Mobile Administration unter "Lizenz" vorhanden?

Grüße

**Comment by Torchok19081986** [comment]
Morgen, gerade nachgeschaut. Das AppKey ist dort vorhanden.

**Comment by MatthiasGuse** [comment]
Sollte sich das Problem nach einem Neustart des Services oder des Servers nicht behoben haben, wenden Sie sich bitte an den Support.

Viele Grüße
