### ISSUE TITLE
Error ./Documents/{documentKey}/Print - Erweiterter Belegstatus in Verbindung mit Folgeformularen

### ISSUE THREAD

**Issue by ThePholph** [selectline-software/selectline-api#15]
**API Version: 20.1.2.0**

Der Druck von Druckvorlagen, die Folgeformulare enthalten, funktioniert über die API nicht, wenn es sich um Belege mit erweiterten Belegstatus handelt, die im Status „in Bearbeitung“ stehen. Bei "einfachen" Druckvorlagen (ohne Folgeformulare) bekomme ich zwar folgenden Response, dennoch funktioniert der Druck.

`{
  "ResponseDetails": "Hinweis: Der Beleg 40500522 wurde nicht als gedruckt gekennzeichnet, da er den Status „in Bearbeitung“ besitzt.",
  "ResponseType": "PrintDocumentInformation",
  "ErrorCode": -1
}`

Ich hoffe, Ihr könnt mir weiterhelfen, da Folgeformulare bei unseren Kunden sehr häufig vorkommen.

Vielen Dank.

**Comment by VivienSchuboth** [comment]
Hallo,
wir werden uns dieses Problem anschauen und schreiben dir, 
sobald wir weitere Informationen haben.

Viele Grüße,
Vivien

**Comment by VivienSchuboth** [comment]
Guten Tag,
mit der nächsten Version (20.3.0) ist diese Problematik behoben. 
Über die SelectLine API können dann Belege mit Folgeformularen gedruckt werden, auch wenn die Belege sich im Zustand "In Bearbeitung" befinden.

Mit freundlichen Grüßen,
Vivien

**Comment by ThePholph** [comment]
Hallo,

danke für die Info. Sobald ich dies Testen konnte und alles funktioniert, werde ich den Fall schließen.

Vielen Grüße

Daniel
