### ISSUE TITLE
Anlegen Chargennummer

### ISSUE THREAD

**Issue by LandoWalter** [selectline-software/selectline-api#150]
Hallo,

gibt es eine Möglichkeit mit der API neue Chargennummern anzulegen?
Mit dem PUT-Request /SerialNumbers/{serialNumberId} bekomme ich keine neue Chargennummer angelegt. Gibt es hier eine andere Route?

Route: /SerialNumbers/1200050000000030 PUT
`{
  "ArticleNumber": "300011",
  "Description": "Test",
  "ExpirationDate": "2021-08-11T14:28:53.206Z",
  "Flag": "C",
  "SerialNumberId": 116,
 }`

Response:
`{
    "Message": "The request is invalid."
}`

SelectLine: 21.2.3
SL-Mobile: 21.2.3

**Comment by LandoWalter** [comment]
Hallo Herr Guse,

vielen Dank für Ihre Nachfrage.

Wir haben einen Kunden der Ware von seinen Lieferanten einbuchen möchte.
Diese Ware hat einen Barcode in dem Artikelnummer, Chargennummer und Verfallsdatum für den jeweiligen Artikel steht. Diese einzelnen Informationen können über einen RegEx ausgelesen werden.
Jetzt soll geprüft werden, ob es die vorgegebene Chargennummer bereits in der Wawi gibt und wenn sie vorhanden ist, soll die Ware auf diese Charge gebucht werden mit dem Verfallsdatum. (sollte über die Route: /SerialNumbers/{serialNumberId} GET zu prüfen sein.)
Wenn diese Chargennummer noch nicht im System ist, soll diese Chargennummer für den Artikel angelegt werden, zusammen mit Informationen über Lager, Standort, Verfallsdatum, usw.

Dies soll über die API gelöst werden, weil die gesamten Informationen über diesen einen Barcode kommen und der Kunde diese Informationen sonst immer händisch abtippen muss. Mit einem Scan wünscht sich der Kunde, dass die Informationen automatisch geprüft werden können und ihm Tipp- und Klickarbeit abgenommen wird.

Viele Dank und viele Grüße

**Comment by MatthiasGuse** [comment]
Hallo,
Sie brauchen eine Charge/Serie nicht explizit anlegen, wenn Sie sie einlager wollen. Es genügt, wenn die Chargennummer bei der Einlagerung angegeben wird. Sie wird dann automatisch angelegt.

Sie erfüllen Ihre Anforderung also über die Lagerung im Beleg z.B. "/Documents/{documentKey}/ArticleItem" und nicht über die Route "/SerialNumbers/".

Viele Grüße

**Comment by LandoWalter** [comment]
Hallo Herr Guse,
vielen Dank für Ihre Antwort. Mit einer Belegübergabe über die API bekomme ich auch neue Chargennummern angelegt.
Vielen Dank nochmal.
