### ISSUE TITLE
Auslesen von Artikelinformationen für Artikel mit Sonderzeichen -> URL-Encoding

### ISSUE THREAD

**Issue by h2-Systems** [selectline-software/selectline-api#153]
Hallo SelectLine,

bei einem Kunden wollen wir über den Befehl `/Articles/{articleNumber}` Artikel auslesen und verarbeiten,
mehrere Artikel haben jedoch ein ` / ` oder ` + ` in ihrem Namen, welches von der API nicht verarbeitet wird.
Wenn wir die Zeichen nun regulär mit den entsprechenden URL-Encodings ersetzen wird der Artikel nicht gefunden und wir bekommen folgenden Fehler:

```
HTTP-Fehler 404.11 - Not Found
Das Anforderungsfilterungsmodul ist so konfiguriert, dass Anforderungen abgelehnt werden, die eine doppelte Escapesequenz enthalten.
```

**Comment by h2-Systems** [comment]
Nach dem Setzen der Flag `allowDoubleEscaping=true` in der web.config scheint das Problem für ` + ` nicht mehr aufzutreten.
Für Artikel mit ` / ` kommt dafür jetzt folgender Fehler:

```
HTTP-Fehler 404.0 - Not Found
Die gesuchte Ressource wurde entfernt oder umbenannt, oder sie steht vorübergehend nicht zur Verfügung.
```

**Comment by VivienSchuboth** [comment]
Guten Tag,

das Zeichen sollten Sie vor dem Senden encodieren. Im Folgenden Link steht Ihnen eine Schritt-für-Schritt-Anleitung zur Verfügung:
https://demo.slmobile.de/demoApi/Help/HowToEncodeUrlValues

Falls Sie diese Schritte nicht abgearbeitet haben, kann es natürlich dazu kommen, dass Sie damit eine komplett neue, der API **unbekannte**, Route aufrufen:
`Articles/{articleNumber part1}{Slash aus der Artikelnummer als Trennzeichen}{articleNumber part2}`

Damit tritt genau der von Ihnen genannte Fehler dann auch auf.

Viel Erfolg und bei Fragen melden Sie sich gerne zurück.

Beste Grüße

**Comment by h2-Systems** [comment]
Guten Tag,

Natürlich haben wir die ` / ` durch das entsprechende Encoding ersetzt, der Fehler tritt aber nicht nur in der eigenen Entwicklung, sondern auch in der Swagger Testumgebung, welche die Ersetzung automatisch macht, auf.

**Comment by h2-Systems** [comment]
Habe sie für das Problem bereits eine Lösung, bzw. konnten sie es denn nachstellen?

**Comment by VivienSchuboth** [comment]
Guten Tag,

den Fehler konnte ich in unserer aktuellsten Version reproduzieren.
Danke für den Tipp!

Ich werde den Fehler aufnehmen und mit meinem Team zeitig eintakten.
Informationen, zu wann der Fehler behoben wird, werde ich Ihnen hier über das Forum mitteilen.

Beste Grüße

**Comment by VivienSchuboth** [comment]
Guten Tag,

der Fehler basierte in unserem Fall auf einer fehlerhaften Encodierung. 
Anstatt der Tilde "~",  verwendeten wir das Prozentzeichen "%". 
Wie auf der [Hilfeseite](https://demo.slmobile.de/demoApi/Help/HowToEncodeUrlValues) beschrieben wurde, lösen jedoch

> Sonderzeichen wie z.B. Prozent '%' ohne Encodierung und Decodierung ein ungewünschtes Verhalten [aus].

Durch eine fehlerhafte Encodierung wurde die Abfrage also wie folgt abgeschickt:
`GET {{url}}/Articles/70%2F111`
Hierbei lautete die angelegte Artikelnummer  aus der Warenwirtschaft "70/111".

Korrekt sieht es wie folgt aus: 
`GET {{url}}/Articles/70~2F111`

Geben Sie diesen Wert 70~2F111 ebenfalls bei Swagger in das Feld ein, erhalten Sie Ihre abrufbaren Daten zu Ihrem Artikel.

Beste Grüße
