### ISSUE TITLE
Fehler 42-000

### ISSUE THREAD

**Issue by Logic-Bits** [selectline-software/selectline-api#156]
Hallo Frau Schuboth,

Frische Installation von SL + Mobile.
Ich kann Belege auslesen, aber beim Erstellen kommt der 42-000 Fehler.
User wurde schon gelöscht und neu angelegt.
Backendmanager auch neu gestartet.

Fehler:
![grafik](https://user-images.githubusercontent.com/2421123/130059907-884ab36e-73d2-472e-8da8-d4caa00861c6.png)

Get funktioniert:
![grafik](https://user-images.githubusercontent.com/2421123/130059941-eb5145d6-b555-4844-9c7a-9afe4cc8d949.png)

Log schreibt (nur bei Post):
{"Name":"SQLServer","TimeStamp":"2021-08-19T07:49:14.433Z","ServerTimeStamp":"2021-08-19T07:49:14.433Z","Host":{"Name":"xxx\u00DCRO","Version":"Windows 10 (Version 10.0, Build 19042, 64-Bit-Edition)","UserName":"xxx"},"Process":{"FileName":"C:\\Program Files (x86)\\SelectLine Software\\Mobile Anwendungen\\SelectLine API Backend\\SelectLine.API.Backend.exe","Name":"SelectLine.API.Backend.exe","ProcessId":"15972","ThreadId":"4428","Runtime":"00:00:17.9630000","MemoryPrivateBytes":75948032},"LogLevel":"Error","Message":"TXSQLServer.SQLConnect","Exception":{"Type":"EMSError","Message":"SQL Server Network Interfaces: Error Locating Server\/Instance Specified [xFFFFFFFF]. \\nExceptionklasse: EMSError\\nSQL Server Fehlernummer: -1\\nOle Fehlernummer: -2147467259\\nData Access Fehlernummer: -1\\nServername: \\nLetzter Fehler: SQL Server Network Interfaces: Error Locating Server\/Instance Specified [xFFFFFFFF]. \\nProzedur: \\nZeile: 0"},"Program":{"Version":"21.2.3.0"}}

Bitte um baldige Antwort.
Vielen Dank

**Comment by VivienSchuboth** [comment]
Guten Tag,
scheinbar kann sich die Backend-Warenwirtschaft nicht an Ihrem SQL-Server anmelden.
Daher würde ich meinen, dass Ihr Fehler sich ebenfalls auf das Erstellen von Belegpositionen und der Durchführung von Lagerungen reproduzieren lässt.

Könnten Sie bitte Ihre Daten in Ihrem Mobile Manager überprüfen?

Beste Grüße,
Vivien Schuboth

**Comment by Logic-Bits** [comment]
Meldet sich der Backend Manager nur beim schreiben an?
Wenn ich mich mit dem User in SL anmelde, kann ich belege erzeugen.

Was soll ich noch überprüfen?

Danke

**Comment by VivienSchuboth** [comment]
Guten Tag,

nein, nicht direkt. Der Verbindungsaufbau zur Backend Warenwirtschaft erfolgt mit dem Login eines API-Benutzers an der API-Schnittstelle. Falls es nicht geklappt hat, bekommt man zunächst keine Fehlermeldung zurück. Das hat unter Anderem den Grund, dass zum Lesen von verschiedenen Datensätzen diese Backend Warenwirtschaft _nicht_ benötigt wird.

Symptome, dass es nicht geklappt hat, treten dann erst auf, wenn zwingend Funktionalität aus der Warenwirtschaft benötigt wird. Das trifft beispielsweise auf das Anlegen von Belegen zu. 


Falls die Datenbank, der Datenpfad und die Benutzereingaben stimmen, könnten Sie folgendes probieren:

- Prüfen Sie bitte zunächst, ob die Tests innerhalb des Mobile Managers korrekt ausgeführt werden konnten.

Falls Ihre Tests erfolgreich durchgelaufen sind, fahren Sie bitte, wie folgt fort:

- Legen Sie eine Verlinkung zur SelectLine Warenwirtschaft auf dem Desktop an. Danach öffnen Sie bitte die Eigenschaften dieser Verlinkung.

![image](https://user-images.githubusercontent.com/34538107/98664062-2cbbf680-234a-11eb-9ade-285cdafd7618.png)

- Dort gibt es eine Eigenschaft "Ziel", in der auf die SelectLine Warenwirtschaft verwiesen wird. In dieses Feld tragen sie bitte noch folgende Werte ein: `Bsp.: **servermode** **m**:wawi **kuerzel**:sv **passwort**:

'm': Der Name des Mandanten, Bsp. für den Mustermandanten, siehe oben
'kuerzel': Das Kürzel des WAWI-Benutzers
'passwort': Das zugehörige Passwort, falls vorhanden 

![image](https://user-images.githubusercontent.com/34538107/98664426-a6ec7b00-234a-11eb-8cdb-03291f32c108.png)

- Übernehmen Sie danach die Änderung und öffnen Sie nun die Anwendung erneut.

Treten dabei Fehlermeldungen auf?

Bei Fragen melden Sie sich gerne.

Mit freundlichen Grüßen,
Vivien Schuboth

**Comment by Logic-Bits** [comment]
Hallo,

der User stimmt und ist auch sysadmin.
Der User und Passwort ist korrekt, sonst würde ja der GET auch nicht funktionieren.

wenn ich mit servermode starte, dann passiert einfach gar nichts.

**Comment by VivienSchuboth** [comment]
Guten Morgen,

das scheint erstmal ok zu sein.

Die Problematik mit dem Umlaut im Servernamen könnte ich mir als Auslöser vorstellen.
Ich werde diese Situation versuchen nachzustellen.

Ich melde mich zurück, sobald ich neue Informationen habe.

Bis dahin,
Vivien Schuboth

**Comment by Logic-Bits** [comment]
Hallo,

gibt es schon ein Update?
Wir müssen unbedingt diese Woche das Problem noch gelöst bekommen.

Vielen Dank

**Comment by Logic-Bits** [comment]
Hallo @VivienSchuboth, ich bräuchte bitte Feedback, danke!

**Comment by VivienSchuboth** [comment]
Guten Morgen,

der Fehler wurde aufgenommen, nachgestellt und behoben.
Diese Fehlerbehebung steht Ihnen mit der nächsten Version (V21.3) zur Verfügung.

Beste Grüße
