### ISSUE TITLE
Artikel anlegen

### ISSUE THREAD

**Issue by Lars-Mue** [selectline-software/selectline-api#16]
Hallo ,

sehe ich das richtig, dass es aktuell nicht möglich ist Artikel über die API anzulegen?
Ist es geplant , so ein Feature einzuführen?

Mit freundlichen Grüßen

**Comment by jprause1234** [comment]
Hallo,

das ist richtig. Das ist ein Wunsch, welcher auch schon im Wünsche Forum stehen sollte. Bitte dort entsprechend Stimmen vergeben oder den Wunsch anlegen, denn diese Stimmen beeinflussen die Reihenfolge in der wir die Themen bearbeiten.

Viele Grüße
Jan

**Comment by ascharfen** [comment]
Hallo,

gibt es schon eine Umsetzung zur Möglichkeit der Artikelanlage? Mich würde insbesondere die Anlage von Stücklistenartikeln interessieren. Grüße!
