### ISSUE TITLE
Abruf von Positionen aus Beleg mit Kommentaren schlägt fehl

### ISSUE THREAD

**Issue by ThorstenPoppe** [selectline-software/selectline-api#160]
Hallo zusammen,

wir haben aktuell in der Version 21.2.3 ein Problem mit dem Abruf von Positionen über /Documents/{documentKey}/Positions.
In den Belegen werden häufig Kommentare verwendet, der Abruf schlägt dann mit der Meldung "ResponseCode": "42-000",  "Message":"SerialChargeKind.FromValue() Parametername: value Der tatsächliche Wert war .\" fehl.
Lösche ich die Kommentarzeile aus dem Beleg heraus, funktioniert der Abruf wieder.
Es handelt sich hierbei um bereits existierende Belege aus älteren Versionen, diese Kommentarzeilen haben im Feld SerieCharge einen Leerstring stehen.
Füge ich in der aktuellen Version eine Kommentarzeile zu, steht im Feld SerieCharge ein "O", dann funktioniert der Abruf auch wieder.
Ich werde nun beim Kunden die Kommentarzeilen updaten und im Feld SerieCharge ein "O" einfügen, damit die Abrufe wieder funktionieren.
Bitte um schnellstmögliche Korrektur!

**Comment by VivienSchuboth** [comment]
Guten Tag,

dieses Problem kann intern (noch) nicht nachgestellt werden.
Kommentare wurden in unserem Test, wie folgt angelegt:

```
POST {{url}}/Documents/PPZ072/CommentPosition
{
    "Name" : "Ein Test Kommentar",
    "AdditionalDescription" : "Test Comment",
    "Memo" : "Dies ist ein Kommentar zum Testen der Funktion",
    "Employee" :"2",
    "ReferenceCustomer" : "10021",
    "IsPrintLock" : "true",
    "CustomFields":
        {
            "Text1" : "abc"
        }
}
```

Es wurden neben Artikeln, ebenfalls mehrere Kommentare zu einem Beleg hinzugefügt, der in unserem Fall ein Packzettel ist.
Danach wurde eine Liste von allen Positionen zu diesem Beleg abgerufen.

`GET {{url}}/Documents/PPZ072/Positions`

Die Rückgabe erfolgte problemlos.

Was beinhalten Ihre Kommentare denn standardmäßig noch?
Sehen Sie wesentliche Unterschiede, die zum Nachstellen des Fehlers ausschlaggebend sein können?

Beste Grüße

**Comment by ThorstenPoppe** [comment]
Guten Morgen,

es handelt sich hierbei nicht um die Anlage von Kommentaren über die API, sondern den Abruf von bestehenden Belegen mit Kommentaren. 
Die Kommentare in den Belegen, die mit vorherigen Versionen der Warenwirtschaft angelegt wurden, enthalten im Feld SerieCharge einen Leerstring. Werden dann über die API die Positionen des Belegs abgerufen, kommt es zu der Fehlermeldung.
Wird in der obigen Version der Warenwirtschaft ein Beleg mit Kommentar Position angelegt, wird in das Feld SerieCharge ein "O" eingetragen, dann funktioniert auch der Abruf der Positionen über die API.

Viele Grüße

**Comment by SusanneSchadenberg** [comment]
Das Verhalten wird mit dem nächsten Hotfix korrigiert.

Eine schöne Weihnachtszeit und einen guten Start in das Jahr 2022 wünscht das Selectline Team.

**Comment by SusanneSchadenberg** [comment]
Geschlossen da dieser Fehler mit Version 21.3.5 behoben wurde.

Gruß Susanne
