### ISSUE TITLE
Übergabe eines Beleges Fehlermeldung WindowOnTheServerWasOpenedException

### ISSUE THREAD

**Issue by ThorstenPoppe** [selectline-software/selectline-api#161]
Hallo,

wir möchten Aufträge in Packzettel über die API übergeben, der Kunde hat das Kreditlimit überschritten.
Es erfolgt dann keine Übergabe, sondern die Exception WindowOnTheServerWasOpenedException mit ErrorCode -1
Gibt es eine Möglichkeit, die Übergabe trotzdem durchzuführen (Schalter, Parameter, etc.)?
Stichwort "Stiller Modus", wie bei der COM Schnittstelle.
Oder muss der SL Kunde die Einstellungen für das Kreditlimit so wählen, dass das Fenster bei der Übergabe nicht erscheint?

**Comment by VivienSchuboth** [comment]
Guten Tag,

derzeit gibt es noch keine Möglichkeit dieses Fenster zu unterdrücken, da eine Option, wie es sie auch für [einige andere Fenster](https://demo.slmobile.de/demoApi/Help/DefaultValues) bereits gibt, derzeit noch fehlt.

Ich nehme Ihren Wunsch daher erst einmal auf. Bis zur Umsetzung dieses Features muss leider das Kreditlimit beachtet werden, um diesem Fenster aus dem Weg zu gehen.

Eine Frage habe ich dafür noch:
Kommt Ihnen der Fehler bei der Umstellung des Belegstatus entgegen oder direkt bei dem POST zum Anlegen eines Belegnachfolgers?

Beste Grüße

**Comment by VivienSchuboth** [comment]
Guten Morgen,

welche Version setzen Sie denn ein?

Beste Grüße

**Comment by ThorstenPoppe** [comment]
Wir setzen die Version 21.2.3 ein.

**Comment by SusanneSchadenberg** [comment]
Hallo,
besteht das Problem immer noch bei Ihnen?

Mit der neuesten Version unserer Software kann ich das nicht nachstellen.
Über die Warenwirtschaft wurde ein Kunde mit Kreditlimit angelegt
und nachfolgend über die SelectLine API:

    ein Auftrag mit dem Kunden angelegt
    Positionen hinzugefügt, die einen Preis besitzen, der das Kreditlimit übersteigt
    der Belegbearbeitungsstatus geändert auf "Abgeschlossen"
    ein Belegnachfolger angelegt für Packzettel "P" und mit Übergabe der Positionen

Es folgte die Rückgabe der Nummer des angelegten Packzettels. Eine Fehlermeldung kam nicht zurück.
Haben Sie noch besondere Einstellungen oder Schritte durchgeführt?

Gruß Susanne
