### ISSUE TITLE
Internalserver Error beim Übertrag ins ARKALK Tabelle

### ISSUE THREAD

**Issue by Torchok19081986** [selectline-software/selectline-api#162]
Hallo , ich habe folgendes Problem. Ich versuche gerade via macro einen artikel anlegen und anschließend die tabelle ARKALK und ARTLIEF via macro zu beschreiben. Die Daten sind vorhanden , aber wenn man versucht diese Daten mit Hilfe der RestClient zu übergeben, dann erscheint InternalServerError als Response. 
mein macro hat 14 parameter. MacroParamter object hat Name und Value als property. Die Value ist von Datentyp String. 
Meine Vermutung ist, dass es an der float werten liegt, welche nicht richtig serialisiert wurden. 
 RestRequest request = new RestRequest("Macros/" + m.Name + "", Method.POST)
 {
     RequestFormat = RestSharp.DataFormat.Json
 };

  request.AddHeader("accept", "application/json");
  request.AddHeader("Content-Type", "application/json");
  request.AddHeader("Authorization", "LoginId " + AccessToken2);
  request.AddJsonBody(macroparamter_liste).

  string json = request.JsonSerializer.Serialize(macroparamter_liste);

  Log4NetClass.WriteDebugInfo(json);

  IRestResponse response = client.Execute(request);

  HttpStatusCode status = response.StatusCode;

  if(status == HttpStatusCode.OK)
  {
      MessageBox.Show("Artikel mit dem Nummer " + article.Text + " wurde in Artikelkalkulation Tabelle angelegt.", "Info", MessageBoxButton.OK, MessageBoxImage.Information );
  }
  else
  {
      MessageBox.Show("Artikel mit dem Nummer " + article.Text + " wurde in Artikelkalkulation Tabelle nicht angelegt.\r\nEs wurde Status : " + response.StatusCode + " von dem Server zurückgegeben." , "Info", MessageBoxButton.OK, MessageBoxImage.Warning);
  }

die seralisierte Json schaucht auch ok und folgendermaßen aus. 
[{"Name":"ArtNr","Value":"100002"},{"Name":"LetzerES","Value":"65"},{"Name":"LetzerESVon","Value":"70006"},{"Name":"AutoKalk","Value":"M"},{"Name":"AutoLieferant","Value":"NULL"},{"Name":"Kalkschema","Value":"A30"},{"Name":"ESPreis","Value":"0"},{"Name":"LPSumme","Value":"0"},{"Name":"Kalkulationspreis","Value":"65"},{"Name":"ListenPreis","Value":"0"},{"Name":"LetzerEK","Value":"65"},{"Name":"GroessterEK","Value":"65"},{"Name":"KleinsterEK","Value":"65"},{"Name":"MittlererEK","Value":"65"}]

kann jemand was dazu sagen ? Ich bin am verzeweiln 1000%.

**Comment by MatthiasGuse** [comment]
Hallo,

das Anlegen von Stamm- oder Bewegungsdaten per Makro wird seitens SelectLine nicht unterstützt oder supportet und geschieht immer auf eigene Gefahr.

Um auszuschließen, ob es sich um einen generellen API Fehler in handelt, können Sie testen ob sich ihr Makro im Makroassistenten der Warenwirtschaft gleich bzw. anders verhält.

Viele Grüße

**Comment by ThePholph** [comment]
Hallo,

wenn es sich bei dem Beispiel Json um die kompletten Daten handelt, fehlt hier etwas. Die Parameter stehen immer als Array in der Property "Parameters", zudem fehlt die Property "MacroName".

Hier ein Speispiel
```
{
  "MacroName": "TBXad001",
  "Parameters": [
     {
      "Name": "belegTyp",
      "Value": "#DocumentType#"
    },
   ...
  ]
}
```

Grüße

Daniel

**Comment by SusanneSchadenberg** [comment]
Hallo,
besteht das Problem bei Ihnen immer noch oder konnte es in der Zwischenzeit gelöst werden?
Gruß Susanne
