### ISSUE TITLE
ExtraFields werden nicht eingetragen

### ISSUE THREAD

**Issue by dotMortis** [selectline-software/selectline-api#163]
Hallo,

ich versuche mehrere Extrafelder in unserer BELEGP Tabelle zu füllen, leider sind nach erfolgreichem Anlegen eines "ArticleItem" für ein Document keine der Extrafelder gefüllt.

![image](https://user-images.githubusercontent.com/29275165/133242918-be1bcf48-9c8d-417a-9134-fbc7d9b375dd.png)

API-Call:
POST: https://xxxx/slmobileApi/Documents/C16003008/ArticleItem

```json
{
    "ArticleNumber":"7000457",
    "ExtraFields":{
        "_PRICE": "2",
        "_COMMISSIONNAME": "Test name"
    }
}
```

SelectLine: 21.2.4
SL_Mobile: 21.2.4

**Comment by dotMortis** [comment]
Okay, wir haben etwas rumgetestet.
Die Belegtabelle selbst hatte keine eigenen Extrafelder nur die BelegP Tabelle.
Als wir in der Belegtabelle einfach zum Testen ein Extrafeld angelegt haben, wurden die ExtraFelder in BelegP plötzlich wie erwartet gefüllt.

Anscheinend gibt es hier ein super seltsames Verhalten.

**Comment by dotMortis** [comment]
Guten Morgen,
danke schonmal.
Sehr seltsam, wir werden versuchen diesen Fehler zu reproduzieren und hoffe, dass wir genauere Informationen dazu finden.

**Comment by pietzschke** [comment]
Hallo!
Wir haben vermutlich das gleiche Problem, folgendermaßen konnten wir es auch in einem neuen vom Mustermandaten abgeleiteten Mandaten nachstellen.
Nach der Anlage haben wir direkt unter Vorgabewerte zwei neue Felder unter ExtraFelder für die Belegpositionen hinterlegt.
Bei der Anlage über die API werden diese nicht gepflegt.

**Comment by Micha-Richter** [comment]
Habt ihr die API/den BackendManager mal neu gestartet?
Das hat bei mir in diesen Fällen bisher immer geholfen.

Anscheinend kriegt die API diese Änderungen manchmal nicht mit..

**Comment by pietzschke** [comment]
Danke für den Hinweis, hab ihn nun mehrfach neu gestartet, unterschiedliche Mandaten genutzt.
Leider kein Erfolg, die Felder bleiben leer

**Comment by MatthiasGuse** [comment]
Die API kennt frisch angelegte Extrafelder und Druckvorlagen, sowie geänderte Mandanteneinstellungen erst, wenn man sich per [Logut] abmeldet oder das halt durch Beenden und Starten des Backendmanagers tut.

Das hier nicht alle Felder übernommen wurden, lag am verwendeten "Content-Type: application/x-www-form-urlencoded" der laut den Entwicklern unserer API nicht unterstützt wird. Die Dokumentation wird dahingehend erweitert.
Es wird immer JSON erwartet.

Viele Grüße

**Comment by dotMortis** [comment]
Scheint ja nun alles geklärt zu sein.
Danke nochmal.
