### ISSUE TITLE
Fehlermeldung aus Makro zurückmelden

### ISSUE THREAD

**Issue by MPIT-Eckart** [selectline-software/selectline-api#165]
Guten Tag,

ist es möglich für POST/Makros ein Makro so zu gestalten, dass eine Fehlermeldung zurückgegeben wird?

Hintergrund: Über das Makro soll soll im Kundenstamm ein Eintrag in einem Extrafeld gesetzt werden, wenn die Nummer vorhanden ist und ein Beleg für den Kunden existiert. Sofern die Nummer nicht vergeben ist, oder kein Beleg der Nummer zugewiesen ist, soll ein Fehler zurückgegeben werden.

**Comment by MatthiasGuse** [comment]
Hallo!

Rückgabewerte aus Makros sind derzeit nur bei API Makros möglich. Also nur über die Route /Macros/{macroFileName} 
Je nach Ergebnis Ihrer Aktion können Sie in dem Makro bspw. eine berechnete Spalte zurückgeben, in der sie den Erfolg bzw. Ihre Meldung zurückgeben. Eine Beschreibung der API Makros finden Sie hier: [https://demo.slmobile.de/demoApi/Help/HowToMacro](url)

Viele Grüße

**Comment by MPIT-Eckart** [comment]
Guten Tag Herr Guse,

ich danke für die Rückmeldung.
Das Makro konnte entsprechend eingerichtet werden und funktioniert!

Issue kann geschlossen werden.

Mit freundlichen Grüßen

Phillip Eckart
maswterplan IT GmbH
