### ISSUE TITLE
Paging Problem bei "StoreInformation"

### ISSUE THREAD

**Issue by timothy3001** [selectline-software/selectline-api#166]
Hallo zusammen,

mir ist gerade ein Problem beim HTTP API call `​/Documents​/{documentKey}​/Positions​/{identifier}​/StoreInformation` aufgefallen. Vermutlich kann ich da einen Workaround für finden, aber trotzdem sollte man das vielleicht fixen, hat mich etwas Zeit gekostet, das zu finden.

Entweder ich mache etwas grundlegend falsch, oder da passt was mit der Pagination nicht: Wenn ich einen Wareneingangbeleg habe, mit einer Seriennummer, kann ich die Lagerinformationen über `​/Documents​/{documentKey}​/Positions​/{identifier}​/StoreInformation` abrufen. Wenn ich die Page im Filter angebe, bekomme ich bei Page 0 UND bei Page 1 denselben Wert, mit demselben Identifier. 

Reproduzieren:
1. Bestellung oder ähnliches anlegen, mit einer Position
2. Beleg in Wareneingang überführen, Seriennummer vergeben
3. `​/Documents​/{documentKey}​/Positions​/{identifier}​/StoreInformation` aufrufen mit Page 0
4.  `​/Documents​/{documentKey}​/Positions​/{identifier}​/StoreInformation` aufrufen mit Page 1

Bei beiden Pages kommt nur ein Wert zurück (auch wenn items (Anzahl items pro Page) auf > 1 gesetzt ist), es ist aber derselbe Wert. Erwarte hätte ich, dass bei Page 1 eine leere Liste zurückgegeben wird. Diese wird jedoch erst bei Page 2 zurückgegeben.

~~Oder ist die Pagination 1-basiert?~~

EDIT: Ok, andere Abrufe von Listen scheinen 0-basiert zu sein.

**Comment by VivienSchuboth** [comment]
Guten Morgen,

ja, das Abrufen von Listen ist 0 basiert.

Zu ihrer anderen Schilderung folgendes:
Die Route `GET ​{{url}}/Documents​/{documentKey}​/Positions​/{identifier}​/StoreInformation`
besitzt neben dem `Filter`-Property, auch ein Property `Page`. 
Nutzen Sie dieses Property für Ihr Paging?
Wie sieht Ihr spezifischer Abruf denn aus?

Beste Grüße

Ausschnitt aus der öffentlichen Demo der SelectLine API Hilfe (Stand, 09/2021) :

![image](https://user-images.githubusercontent.com/34538107/134464573-d0a1ae64-b422-490e-9230-8a176dee1df7.png)

**Comment by SusanneSchadenberg** [comment]
Hallo,
bitte entschuldigen Sie die verspätete Rückmeldung.
In der aktuellen Version 21.3.4 kann ich das Verhalten bei documentPositionListFilter.page nicht reproduzieren. Bei documentPositionListFilter.items liefern 0 und 1 dieselben Daten.
Ich werde dafür einen Fehler aufnehmen.

Eine schöne Weihnachtszeit und einen guten Start in das Jahr 2022 wünscht das Selectline Team.

Gruß Susanne

**Comment by SusanneSchadenberg** [comment]
Hallo,
ich kann in der aktuellen Version den Fehler nicht repoduzieren.

Eine schöne Weihnachtszeit und einen guten Start in das Jahr 2022 wünscht das Selectline Team.

Gruß Susanne

**Comment by timothy3001** [comment]
Hallo,

vielen Dank, wünsche ich Ihnen auch.

Sorry, habe ganz vergessen, die Version zu nennen. Nur kurz als Nachtrag: Dateiversion: 20.1.2 Build 184700 

Werde bei uns mal ein Update veranlassen.

Viele Grüße
