### ISSUE TITLE
Falsche / Irreführende Fehlermeldung

### ISSUE THREAD

**Issue by Logic-Bits** [selectline-software/selectline-api#167]
Hallo,

KindFlag ist nicht gesetzt beim Anlegen von einem Beleg.
Fehlermeldung:

  "StatusCode": "BadRequest",
  "ResponseCode": "42-007",
  "Message": "Es wurde kein Parameter übermittelt. Nähere Informationen sind in den Details enthalten.",
  "Details": "documentKind"

nachdem "documentKind" gesetzt wurde kommt der Fehler natürlich wieder.
Könnte aber einigen Leuten das Troubleshooting sparen (KindFlag).

**Comment by MatthiasGuse** [comment]
Danke für den Hinweis. Wir werden das zukünftig verbessern.

**Comment by SusanneSchadenberg** [comment]
Hallo,
der Fehler wurde mit der aktuell ausgelieferten Version 22.1 behoben.
Gruß Susanne
