### ISSUE TITLE
Beleg Anlage funktioniert nicht

### ISSUE THREAD

**Issue by Logic-Bits** [selectline-software/selectline-api#169]
Hallo,

neue API Installation, alle Tests im Mobile Manger sind ok.
via SA Login.
API Login klappt auch.
SL Version 21.2.3

Status: 500
Response: 
{
  "StatusCode": "InternalServerError",
  "ResponseCode": "42-000",
  "Message": "Client.Send failed. See InnerException",
  "Details": null
}

Payload (klappt bei mir Lokal):

{"KindFlag":"A"}

Im LOG:

{ "Name": "SelectLine.Erp.WebApi.WebHost", "TimeStamp": "2021-09-17T12:30:00.0827850Z", "ServerTimeStamp": "2021-09-17T12:30:00.0827850Z", "Host": {"Name":"XXX-SL","Version":"Microsoft Windows NT 10.0.14393.0","UserName":"SelectLine","64bit":true}, "Process": {"FileName":"c:\\windows\\system32\\inetsrv\\w3wp.exe","Name":"w3wp","64bit":true,"ProcessId":6880,"ThreadId":143,"Runtime":"1:04:21:55.6497624","PrivateBytes":461742080}, "LogLevel": "Error", "Message": "Client.Send failed. See InnerException", "Exception": {"Message":"Client.Send failed. See InnerException","InnerException":{"Message":"Eine Ausnahme vom Typ \"SelectLine.Messaging.NamedPipe.NamedPipeClientCancellationException\" wurde ausgelöst.","StackTrace":"   bei SelectLine.Messaging.NamedPipe.NamedPipeClient.<SendAsync>d__10.MoveNext()\r\n--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---\r\n   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   bei SelectLine.Messaging.Friend.FriendClient.<SendInternalAsync>d__26.MoveNext()"}}, "CallerStack": ["SelectLine.Erp.WebApi.Controllers.Attributes.CatchExceptionAttribute.OnException(System.Web.Http.Filters.HttpActionExecutedContext context)","System.Web.Http.Filters.ExceptionFilterAttribute.OnExceptionAsync(System.Web.Http.Filters.HttpActionExecutedContext actionExecutedContext,System.Threading.CancellationToken cancellationToken)","System.Web.Http.Filters.ExceptionFilterAttribute.ExecuteExceptionFilterAsyncCore(System.Web.Http.Filters.HttpActionExecutedContext actionExecutedContext,System.Threading.CancellationToken cancellationToken)"] }

![grafik](https://user-images.githubusercontent.com/2421123/134298444-024b3e5e-49cb-410e-91c1-1d3e206310c3.png)

**Comment by Logic-Bits** [comment]
Hallo, SL ist an dem Problem. Backendmanager macht Probleme. Noch ist unklar warum.

**Comment by SusanneSchadenberg** [comment]
Hallo,
derzeit gibt es noch ein Problem beim automatischen Start des Backendmanagers.
Der Fehler liegt in der Warenwirtschaft. Der Backendmanager startet zwar automatsich aber die Backendwawi schließt sich nicht, wenn die DB-Verbindung verloren gegangen ist.
Der Fehler wird derzeit bearbeitet.
Gruß Susanne

**Comment by SusanneSchadenberg** [comment]
Hallo,
der Fehler wurde mit der aktuell ausgelieferten Version 22.1 behoben.
Gruß Susanne
