### ISSUE TITLE
Tabellenbezeichnungen in API-Dokumentation in Englisch

### ISSUE THREAD

**Issue by aameyer** [selectline-software/selectline-api#17]
Für einen Teil der Felder in der API-Dokumentation sind derzeit auch die Tabellen- und Spaltenbezeichnungen ins Englische übersetzt worden, bspw. GET.../DocumentKinds/{documentKindKey}

Name   string
String length: inclusive between 0 and 30   [VOUCHER TYPE].[Designation]

[VOUCHER TYPE].[Designation] hilft an dieser Stelle aber nicht weiter, die relevante Information wäre hier [BELARTEN].[Bezeichnung]. Oder soll die Dokumentation auf etwas anderes als den Eintrag in der Datenbank verweisen?

**Comment by VivienSchuboth** [comment]
Guten Tag,
anscheinend wurde an dieser Stelle zu viel übersetzt.
Danke für den Hinweis!

Gruß, 
Vivien
