### ISSUE TITLE
Belege die auf Punkt enden sind nicht abrufbar

### ISSUE THREAD

**Issue by timothy3001** [selectline-software/selectline-api#170]
Hallo *,

bei einem Kundenprojekt, das wir betreuen wird unter anderem ein Belegnummernkreis eingesetzt, der auf Punkt endet, aufgrund des Datums.

Ein Bestellbeleg kann daher folgenden Aufbau besitzen: `ABC19.8.`

Aufgrund des Punktes am Ende kann der Beleg offensichtlich nicht über die API abgerufen werden, zum Beispiel bei Nutzung des Endpunkts `/Documents/{documentKey}`.

Wenn ich einen Beleg anlege, der nicht auf einen Punkt endet, jedoch einen enthält, kann ich das Dokument problemslos  abrufen, bspw. `ABC19.8`

**Reproduzieren**:
1. Bestell-Beleg mit Belegnummer anlegen, die auf `.` endet (z.b. `ABC19.8.`)
2. Belegnummer über `/Documents/ABC19.8.` abrufen

Als Antwort erhält man einen 404 Not Found Error.

Ist dieses Verhalten bekannt? Gibt es hier evtl. einen Workaround? Den Punkt mittels `%2E` zu escapen hat leider nicht geholfen.

**Comment by VivienSchuboth** [comment]
Guten Abend,
wie bereits in der API-[Hilfeseite ](https://demo.slmobile.de/demoApi/Help/HowToEncodeUrlValues) geschildert, ist für die Encodierung in der Url das Prozentzeichen unzulässig.
Nutzen Sie bitte die Tilde **~**. 
Daraus folgt für Ihr Beispiel: **~2E**

Beachten Sie die Unterscheidung zwischen dem erwähnten QueryString (Encodierung mit %) und der URL inkl. ihrer Parameter (Encodierung mit der Tilde).

Beste Grüße,
Vivien
