### ISSUE TITLE
EAN

### ISSUE THREAD

**Issue by Logic-Bits** [selectline-software/selectline-api#171]
Hallo,

ist es möglich Artikel über die EAN in einen Beleg zu setzen?
(ohne Extra Query oder Artikelsuche).

Danke!

**Comment by MatthiasGuse** [comment]
Hallo,

nien, das ist nicht möglich. Die Artikelnummer, die Sie in einer Belegposition einfügen muss eindeutig sein und einer reellen Artikelnummer entsprechen.

Um einen Artikel anhand einer GTIN, Hersteller-Artikelnummer, Serie- / Charge oder Referenz zu ermitteln, können Sie die Route GET /Articles/{articleNumber} mit dem Parameter ?considerReferenceAndSerial=true verwenden. Anstelle von "{articleNumber}" geben Sie den entsprechenden Wert an über den Sie suchen wollen.

Bsp.: `.../slmobileApi/Articles/12345670/?considerReferenceAndSerial=true`

Viele Grüße
