### ISSUE TITLE
Formular Druck - Email

### ISSUE THREAD

**Issue by Grewamor** [selectline-software/selectline-api#174]
Hallo, ich versuche ein Formular per Mail zu versenden. Und erhalte folgenden Fehler. Können Sie mir helfen?

```
{
  "ResponseDetails": "Hinweis: Fehler beim Drucken: Fenster wird versucht zu öffnen: Bestätigen; CRM2 wurde bereits einmal erfolglos gestartet. Trotzdem noch einmal versuchen?; ",
  "ResponseType": "PrintDocumentInformation",
  "ErrorCode": -1
}
```
Aus der SelectLine heraus gibt es kein Fehler und kein Fenster, was auf geht. Die Mail wird gesendet.

![image](https://user-images.githubusercontent.com/18594343/136003013-d1f7b245-a688-4990-b6b6-fad80fced577.png)

SL: 21.2.7
Mobil: 21.2.7

**Comment by ThePholph** [comment]
Hallo,

ist denn das "Standard E-Mail-Programm" auf dem System der SL-API / SL-Mobile installiert und konfiguriert?
Hierbei ist es auch wichtig den Benutzerkontext zu berücksichtigen. Trotz dessen kann ich mir vorstellen, dass es evtl. Probleme geben wird, selbst wenn dies der fall ist. 

Ich würde hier ein kleines Tool oder einen Service schreiben, der den Druck des Dokuments übernimmt (via Sl.API) und das Resultat dann via smtp, EWS-API, RESTAi, etc. versendet.

Grüße

Daniel

**Comment by ThePholph** [comment]
Hallo,

aber die Option "Standard E-Mail-Programm" ist im Screenshot oben hinterlegt, also bei Ihnen eingetragen, oder?

Grüße

Daniel

**Comment by Grewamor** [comment]
Korrekt.

**Comment by Futo8681** [comment]
Hallo, 

ich bekomme die selbe Fehlermeldung beim Drucken über die API mit Druckziel E-Mail. 
Im Gegensatz zum Fall oben habe ich jedoch in den Mandanteneinstellungen eingestellt, dass auch für ausgehende E-Mails die interne Mailfunktion verwendet werden soll: 
![Bildschirmfoto 2022-01-31 um 10 57 30](https://user-images.githubusercontent.com/68660258/151773306-615217f9-23a8-421b-aea7-3cc717893683.png)

Wenn in SelectLine der Beleg (Auftrag) mit Druckziel E-Mail gedruckt wird, funktioniert auch alles einwandfrei. 
Der mit dem API Benutzer verknüpfte Benutzer hat auch alle benötigten Berechtigungen für das CRM Modul. 

Wie kann man den Fehler beheben? 

Beste Grüße

Tom

**Comment by SusanneSchadenberg** [comment]
Hallo,
vielen Dank für Ihre Nachricht bzw. Info.
Leider muss ich das Fehlerverhalten bestätigen.
Ihren Fehler habe ich aufgenommen und intern zur weiteren Prüfung/Behebung weitergeleitet.

Viele Grüße aus Magdeburg
Susanne

**Comment by MatthiasGuse** [comment]
Der Fehler wurde mit der kürzlich veröffentlichten Version 23.1.0 behoben.

Beste Grüße
