### ISSUE TITLE
Lagern von Handelsstückliste mit /Documents/{documentKey}/Positions/Store

### ISSUE THREAD

**Issue by h2-Systems** [selectline-software/selectline-api#175]
Zusatz zu Bug #143
(Belegübergabe mit Ändern des Lagers in der Belegpostition)

Wie mit dem Workaround im Issue #143 beschrieben, machen wir die Übergabe zuerst ohne Menge, aktualisieren dann mit `/Documents/{documentKey}/Positions/{documentPositionIdentifier}` das Lager in der Position und Lagern danach mit `/Documents/{documentKey}/Positions/Store` die Menge aus dem Übergebenen Beleg ein.

Dabei ist nun aufgefallen, dass der Lagerbefehl für eine Handelsstückliste zwar die Menge von 0 auf die angegebene Menge erhöht, jedoch keine Lagerung für die Artikel in der Handelsstückliste ausgeführt wird.
Wiederholen wir den Lagerbefehl auf die Handelsstückliste unverändert wird die Lagerung ohne Probleme ausgeführt.
Dies hat dann natürlich zur Folge, dass die Artikel der Handelsstückliste mit der Doppelten Menge gelagert werden.

Das Problem lässt sich folglich "umgehen" wenn der Lagerbefehl `/Documents/{documentKey}/Positions/Store`  für die Handelsstückliste 2 mal mit der halben Menge ausgeführt wird, was aber natürlich nicht zielführend sein kann.

**Comment by SelectLine** [comment]
Gerne können wir uns Ihres Problems bei SelectLine näher anschauen. Da der API-Support nicht Teil der Supportvertragsbedingungen ist, bieten wir Ihnen dies gerne als kostenpflichtige Dienstleistung an (Abrechnung erfolgt nach Aufwand).
Wenn Sie daran Interesse haben, wenden Sie sich bitte mit der Vorgangsnummer github-issue175 und Ihrer Fachhändlernummer an support@selectline.de
Sollte sich im Verlauf des Supportfalls herausstellen, dass das Problem auf einem Fehler der SelectLine API beruht, so werden Ihnen dafür keine Supportkosten berechnet.
