### ISSUE TITLE
POST ./Signatures

### ISSUE THREAD

**Issue by ThePholph** [selectline-software/selectline-api#177]
Hallo,

ich habe in meiner App nun die Funktion der Unterschriften eingefügt. Die Anlage funktioniert auch einwandfrei, jedoch werden  trotz Flag, die Unterschriften nicht überschrieben, wenn ein zweites Mal der Request durchgeführt wird (bspw. unleserlich, Nachtrag oder Änderung). Ich erhalte auch keine Fehlermeldung durch die API.

Vielen Dank.

Daniel

**Comment by ThePholph** [comment]
Hallo,

die 21.2.3

Grüße

Daniel

**Comment by SusanneSchadenberg** [comment]
Hallo Daniel,
bitte entschuldige die verspätete Rückmeldung. 
Wir konnten den Fehler nachstellen und werden diesen in einer der nächsten Versionen beheben.

Gruß Susanne
