### ISSUE TITLE
Die Eigenschaft konnte nicht zugeordnet werden

### ISSUE THREAD

**Issue by Logic-Bits** [selectline-software/selectline-api#178]
Hallo,

![grafik](https://user-images.githubusercontent.com/2421123/139440931-ff18a356-c093-46d6-abd7-1014614ab98f.png)

https://demo.slmobile.de/demoApi/swagger/ui/index#/Document/Document_ReadDocumentsAsync
kann man über die Dokumentsuche via API nicht in Extrafelder suchen?
Habs mit und ohne Unterstrich versucht.

Danke!

**Comment by ThePholph** [comment]
Hallo,

wie sieht denn der Request aus? Ich hätte es jetzt mit http://domain:port/api/Documents?filter=_ORDERGUID EQ 'xxxxxxxx-xxxx-4xxx-Nxxx-xxxxxxxxxxxx' versucht. Nutze die Funktion nicht, da die Suche bzw. das Filter über die API zu langsam für unsere Anwendungen ist.

Grüße

Daniel

**Comment by Logic-Bits** [comment]
Hallo,

der Filter ist ExtraFields._ORDERGUID, nach der "Model" Logik muss man filtern (so wars zumindest für andere Eigenschaften).

Danke für die Hilfe.

Gruß

**Comment by ThePholph** [comment]
Hallo,

das wird nicht funktionieren, da die Property hier "ExtraFieldsWithType" heißt und zudem noch ein Array ist, was ich bis heute nicht nachvollziehen kann. Via Get bekommt man ein Array geliefert und via Post muss ein Objekt ohne Array geliefert werden, für dieselben Felder. Als Begründung wurde genannt, dass die Datentypen ja erkennbar sein müssten. Was bei JSON eig. implizit erfolgt und auch durch jeden Parser erkannt wird, wenn es korrekt aufbereitet wird.

Wie es aussieht, arbeiten Sie auch mit der Codegenerierung für die Models von SL bzw. Swagger, was ich nur bedingt empfehlen kann. Da man hier extrem eingeschränkt wird, sobald Fehler oder unerwünschte Effekte der API umgangen werden müssen.

Grüße

Daniel

**Comment by VivienSchuboth** [comment]
Guten Morgen,
ich stimme Daniel zu, dass Ihr Wunsch - nach Extrafeldern bei der Belegabfrage zu filtern - nicht möglich ist.
Der Grund ist hierfür, dass das tabellenübergreifende Filtern bisher nur eingeschränkt bzw. gar nicht unterstützt wurde.
Falls dies gewünscht ist, kann ich Sie leider aktuell nur an das UserVoice-Forum weiterleiten, um auch die evtl. hohe Priorität für Sie aufzuzeigen.

Grüße,
Vivien
