### ISSUE TITLE
Anlage eines Journals geht nicht

### ISSUE THREAD

**Issue by Lars-Mue** [selectline-software/selectline-api#179]
Hallo, 

ich habe Probleme einen Journaleintrag über die API zu erstellen. 
Meine JSON sieht so aus: 
{
	"Date":"2021-11-05T08:05:41.4798184+01:00",
	"StatusId":1,
	"Label":"Test",
	"Text":"Test",
	"JournalLinkInformation":{
		"LinkType":"document",
		"DocumentTyp":"F",
		"DocumentNumber":"N3717"
	}
}

Der Beleg ist in der SelectLine ebenfalls vorhanden. 
![image](https://user-images.githubusercontent.com/64889790/140474469-ed52c6fe-9673-49b5-8e2d-248616f4e15f.png)

Die API meldet mir aber folgendes zurück: 

![image](https://user-images.githubusercontent.com/64889790/140474580-d907cf49-32c4-4973-8c09-e079ad2c0984.png)

Woran liegt das, dass die API den Beleg nicht finden kann?
Grüße 
Lars

**Comment by VivienSchuboth** [comment]
Guten Tag,
Sie haben _DocumentTyp_ anstatt _DocumentType_ geschrieben. 
Das dürfte das Problem bereits lösen.

Grüße,
Vivien

**Comment by bastelbastel** [comment]
Hallo,

nach diesem Fehler habe ich auch schon eine Weile gesucht.
Ich hatte das (falsche) Beispiel aus Swagger kopiert.

![Swagger_Journal](https://user-images.githubusercontent.com/75033704/142894269-fcc4965a-71ac-4b01-a0d8-8be55f1e2be8.png)

viele Grüße

**Comment by SusanneSchadenberg** [comment]
Hallo,
vielen Dank für den Hinweis.
Das "falsche" Beispiel  wird in der nächsten Version korrigiert.
Viele Grüße aus Magdeburg
Susanne
