### ISSUE TITLE
ExtraFelder in Beleg/BelegP füllen

### ISSUE THREAD

**Issue by Lars-Mue** [selectline-software/selectline-api#18]
Hallo,

wie ist es möglich, Angelegte Extra Felder über die API zu füllen.
Die Belege / Positionen werden Ohne Probleme gefüllt bzw. Erstellt.
Die Extra Felder bleiben allerdings leer und wir bekommen keinen Fehler als Response.

Vielen Dank im Voraus für die Antwort.

Grüße

**Comment by Lars-Mue** [comment]
Hallo, 

dieses Thema ist uns sehr wichtig.
Wir müssten so schnell wie möglich hierfür eine Lösung finden. 
Vielen Dank.

**Comment by jprause1234** [comment]
Hallo,

dass muss im Body in folgendem Format angegeben werden:
"ExtraFields":
    {
      "_EXTRABELEG" : "Test",
      "_EXTRABELEG1" : "Test",
      ...
    }
Hierbei steht links der Name des Extrafeldes und rechts der zu schreibende Wert.

Viele Grüße
Jan Prause

**Comment by ThePholph** [comment]
Hallo,

hierbei ist es nur etwas verwirrend, da im POST "ExtraFields" als Objekt übergeben werden muss und via GET erhält man "ExtraFieldsWithType" als Array mit Angabe des Datentyps. Was aufgrund implizierter Erkennung der Datentypen in JSON nicht notwendig wäre.

Viele Grüße

Daniel

**Comment by Lars-Mue** [comment]
Hallo,

so wie Jan Prause das geschrieben hat habe ich das ganze auch schon versucht.
Allerdings geht der Request einfach durch, der Beleg wird angelegt aber die Extra Felder bleiben leer.

Grüße

**Comment by jprause1234** [comment]
Ich habe sowohl das Anlegen als auch das Aktualisieren von Belegen (Positionen habe ich nicht erneut getestet) ausprobiert und dabei funktionierte alles wie es sollte.
Ist es möglich den Body hier mal zu posten, der bei der Anlage gesendet wird?

Viele Grüße
Jan Prause
