### ISSUE TITLE
Backendmanager startet nicht automatisch

### ISSUE THREAD

**Issue by Logic-Bits** [selectline-software/selectline-api#180]
Hallo,

ich dachte der Backend Manager startet automatisch falls der noch nicht läuft?
Oder gibts Gründe dass der nicht autom. startet?

  "StatusCode": "InternalServerError",
  "ResponseCode": "42-000",
  "Message": "Es konnte keine Verbindung zur Backend-Wawi hergestellt werden.\r\nBitte prüfen Sie im Mobile Manager ob der BackendManager aktiv ist.",
  "Details": null

**Comment by SusanneSchadenberg** [comment]
Hallo,
derzeit gibt es noch ein Problem beim automatischen Start des Backendmanagers.

Der Backendmanager startet nicht automatisch, wenn der SQL-Server noch nicht erreichbar ist.
Ist das bei Ihnen auch der Fall?

Viele Grüße aus Magdeburg

**Comment by Logic-Bits** [comment]
Hallo, sorry - die Nachrichtig habe ich übersehen.
Gut Möglich - es ist ein Extra Server, da läuft nur SL-Mobile / API.
Version 21.3.0

Heute wieder der Fall beim Kunden:

  "StatusCode": "InternalServerError",
  "ResponseCode": "42-000",
  "Message": "Es konnte keine Verbindung zur Backend-Wawi hergestellt werden.\r\nBitte prüfen Sie im Mobile Manager ob der BackendManager aktiv ist.",
  "Details": null
}

Status: 500
Response: 
{
  "StatusCode": "InternalServerError",
  "ResponseCode": "42-000",
  "Message": "Es konnte keine Verbindung zur Backend-Wawi hergestellt werden.\r\nBitte prüfen Sie im Mobile Manager ob der BackendManager aktiv ist.",
  "Details": null

Ich kann aber dann in den Manager rein gehen und auf starten klicken. Dann funktioniert es.

**Comment by rogeralthaus** [comment]
Hallo Zusammen
Ich habe das Problem auch. (21.3.10) Bekomme die Meldung immer wenn ich ein [POST]/Documemts/ (Create) versuche.
Nach 30 Sekunden ist die Meldung da..
Auch bei mir ist der Backend-Manager immer am laufen.

**Comment by aameyer** [comment]
Ich habe hier mit einer 21.3.6 ähnliche Probleme. Teilweise wird der Login aber auch abgelehnt mit 

Status 409
Response: {
"StatusCode":"Conflict",
"ResponseCode":"02-003",
"Message":"Authentifizierung fehlgeschlagen.",
"Details":null}

ResponseCode 02-003 bedeutet laut Dokumentation: "Der Benutzer ist nicht authentifiziert oder die Anmeldeinformationen sind inkorrekt." Mit dem gleichen Login ist eine Anmeldung zu einem späteren Zeitpunkt jedoch ohne Fehler möglich. 
Kann dies auch damit zusammenhängen, dass der Backendmanager nicht vollständig gestartet ist?

Oder wird ResponseCode 02-003 ggf. auch zurückgegeben, wenn einfach keine Lizenz für den zugehörigen WaWi-Benutzer verfügbar ist?

**Comment by rogeralthaus** [comment]
Update:
Der SelectLine.API.Backend.exe hat nach kurzer Zeit beendet. Möglicherweise wegen SQL-Verbindungsproblemen.
Habe den Fehler wiederholt im SQL-Log 
**C:\ProgramData\SelectLine Software\Mobile Anwendungen\Logs\SelectLine.API.Backend\%Username%**
gefunden.

```
{
	"Name": "SQLServer",
	"TimeStamp": "2022-02-28T16:40:30.036Z",
	"ServerTimeStamp": "2022-02-28T16:40:30.036Z",
	"Host": {
		"Name": "SENSWS04",
		"Version": "Windows Server 2019 (Version 10.0, Build 17763, 64-Bit-Edition)",
		"UserName": "Administrator"
	},
	"Process": {
		"FileName": "C:\\Program Files (x86)\\SelectLine Software\\Mobile Anwendungen\\SelectLine API Backend\\SelectLine.API.Backend.exe",
		"Name": "SelectLine.API.Backend.exe",
		"ProcessId": "2228",
		"ThreadId": "504",
		"Runtime": "00:00:04.7160000",
		"MemoryPrivateBytes": 98172928
	},
	"LogLevel": "Error",
	"Message": "TXSQLServer.SQLConnect",
	"Exception": {
		"Type": "EMSError",
		"Message": "TCP Provider: An existing connection was forcibly closed by the remote host.\\n\\nExceptionklasse: EMSError\\nSQL Server Fehlernummer: 10054\\nOle Fehlernummer: -2147467259\\nData Access Fehlernummer: 10054\\nServername: \\nLetzter Fehler: TCP Provider: An existing connection was forcibly closed by the remote host.\\n\\nProzedur: \\nZeile: 0"
	},
	"Program": {
		"Version": "21.3.10.0"
	}
}
```
Habe auf dem API-Server den Native Client aktualisiert auf 11.0.7001.0.
https://www.microsoft.com/en-US/download/details.aspx?id=50402

Diese Meldungen bleiben jetzt aus und der Prozess stirbt nicht mehr nach kurzer Zeit.
Allerdings dauert es immer nach dem Login Request immer noch fast 30 Sekunden bis der
SelectLine.API.Backend.exe im Taskmanager erscheint.
Wenn ich also anmelde und dann 30 Sekunden warte bevor ich /Document/Create absende, funktioniert es dann fehlerfrei.

**Comment by aameyer** [comment]
Ich habe jetzt auf unserem System das Problem, dass die Fehlermeldung "Es konnte keine Verbindung zur Backend-Wawi hergestellt werden.\r\nBitte prüfen Sie im Mobile Manager ob der BackendManager aktiv ist." dauerhaft auftritt und auch nicht mehr zu beheben ist. Wir haben inzwischen alle ggf. verantwortlichen Prozesse sowohl über den SL Mobile Manager als auch über den Taskmanager neu gestartet und inzwischen auch den kompletten Server neu gestartet, und der Fehler bleibt bestehen.

**Comment by rogeralthaus** [comment]
Wird der Prozess "SelectLine.API.Backend.exe" gar nie gestartet? (Im Taskmanager überwachen.) Das kann schon mal bis zu 30 Sekunden dauern. Ist der Backend-Manager Prozess denn am laufen?
Was steht in den Logdateien?

**Comment by SusanneSchadenberg** [comment]
Hallo ,
der Fehler wurde mit der aktuell ausgelieferten Version 22.1 behoben.
Gruß Susanne

**Comment by aameyer** [comment]
Hallo,
wir haben nach einem Update auf die 22.1.2 weiterhin das Problem, dass der Backendmanager nach einem Serverneustart nicht  korrekt startet. Im Mobile Manager sind alle Tests erfolgreich, trotzdem ist die Route für die API nicht verfügbar. Nach Beenden und erneutem Starten des Backend-Managers ist die Route dann auch wieder normal verfügbar. Das Fehlerbild ist aber zumindest anders als vorher, statt der Rückgabe einer Fehlermeldung ist die gesamte API einfach nicht erreichbar.

**Comment by aameyer** [comment]
Hallo,
ein zweites Problem: Auf einem weiteren System mit der 22.1.2 erhalte ich jetzt wieder die Fehlermeldung "Es konnte keine Verbindung zur Backend-Wawi hergestellt werden.". Am Vortag war die Backend-Wawi noch vorhanden, und dieser Server wurde nicht neu gestartet, er Dienst sollte also durchgelaufen sein. Im Gegensatz zum anderen System (siehe Eintrag vom 1.7.) ist hier die API-Route selbst erreichbar, gibt aber entsprechende Internal Server Errors zurück.
