### ISSUE TITLE
Inventuranlage

### ISSUE THREAD

**Issue by burgt** [selectline-software/selectline-api#181]
Hallo,

ich habe das Problem das ich keine Inventurbelege anlegen kann. Laut Dokumentation 

https://demo.slmobile.de/demoApi/Help/Api/POST-Documents

wird der Belegtyp I zugelassen. Löse ich eine Beleganlage über den o.g. Befehl aus erhalte ich folgenden Responsecode:

{
  "StatusCode": "BadRequest",
  "ResponseCode": "42-017",
  "Message": "Der Belegtyp 'documentKind' ist für diese SelectLine API Anfrage nicht zulässig.",
  "Details": {
    "failure": "Belegtyp I wird nicht unterstützt."
  }
}

Ist nun die Dokumentation falsch oder liegt die API falsch?

**Comment by SusanneSchadenberg** [comment]
Hallo,
Inventuren werden über eine gesonderte Funktion/Controller aufgerufen bzw. bearbeitet 
z.B. put/Inventories/{number}/Warehouses/{warehouse}/Articles/{article}

Eine detaillierte Beschreibung finden Sie auf der API Hilfeseite unter Startseite / API-Funktionen / **Inventory** 

Viele Grüße aus Magdeburg
Susanne

**Comment by burgt** [comment]
Hallo,

das hatte ich gesehen, aber über diese Funktion lässt keine neue Inventur anlegen, sondern lediglich eine bestehende bearbeiten.

Grüße,
Thorsten Burg

**Comment by SusanneSchadenberg** [comment]
Hallo Herr Burg,
derzeit ist es leider nicht möglich, eine Inventur über die API anzulegen.

Gern können Sie hierzu einen Eintrag in unserem Wunschforum verfassen bzw. zu einem evtl. bereits vorhandenen mit abstimmen.
Nur so können wir herausfinden, inwieweit Ihre Anforderung auch von anderen Anwendern gewünscht wird.

Grüße
Susanne
