### ISSUE TITLE
WindowOnTheServerWasOpenedException

### ISSUE THREAD

**Issue by Logic-Bits** [selectline-software/selectline-api#182]
WindowOnTheServerWasOpenedException wird ausgegeben wenn man einen Beleg anlegen möchte mit einer existierenden Belegnummer.
Ein eigener Fehlercode wäre doch hier passend dass man darauf reagieren kann.

Danke

**Comment by SusanneSchadenberg** [comment]
Hallo,
vielen Dank für Ihren Hinweis. Welche Version ist bei Ihnen im Einsatz? Bei meinen Versuchen wird zusätzlich als Detail "Die Aktion wurde abgebrochen, weil versucht wurde ein Fenster zu öffnen.", angezeigt.

**Comment by Logic-Bits** [comment]
Hallo,

war die aktuellste 21.3.3.
Ja die Info wird auch angezeigt - aber das zusätzliche Detail bringt ja auch icht mehr Infos sondern schreibt das nur "Menschlich" aus.

Ich muss ja als Software i-wie darauf reagieren und dazu werden Details gebraucht wie Ihr Sie ja schon hier habt: 
https://demo.slmobile.de/demoApi/Help/ResponseCodes

(Ich geh davon aus aus dass WindowOnTheServerWasOpenedException immer kommt wenn ein Fenster sich öffnet und nicht ausschließlich bei vorhandener Belegnummer).

Gruß

**Comment by SusanneSchadenberg** [comment]
Sicherlich haben Sie recht. Für mich war es erst einmal wichtig zu wissen, ob die Details mitkommen oder ob dort ein grundsätzlicher Fehler vorhanden ist. 
Ich nehme den „Fehler“ auf und wir werden den demnächst eintakten.

Danke für Ihre Hilfe!
Beste Grüße

**Comment by SusanneSchadenberg** [comment]
Hallo,
der Fehler wurde mit der aktuell ausgelieferten Version 22.1 behoben.
Gruß Susanne
