### ISSUE TITLE
Fehler in Documents bei ./POST u. ./PUT mit Projektbezug

### ISSUE THREAD

**Issue by ThePholph** [selectline-software/selectline-api#184]
Hallo,

seid der 21.3.6 bekommen wir bei POST und PUT von Belegen mit Projektbezug folgenden Fehler:

```
{
    " StatusCode ": " BadRequest ",
    " ResponseCode ": " 42 - 031 ",
    " Message ": " UpdateDocumentErrorException ",
    " Details ": {
        " ResponseDetails ": " Das Feld[Projekt]darf nicht geändert werden.",
        " ResponseType ": " UpdateDocumentError ",
        " ErrorCode ": -1
    }
}
```

Hierzu gibt es keinen Hinweis unter https://apiupdate.selectline.de/ oder in der API-Dokumention. Es gibt zwar eine neue Route Documents/{documentKey}/Project jedoch keinen Hinweis, dass das Feld ProjectId nun ReadOnly ist! Aktuell sind dadurch alle unsere Anwendungen bei mehreren Kunden betroffen!

Zudem lässt sich über die neue Route das zugeordnete Projekt nicht mehr nachträglich ändern oder entfernen. Was ein Rückschritt ist für unsere Anwendungen, da eine aus versehene Falschzuordnung nicht rückgängig gemacht werden kann.

**Comment by SusanneSchadenberg** [comment]
Hallo,
zu erst möchte ich Ihnen ein gesundes neues Jahr wünschen

Mit der Version 21.3 wurde eine neue Route für die Zuordnung eines Projektes zur Verfügung gestellt. 
Diese löst mit dieser Version die kurzfristig bestandene Unterstützung einer Projektzuordnung über die Anlage und Bearbeitung der Belege ab, da es dabei häufig zu Konflikten kam, die das erwartete Ergebnis verfälscht haben.

Leider hatten wir es verpasst, die neue Route zu dokumentieren, dafür möchte ich mich entschuldigen.

Dass durch die neue Route ein nachträgliches Ändern oder Entfernen von zugeordneten Projekten nicht zugelassen wird, haben wir aufgenommen. Die Umsetzung wird in einer der nächsten Versionen erfolgen. Wann genau eine Umsetzung erfolgen wird, kann ich diesen Moment noch nicht sagen.

**Comment by ThePholph** [comment]
Hallo,

vielen Dank für die Information. 

Bzgl. der Einführung neuer Routen zu Objekten möchte ich noch allgemein etwas anmerken, da in der API immer relativ schnell neue Routen erstellt werden. 

Neue Routen, die eingeführt werden für Dinge, die eig. sehr gut über PUT des eigentlichen Objekts funktionieren und im gleichen Kontext agieren, führen zur Verlangsamung der Performance sowie unnötiger Komplexität auf der Clientseite. Da in dem Fall der Projektzuordnung nun z.B. 2 statt 1 Request erfolgen muss. Dies betrifft besonders Anwendungen, die die Bearbeitung von Belegen umfänglich ermöglichen. Zudem muss immer eine separate Validierung der Änderungen von Properties erfolgen, um diese auf die einzelnen Requests aufzuteilen. 

Neue Routen machen meines Erachtens eig. nur Sinn, für in sich abgeschlossene Operationen oder in einem separaten Kontext. Konflikte lassen sich auch durch Validierungen vermeiden. Eine API sollte immer offen programmiert werden, mit dem Ziel, dass Anforderung durch den Entwickler selbst gelöst werden können. Automatismen oder proprietäre Anforderungen zu lösen sollten nicht das Ziel sein oder zumindest nicht zu Einschränkungen der API führen.

Vielen Dank.

Viele Grüße

Daniel

**Comment by MatthiasGuse** [comment]
Hallo Daniel,

danke für Deine Antwort. Nachvollziehbar und von euch zu erwarten gewesen.
In dem Fall ist es leider so, dass die eigentliche Erweiterung der Projektzuordnung nicht korrekt in die Route der Beleganlage implementiert wurde. So konnte es beispielsweise bei der Beleganlage dazu kommen, dass man eine Fehlermeldung zu einer fehlerhaften Projektzuordnung erhalten hat, jedoch die Antwort zur Beleganlage verloren ging. Daher haben wir das kurzer Hand auf die neue Route ausgelagern müssen. Dass diese Funktion bereits so umfangreich genutzt wurde, war uns nicht bewusst. Ja, du hast Recht - das hätte unter dem Gesichtspunkt "Breaking-Changes sind bestmöglich zu vermeiden" so nicht passieren dürfen. Hier haben wir bereits weitere Maßnahmen ergriffen um soetwas zukünftig weiter zu verbessern.

Aus Sicht der API ist die eigene Route für die Funktionalität der Projektzuordnung jedoch der richtige Weg, da eigene Validierungen laufen und verschiedene Fehlermeldungen zurückgegeben werden können, die nichts mit der Beleganlage zu tun haben. In der Warenwirtschaft ist das auch eine separate Funktion. Die Validierung auf euch als API Programmierer abzuschieben, ist aus unserer Sicht kein guter Weg, da ihr dazu ja Kenntnis über unsere Validierung haben müsstet, was wiederum auch die Komplexität eurer Anwendung und unseren Dokumentationswaufwand erhöhen würde. Eine unzureichende Validierung würde unter Umständen zu fehlerhaften Daten führen, was wir als Hersteller natülich vermeiden möchten.

Für das Entfernen einer Projektzuordnung werden wir euch kurzfristig auch eine eigene Route zur Verfügung stellen. Sobald die da ist, erhaltet ihr eine Info von uns.

Viele Grüße

Matthias

**Comment by ThePholph** [comment]
Hallo Matthias,

vielen Dank für die ausführliche Antwort. Das mit der Validierung ist etwas falsch rüber gekommen. Natürlich sollt das lieber Ihr erledigen. Ich meinte damit nur, dass das Problem auch durch eine Validierung eurerseits gelöst werden kann. Was ich mit selbst lösen meine, ist dass wir als Entwickler nur die richtigen Möglichkeiten brauchen, so dass Automatismen, die es in der WaWi und COM gibt, nicht nötig sind und es euch als Bereitsteller der API auch einfacher gemacht werden kann. Ich weiß, dass es technisch bei eurer Lösung schwierig ist und andere Partner das Gegenteil wünschen 😄, aber ich wollte es einfach nochmal anbringen.

Finde es sehr gut, dass Ihr die Probleme nachvollziehen könnt und hier Anregungen für Verbesserungen aufnehmt! Für uns ist es einfach nur wichtig verlässliche Lösungen für unsere Kunden bereitzustellen, die nicht bei jedem Update tiefgreifende Anpassungen erfahren müssen. 

Dank dir und ein schönes WE.


Viele Grüße 

Daniel

**Comment by MatthiasGuse** [comment]
Die neue Route zum entfernen einer Projektzuordnung steht mit der Version 21.3.9 zur Verfügung.
