### ISSUE TITLE
Fehler bei Positionsanlage

### ISSUE THREAD

**Issue by babicsal4u** [selectline-software/selectline-api#185]
Hallo
Ich wollte eine Position bei einem bestehenden Beleg anlegen aber ich kriege immer die gleiche Fehlermeldung.
[felherMeldungPositionAnlegen.txt](https://github.com/selectline-software/selectline-api/files/7774010/felherMeldungPositionAnlegen.txt)
Und hier ist mein JSON, den ich schicke:
[jsonPositionSchicken.txt](https://github.com/selectline-software/selectline-api/files/7774013/jsonPositionSchicken.txt)
Mein Backendmanager funktioniert normal, die Belege sind vorhanden...
Hat jemand Ideen?

Danke

**Comment by babicsal4u** [comment]
Ich habe das Beispiel aus API.postman collection benutzt und zwar Zeile 2171 (Create article position)

**Comment by ThePholph** [comment]
Hallo,

"sample string 1" und "Identifier" fallen sofort auf. Ist das wirklich der Request der abgeschickt wurde?

Viele Grüße

Daniel

**Comment by babicsal4u** [comment]
> Hallo,
> 
> "sample string 1" und "Identifier" fallen sofort auf. Ist das wirklich der Request der abgeschickt wurde?
> 
> Viele Grüße
> 
> Daniel

Hallo Daniel,
Danke, aber ich habe das Problem gefunden. Bei ContentType musste ich application/json stellen und das habe ich leider nicht gemacht. 
Lg
