### ISSUE TITLE
Vergleich API <-> COM - wer kann mir da etwas konkretes sagen?

### ISSUE THREAD

**Issue by mfahs** [selectline-software/selectline-api#186]
Hallo zusammen!
In Bezug auf die API bräuchte ich von Wissenden mal eine Info: Ein Kunde von uns setzt seit ewigen Zeiten ein sehr stabil laufendes Programm zur Übergabe von Aufträgen an die Warenwirtschaft ein, das natürlich die gute alte COM-Schnittstelle nutzt. Jetzt laufen bei dem Anwender mittlerweile so viele Aufträge auf, dass es zu einem zeitlichen Problem kommt. Vergangene Woche mussten 2000 Aufträge am Stück eingelesen werden, für die das Programm dann ca. 6 Stunden gurgelte. Fehlerfrei, aber eben 6 Stunden... 
(Fairerweise muss ich gestehen, dass ich die COM-Schnittstelle nach jeweils 20 Aufträgen beende und dann wieder neu öffne, was natürlich immens Zeit kostet. Das musste leider sein, weil die COM-Schnittstelle sonst nach einer Zeit irgendwann die Ohren anlegte und nicht mehr ansprechbar war.)
  
Nun die Frage: Wenn wir das Programm auf die API umstellen - ist dann eine signifikante (!), zumindest deutlich spürbare  Geschwindigkeits-Steigerung zu erwarten? Wenn das mit "JA" beantwortet werden kann, könnte man sich der Idee mal nähern und schauen, ob alle benötigten Funktionen der COM-Schnittstelle auch in der API vorhanden sind. 
Wenn aber nur ein "Nö" oder "Vielleicht" oder "Hmmm..." kommt, könnne wir uns den ganzen Aufwand sparen.

Gibt es hier jemanden, der mir in Bezug auf die Geschwindigkeit von COM und API (gerne auch "bauchmässig"!) etwas sagen kann? Vielen Dank dafür!

Grüße aus Hamburg,
Martin Fahs

**Comment by mfahs** [comment]
Moin Thorsten,

vielen Dank - das ist mal eine hilfreiche Aussage! Wenn ich das zusammenfasse, hört sich das nach 
- stabiler als COM
- schneller. Keine Rakete, aber schneller. (Wenn Du schreibst 20-25 Aufträge/Minute, würde das bei 2000 Aufträgen ca. 1.75 - 2 Stunden bedeuten. Das ist ja schon mal eine Verbesserung!

Dann lege ich nochmal nach: Im konkreten Fall mussten wir sogar verhindern, dass das Programm auf mehreren Arbeitsplätzen gleichzeitig zur Übergabe von Aufträgen gestartet wird, weil es sonst die COM-Schnittstelle zerrissen hätte. 
Wie würde da wohl die API mitspielen? Wäre es denkbar, dort die Übergabe auf drei Arbeitsplätzen zu starten? (was vermutlich dann aber wieder den Zeitbedarf hochschrauben würde...)

Vielen Dank für die Infos!
Martin

**Comment by Micha-Richter** [comment]
Hallo Herr Fahs,

das können Sie sicher tun, aber die 3 Clients laufen dann gegen dieselbe API. 
Sie würden aus meiner Sicht nichts gewinnen (und bauchmäßig eher noch Probleme "heraufbeschwören"..).

**Comment by mfahs** [comment]
Gut. Dann war mein Gedanke völlig richtig. 
Dann lassen wir mal schnell die Finger davon ;-)

Danke!

**Comment by ThorstenPoppe** [comment]
Warum wollt ihr das auf 3 Clients gleichzeitig starten?
Eigentlich reicht doch eine Anwendung, die die Auftragsdaten an die API sendet, oder?
Bei mehreren Startvorgängen müsst ihr ja auch die Auftragsdaten splitten, damit nicht aus Versehen was doppelt angelegt wird.
Ich denke, das wäre hier ein klassischer Fall einer "Server Anwendung".
Die API ist generell schon etwas langsamer durch das Frage / Antwort Spiel, bzw. die Netzwerk Latenz.
Die Abfrage von Daten machen wir in den meisten Fällen doch weiterhin über direkte SQL-Anbindung.
Dafür ist sie aber tatsächlich stabiler und muss nicht erst "gestartet" werden, was bei der COM ja durchaus 30 Sekunden dauern kann.

**Comment by mfahs** [comment]
>> Warum wollt ihr das auf 3 Clients gleichzeitig starten?

In dem Program, in dem die Aufträge auflaufen, wird auch noch einiges von den MA geprüft und ergänzt, bevor es in die Wawi geschaufelt werden lann. Und da mehrere Mandanten in der Wawi betroffen sind, können die sich da im Haus problemlos einige, wer was übergibt. Aber was Michael Richter schon sagte: EINE API kann natürlich nur EINEN Auftrag gleichzeitig erledigen. Wenn also drei Jobs abgefeuert werden, dauert das Anlegen eines Auftrages eben auch 3x so lange wie wenn nur ein Job ankommt, Aber es ist ja schon mal erfreulich, dass es in so einem Fall die API nicht zerreissen würde :-)

**Comment by MatthiasGuse** [comment]
Hallo Herr Fahs,

im Fall der drei "gleichzeitig" arbeitenden User würden sie ja korrekterweise auch verschiedene User für die API benutzen. Insbesondere bei verschiedenen Mandanten ist ja einem User immer ein Mandant zugeordnet. 
Jeder User erhält in der API sein eigenes Backend, womit dann auch verschiedene Aktionen, wie z.B. die Beleg- / Positionsanlage, parallel stattfinden können. Die Rechnung - 3 Jobs auf einmal dauern so lange wie 3 hintereinander - würde ich daher so nicht stehen lassen wollen, wenn es verschiedene User sind. Das wird dann schneller sein.
Letztendlich spielt die Konstellation von Webserver und SQL Server hier bei der Performance auch mit hinein. Der (Netzwerk-)Zugriff der API Installation auf den SQL Server kann hier entscheidend für Geschwindigkeit der API-Anwendung werden.

Einen pauschalen Geschwindigkeitsvergleich kann man so leider nicht abgeben. Sollten Sie größere Änderungen an Ihrer Anwendung vorhaben, lohnt sich ein bisschen tieferer Blick in die API bestimmt. Beispiele finden Sie ja hier https://github.com/selectline-software/selectline-api. Auf ganz ganz lange Sicht kann die API aber nur das Mittel der Wahl werden. ;-)

Ein Dankeschön auch an die Mitwirkenden!
Viele Grüße

**Comment by mfahs** [comment]
Hallo Herr Guse,

haben Sie vielen Dank für die ganzen Infos! 
Großartig, wenn 3 Jobs parallel _nicht_ so lange dauern wie drei Jobs seriell! 
Wir haben auch schon den Auftrag, das Programm umzubauen - ich bin gespannt, wie die Performance dann in unserem konkreten Beispiel steigt!

Viele Grüße aus Hamburg!

**Comment by MatthiasGuse** [comment]
Hier nochmal zum Abschluss ein nicht ganz representativer Vergleich, wie sich die Performance verhält, wenn mit mehreren Usern parallel gearbeitet wird. Getestet mit Postman unter "Idealbedingungen" - SQL Server, Wawi, API gemeinsam auf einer HyperV Instanz (2 Kerne, 4GB RAM) installiert. Jeder Beleg wurde mit drei Positionen gefüllt, die mit zufälligen Mengen, Preisen und Bezeichnungen gefüllt wurden. Bei der Erhöhung von zwei auf drei User ergab sich keine weitere Steigerung, da die Rossourcen der HyperV Instanz ausgeschöpft wurden.


<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/mguse/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/mguse/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">



</head>

<body link="#0563C1" vlink="#954F72">



Anzahl   User (parallel) | Anzahl Belege   gesamt | Zeit gesamt (s) | Zeit pro   Datensatz (s)
-- | -- | -- | --
1 | 200 | 174 | 0,87
2 | 200 | 118 | 0,59
1 | 400 | 340 | 0,85
2 | 400 | 246 | 0,62
1 | 600 | 510 | 0,85
3 | 600 | 370 | 0,62



</body>

</html>

**Comment by Micha-Richter** [comment]
Hallo Matthias,

würdest du das PowerShell-Skript hier veröffentlichen?
Ich habe auf einem Kundensystem Zeiten für die Beleganlage, die meilenweit von deinen Zeiten oben abweichen und würde gern sehen, wie sich euer Skript in dieser Umgebung verhält. 

Vielen Dank im Voraus!

**Comment by MatthiasGuse** [comment]
Hier das Skript:

```
$anzahlBelege = 200
$anzahlPositionenProBeleg = 3

Write-Host "Lade Wawi ...";
$wawi = New-Object -ComObject XFAKT.App;
while (!$wawi.ApplicationReady()) {};
Write-Host "Wawi geladen";

$stopwatch = [system.diagnostics.stopwatch]::StartNew()

for ($i = 0; $i -lt $anzahlBelege; $i++) {
    # Beleg erstellen
    $beleg = $wawi.NeuerBelegAuto('F', '');
    $beleg.SetAdresse('10001');

    # Pos erstellen und speichern
    for ($j=0; $j -lt $anzahlPositionenProBeleg; $j++) {
        $pos = $beleg.CreatePos('A');
        $pos.SetArtikel('100001');
        $menge = Get-Random -Minimum 1 -Maximum 300
        $pos.SetEingabeMenge($menge);
        $preis = Get-Random -Minimum -1 -Maximum 100
        $pos.SetEinzelPreis($preis);
        $dummy = $pos.Save(0);
        $dummy = [System.Runtime.Interopservices.Marshal]::ReleaseComObject($pos);
    }

    $dummy = $beleg.Save;
    $dummy = [System.Runtime.Interopservices.Marshal]::ReleaseComObject($beleg); 
}

$stopwatch.Stop()
$dauer = [math]::Round($stopwatch.Elapsed.TotalSeconds,0)

Write-Host "Das Anlegen von $anzahlBelege Belegen mit je $anzahlPositionenProBeleg Positionen pro Beleg hat $dauer Sekunden gedauert"

$dummy = [System.Runtime.Interopservices.Marshal]::ReleaseComObject($wawi); 
```

**Comment by Micha-Richter** [comment]
Ups...da habe ich den Satz 

> Ein Powershell Script, welches ebenfalls 200 Aufträge mit je drei Positionen anlegt, benötigt auf gleichem System ca. 70s für das Anlegen der Belege. Der Start der Wawi ist hier nicht mit einbezogen und muss noch hinzugezogen werden.

aber total missverstanden. Ich ging davon aus, dass hier die API verwendet wird.

Dann ist die API 2,5x LANGSAMER als die COM-Schnittstelle!?!? (174s statt 70s)

**Comment by MatthiasGuse** [comment]
Stimmt. Das stand da nicht so eindeutig. Habe den Satz oben angepasst.

Offenbar ja. Allerdings muss man hier noch unterscheiden, dass bei COM der Start nicht mitberechnet ist und das Skript lokal auf der Maschine lief. Der Test der API lief über das Netzwerk von einem anderen PC per Postman. Technisch gesehen kann die API aber nicht schneller als COM sein.

Viele Grüße
