### ISSUE TITLE
Nicht möglich einen Versandartikel ohne UnitPrice zu setzten

### ISSUE THREAD

**Issue by Logic-Bits** [selectline-software/selectline-api#187]
![grafik](https://user-images.githubusercontent.com/2421123/148994830-56e55562-9a47-4c9e-9616-80291ca03387.png)

Hallo.
Denke das ist selbsterklärend.
Sieht auch nach einem internen Fehler aus der nicht abgefangen wurde.

Da es in der SL direkt geht denke ich handlet es sich hier um ein Bug und nicht ein "Feature".
Version 21.3.6

**Comment by SusanneSchadenberg** [comment]
Hallo,
das ist weder ein Bug noch ein Feature :-) 
Das Feld "UnitPrice" ist ein Pflichtfeld und ist auch so in der API Hilfe dokumentiert.
Gruß Susanne

**Comment by Logic-Bits** [comment]
Hallo,

Danke für die schnelle Rückmeldung.
Sorry dass ich da nicht nachgeschaut habe - dachte dass wie bei /ArticleItem es noch keine Doku für die Pflichtfelder gibt.
Kommt da dann mal eine Erweiterung dass dass man die Preispflege in der Selectline auch verwenden kann? (Gruppen-, Kundenpreise, etc)?
Es ist mir ja rein via API nicht möglich den richtigen Preis herauszufinden.

Vielen Dank

**Comment by MatthiasGuse** [comment]
Hallo, 
Preisfunktionen stehen bereits auf der langen Liste der zukünftigen Funktionen.

Viele Grüße
