### ISSUE TITLE
Kontengruppe bei Beleganlage füllen

### ISSUE THREAD

**Issue by ThorstenPoppe** [selectline-software/selectline-api#19]
Hallo zusammen,

wir müssen bei der Anlage eines neuen Belegs die Kontengruppe füllen, leider finde ich dazu nicht das passende Segment im DocumentCreateModel. Die Feldbeschreibungen sind dort auch teils auf Englisch, was zur Findung der passenden Felder nicht gerade hilfreich ist.
Im CustomerCreateModel wäre es das Segment AccountGroupNumber, wie heißt es im DocumentCreateModel?

Viele Grüße,
Thorsten

**Comment by jprause1234** [comment]
Hallo,

aktuell ist die Kontengruppe bei Belegen nur lesend verfügbar und heisst dort "BankAccountGroup" im Unterobjekt "Payment". Ich schaue mal, warum man diese Eigenschaft nur lesen und nicht schreiben kann. Ein einheitlicher Name in allen Ressourcen wäre sicher auch gut. Das nehme ich gleich mal als Fehler auf.

Viele Grüße
Jan Prause

**Comment by ThorstenPoppe** [comment]
Hallo Herr Pause,

das Feld "BankAccountGroup" habe ich gefunden und kann es auch beschreiben (ist also nicht nur lesend - das dazugehörige Label schon).
Hat sich also geklärt - wenn die Felder einheitlich wären oder zumindest in der Beschreibung der passende Tabellen Feldname auf Deutsch steht, wäre das schon sehr hilfreich.
Vielen Dank bis dahin!

Thorsten Poppe
