### ISSUE TITLE
Communication link failure

### ISSUE THREAD

**Issue by Logic-Bits** [selectline-software/selectline-api#190]
Hallo,

was hats mit dem Fehler auf sich?

{
  "StatusCode": "BadRequest",
  "ResponseCode": "42-036",
  "Message": "CreateDocumentErrorException",
  "Details": {
    "ResponseDetails": "Communication link failure",
    "ResponseType": "CreateDocumentError",
    "ErrorCode": -1
  }
}

sieht mir nicht nach einem Inhaltlichen Fehler aus.

Vielen Dank

**Comment by SusanneSchadenberg** [comment]
Hallo,
vielen Dank für die Info. 
Gerne würden wir den Fehler auf den Grund gehen, aber dazu benötigen wir noch ein paar Informationen.

Den Fehler konnten wir ab und an beobachten, wenn die DB-Verbindung zwischenzeitlich weg war. War das bei Ihnen vielleicht auch der Fall?
Steht dazu etwas in den Logs?

Vielen Dank schon mal im Voraus.

Gruß Susanne

**Comment by Logic-Bits** [comment]
Eine E-Mail mit den Logs ist auf die Support Email geschickt.
Danke

**Comment by SusanneSchadenberg** [comment]
Die Logs habe ich erhalten aber es gibt keinen Eintrag vom 24.01.2022. 
Der letzte Eintrag in den Log ist der 19.01.2022.
Gruß Susanne

**Comment by Logic-Bits** [comment]
Mehr Infos habe ich dazu leider auch nicht. Logs sind von heute.
Bei einem anderen Kunden hatten wir auch schon (vermutlich) das Problem dass er anscheinend die Verbindung verliert.
In dem Fall ist der SQL Server aber auch gleichzeitig der IIS Server / SL Server (alles lokal).

Wäre es nicht Sinnvoll die Verbindung (zu SQL) neu aufzubauen falls Ihr ein Verbindungsfehler bekommt?

Danke

**Comment by SusanneSchadenberg** [comment]
Derzeit gibt es noch ein Problem beim automatischen Start des Backendmanagers.
Der Fehler liegt in der Warenwirtschaft. Der Backendmanager startet zwar automatsich aber die Backendwawi schließt sich nicht, wenn die DB-Verbindung verloren gegangen ist.
Der Fehler wird derzeit bearbeitet.
Gruß Susanne

**Comment by SusanneSchadenberg** [comment]
Hallo,
der Fehler wurde mit der aktuell ausgelieferten Version 22.1 behoben.
Gruß Susanne
