### ISSUE TITLE
Articles: Mehrdeutiger Spaltenname "Bestand"

### ISSUE THREAD

**Issue by ElfioGmbH** [selectline-software/selectline-api#192]
Hallo zusammen,

wenn wir alle Artikel abrufen wollen, die einen Lagerbestand größer 0 haben, bekommen wir die Fehlermeldung **Mehrdeutiger Spaltenname "Bestand"** zurück.

Request URL:

> https://example.com/slmobileApi/Articles?articleListFilter.onlyStockedArticles=true

Response body:

> {
>   "StatusCode": "InternalServerError",
>   "ResponseCode": "20-000",
>   "Message": "Mehrdeutiger Spaltenname \"Bestand\".",
>   "Details": null
> }

Wir verwenden aktuell die Version 21.3.6 (Warenwirtschaft und Mobile).

**Comment by SusanneSchadenberg** [comment]
Hallo,
über den Filter "get//{{url}}/Articles?=stock gt 0" bekommen Sie alle Artikel mit einem Lagerbestand größer 0. 
Oder wollten Sie etwas anderes Abfragen?
Viele Grüße aus Magdeburg
Susanne

**Comment by motionnow** [comment]
In der aktuellen Version geht doch auch.
/Articles?OnlyStockedArticles=true

**Comment by SophiaWeise** [comment]
Hallo,

die Fehlerbehebung ist abgeschlossen und steht Ihnen mit der kommenden Version zur Verfügung.

Beste Grüße,
Sophia
