### ISSUE TITLE
Fehlerhafte Menge bei Anlegen von Artikelpositionen

### ISSUE THREAD

**Issue by h2-Systems** [selectline-software/selectline-api#193]
Wenn wir in den Versionen 21.3.8/9 eine Artikelposition mit dem Befehl `/Documents/{documentKey}/ArticleItem` einfügen setzt die SelectLine immer die Menge auf 1, egal was wir im body als Quantity übergeben

**Comment by Micha-Richter** [comment]
Habt ihr schon versucht, die Menge in CalculatedQuantityValue zu übergeben?

**Comment by h2-Systems** [comment]
Ah, ok. Mit CalculatedQuantityValue scheint er jetzt die richtige Menge zu übergeben.
Da werden wir wohl unser Transferprogram für die aktuellen Versionen anpassen müssen.

Danke für die Rückmeldung!

**Comment by Micha-Richter** [comment]
Noch besser wäre die Korrektur der API: was soll man mit einem wirkungslosen Quantity anfangen??
Darüber sollte nicht jeder Entwickler wieder neu stolpern.

**Comment by VivienSchuboth** [comment]
Guten Tag,

Hier scheint ein Verständnisproblem vorzuliegen:
CalculatedQuantityValue ist die Gesamtmenge der anzulegenden Position. Diese wird unabhängig von der Lagerung gehandhabt.

In den "StoreInformation" befinden sich die Informationen zu einer Lagerung. Die darin enthaltende Menge bestimmt also in welcher Menge Sie den Artikel in ein bestimmtes Lager einlagern wollen. Das erlaubt Ihnen eine einzelne Position für einen Artikel anzulegen und den Artikel trotzdessen in verschiedene Läger einzulagern.

Sie können also einen Artikel ("Tisch" als Beispiel) in den Beleg einmalig einfügen und diesen trotzdem in verschiedene Läger einlagern.. und das in verschiedenen Teilmengen.

Ich sehe darin deutlich einen Nutzen. Sie nicht?

Freundliche Grüße

**Comment by Micha-Richter** [comment]
Verständnisproblem, richtig :| 
Ich bin mit der Beschreibung oben davon ausgegangen, dass Quantity ein zulässiges Feld in ArticlePositionItem ist und nicht ausgewertet wird. Sorry!

Es muss allerdings auch eine Änderung am Modell gegeben haben, sonst hätte der OP ja nicht das Problem gehabt!?

**Comment by MatthiasGuse** [comment]
Ja, "CalculatedQuantityValue" wird immer wieder gerne übersehen und führt zu solchen Effekten und den Nachfragen. 
In der kommenden Version werden wir das Feld "CalculatedQuantityValue" als Pflichtfeld in den Routen deklarieren. Dann ist zumindest die Fehlermeldung eindeutig.

Viele Grüße

**Comment by ThePholph** [comment]
> Ja, "CalculatedQuantityValue" wird immer wieder gerne übersehen und führt zu solchen Effekten und den Nachfragen. In der kommenden Version werden wir das Feld "CalculatedQuantityValue" als Pflichtfeld in den Routen deklarieren. Dann ist zumindest die Fehlermeldung eindeutig.
> 
> Viele Grüße

Hallo Matthias,

wenn, dann bitte nur im POST. Meiner Meinung nach wäre eine bessere Kennzeichnung in der Doku ausreichend. Da gebe es wichtigere Themen in der API umzusetzen.

Viele Grüße

Daniel

**Comment by MatthiasGuse** [comment]
Hallo Daniel,

ja, natürlich nur im Put und im Post. Die Doku wird ebenfalls angepasst. Hierzu treten relativ häufig zu Probleme und Anfragen auf, weshalb wir das jetzt anpassen.

Viele Grüße
Matthias

**Comment by ThePholph** [comment]
Hallo Matthias,

genau deshalb sagt ich bitte NUR im POST. Im PUT macht dies nicht wirklich Sinn und bereitet mir wieder mehr Arbeit. Da bei einem PUT nur die Änderungen übertragen werden. Das bedeutet wenn in einer unserer Anwendungen nur der Liefertermin angepasst wird bekäme ich aktuell einen Fehler?! 

Danke 

Grüße 

Daniel

**Comment by MatthiasGuse** [comment]
Ahh. Stimmt, da habt ihr Recht. Dann werden wir das intern prüfen und in Abhängigkeit vorhandener Lagerinformationen einen eindeutigen Fehler zurückgeben, wenn der Wert beim PUT nicht gefüllt ist.

**Comment by Micha-Richter** [comment]
Klingt für mich immer noch zu kompliziert, Matthias..und wenn ihr sowieso rangeht, kann man noch mal 2 Minuten drüber nachdenken..

Aus meiner Sicht spielt das (übergeordnete) CalculatedQuantityValue doch nur eine Rolle, wenn ich **keine** Lagerinformationen übergebe. 
Sobald Lagerinformationen mitkommen, sollte CalculatedQuantityValue imho überflüssig sein und weggelassen werden können. Das könnt ihr doch dann in der API selbst berechnen. (POST)

Beim PUT muss man auch vollständige StoreInformation's übergeben, denke ich (woher sollte die Wawi wissen, welche Lagerinformationen aktualisiert werden sollen?). 
Von daher könnte hier dasselbe Verhalten wie oben beim POST beschrieben ziehen!?

Zusammengefasst ist dann die Idee eines **Pflichtfeldes** Overkill. Wenn CalculatedQuantityValue nur bei POST/PUT ohne Lagerinformationen benötigt wird, dann sollte nur dieser Fall geprüft und der (dann sowieso offensichtliche!) Fehlerfall mit einer aussagekräftigen Info abgewiesen werden.

**Comment by ThePholph** [comment]
> Ahh. Stimmt, da habt ihr Recht. Dann werden wir das intern prüfen und in Abhängigkeit vorhandener Lagerinformationen einen eindeutigen Fehler zurückgeben, wenn der Wert beim PUT nicht gefüllt ist.
> 
> Mit PATCH ist vorerst nicht zu rechnen.
> 
> Grüße

Hallo Matthias,

erstmal Danke für die Offenheit bzgl. Einwänden unsererseits. Ich kenne andere ERP-Hersteller, da hat man nicht so eine Kurze Leitung zur Entwicklung und muss mit dem halben Globus telefonieren bis etwas passiert😅

Wenn Ihr es zwingend validieren wollt, wäre dass eine Lösung. Ich finde es muss nur korrekt Dokumentiert und vorgegeben werden. 

Da ist Kontinuität und Update-Sicherheit ein viel wichtigeres Thema. Denn wenn ich einmal eine Umsetzung mit der API erstellt habe, weiß ich eig. wie ich vorgehen muss. 

Hier könnte man auch mit Workshops für angehende API-Entwickler entgegenwirken. Das wäre durch eine Kursgebühr sogar bezahlt😀

Nur meine Meinung.

Viele Grüße 

Daniel

**Comment by MatthiasGuse** [comment]
Hallo Micha, hallo Daniel,

danke für euer Engagement. 🙏🏻 Schaut euch gerne mal die Jobangebote auf unserer Homepage an. Vielleicht ist ja was dabei 😁 😉 

Wir haben uns intern jetzt darauf geeinigt, dass wir "CalculatedQuantityValue" immer erwarten, wenn "StoreInformation" mitgeliefert wird. Fehlt das in dem Fall, kommt ein aussagekräftiger Fehler zurück. Das trifft dann für POST und PUT gleichermaßen zu. 
Weglassen oder den Wert berechnen geht aus folgenden Gründen nicht immer:
- Die Belegposition kann gegenüber den StoreInformation eine abweichende Mengeneinheit haben.
- Beim PUT kann man bspw. die Menge erhöhen indem man die die StoreInformation nur für die zu addierende Menge mitliefert und CalculatedQuantityValue entsprechend anpasst.

Daher die implizite Pflicht CalculatedQuantityValue dann anzugeben. 

Es gibt in größeren Abständen Webinare zur API. Das letzte war erst im Januar. Einen richtigen API Workshop werden wir vermutlich erst wiederbleben, wenn das Zusammentreffen wieder einfacher ist.

Viele Grüße
Matthias

**Comment by Micha-Richter** [comment]
Es wird jetzt vermutlich nervig, aber trotzdem: die Begründung ist für mich nicht stichhaltig.

Ich gehe davon aus, dass die Wawi beim POST intern prüft, ob die Mengen aus StoreInformation insgesamt die CalculatedQuantityValue erreichen, und dafür auch Mengeneinheiten umrechnet!?
Ihr erwartet jetzt, dass eine Anwendung "draußen" absolut genauso rechnet wie die Wawi intern, aber gerade bei Mengenumrechnungen ergeben sich immer wieder Rundungsabweichungen.

Beim PUT tritt dasselbe Problem dann u.U. auch auf. 
Und außerdem muss man sich vor dem PUT auch noch die aktuelle Menge der Position holen und die neue Gesamtmenge ausrechnen - statt einfach eine neue StoreInformation reinzuschieben.

Das könnt ihr besser - und ganz sicher, ohne Leute wie uns dafür einzustellen! :sweat_smile:

**Comment by MatthiasGuse** [comment]
Hallo Micha,

ja, das ist aktuell der Stand. Die Menge der Position (Eingabemenge der Belegposition) muss mit der Lagerung bzw. der Summe aller Lagerungen der Position übereinstimmen. 
Beim POST könnten wir das theoretisch noch aussrechen, müssten dann aber klugsch..., welche Mengeneinheit an die Position geschrieben wird.
Beim PUT geht es so leider nicht, da wir nicht erraten können, was der Nutzer nun machen möchte. Nehmen wir an wir haben eine Position mit Menge 3 (bereits gelagert). Machen wir ein PUT mit "StoreInformation" für die Menge 2, und würden keine "CalculatedQuantityValue" angeben, würde die Positionsmenge auf 2 reduziert werden. Aktuell funktioniert es so, dass in dem Beispiel "CalculatedQuantityValue" mit 5 und die "StoreInformation" für die Menge 2 angegeben wird, um die Position von 3 auf 5 zu erhöhen.
Ich gebe zu, dass das keine sehr schöne Lösung im PUT ist, jedoch sollten wir hier jetzt einen Stand haben, der einen nicht im Wald stehen lässt, weil man einfach nicht herausfinden konnte, wo das Problem ist. Mehr ist aktuell leider nicht drin.

Viele Grüße
Matthias
