### ISSUE TITLE
Print-Funktion der SelectLine API wirft den Fehler AppKeyInvalidException

### ISSUE THREAD

**Issue by arkanis** [selectline-software/selectline-api#194]
Wir versuchen über die Route `POST /Documents/{documentKey}/Print` ([doku](https://demo.slmobile.de/demoApi/Help/Api/POST-Documents-documentKey-Print)) der SelectLine API einen Beleg auszudrucken. Direkt auf den Druckern die in der Vorlage hinterlegt sind (soweit ich es verstanden hab hat die Vorlage zwei weitere Folgevorlagen). Dabei kommt allerdings eine `AppKeyInvalidException` zurück.

Details zum Request den wir probiert haben:

```
POST https://host/slmobileApi/Documents/FAU-1234567/Print
Authorization: LoginId ...

{"MasterName":"ABC_DE_123","NumberOfCopies":1,"PrintTarget":0}
```

Ergebnis:

```
{
    "StatusCode": "BadRequest",
    "ResponseCode": "42-039",
    "Message": "AppKeyInvalidException",
    "Details": "The AppKey is not longer valid. Please log in again with a valid AppKey. "
}
```

- API-Version von `/Info`:
  Description: "REST Service for SelectLine.Erp"
  Version: "21.2.2 Build 342669"
  BuildDate: "07/16/2021 17:45:36"
- Ich hab sensitive Daten in dem Request durch Platzhalter ersetzt ("host", "AU-1234567", "..." im Token und "ABC_DE_123" im MasterName). Der verwendete Hostname war korrekt, der Beleg und die Druckvorlage haben existiert.
- Im Authorization-Header wurde natürlich statt "..." der entsprechende Token gesendet, der von /Login zurück kam.
- Der Login war auch erfolgreich, es kam sowas wie `{"AccessToken":"...","TokenType":"LoginId"}` zurück.
- Bei jedem Versuch wird zuerst `/Login` aufgerufen, dann `/Documents/{documentKey}/Print` mit dem entsprechenden Token, dann `/Logout`. Direkt hintereinander innerhalb von ca. einer Sekunde. Der Token sollte also nicht veraltet sein.
- Der Beleg vom passenden Typ existiert. `GET https://host/slmobileApi/Documents/FAU-1234567` war erfolgreich und hat die Daten zu dem Beleg zurück gegeben.
- Unter PrintTarget haben wir die Werte 0, 1, "Printer" und "Screen" probiert. Nur für die geringe Chance dass es dadurch funktioniert. Dokumentiert hier: https://demo.slmobile.de/demoApi/Help/ResourceModel?modelName=PrintTarget. Macht keinen Unterschied.
- Unter Antwort-Codes steht auch nichts hilfreiches: https://demo.slmobile.de/demoApi/Help/ResponseCode  
  42     Document     Ressourcen für Belege  
  039     AppKeyInvalidException     Der verwendete AppKey ist nicht gültig.
- Ich hatte den gleichen Fehler schon mal als ich nach dem Status der Angebot in der Produktion gesucht hab (in den Routen zu Production glaub ich). Da dachte ich dass dieses SelectLine-Modul wahrscheinlich nicht lizenziert ist. Aber die Route /Documents/{documentKey}/Print gehört zu den Belegen. Daher verwirrt mich der Fehler an dieser Stelle.
- Ich hab den GitHub Issue #22 gefunden. Da war scheinbar der Lizenz-Server out-of-date. Könnte es damit was zu tun haben?
  Bei uns tritt der Fehler allerdings bei jedem Aufruf auf. Bisher war kein einziger Druck erfolgreich.
- Unser SelectLine-Ansprechpartner hat mich bereits an den Support verwiesen und der hat mich hier her verwiesen.

**Comment by MatthiasGuse** [comment]
Hallo,

sind alle Tests im Mobile Manager "grün"?
Haben Sie mal getestet den Druck vom Login zu entkoppeln? D.h. einloggen und einen Moment warten, bevor der Druck gestartet wird?
Ich könnte mir vorstellen, dass das Backend noch gar nicht vollständig geladen ist. Hier werden ja Druckvorlagen und Makros beim Start eingelesen.

Viele Grüße
Matthias

**Comment by arkanis** [comment]
Danke für die Vorschläge. 5 oder 10 Sekunden nach dem Login zu warten und erst dann den Print-Request zu machen hat leider keine Wirkung. Nach wie vor kommt eine AppKeyInvalidException zurück (halt erst 5 oder 10 Sekunden später).

Zu dem Mobile Manger muss ich erst mal den passenden Ansprechpartner raus finden und dann fragen. Werde der Sache aber nachgehen.

**Comment by ThePholph** [comment]
Hallo,

nur um es auszuschließen: 

Ein gültiger AppKey wird beim Login aber mitgegeben und ist auch Lizensiert? Ich bin mir nicht sicher, ob der Druck über die API ohne AppKey funktioniert.

Viele Grüße

Daniel

**Comment by arkanis** [comment]
Danke für den Tipp Daniel! Bisher hab ich angenommen dass sich der "AppKey" auf die SelectLine-Lizenz bezieht (passt zu der komischen englischen Übersetzung wie KindFlag). Ich hab noch etwas rum gesucht und [hier](https://www.selectline.ch/de/produkte/module-preise/api.html?file=files/content/downloads/SelectLine%20API.pdf) etwas mehr gefunden. Mir war nicht klar dass die API noch mal eigene Lizenzen verwendet und dass verschachtelte Routen evt. eine andere Lizenz brauchen. Ich werde dem nachgehen und schauen was ich über meinen Ansprechpartner organisieren kann.

Wäre evt. nett das auf https://demo.slmobile.de/demoApi/Help/HowToUse zu erwähnen. Oder generell irgendwo in der Dokumentation. Bisher hab ich es nur in dem verlinkten PDF gefunden.

**Comment by arkanis** [comment]
Mit einem Lizenzierten und beim Login angegebenen AppKey hat es tatsächlich geklappt. Vielen Dank noch mal für den Tipp Daniel!
