### ISSUE TITLE
OpenAPI Spec 3.0

### ISSUE THREAD

**Issue by pietzschke** [selectline-software/selectline-api#195]
Hallo!
Gibt es Pläne die Swagger Dokumentation für die OpenAPI Spec V3 zu aktualisieren?

Einige der Generatoren unterstützen nur noch den neueren Standard.

**Comment by MatthiasGuse** [comment]
Aktuell haben wir das nicht geplant. Werden dies für die Zukunft aber prüfen.

Viele Grüße
