### ISSUE TITLE
Position wird korrekt angelegt, Rückgabe jedoch Status 500 Internal Server Error

### ISSUE THREAD

**Issue by aameyer** [selectline-software/selectline-api#196]
Hallo,

ich habe hier einmalig folgendes Verhalten auf einem Kundensystem beobachten bzw. nachvollziehen können:

Es ist einmalig vorgekommen, dass als Response auf das Anlegen einer Belegposition ein Internal Server Error mit Status 500 zurückgegeben wurde. Die Belegposition wurde jedoch trotzdem korrekt mit Zuschlagsartikel angelegt. Da bei einer Fehlermeldung davon auszugehen ist, dass die Operation nicht erfolgreich ausgeführt wurde, versuchen wir, die Position erneut anzulegen - in der Folge ist die Position dann doppelt vorhanden.

Detailliert:

- Beim Kunden ist eine SelectLine Version 21.3.6 mit passendem Backend installiert.
- Wir legen Positionen über die Route POST.../Documents/{DocumentKey}/ArticleItem?additionalActions=3 an, im Body werden nur CalculatedQuantityValue und ArticleNumber übergeben. Im Normalfall funktioniert dies soweit fehlerfrei.
- Wenn als Response auf den HTTP-Request ein Fehler zurückgegeben wird, setzen wir den gleichen Request zur Sicherheit nach kurzer Wartezeit einfach ein zweites Mal ab - dies hat sich bisher bewährt als Workaround für diverse Situationen, in denen die API bspw. das Anlegen eines Belegs mit einem Internal Server Error verweigert, nur um dies 60 Sekunden später zuzulassen.

Der Fehler ist so das erste Mal aufgetreten und bisher nicht reproduzierbar. Das gleiche Problem hatten wir in der Vergangenheit beim Anlegen von Belegen (Issue #7 - Internal Server Error zurückgegeben, Beleg trotzdem angelegt). In diesem Fall sind die Lösungen aus Issue #7 jedoch nicht anwendbar bzw. schon umgesetzt:
- Wir verwenden einen Login, der mit jeweils einem eigenen API- sowie einem eigenen WaWi-Benutzer verknüpft ist, und arbeiten mit diesem alle Requests sequentiell ab. Requests an die API mit anderen Logins werden nicht parallel gesendet, es kann hier also eigentlich keinen Konflikt durch andere laufende Requests geben, und der Backend-Prozess sollte aktuell auch nur diesen Request verarbeiten.
- Aufgrund Issue #7 legen wir die Belege zuerst nur mit Belegtyp ohne weitere Kopfdaten an, alle restlichen Daten werden anschließend mit einem Update hinzugefügt. Dies ist für die Belegpositionen jedoch nicht möglich, da eine ArticleNumber und CalculatedQuantityValue Pflichtfelder sind - wir können hier also nicht erst eine "leere" Position anlegen.

MFG
Alexander Meyer

**Comment by ThePholph** [comment]
Hallo,

da der Fehler bisher nur einmalig aufgetreten ist und zu wenig Logdaten vorliegen, um bspw. Probleme auf Seiten der Infrastruktur (Operationssystem etc.) auszuschließen, würde ich es erstmal beobachten und mehr Daten sammeln.

Die beschriebenen Probleme tauchen bei uns nicht auf und wir setzen die API für zahlreiche eigene Services, Schnittstellen und Frontend-Anwendungen ein, mit teilweise mehreren 100 Positionen und Belegen.

Bei uns sind auch so manche Probleme auf korrelierende Anwendungen bzw. Netzwerkprobleme zurückzuführen gewesen. Die Analyse ist hier nur sehr mühselig, da, je nach Umgebung, der jeweilige Infrastruktur-Partner stark eingebunden werden muss.

Wie beschrieben, am besten beobachten und weiter Daten sammeln, da die aktuelle Datenlage keine gute Grundlage für fundierte Aussagen ist.

Viele Grüße

Daniel

**Comment by MatthiasGuse** [comment]
Hallo,

das unter #7 geschilderte Verhalten sollte mittlerweile keine Relevanz mehr haben und hier keine Rolle spielen.

Wie Daniel schon schreibt, das konkrete Auftreten mit möglichst genauer Zeit zu dokumentieren. Anhand der Logs können wir dann schauen ob sich etwas zeigt.

Viele Grüße

Matthias
