### ISSUE TITLE
Werkaufträge über Belegposition anlegen

### ISSUE THREAD

**Issue by pietzschke** [selectline-software/selectline-api#197]
Hallo,
bei der Anlage einer Belegposition übergeben wir einen Artikel mit der Dispositionsart "Auftrag" und würden gerne dazu per API auch automatisch den Werkauftrag anlegen. Siehe Dialog im Screenshot:
<img width="709" alt="Bildschirmfoto 2022-02-07 um 13 08 40" src="https://user-images.githubusercontent.com/7756693/152788066-baf6d9b1-ea01-499c-888b-88695152ae8c.png">

Lässt sich das umsetzen? Eventuell per Feld angeben, dass automatisch die Anlage erfolgt

Danke und VG

**Comment by MatthiasGuse** [comment]
Duplicate of #183 

Die API führt solche Automatismen bisher grundsätzlich nicht durch. Das betrifft also ebenfalls das Anlegen von auftragsbezogenen Bestellungen und Fertigungsaufträgen. Aktuell kann ich leider auch keinen Workaround vorschlagen, um die Anforderung auf anderem Wege zu erfüllen.

Viele Grüße
