### ISSUE TITLE
missing module

### ISSUE THREAD

**Issue by git828** [selectline-software/selectline-api#2]
Ich wollte die Beispiele in c# ausprobieren.
missing Project SelectLine.Erp.CustomerModule.Models;
missing Project SelectLine.Erp.Models.ApiResponseModels;
missing Project Selectline.Erp.PersonModule

**Comment by SFasel** [comment]
Um welches Beispiel handelt es sich?

**Comment by git828** [comment]
API Console und WPF Demo

**Comment by SFasel** [comment]
Ich hab den aktuellen Stand aus dem GitHub geprüft und kann damit den Fehler nicht nachstellen.
Bitte überprüfen Sie, dass sie ebenfalls die aktuellen Projekte aus dem GitHub benutzen.

**Comment by git828** [comment]
Hier noch die Fehlermeldung:
D:\SelectLine Erp\Modules\SelectLine.Erp.CustomerModule\SelectLine.Erp.CustomerModule.csproj : error  : Die Projektdatei konnte nicht geladen werden. Ein Teil des Pfades "D:\SelectLine Erp\Modules\SelectLine.Erp.CustomerModule\SelectLine.Erp.CustomerModule.csproj" konnte nicht gefunden werden.  D:\SelectLine Erp\Modules\SelectLine.Erp.CustomerModule\SelectLine.Erp.CustomerModule.csproj

D:\SelectLine Erp\Modules\SelectLine.Erp.PersonModule\SelectLine.Erp.PersonModule.csproj : error  : Die Projektdatei konnte nicht geladen werden. Ein Teil des Pfades "D:\SelectLine Erp\Modules\SelectLine.Erp.PersonModule\SelectLine.Erp.PersonModule.csproj" konnte nicht gefunden werden.  D:\SelectLine Erp\Modules\SelectLine.Erp.PersonModule\SelectLine.Erp.PersonModule.csproj

**Comment by SFasel** [comment]
Haben Sie die Beispiele neu heruntergeladen?

**Comment by git828** [comment]
Heruntergeladen und es klappt. Hatte vermutlich ein altes Respo.
Vielen Dank !
