### ISSUE TITLE
Meldung 403 Forbidden - Mit neu generiertem Access-Token 

### ISSUE THREAD

**Issue by Julian-Jansen** [selectline-software/selectline-api#202]
Guten Tag,

bei der Nutzung der SelectLine-API erhalten wir nun immer häufiger die Fehlermeldung 403 Forbidden, auch wenn der Access-Token unmittelbar vor dem eigentlichen Request abgerufen wurde.

Kurz zu unserem Szenario:
Es werden pro Stunde ca. 500 Requests an die SelectLine API abgegeben. Der Großteil dieser Anfragen wird fehlerfrei bearbeitet. Trotzdem kommt es (in einer ansteigenden Frequenz) immer wieder zu dem oben skizzierten Fehler. Auch der aufgerufene Endpunkt ist variabel. Der Fehler Tritt beim ändern von Positionen, Anlage von Aufträgen, ändern von Mengen etc. auf.

Hier ein ganz konkretes Beispiel:

224900	http://xxx/slmobileApi/Documents/F0624167742/ArticleItem	POST	{"ArticleNumber":"213","CalculatedQuantityValue":"1","CustomNumber":"0"}	403	Forbidden	{    "StatusCode": "Forbidden",    "ResponseCode": "42-003",    "Message": "User (LoginId: a4c9dc9c-1db6-4b10-a2f6-c130adedf4c2) not found.",    "Details": null  }	2022-02-20 16:29:28.853

224904	http://xxx/slmobileApi/Documents/F0624167742/ArticleItem	POST	{"ArticleNumber":"213","CalculatedQuantityValue":"1","CustomNumber":"0"}	201	Created	{    "Kennung": "20B54820-331C-4A8A-8244-1E40DC66D9F8"  }	2022-02-20 16:29:35.193

Da unsere Entwickler keine Informationen bzgl. der Lifetime eines Access-Token finden konnten, wird vor jedem Request ein neuer Access-Token abgerufen. 

Wie können wir den Fehler weiter eingrenzen, gibt es Logs/Tabellen mit denen wir feststellen können, warum der gerade generierte Token nicht erkannt wird?

**Comment by ThePholph** [comment]
Hallo Julian,

kurz noch ein paar Fragen:

- Erfolgen die Request parallel?
- Wenn ja, verwendet Ihr verschiedene API-Benutzer der nur einen?

Vielen Dank.

Viele Grüße

Daniel

**Comment by Julian-Jansen** [comment]
Hallo Daniel,

vielen Dank für die schnelle Antwort.

TLDR:
Ja - parallele Requests
Es gibt nur einen Benutzer der verwendet wird.

Ich vermute, dass du darauf hinweisen möchten, dass in diesem Falle die Anmeldungen "überschrieben" werden und immer nur der letzte Access-Token "gültig" ist. Falls die Annahme richtig ist, dann müssten wir ein wenig mehr über die AccessToken wissen. Wie lange können wir die Tokens nutzen und können wir die Lifetime via KeepAlive verlängern ? 

 **Details**
Das Systemumfeld ist wie folgt aufgebaut:

Wir haben in einer SQL-Datenbank Routinen zur Kommunikation mit der SelectLine-API erstellt. Unsere SQL-Datenbank spricht direkt mit der SelectLine-API, vom LogIn bis hin zum Verarbeiten der Antworten. Die Datenbank-Prozeduren (die dann mit der SelectLine-API sprechen) werden von 9 unterschiedlichen Softwareprodukten aufgerufen. Dabei wird für jeden Login der selbe Benutzer verwendet.

**Comment by Julian-Jansen** [comment]
Hallo Daniel,

falls der Token tatsächlich eine Gültigkeit von mindestens 24 Stunden besitzt, so würde die Anpassung minimal ausfallen. Wir könnten in diesem Fall den Token jede Nacht neu generieren (zu einer Zeit in der keine/fast keine Last auf dem System liegt). 

Das Fehlerhandling ist natürlich wichtig und richtig, aber auch das lässt sich im SQL ganz gut umsetzten ;-) 

Vielen Dank für die Hinweise und vermutlich auch die korrekte Fehlerursache - das hat schon sehr geholfen. Eine Bitte habe ich noch, falls du Informationen bzgl. der Gültigkeit hast, würdest du mir die Quelle geben ? - Bevor ich diese Anpassungen in das Team gebe, würde ich mich da gerne Rückversichern um doppelte Aufwände zu verhindern.

Gruß

Julian

**Comment by Micha-Richter** [comment]
Kurze Anmerkung dazu: das AccessToken-Handling direkt in der DB abzubilden ist imho einfach: legt es direkt in der DB irgendwo ab und lasst es von allen Routinen verwenden (hier hilft die DB als zentrale, für alle gültige Ablage des Tokens).
Sowie irgendwann ein API-Call fehlschlägt, holt ihr ein neues Token und legt das wieder zentral ab.

Debugging/Fehlerhandling in SQL sollte alles gehen.

**Comment by MatthiasGuse** [comment]
Hallo Julian,

so wie ihr das schildert, kann ich nur zustimmen, dass mit ziemlicher Sicherheit der Token schon wieder ungültig geworden ist, weil ein weiterer Login gefolgt ist.

Standardmäßig hat der Token eine Gültigkeit von 14 Tagen. Der Wert wäre noch einstellbar, wenn man das wirklich will. (Eine Aufgabe für die Erweiterung der Doku existiert bereits.)

Wenn ihr das so umsetzt, dass ihr euch alle 24h einen neuen Token holt, löst es bitte so, dass ihr euch vorher per Logout korrekt abmeldet. Damit wird auch das Backend korrekt neugestartet. Erst dann sind in der API evtl. geänderte Druckvorlagen / Makros oder Mandanteneinstellungen korrekt geladen.

Viel Erfolg weiterhin!

Grüße
Matthias

**Comment by ThePholph** [comment]
Hallo Julian,

wie Micha schreibt, könnt ihr es auch lösen. Das mit den 24 h wär mir zu heikel, da ihr so Verbindungsabbrüche, Neustarts etc. nicht abfangt. Wenn Updates auf dem Server anstehen und der IT-Dienstleister ist der Meinung, ich muss heute mal Updates einspielen, ohne Bescheid zu geben, funktioniert die Anwendung bis zum geplanten neu Holen des Tokens nicht.

@Micha-Richter ich habe nichts gegen die SQL-Einbindung, nur sind klare Trennungen gewisser Anwendungen beim Load-Balancing, Debuggen, Updaten, Analysieren sowie beim Vermeiden von Regressionen sehr empfehlenswert. Vor allem, wenn es sich nicht um die Eigene-, sondern um eine Kunden-Umgebungen handelt.

Viele Grüße

Daniel

**Comment by Julian-Jansen** [comment]
Hallo Micha,
Hallo Matthias,
Hallo Daniel,


vielen Dank für die Details. Wir haben jetzt alle Informationen die wir benötigen um das "Problem" zu lösen. Den Hinweis mit dem LogOut nehmen wir natürlich gerne mit auf. 

Schön das es so schnelle und kompetente Antworten gegeben hat, dass war sehr angenehm.
