### ISSUE TITLE
GET /Currencies liefert in der aktuellen  "Swaggerdemo.slmobile.de/demoApi/swagger/docs/v1" kein Array zurück

### ISSUE THREAD

**Issue by rogeralthaus** [selectline-software/selectline-api#206]
"GET /Currencies" liefert in der aktuellen  API Definition "Swaggerdemo.slmobile.de/demoApi/swagger/docs/v1" kein Array zurück.
NSwag generiert deshalb dann die Funktion falsch.

Änderungsvorschlag:

Bestehend:
"responses": {
					"200": {
						"description": "OK",
						"schema": {
							"$ref": "#/definitions/SelectLine.Erp.CurrencyModule.Models.Currency"
						}
					},
					
Neu:					
"responses": {
					"200": {
						"description": "OK",
						"schema": {
							"type": "array",
							"items": {
								"$ref": "#/definitions/SelectLine.Erp.CurrencyModule.Models.Currency"
							}
						}
					},	
					
Viele Grüsse
Roger

**Comment by SusanneSchadenberg** [comment]
Hallo Roger,

vielen Dank für die Info. 
Wir haben den Fehler aufgenommen und er wird mit einer der nächsten Versionen behoben werden.

Viele Grüße aus Magdeburg!

Gruß Susanne
