### ISSUE TITLE
Arbeitsschritte eines Werkauftrages starten

### ISSUE THREAD

**Issue by pd167** [selectline-software/selectline-api#208]
Hallo,

ich finde in der Dokumentation so keine Möglichkeit ein Arbeitspaket eines Werkauftrages zu starten.
Es gibt wohl die route ein Arbeitspaket zu Interrupten 

`/ProductionControl/{type}/{identifier}/WorkSteps/{workStepIndex}/Interrupt`

Aber diese zu starten gibt es nur für den Fertigungsauftrag?

`/ProductionOrders/{productionOrderIdentifier}/ProductionSteps/{productionStepIdentifier}/OperatingTimes`

Letztendlich wollen wir die Start- und Endzeit eines Arbeitssteps zu einem Werkauftrag erfassen.
Fehlt die Dokumentation zu diesem Schritt oder ist es noch nicht möglich?

**Comment by ThePholph** [comment]
Hallo,

Werkaufträge werden nicht über die SL.API unterstützt. ProductionControl bezieht sich auf die Produktionssteuerung, nicht auf Werkaufträge.

Viele Grüße

Daniel
