### ISSUE TITLE
DeliveryDate in Beleg leer setzen

### ISSUE THREAD

**Issue by Logic-Bits** [selectline-software/selectline-api#209]
Hallo,

ist es möglich Leer / Null als DeliveryDate anzugeben? Es wird immer das Tagesdatum verwendet.

Vielen Dank

**Comment by MatthiasGuse** [comment]
Es handelt sich hier um einen Vorgabewert, der aus der Wawi stammt.

In den Mandanteneinstellungen kann dieser geleert werden. 
![grafik](https://user-images.githubusercontent.com/31447000/157229062-984e2aa9-57ea-4d09-b1ef-135cf0615633.png)
Dann wird (nach erfolgreichem Ab- und Anmelden an der API) der Liefertemin nicht mehr vorbelegt.

Viele Grüße

**Comment by Logic-Bits** [comment]
Hallo, 

wenn ich mich recht erinnere steht hier 0 drin.
Aber ich benutze ja die API damit ich das setzten kann :)

**Comment by MatthiasGuse** [comment]
0 Tage, heißt Liefertermin = Heute - Sie müssen keinen Wert eintragen, damit der Wert leer bleibt. 

Die Vorgabewerte der Wawi werden bei der Beleganlage immer dann verwendet, wenn über die API kein anderer Wert geliefert wird. Aktuell ist es so, dass die API nur ein Datum setzen kann. Leeren können Sie den Wert aktuell nicht.

Viele Grüße
