### ISSUE TITLE
Fehler bei Neuberechnung der Preise im Beleg bei DELETE ./Documents/{documentKey}/Positions/{documentPositionIdentifier} 

### ISSUE THREAD

**Issue by ThePholph** [selectline-software/selectline-api#21]
Version: 20.1.6

Hallo,

mir ist bei einem Kunden aufgefallen, dass die Summen der Belege beim DELETE von Positionen nicht aktualisiert werden, beim POST und PUT hingegen schon. Ist dies gewollt? Wenn ja ist es leider nicht dokumentiert und das Verhalten sollte bei jeder Methode (POST, PUT, DELETE) das gleiche sein. Zusätzlich erfolgt beim erweiterten Belegstatus keine Aktualisierung, wenn der Beleg zusätzlich nochmal gespeichert und der Status dabei auf "manuell erledigt" gesetzt wird.

Es entstehen dadurch unschöne Inkonsistenzen in der Datenbank, die wir nacharbeiten müssen, da Belege noch Beträge aufweisen, obwohl keine Positionen vorhanden sind!

Ich hoffe hierzu gibt es schnellstmöglich eine Lösung.

Viele Grüße

Daniel

**Comment by ThePholph** [comment]
Hallo,

wir benötigen hierzu wirklich umgehend eine Rückmeldung.

Viele Grüße

Daniel

**Comment by VivienSchuboth** [comment]
Guten Morgen,
wir schauen uns diese Problematik an und melden uns bei Ihnen, wenn wir weitere Informationen für Sie haben.

Mit freundlichen Grüßen,
Vivien

**Comment by VivienSchuboth** [comment]
Hallo,
wir haben den Fehler nachvollziehen können und behoben. 
Die Fehlerbehebung wird Ihnen mit der nächsten Version zur Verfügung stehen, sodass Sie auch nach einem DELETE eine korrekte Summe zurückgeliefert bekommen.

Mit freundlichen Grüßen,
Vivien

**Comment by ThePholph** [comment]
Hallo,

vielen Dank.

Viele Grüße

Daniel
