### ISSUE TITLE
API Beleg als PDF drucken

### ISSUE THREAD

**Issue by CKMJUST** [selectline-software/selectline-api#210]
Hallo an Alle!

Ich suche nach einer Möglichkeit einen Auftrag zu drucken.

Diese Funktion sollte eine alte COM Implementierung ersetzten!

 
  int _druckrueckgebe = _SelectLine_XFAKT.DruckeBelegMitVorlage(
                    _belegtyp,
                    _belegnummer,
                    _vorlage, _vorlagetyp, _Optionen);

Wie kann ich die COM Funktion auf API ändern?

Vielen Dank im Voraus!

**Comment by dupeNoob** [comment]
Hallo CKMKUST,

hierfür kann die Route /Documents/{documentKey}/Print verwendet werden.
Diese ist hier beschrieben: https://demo.slmobile.de/demoApi/Help/Api/POST-Documents-documentKey-Print
Ein Vergleich der COM und API Funktionen kann man hier nachlesen: 
https://www.selectline.de/data/uploads/2017/06/api_Vergleich_API_und_COM.pdf

**Comment by CKMJUST** [comment]
Hallo dupeNoob!

Vielen Dank Deine Antwort!
