### ISSUE TITLE
Belegdruck - Frage zu PrintTarget

### ISSUE THREAD

**Issue by CKMJUST** [selectline-software/selectline-api#212]
Hallo!

Als SelectLine API Anfänger habe ich noch eine Frage zum Thema Belegdruck.
Ich habe erfolgreiche Drucktests mit "PrintTarget" : "Printer" und "PrintTarget" : "File" durchführen können.

Nur ist mir nicht ganz klar, wie die API auf  "PrintTarget" : "Screen" reagieren soll.
Als Rückgabe habe ich immer eine Fehlermeldung erhalten.

Was ist das Ziel von "Screen", bzw wie oder was wurde hier in der API implemetiert?

Vielen Dank im Voraus!

**Comment by MatthiasGuse** [comment]
Hallo,

die aufgelisteten Ziele entsprechen den möglichen Ausgabezielen in der Warenwirtschaft. Eine Ausgabe auf dem Bildschirm oder in die Zwischenablage sind aus Sicht der API nicht sinnvoll zu nutzen und führen auch zu keinem verwertbarem Ergebnis.

Wir werden die Doku entsprechend um diese Info erweitern. Der Vollständigkeit halber werden die Ziele aber trotzdem in der Liste enthalten bleiben.

Viele Grüße
