### ISSUE TITLE
Versandartikel und OSS Verfahren

### ISSUE THREAD

**Issue by Grewamor** [selectline-software/selectline-api#213]
Hallo,

beim Anlegen eine Versandartikels über die API wird das OSS-Verfahren nicht korrekt berücksichtigt.

![image](https://user-images.githubusercontent.com/18594343/158971910-5b91158d-fb3b-4896-a8e4-ad1b53d7360b.png)

![image](https://user-images.githubusercontent.com/18594343/158968720-1b1a2ee9-e44c-4e8a-b185-f970ce8dc99f.png)

2. Position per API angelegt.
3. Position direkt in der SL hinzugefügt.

Mache ich ein Fehler oder liegt das Problem an der API?

Viele Grüße
Morris

**Comment by SusanneSchadenberg** [comment]
Hallo Morris,
Sie machen keinen Fehler :-). 
Der Fehler liegt bei der API. 
Wir haben den Fehler nachvollzogen und an die Entwicklung weitergeleitet.

Viele Grüße aus Magdeburg
Susanne

**Comment by Grewamor** [comment]
Vielen Dank,
Ich habe nun notdürftig das Problem für den Kunden "behoben", uns setze das Flag per SQL.

**Comment by SusanneSchadenberg** [comment]
Hallo,
der Fehler wurde mit der aktuell ausgelieferten Version 22.1 behoben.
Gruß Susanne
