### ISSUE TITLE
POST /Signatures  generiert Fehlermeldung im Auftrag beim Anzeigen der Unterschrift

### ISSUE THREAD

**Issue by rogeralthaus** [selectline-software/selectline-api#218]
Der Aufruf ist Erfolgreich (HTTP201) und der Datensatz wird der Tabelle auch angelegt.
Erhalte dann aber beim Anzeigen im Auftrag die Fehlermeldung 
"Beim laden des Bildes wurde folgender GDI+ Fehlercode gemeldet: InvalidParameter"

Die Dokumentation sagt zum Attribut Picture "Binäre Speicherung des Bildes als Byte-Array". 
Gehe davon aus das was mit dem Format nicht stimmt.
Wie (oder wo finde ich) die genaue Spezifikation der Codierung und Format des Unterschriftsbildes?

**Comment by SusanneSchadenberg** [comment]
Hallo,
wir unterstützen alle gängigen Formate (jpeg, gif, png, tiff, bmp)
Welches Format verwenden Sie?
Könnten Sie mir Ihr Bild zukommen lassen?
Welchen Aufruf verwenden Sie?

Viele Grüße aus Magdeburg
Susanne

**Comment by ThePholph** [comment]
Hallo,

ich hatte ein ähnliches Problem und habe es wie folgt gelöst (TypeScript):

``` 
// canvas-Element in DataURL wandeln
 let pic = canvas.toDataURL("image/png");

// Objekt für Unterschrift in Sl erstellen
let data: any = {};

data.DocumentType = this.Ticket.KindFlag;
data.DocumentNumber = this.Ticket.Number;
data.Picture = pic.split(',')[1];
```

Zum Auslesen im Client nutze ich dann:

```
// Unterschrift in Image anzeigen
this.image = this.sanitizer.bypassSecurityTrustResourceUrl('data:image/jpeg;base64,' + sig[0].Picture);
```

Zugegeben ein POST mit multipart/form-data, wäre wesentlich angenehmer gewesen!

Ich hoffe, ich konnte helfen.

Viele Grüße

Daniel
