### ISSUE TITLE
Fehlermeldungen bei API-Login

### ISSUE THREAD

**Issue by aameyer** [selectline-software/selectline-api#22]
Wir beobachten auf einem Kundensystem seit kurzem Fehlermeldungen beim Login. Installiert ist dort eine Version 20.1.2 Build 184700. Unser Dienst meldet sich dort stündlich mit zwei API-Benutzern an, die mit dem gleichen SelectLine-Benutzer verknüpft sind. In den meisten Fällen ist die Anmeldung erfolgreich, teilweise schlägt die Anmeldung jedoch fehl, und es werden stattdessen verschiedene Fehler zurückgegeben:
6.6.2020 18:19 Uhr nur für Benutzer 2:
Error: Request failed with status code 500|{"StatusCode":"InternalServerError","ResponseCode":"02-000","Message":"Ein Element mit dem gleichen Schlüssel wurde bereits hinzugefügt.","Details":null}
7.6.2020 04:20 Uhr sowie 07:20 Uhr für beide Benutzer:
Error: Request failed with status code 400|{"StatusCode":"BadRequest","ResponseCode":"02-008","Message":"BadRequest","Details":null}
7.6.2020 23:21 Uhr nur für Benutzer 2:
Error: Request failed with status code 500|{"StatusCode":"InternalServerError","ResponseCode":"02-000","Message":"Ein Element mit dem gleichen Schlüssel wurde bereits hinzugefügt.","Details":null}
8.6.2020 00:21 Uhr und stündlich wiederholend bis 08:21 Uhr für beide Benutzer:
Error: Request failed with status code 400|{"StatusCode":"BadRequest","ResponseCode":"02-039","Message":"AppKeyInvalidException","Details":"AppKey is invalid"}
8.6.2020 12:16 Uhr für beide Benutzer:
Error: Request failed with status code 400|{"StatusCode":"BadRequest","ResponseCode":"02-008","Message":"BadRequest","Details":null}

Zwischenzeitlich ist die Anmeldung mit den gleichen Logindaten wieder erfolgreich.
Sowohl in der SelectLine als auch an den Logindaten wurde dabei nichts geändert - es werden also die gleichen Logindaten teilweise akzeptiert, teilweise verworfen, und dies mit verschiedenen Fehlercodes 02-000, 02-008 sowie 02-039.

Der Fehler "ResponseCode":"02-000","Message":"Ein Element mit dem gleichen Schlüssel wurde bereits hinzugefügt." scheint teilweise aufzutreten, wenn zwei Benutzer parallel angemeldet werden, scheinbar werden die Requests hier nicht wirklich unabhängig voneinander verarbeitet. Dass der AppKey zeitweise nicht erkannt wird, kann ich dagegen gar nicht nachvollziehen.

**Comment by ThePholph** [comment]
Hallo,

das Problem mit den zwei Benutzern parallel, kenne ich noch nicht. Jedoch den Fehler "AppKey is invalid". Hier gab es heute und auch in der Vergangenheit, immer wieder Probleme mit dem Lizenzserver. Die Lizenz konnte hier nicht validiert werden. Sollte jedoch inzwischen behoben sein. Wenn eine Version 19.3.x verwendet wird, dann bitte versuchen die Update.20d-Datei vom Partnerportal zu laden und unter ./Daten/Update im SelectLine-Verzeichnis abzulegen.

Wir hatten / haben damit auch zu kämpfen.

Viele Grüße

Daniel

**Comment by aameyer** [comment]
Hallo,
wie beschrieben ist dies bereits eine Version 20.1.2.

**Comment by aameyer** [comment]
Nach Rücksprache mit dem SelectLine Support scheint zumindest der Fehler vom 8.6.2020 "AppKeyInvalidException";"AppKey is invalid" tatsächlich darauf zurückzuführen zu sein, dass in diesem Zeitraum der SelectLine Lizenzserver nicht auf dem aktuellen Stand war. Damit bleiben aber noch die bereits vorhandenen Schlüssel sowie die Bad Requests, welche ich nicht nachvollziehen kann.

**Comment by VivienSchuboth** [comment]
Guten Tag,
um einen besseren Überblick über diese Problematik zu bekommen, würde ich Sie bitten, uns kurz  zu erklären, was genau Sie mit Ihrem Dienst tun wollen und wie dieser Wunsch, in Kombination mit der SelectLine API, umgesetzt wurde.

Mit freundlichen Grüßen,
Vivien

**Comment by aameyer** [comment]
Der Dienst soll sowohl Belege aus der SelectLine automatisch exportieren und in diverse Dateiformate schreiben als auch Belege aus Dateien einlesen und in der SelectLine anlegen. Siehe dazu auch Issues #7 und #8 . In diesem Fall wollen wir einfach verschiedene Belegtypen auslesen und haben für jeden Belegtyp eine Strecke mit einem eigenen API- und WaWi-Benutzer angelegt, der Informationen zu den Belegen über API und API-Makros auslesen soll.

Da die Strecken unabhängig voneinander arbeiten, kann es passieren, dass über den Dienst versucht wird, mehrere API-Benutzer zeitgleich anzumelden. In diesem Fall reagiert das API-Backend in seltenen Fällen mit diesem Fehler für einen oder mehrere Benutzer: 

Request failed with status code 500
StatusCode: InternalServerError
ResponseCode: 02-000
Message: Ein Element mit dem gleichen Schlüssel wurde bereits hinzugefügt.
Details: null

Inzwischen sind für die verschiedenen API-Benutzer jeweils eigene WaWi-Benutzer hinterlegt, das Problem ist damit aber offenbar nicht behoben. Anscheinend gibt es im Backup ein potentielles Timing-Problem, wenn mehrere Logins zeitnah durchgeführt werden, auch wenn die API-Benutzer verschiedene Backend-Prozesse erhalten.
