### ISSUE TITLE
Breaking Changes

### ISSUE THREAD

**Issue by Logic-Bits** [selectline-software/selectline-api#220]
Hallo,

wo / wann werden breaking changes der API mitgeteilt?
z.B. Token auf AccessTokenModel.

Danke

**Comment by konrad79** [comment]
Sämtliche technische Änderungen (auch der API) werden immer mit dem Release einer neuen Version veröffentlicht. Im Downloadbereich finden sich detaillierte Dokumente, was sich technisch alles geändert hat (Datenbankänderungen, API-Änderungen uvm.).
Zusätzlich gibt es den API-Update-Helper:
https://apiupdate.selectline.de/

Dort hat man auch mit Erscheinen einer neuen Version die Möglichkeit, die konkreten Änderungen zu seiner aktuellen Version abzugleichen.

Und für einen Ausblick, was sehr wahrscheinlich in einer neuen Version kommen wird, gibt es den Ausblick auf die Weiterentwicklungen unter:
https://www.selectline.de/data/uploads/dev/Neuerungen%20und%20Korrekturen%20Web.htm

Dort findet man alle Feature und gelösten Fehler für die nächste Version. Aktuell ist das die 22.1.0.
Da findet sich auch für die API einiges.
Und weil die 22.1 in Kürze ausliefern und schon die Arbeit an der 22.2 begonnen haben, stehen in dieser Übersicht sogar schon erste neue Punkte für die dann folgende Version drin.

Viel Spaß beim Stöbern :-)
Konrad Mühler

**Comment by Logic-Bits** [comment]
Ah OK, Super! Dankeschön
