### ISSUE TITLE
Aktionspreis/Preis 4

### ISSUE THREAD

**Issue by ub-net** [selectline-software/selectline-api#221]
Wie man den Listenpreis liest habe ich gesehen. Wie man aber den Aktionspreis oder den "Preis 4"  eines Artikels liest, das habe ich nich tgefunden. Kann mir da wer helfen, bitte?

**Comment by MatthiasGuse** [comment]
Wie schon beschrieben, gibt es aktuell noch keine Funktion die Preise abzufragen. 

Viele Grüße
