### ISSUE TITLE
Stücklistentyp "Fertigung" wird nicht zurück geliefert

### ISSUE THREAD

**Issue by Grewamor** [selectline-software/selectline-api#222]
Hallo,

ist eine Artikel vom Stücklistentyp "Fertigung", liefert die API dennoch ArticleKind "Default" zurück.

![image](https://user-images.githubusercontent.com/18594343/162693980-3e741ba8-73da-4b85-be98-7419fb236a20.png)

Habe jetzt ein Workaround mit Hilfe des Labes durchgeführt. Dennoch kann da vielleicht mal jemand drüber schauen.

Viele Grüße
Morris

**Comment by MatthiasGuse** [comment]
Hallo,

die Fehlerbehebung ist abgeschlossen und steht Ihnen mit der zukünftigen Version 22.3 zur Verfügung.

Viele Grüße
