### ISSUE TITLE
Beleg als PDF auslesen

### ISSUE THREAD

**Issue by h2-Systems** [selectline-software/selectline-api#223]
Hallo,

ich möchte über die neue Funktion /Documents/{documentKey}/PrintPdf ein Beleg zurückbekommen und danach als PDF speichern. Allerdings zeigt die resultierende Datei nur eine weiße Seite an. Könnte das daran liegen, dass der Rückgabewert der API temporär in einen string gespeichert wird? Gibt es für diese Funktion vielleicht schon eine Demo?

Vielen dank im Voraus,
Alex

**Comment by MatthiasGuse** [comment]
Hallo,

ich habe soeben die Postmancollection um das Beispiel für diese Route erweitert. Damit lässt sich das PDF erstellen und direkt anzeigen. Es wird `Content-Type` `application/pdf` zurückgeliefert.
Wie rufen Sie die Funktion auf? Per Swagger ist das bspw. nicht möglich, da hier keine Dateien unterstützt werden.

Beste Grüße

**Comment by h2-Systems** [comment]
Hallo,

jetzt wird die Rückgabe direkt in eine PDF umgewandelt. 

Vielen Dank für Ihre Hilfe,
Alex
