### ISSUE TITLE
Beleg wird korrekt angelegt, Rückgabe jedoch Status 500 Internal Server Error

### ISSUE THREAD

**Issue by aameyer** [selectline-software/selectline-api#225]
Hallo,
ähnlich zum Issue #196 habe ich auf dem gleichen Kundensystem jetzt den Fall beobachten können, dass ein Beleg erfolgreich angelegt wurde, die Response aber Status 500 zurückgegeben hat. Es betrifft wieder den gleichen Kunden, immer noch auf der Version 21.3.6. Konkreter Verlauf:
05.05.2022 08:00:06.759 | REQUEST | POST.../Documents
    Request Data: {"KindFlag":"8"}
05.05.2022 08:00:37.036 | RESPONSE
    Response Status: 500 "InternalServerError"
    Response Data: { StatusCode: 'InternalServerError', ResponseCode: '42-000', Message: 'Client.Send failed. See InnerException', Details: null }
05.05.2022 08:00:38.038 | REQUEST | POST.../Documents
    Request Data: {"KindFlag":"8"}
05.05.2022 08:00:38.221 | RESPONSE | POST.../Documents
  Response Status: 201 "Created"
  Response Data: {"documentKind":"8","documentNumber":"EO22-0221"}

Was hier konkret passiert, ist folgendes: Um 08:00:06 wird der Request abgesetzt, einen neuen Beleg anzulegen (ohne weitere Kopfdaten, vollständig leer.) In der SelectLine findet sich jetzt auch der Beleg mit der Belegnummer EO22-0220, angelegt am 05.05.2022 um 08:00:36. Die API gibt jedoch um 08:00:37 einen Internal Server Error zurück. Daraufhin setzen wir den Request erneut um 08:00:38 ab, in der SelectLine findet sich jetzt der Beleg EO22-0221, angelegt um 08:00:38.

Das Anlegen des Belegs funktioniert also in beiden Fällen, der erste Aufruf benötigt nur etwas länger, was vermutlich zur Rückgabe des Internal Server Errors führt. In der SelectLine Ereignisanzeige finde ich keinen Fehler und nur einen einzigen Eintrag im entsprechenden Zeitraum:
05.05.2022 08:00:32;0:00:03;CDVSV01;FAKT;21.3.6 Build 476229;201210011;;Windows Server 2016 (10.0.14393 );Start;;;;
Für mich sieht dies danach aus, dass der SQL-Server die Connection nur mit Verzögerung geöffnet hat.
Im Windows-Ereignisprotokoll gibt es keine zugehörige Einträge vom SQL Server.

Ich vermute, dass das Backend hier nicht schnell genug startet und die API einen vermeintlichen Timeout des SQL Servers erkennt, bevor der SQL Server selbst einen Timeout zurückgegeben hat. Tatsächlich führt der SQL Server den Request ja fehlerfrei aus, nur mit knapp 30 Sekunden Verzögerung. Dies würde auch erklären, warum der Fehler selten auftritt und nicht reproduzierbar ist, wenn es sich hier um ein Timing-Problem handelt.

**Comment by MatthiasGuse** [comment]
Hallo,

30s ist die Timeout-Zeit, die auf die Antwort des Backends gewartet wird. Sie schreiben: "Ich vermute, dass das Backend hier nicht schnell genug startet" - wenn Sie direkt vor dem Post/Documents einen Login machen, ist das möglich, dass das Backend so lange braucht um zu starten. 
Solche Szenarien um den Start des Backends haben wir zur Version 22.1 betrachtet und das Startverhalten / die Stabilität des Backends optimiert. Hier sollte der Start des Backends auf keinen Fall mehr so lange dauern. Für den Fall, dass das doch noch so sein sollte, haben wir in der 22.1 die Timeout-Zeit hier auch einstellbar gemacht (siehe Dokument "Installation SelectLine Webanwendungen" auf unserer Homepage).

Ohne ein Update auf die aktuelle Version macht es keinen Sinn weiter nach der Ursache des Problems zu suchen.

Viele Grüße

Matthias

**Comment by aameyer** [comment]
Hallo,
der Login hat direkt vor dem Post/Documents stattgefunden, von daher passt das zu Ihrer Erklärung. Ich werde einmal das Update durchführen und beobachten, ob das Problem dann immer noch auftritt.

**Comment by MatthiasGuse** [comment]
Hallo, hat sich das Problem Ihrerseits erledigt?

Viele Grüße

**Comment by aameyer** [comment]
Hallo,
das Problem scheint seit dem Update auf die 22.1 nicht mehr aufgetreten zu sein.
