### ISSUE TITLE
Fehlerhafte Mengen bei Lieferscheinerstellung

### ISSUE THREAD

**Issue by LukWlbr** [selectline-software/selectline-api#226]
Hallo zusammen,

ich habe aktuell ein Problem bei meiner Belegerstellung per API (Lieferscheine).

Ich lege über die API einen neuen Lieferschein an und erstelle über den EP `/Documents/{documentKey}/ArticleItem` neue Belegpositionen.
In einer bestimmten Konstellation (ich weiß nicht welche, da ich es aktuell nicht nachstellen kann) werden fehlerhafte Mengen gespeichert.
Obwohl die richtigen Mengen ausgelagert wurden und auch in den Tabellen `LAGERPROTOKOLL` und `LAGERPOSITION` richtig sind, ist meine Spalte `Menge` in der Tabelle `BELEGP` zu wenig. Folglich wird auch zu wenig zur Rechnung übergeben und mir geht eine Menge Geld flöten...

Im folgenden Screenshot sieht man die Belegpositionen die ich ermitteln konnte, welche in meinem Fall aktuell ca. 40 Stück sind.
Bei der Analyse ist mir aufgefallen, dass die Menge **immer nur einer** Menge aus Lagerprotokoll/Lagerposition entspricht.
Es ist dabei egal ob die Position eine oder mehrere Chargen verwendet.
Im Screenshot habe ich eine Position als Beispiel auch mit Lagerprotokoll + Lagerposition ausgegeben, das beschriebene Problem besteht allerdings bei allen 40 Positionen... 

![image](https://user-images.githubusercontent.com/34090196/167298494-32e8a13e-40e6-47a7-8cb6-2dbcda1ea3c1.png)

Vielen Dank im Voraus und Beste Grüße, 
Luk

**Comment by SusanneSchadenberg** [comment]
Hallo Luk,
welche Version ist den im Einsatz?
Mit der aktuellen Version bekomme ich weder mit post/{{url}}/Documents/xxx/ArticleItem noch mit post//{{url}}/Documents/xxx/SalesBOMPosition nachgestellt.
Viele Grüße aus Magdeburg
Gruß Susanne

**Comment by LukWlbr** [comment]
Hallo Susanne,

es ist Version 21.3.9 im Einsatz. 

Ich habe aktuell dasselbe Problem, dass ich es nicht nachstellen kann... Ich habe es lediglich im Nachhinein gesehen, dass es in irgendeiner bestimmten Konstellation recht "regelmäßig" auftritt.

**Comment by LukWlbr** [comment]
Kurz noch zur Info: Das Problem ist das erste mal im September letzten Jahres aufgetreten und tritt seitdem alle paar Wochen mal auf...

**Comment by MatthiasGuse** [comment]
Hallo,
ist es möglich uns Logfiles bereitzustellen, die in den Zeitraum des Auftretens fallen?

Viele Grüße

**Comment by LukWlbr** [comment]
Hallo, 

erstmal danke für die Rückmeldung.

> ist es möglich uns Logfiles bereitzustellen, die in den Zeitraum des Auftretens fallen?

Gibt es in SelectLine Logfiles, die ich zur Verfügung stellen könnte?

> Editieren Sie die Menge aus Ihrer Anwendung heraus nach der initialen Anlage nochmal?

Eigentlich nicht, nein.

Liebe Grüße

**Comment by MatthiasGuse** [comment]
Hallo,

ja. Logfiles werden standardmäßig für Fehler erstellt. Sie finden diese (bei Ihrem Versionsstand) im Installationsverzeichnis der mobilen Anwendungen unter dem Verzeichnis "Logs". Allerdings werden diese je nach Umfang nur für einen gewissen Zeitraum gespeichert. Wenn Sie einen relativ genauen Zeitpunkt + Belegnummer für das Auftreten des Fehlers nennen können, der nur einige Tage zurückliegt, lassen Sie mir die Logs (ganzes Verzeichnis) bitte über unseren Support zukommen.

Bei Ihrem Screenshot ist mir noch aufgefallen, dass es sich offenbar um Chargenartikel handelt, die diesen Fehler zeigen. Können Sie mir bitte dazu ein Beispiel zukommen lassen, wie sie per API so eine Position, die mehrere Chargennummern für eine Position enthält, erstellen?

Viele Grüße
Matthias
