### ISSUE TITLE
XML der XRechnung (E-Mail) per API erzeugen / erhalten

### ISSUE THREAD

**Issue by Grewamor** [selectline-software/selectline-api#227]
Hallo liebes SL-API-Team,

ist es möglich, die XML der XRechnung (E-Mail) per API zu erzeugen / erhalten?

Viele Grüße
Morris

**Comment by SusanneSchadenberg** [comment]
Hallo Morris,

derzeit ist das Erzeugen bzw. erhalten von XML für XRechnung per API nicht möglich. 
Gern können Sie hierzu einen Eintrag in unserem Wunschforum verfassen bzw. zu einem evtl. bereits vorhandenen mit abstimmen.
Nur so können wir herausfinden, inwieweit Ihre Anforderung auch von anderen Anwendern gewünscht wird.

Viele Grüße aus Magdeburg
Susanne
