### ISSUE TITLE
Versandkosten autom. einfügen

### ISSUE THREAD

**Issue by Logic-Bits** [selectline-software/selectline-api#229]
Hallo,

gibt es eine Möglichkeit die Versandkosten (wie in der Lieferbedingung hinterlegt) via API in den Beleg anzulegen?
https://demo.slmobile.de/demoApi/swagger/ui/index#/Document/Document_CreateDocumentPositionWithShippingItemByDocumentKey
hier muss der Preis ja angegeben werden - der ist aber in der SL gestaffelt hinterlegt.

Danke!

**Comment by SusanneSchadenberg** [comment]
Hallo,

die Möglichkeit besteht derzeit nicht.
Gern können Sie hierzu einen Eintrag in unserem Wunschforum verfassen bzw. zu einem evtl. bereits vorhandenen mit abstimmen.
Nur so können wir herausfinden, inwieweit Ihre Anforderung auch von anderen Anwendern gewünscht wird.

Viele Grüße aus Magdeburg
Susanne

**Comment by SusanneSchadenberg** [comment]
Hallo,
noch ein Nachtrag zu Ihrer Frage.
Wie schon geschrieben über den von Ihnen gewählten Weg ist es nicht möglich, die Versandkosten automatisch zu hinterlegen. 
Es gibt aber einen anderen Weg :-)
Wenn Sie den Belegbearbeitungsstatus via API auf "Geschlossen" setzten put//{{url}}/Documents/xxx/Status) werden die Versandkosten (auch gestaffelt) automatisch eingefügt.
Viele Grüße aus Magdeburg
Susanne
