### ISSUE TITLE
Beleg Rabatt

### ISSUE THREAD

**Issue by Lars-Mue** [selectline-software/selectline-api#23]
Hallo,

ich lege über die API Aufträge an. Allerdings wird der Gesamtpreis  nicht neu berechnet bei einem Rabatt. Hier ein Beispiel JSON:

{
    "KindFlag": "F",
    "ExtraFields": {
        "_BESTELLART": "Online-Shop"
    },
    "BusinessPartner": {
        "LastName": "Test",
        "Salutation": "MRS",
        "FirstName": "Test",
        "Address": {
            "Number": "12800",
            "Street": "Test Weg 5",
            "City": "TestStadt",
            "ZipCode": "12345",
            "CountryId": "DE"
        }
    },
    "DeliveryAddress": {
        "Salutation": "MRS",
        "FirstName": "Test",
        "LastName": "Test",
        "adr": {
            "Number": null,
            "Street": "Test Weg 5",
            "City": "Teststadt",
            "ZipCode": "12345",
            "CountryId": "DE"
        }
    },
    "payment": {
        "PaymentTerm": "2"
    },
    "CurrencyCode": "EUR",
    "CurrencyLabel": "EUR",
    "DeliveryDate": "2020-06-20T00:00:00+02:00",
    "DiscountAmount": 6.88337
}
Der Rabatt wird in den Beleg eingetragen aber nicht verrechnet . Auch durch manuelles ändern in der SelectLine,  ändert sich in dem Importierten Beleg der Preis nicht.  Der Preis lässt sich erst wieder durch den Rabatt beeinflussen, wenn der Beleg kopiert wird. 

Vielen Dank im Voraus für die Antwort .

Freundliche Grüße

**Comment by VivienSchuboth** [comment]
Guten Tag,
danke für Ihren Hinweis. Wir werden uns dieses Problem ansehen und melden uns mit unserer Rückmeldung, sobald wir mehr wissen. 

Mit freundlichen Grüßen,
Vivien Schuboth

**Comment by SteveSteglitz** [comment]
Hallo, 
wir haben versucht, das Verhalten nachzustellen. Leider funktionieren unsere Versuche wie erwartet. Wir haben folgenden API Aufruf probiert.

```
{
	"KindFlag": "F",
	"BusinessPartner":
	{
		"Address":
		{
		"Number": "10001"
		}
	},
	"DeliveryAddress": {
		"Salutation": "MRS",
		"FirstName": "Test",
		"LastName": "Test",
		"Address": {
			"Number": null,
			"Street": "Test Weg 5",
			"City": "Teststadt",
			"ZipCode": "12345",
			"CountryId": "DE"
		}
	},
	"DiscountAmount": 6.88337,
	"payment": {
		"PaymentTerm": "10"
	},
	"CurrencyCode": "EUR",
	"CurrencyLabel": "EUR", 
	"DeliveryDate": "2020-06-20T00:00:00+02:00"
}
```

Anschließend wurde für jede Position, die wir in der Warenwirtschaft hinzugefügt hatten der Belegrabatt berücksichtigt. Können Sie das Ganze noch einmal ausprobieren ggf. den Body des API Calls auf das nötigste reduzieren?
Beispielsweise:
```
{
	"KindFlag": "F",
	"BusinessPartner":
	{
		"Address":
		{
		"Number": "10001"
		}
	},
	"DiscountAmount": 6.88337	
}

```
Wichtig ist jedoch, dass ein Kunde mitgegeben wird. Wenn ein Kunde nachträglich hinzugefügt oder gewechselt wird, wird der Belegrabatt zurückgesetzt. Das Verhalten ist mit dem Arbeiten in der Warenwirtschaft identisch. 

Viele Grüße
Steve
