### ISSUE TITLE
Memofelder in ExtraTabellen können noch immer nicht geschrieben werden. 

### ISSUE THREAD

**Issue by davidhommel** [selectline-software/selectline-api#230]
Hallo,

der in Issue #107 beschriebene Fehler beim Schreiben in Memofelder von Extratabellen besteht entgegen der Antwort von Frau Schuboth immernoch in der aktuellen Version 22.1

Es wird exakt die gleiche Fehlermeldung ausgegeben und es erfolgt kein Eintrag im Memofeld der Extratabelle. Wir haben sowohl das Schreiben in die Extratabelle selbst, als auch in die _Extra versucht. Bei letzterem kommt die in #107 beschriebene Fehlermeldung. Bei ersterem wird ein Eintrag erstellt, das dazugehörige Memo aber schlicht verworfen.

Unsere Aufrufe (_KOMMENTAR ist Memo-Feld):

https://SERVER/slmobileApi/ExtraTable/XPruefberichte

```
{
    "IdentifierName": "PBID",
    "Fields": {
        "_INT1": "3",
        "_TEXT5": "ohne Beanstandungen",
        "_TEXT4": "ohne Beanstandungen",
        "_TEXT3": "ohne Beanstandungen",
        "_BOOL1": "1",
        "_FLOAT1": "8.34",
        "_DATZEIT1": "2022-06-01T00:00:00.0000000+01:00",
        "_TEXT2": "Nein",
        "_KOMMENTAR": "Postman-Test"
    }
}
```
**> Hierbei wird der Kommentar einfach verworfen**

https://SERVER/slmobileApi/ExtraTable/XPruefberichte_Extra
```
{
    "IdentifierName": "XPruefberichte_Extra_ID",
    "Fields": {
        "_KOMMENTAR": "Postman-Test"
    }
}
```
**> Hier wird folgender Fehler zurückgemeldet:**
`{
"StatusCode": "InternalServerError",
"ResponseCode": "05-000",
"ResponseId": 0,
"ResponseIdDescription": "Undefined",
"Message": "Ungültiger Spaltenname \"AngelegtAm\".\r\nUngültiger Spaltenname \"AngelegtVon\".",
"Details": null 
}
`

Wir verwenden Version 22.1

**Comment by davidhommel** [comment]
Gibt es bisher irgendwelche Erkentnisse?

**Comment by MatthiasGuse** [comment]
Hallo,

wir konnten das beschriebene Verhalten nachvollziehen und planen die Behebung zur Version 22.2.

Viele Grüße

**Comment by SophiaWeise** [comment]
Hallo,

die Fehlerbehebung ist abgeschlossen und steht Ihnen mit der kommenden Version **22.2.0** zur Verfügung.

Beste Grüße
