### ISSUE TITLE
POST requests should return created object (ExtraTable)

### ISSUE THREAD

**Issue by benwalch** [selectline-software/selectline-api#232]
It's common practise of REST-like APIs to return the created object, which enables the further processing of it's data (e.g to expose the automatic assigned identifier (id) back to the sender)

In its current state, the API's response body is empty when creating objects through POST requests, which makes it hard to retrieve the id for the created object.

API Version: 21.3.10 Build 519580

**Comment by MatthiasGuse** [comment]
Hello,

which POST request do you use? Please give an example, where ist no content in the body.

**Comment by benwalch** [comment]
For example at the `/ExtraTable` endpoint.
```
curl -X POST https://<host>/slmobileApi/ExtraTable/<table> -H 'Content-Type: application/json' \
--data-raw '{
  "IdentifierName": "ID",
  "Fields": {
    "<field>": "<value>"
  }
}'
```
the response code is 200, which indicates a success and the object is created. But the response body is empty. 
This is also the case at other endpoints, when creating (POST) or updating (PUT) objects.
(`/Customers`, `/Customers/{CustomerNumber}/ContactPersons`, ...)

**Comment by MatthiasGuse** [comment]
For the next release (Version 22.2) we have finished the the return of the created object. You will get the code 201 and the content in the body like this:
![grafik](https://user-images.githubusercontent.com/31447000/172846736-85228f9a-5b90-4a9d-b512-0a3fbc7f5070.png)

**Comment by MatthiasGuse** [comment]
For the next release (Version 22.2) we have finished the the return of the created object. You will get the code 201 and the content in the body like this:
![grafik](https://user-images.githubusercontent.com/31447000/172867493-2a8c0de4-d32c-4dc2-8229-423a7c5a4af6.png)

**Comment by benwalch** [comment]
that's great news to hear.
when is the release planned?

**Comment by MatthiasGuse** [comment]
currently no fixed date - probably at the end of Q3

**Comment by benwalch** [comment]
any news / dates for a planned release of 22.2?

**Comment by SelectLine** [comment]
The version 22.2 is planned to release in September/October this year.

**Comment by MatthiasGuse** [comment]
Version 22.2 is released.
