### ISSUE TITLE
Webserver antwortet mit Conflict auf request mit Unterschiedlichen Benutzernamen

### ISSUE THREAD

**Issue by Torchok19081986** [selectline-software/selectline-api#234]
Hallo, ich habe ein paar Schwierigkeitenin der Mobile API. Wir haben 2 unterschiedliche Bentutzer in WaWi und Mobile API angelegt. Danach sind biede mit einem WaWi und Mandanten verknüpft. Auf die Login Request anwortet Webserver bzw. API mit StatusCode Conflict. SL Mobile API in V 22.1.2 und WaWi in der Version 22.1.4.  Kann mir jemand hier helfen ?

**Comment by MaikGoertz** [comment]
Moin.
Wie wird der Login Request ausgeführt?
Wenn beim Login "Conflict" als Response zurück gegeben wird, ist es vermutlich ein ungültiger AppKey.
Ist der AppKey in der Lizenz vorhanden und wird richtig übertragen?

**Comment by Torchok19081986** [comment]
Morgen, im Swagger ausgeführte Account Methode liefert 02-020 Response auf das Request für Login zurück .  Es wurde 2 benutzer im Mobile Manager als API Benutzer angelegt und mit WaWi Benutzer verknüpft.  Beide haben im Wawi nur Zugriff auf entsprechende Mandaten.

**Comment by ThePholph** [comment]
Guten Morgen,

siehe "ResponseIdDescription", hier liegt ein Lizenzproblem vor. Habt Ihr einen gültigen AppKey (siehe Kommentar von Maik)?
Evtl. auch den Request mal posten.

Viele Grüße

Daniel

**Comment by Torchok19081986** [comment]
Morgen, Vielen Dank für Antwort. 
Kunde hat keinen Toolbox in keinen Version bzw. nicht lizensiert hat. Braucht man für das API pro Benutzer eine ToolBox Lizenz ?

**Comment by Torchok19081986** [comment]
Ok. Vielen Dank für die Erklärung.  Das selbe Prinzip läuft auch bei anderen Kunde und sie haben keinen Appkey lizensiert, aber sie haben Toolbox mit Gold und Runtime.  Wie beantragt man die Appkey für Kunden für das Software bzw. was wird es dann für Kunden kosten ?

**Comment by konrad79** [comment]
Die Lizenzierung eines AppKeys funktioniert wie jede andere Lizenzierung von SelectLine Produkten auch. 
Dafür muss der jeweilige Fachhändler des Kunden sich an das Partnermanagement von SelectLine wenden. Der Fachhändler weiß, wie das geht ;-)

**Comment by Torchok19081986** [comment]
Ok. Vielen Dank.  Dann muss das App mit die Appkey geändert werden und Änderungen umprogrammiert werden.
