### ISSUE TITLE
Druckvermerk wird nicht gesetzt

### ISSUE THREAD

**Issue by burgt** [selectline-software/selectline-api#237]
Hallo,

ich habe das Problem das bei Verwendung von "/Documents/{documentKey}/Print" mit Datei/PDF Ausgabe der Druckvermerk nicht gesetzt wird. Leider konnte ich auch keine Option finden in der Status beeinflusst werden kann. Eine nachträgliches Aktualisieren des Belegs funktioniert leider nicht, wenn beispielsweise die Rechnung von einer Vorkasse abgeleitet wurde. 

Grüsse,
Thorsten Burg

**Comment by SusanneSchadenberg** [comment]
Hallo Thorsten,

welche Version ist bei Ihnen im Einsatz? 

In der aktuell ausgelieferten Version 22.1.4 wird der Druckstatus bei der Route /Documents/xxxx/Print gesetzt. 
Bei meinen Tests ist mir aufgefallen, das bei der Route Documents/xxxx/PrintPdf der Druckstatus nicht gesetzt wird. Das gebe ich inter zur Fehlerbehebung weiter.

Viele Grüße aus Magdeburg
Susanne

**Comment by burgt** [comment]
Hallo Susanne,

ich hatte den Test sowohl in der Testumgebung als auch beim Kunden mit der Wawi Version 22.1.4 erfolglos getestet. Allerdings ist die SLMobile Version noch auf dem Stand 22.1.2.. Im Downloadbereich steht noch keine neuere Version zur Verfügung.

Grüße,
Thorsten

**Comment by SusanneSchadenberg** [comment]
Hallo Thorsten,
könntest du mir bitte deinen genauen Weg vom Beleg bis zum Druck mit allen Routen beschreiben? Irgendwo muss es einen unterschied zu meinen Tests geben.
Vielen Dank im Voraus!
Gruß Susanne

**Comment by burgt** [comment]
Hallo Susanne,

Ausgangsbasis sind Lieferscheine mit einem Vorkassebeleg in der Prozesskette dir per post /Documents/{documentKey}/Successors in Rechnungsbelege übergeben werden. Der Einzelbeleg wird dann per /Documents/{documentKey}/Print mit PrintTarget "File" ausgegeben. Reicht dir das oder benötigst du mehr Informationen?

Grüße,
Thorsten

**Comment by SusanneSchadenberg** [comment]
Hallo Thorsten,
wird mit dem Belegübergabestatus gearbeitet? Wenn ja, welchen Status hat die Rechnung?
In meinen Tests hat die Rechnung den Status "Erledigt" und der Druckstatus wird dann auch gesetzt.
Gruß Susanne

**Comment by burgt** [comment]
Hallo Susanne,

ich nehme an du meinst den Bearbeitungsstatus? Der wird beim Kunden nicht eingesetzt. Hast du ggf. doch eine höhere SLMobile Version als die von mir eingesetzte 22.1.2?

Grüße,
Thorsten

**Comment by SusanneSchadenberg** [comment]
Hallo Thorsten,

gestern haben wir die 22.1.5 ausgeliefert, aber an der Version liegt es nicht.

Wir haben herausgefunden, warum der Druckstatus zurückgesetzt wird. 
Es liegt an den Mandanteneinstellung/Belege, wenn bei Druck "Druckstatus bei Belegänderung zurücksetzen" aktiviert ist, wird der Druckstatus beim Drucken per API zurückgesetzt.
Ist die Option in den Mandanteneinstellungen bei Ihnen bzw. bei Ihren Kunden aktiv?
Den Fehler, dass beim Drucken die Mandanteneinstellung gezogen wird, nehme ich auf und leite ihn weiter.

Viele Grüße aus Magdeburg
Susanne

**Comment by MatthiasGuse** [comment]
Hallo,

aktuell können wir das Zurücksetzen ohne die gesetzte Option nicht reproduzieren. Wir werden das im Rahmen der Fehlerbehebung im Zusammenhang mit der Option nochmal untersuchen.

Viele Grüße

**Comment by MatthiasGuse** [comment]
Hallo,

im Rahmen der Fehlersuche konnten wir das beschriebene Fehlerverhalten mit der aktuellen Version nur reproduzieren, indem bei dem Pfad der PDF Ausgabe ein ungültiger Pfad angegeben wurde. Wenn also aufgrund des fehlerhaften oder vom API Server aus nicht erreichbaren Pfades keine Datei erstellt wurde, wird auch der Druckstatus nicht gesetzt. 

Bitte prüfen Sie das nochmal.

Viele Grüße
