### ISSUE TITLE
Wartungsverträge lesen

### ISSUE THREAD

**Issue by doblum** [selectline-software/selectline-api#24]
Version 20.2.0
Wenn ich über die Route /Documents/{documentKey} versuche einen Wartungsbeleg zu lesen bekomme ich folgende Fehlermeldung:
{
\"StatusCode\": \"NotFound\",
\"ResponseCode\": \"42-017\",
\"Message\": \"Der übermittelte Parameterwert wird nicht unterstützt: documentKind\",
\"Details\": {
\"message\": \"Document kind V is not supported.\"
}
}

**Comment by VivienSchuboth** [comment]
Guten Tag,

bis heute wurde der Wartungsbeleg nicht in der Liste der unterstützten Belegtypen aufgeführt.
`https://demo.slmobile.de/demoApi/Help/Api/GET-Documents-documentKey`

Seit der Version 20.2 ist diese Information nun zentral im Themenbereich der Belege zu finden.
`https://demo.slmobile.de/demoApi/Help/ApiGroup?controllerName=Document`

Wenn dies in vergangenen Versionen möglich war, dann war das ein ungewolltes Verhalten der SelectLine API.
Falls Sie sich die Unterstützung des Wartungsvertrages wünschen, stellen Sie gern dazu einen Wunsch im Wünscheforum ein. `https://selectline.uservoice.com`

Mit freundlichen Grüßen,
Vivien Schuboth
