### ISSUE TITLE
wie kann ich feststellen, ob ein Customer / Supplier in der anderen Mandanten existiert

### ISSUE THREAD

**Issue by Torchok19081986** [selectline-software/selectline-api#242]
Hallo, ich habe Schwierigkeit festzustellen, ob Kunde / Lieferant in anderen Mandanten über CustomerAPI / SupplierAPI existiert.  
Momentan verwende ich die Methode CustomerReadCustomersAsync() für Customer und SupplierReadSuppliers() für Suppliert und dann davon die ein Element by Nummer mit Linq in C#. Gibt es die Möglichkeit festzustellen, ob Kunde oder Lieferant existiert, ohne, dass man die ganze Liste abfragt ?

**Comment by MatthiasGuse** [comment]
Prinzipiell ist das möglich, indem Sie sich mit zwei unterschiedlichen Benutzern an den jeweiligen Mandanten an der API anmelden und Sie das in Ihrer Anwendung abgleichen. Es gibt auch eine Route um explizit einen Lieferanten anhand des Schlüssels abzufragen. Ebenfalls haben Sie die Möglichkeit über die Filter auf bestimmte Felder in der Listenabfrage einzuschränken.

Viele Grüße
