### ISSUE TITLE
Kein Einloggen in der Programm in einem Server-Client Netzwerk möglich

### ISSUE THREAD

**Issue by Torchok19081986** [selectline-software/selectline-api#243]
Hallo, ich habe ein Problem mit dem Einloggen im Programm. Mit dem AccountAPI kann der Benutzer eingeloggt werden. Am Server, wo das Datenbank und die SL Mobile Mananger mit API und 2 API Benutzern eingerichtet ist, funktioniert aber.  Auf dem Client, wenn man versucht sich einzuloggen, kommt eine Fehlermeldung. Windows Firewall ist aus, Url ist erreichbar, aber Webserver antwortet nicht auf dem Login.

```charp

SelectLineErpAdministrationModuleModelsCredentials credentials1 = new SelectLineErpAdministrationModuleModelsCredentials(settings.Benutzer1Name, "pwd" , SelectLineErpAdministrationModuleModelsCredentials.LoginKindEnum.MobileApi, settings.Appkey);

var apiLogin = new AccountApi();
SelectLineErpAdministrationModuleModelsAccessTokenModel token1 = apiLogin.AccountLogin(credentials1);

````
Alles ist vorhanden. AppKey auch. Bin am verzweifeln. 

Eine andere Frage: ist die Configuration.Default immer localhost ? Wenn ja, muss man immer die Configuration für aktuelle Api wie. z.B.  AccountApi immer mitgeben, wie url, username und password ?

**Comment by Torchok19081986** [comment]
Morgen, am Server, wo der Mobile Manager installiert ist, ist einloggen möglich. Client bzw. Workstation, hat keinen Mobile Manager .  Wie kann ich den Swagger von Client erreichen ?

**Comment by Micha-Richter** [comment]
Im Normalfall aus dem eigenen Netz heraus unter https://<Servername>/slmobileApi/swagger/

**Comment by Torchok19081986** [comment]
ok. Vielen Dank für Antwort. Werde ich heute versuchen.  Was kann dann tun, wenn es 1. nicht erreichbar ist, und 2. im Swagger auch nicht eingeloggt werden kann ? Was kann es dann für Ursachen haben ? Wir haben es mit ausgeschalteten Firewall probiert, Friegabe des Verzeichnises . Leider hat es auch nicht funkioniert.

**Comment by Micha-Richter** [comment]
Schrittweise vortasten:
1. Ist der Server überall im Netzwerk erreichbar? (Ping als Netzwerktest)
2. Kann die Swagger-URL auf dem Server vom Client aus geöffnet werden? (IIS-Test)
3. Liefert ein Aufruf von https://\<Servername\>/slmobileApi/ im Browser ein Ergebnis? (Test "Läuft der Backendmanager und kann vom IIS erreicht werden")
4. Kann man sich über Swagger anmelden? (Test der SelectLine-Benutzerkonfiguration)

Irgendwie so würde ich das versuchen..

**Comment by Torchok19081986** [comment]
Vielen Dank für die Hilfe und Info. Wir haben es bis auf IIS Test erreicht. IIS war von Client nicht mehr erreichbar.  Nach dem Freigabe von *.:443 und anschließenden Neustart des IIS, hat es auf dem Client endlich funktioniert.
