### ISSUE TITLE
HTML-Text bei Artikel-Langtexten wird ignoriert

### ISSUE THREAD

**Issue by Bitlanech** [selectline-software/selectline-api#244]
Guten Tag

Wenn ein Artikellangtext als HTML erfasst wird, werden die HTML-Tags ignoriert -> Langtext wird ausgelesen und nicht HTML-Text.
Gibt es bereits eine Möglichkeit, die HTML-Texte zu einem Artikel abzufragen?

Liebe Grüsse
BitLane

**Comment by motionnow** [comment]
Guten Tag

also wenn du einfach nur nach einer Lösung suchst, egal ob schön oder nicht, dann kannst du über /ExtraTable/Text?filter=BLOBKEY EQ AR2
den Artikel HTML Langtext von 2 anzeigen lassen.
Die URL kannst du dir natürlich nach belieben zusammenbauen.
Den Response bitte aus der API übernehmen. ->Fields.HTMLText

**Comment by Bitlanech** [comment]
Danke für den Tipp. Mir ist bewusst, dass dies möglich ist; ein nativer Endpoint wäre jedoch wünschenswert :)

**Comment by MatthiasGuse** [comment]
Hallo,
der beschriebene Weg über die Route der Extrafelder ist nicht zu empfehlen und wird zukünftig nicht mehr unterstützt werden. 
alternativ können Sie die Makrofunktionalität nutzen. 

Viele Grüße
