### ISSUE TITLE
Möglichkeit alle Journale eines bestimmten Projektes anzuzeigen?

### ISSUE THREAD

**Issue by davidhommel** [selectline-software/selectline-api#246]
Hallo zusammen,

ich suche einen Weg, über die API alle Journale, welche zu einem Projekt gehören (als Hauptdatensatz oder Link), abzuholen. 
Leider finde ich weder in der Doku, noch im Postman oder Swagger ein Beispiel. 
Über den Zusatz ?filter= an der Abfrage könnte ich ja theoretisch filtern, hier kommt allerdingt das Problem aus #245 zum tragen.

Habt Ihr einen Tipp wie ich auf anderem Wege an die Journale zu einem Projekt komme, ohne ein API-Makro schreiben zu müssen?

**Comment by MatthiasGuse** [comment]
Hallo David,

aktuell sehe ich auch nur den einzig sinnvollen Weg über ein Makro.

Viele Grüße
