### ISSUE TITLE
Belegposition ohne Artikelnummer

### ISSUE THREAD

**Issue by motionnow** [selectline-software/selectline-api#247]
Es ist nicht möglich eine Belegposition vom Typ Artikel ohne eine Artikelnummer zu erstellen.
Getestet in der 22.1.5 .
Hier der Response
{
  "StatusCode": "NotFound",
  "ResponseCode": "42-017",
  "ResponseId": 17,
  "ResponseIdDescription": "ParameterValueNotSupportedException",
  "Message": "Der übermittelte Parameterwert wird nicht unterstützt: articleNumber",
  "Details": {
    "message": "Artikelnummer wurde nicht gefunden"
  }
}

**Comment by motionnow** [comment]
Zur Ergänzung für alle die das selbe Problem haben.
Das Problem kann über die Schnittstelle /ExtraTable/BelegP umgangen werden.
Dort einfach einen Eintrag in der BelegP erstellen und dann über die normale PUT der /Documents/{documentKey}/Positions/{documentPositionIdentifier}
bearbeiten.

**Comment by motionnow** [comment]
Zur Ergänzung für alle die das selbe Problem haben.
Das Problem kann über die Schnittstelle /ExtraTable/BelegP umgangen werden.
Dort einfach einen Eintrag in der BelegP erstellen und dann über die normale PUT der /Documents/{documentKey}/Positions/{documentPositionIdentifier}
bearbeiten.

**Comment by motionnow** [comment]
Zur Ergänzung für alle die das selbe Problem haben.
Das Problem kann über die Schnittstelle /ExtraTable/BelegP umgangen werden.
Dort einfach einen Eintrag in der BelegP erstellen und dann über die normale PUT der /Documents/{documentKey}/Positions/{documentPositionIdentifier}
bearbeiten.

**Comment by MatthiasGuse** [comment]
Hallo,
bei der API ist es aktuell nur vorgesehen mit vorhandenen Artikelnummern zu arbeiten. Evtl. hilft Ihnen die Nutzung einer Sammel- oder Dummyartikelnummer.

Das Bearbeiten von Tabellen, die keine Extratabellen sind, sind auf dem Weg über die ExtraTable Routen nicht gewünscht. Mit der Version 22.2 wird dies unterbunden. Zudem ist bei der Nutzung, wie Sie sie mit der BelegP beschrieben nicht sichergestellt, dass valide Daten entstehen. Hier kann es also noch zu evtl. erst später auffallenden Folgefehlern kommen. Daher sollten Sie bereits jetzt davon absehen.

Viele Grüße
