### ISSUE TITLE
Communication link failure

### ISSUE THREAD

**Issue by Logic-Bits** [selectline-software/selectline-api#248]
Hallo,

22.1.0.0 - gibt es Infos zu den Fehler oder einen geplanten Fix?

![grafik](https://user-images.githubusercontent.com/2421123/179482302-b33ad869-29d0-4bfe-9b3d-0bd45b705d69.png)

Vielen Dank

**Comment by MatthiasGuse** [comment]
Hallo,

wäre es möglich, dass Sie etwas mehr zu dem Fehler beschreiben?
In welchem Zusammenhang tritt der auf?

Viele Grüße

**Comment by Logic-Bits** [comment]
Hallo Herr Guse,

hierzu das original Ticket: 
https://github.com/selectline-software/selectline-api/issues/190

mehr Infos gibt es leider nicht - nach Tagen / Wochen X ist das einfach so, ohne dass jmd. etwas ändert.

Vielen Dank

**Comment by MatthiasGuse** [comment]
Der Fehlercode ist hier ein anderer. Kann man denn irgendwie sagen, welcher Aufruf diesen verursacht hat?

**Comment by Logic-Bits** [comment]
Es sollte ein Beleg aus dem Webshop angelegt werden. Das andere Ticket ist bei dem gleichen Kunden / gleiche Funktion.

**Comment by MatthiasGuse** [comment]
Wie schon angemerkt, hat der Fehler inhaltlich nichts mit #190 zu tun.

Die Fehlermeldung deutet auf einen Fehler im SQL hin. Um dies weiter untersuchen zu können, wären die vollständigen Logs vom Datum des Auftretens hilfreich. Falls diese noch zur Verfügung stehen, lassen Sie uns die bitte über den Support, unter Angabe des Github Issues, zukommen.

Viele Grüße

**Comment by Logic-Bits** [comment]
Hallo Herr Guse, Logs und Email ist an den Support raus.

**Comment by MatthiasGuse** [comment]
Leider ist den Logs nicht viel mehr zu entnehmen, als schon in dem oben gezeigten Bild zu sehen ist. 
Können Sie sagen, wie der konkrete Aufruf aussieht, der zu diesem Fehler führt?

Viele Grüße

**Comment by Logic-Bits** [comment]
Hallo,

https://demo.slmobile.de/demoApi/swagger/ui/index#/Document/Document_CreateDocument

CreateDocument mit KindFlag F.

Wollen Sie sich da mal mit draufschalten? Können Sie noch mehr Sachen überprüfen?
Noch ist der Backendmanager nicht neugestartet.

Der Kunde wird sich ohne Lösung alle paar Wochen / Monate wieder melden, ich kann das dann gerne wieder einstellen um zu sehen ob es eine Lösung derweil gibt.

Vielen Dank

**Comment by MatthiasGuse** [comment]
Hallo,

sich da draufzuschalte wird uns nicht viel mehr zeigen. Was meinen Sie damit, dass der Backendmanager noch nicht neugestartet wurde?
Soll das Problem mit einem Neustart des Backendmanagers behoben sein?

Wie schon weiter oben angedeutet, ist das eine Fehlermeldung vom SQL Server. Das deutet auf Verbindungsprobleme mit dem SQL Server hin. Es wäre möglich das Logging einzelner Programmteile zu erhöhen um mehr Information zum Auslöser zu erhalten. Allerdings erhöht das dann deutlich die Menge an geloggten Daten und wirkt sich unter Umständen auch auf die Performance aus. Da das Problem so selten auftritt, ist die Frage ob das dann sinnvoll ist. Bitte entscheiden Sie selbst.

Viele Grüße

**Comment by MatthiasGuse** [comment]
Mit Verweis auf #268 geschlossen.

**Comment by Logic-Bits** [comment]
Übrigens wie in meinen Logs zu sehen ist funktioniert die SQL Verbindung eine Millisekunde vorher noch ...


2022-12-15 16:30:03,913 INFO 5 SLapiORM.SLAsession - Found Customer '30137' by Email: 'fpschlueter@gmx.de'
2022-12-15 16:30:04,710 ERROR 5 SLapiORM.SLAsession - HTTP Response: 

{
  "StatusCode": "InternalServerError",
  "ResponseCode": "42-000",
  "ResponseId": 0,
  "ResponseIdDescription": "Undefined",
  "Message": "Communication link failure",
  "Details": {
    "iid": "00000000-0000-0000-0000-000000000000",
    "ErrorCode": "-2147467259",
    "OLEDBErrorCode": "-2147467259",
    "MessageWide": "Communication link failure",
    "ExceptionName": "EOLEDBError"
  }
