### ISSUE TITLE
Wie kann ich Makro mit API ausführen

### ISSUE THREAD

**Issue by Torchok19081986** [selectline-software/selectline-api#249]
Hallo ,  wie kann Makro mit API ausführen ? Laut Swagger ist es nur mit Post möglich, aber ich würde es gern mit API ausführen, da es bequemer und auch im code einfacher auszuführen .  Im IO.Swagger Bibliothek gibt es SelectLineErpMacroModuleModelsWawiMacroTask object , aber keine Beschreibung. Kann ich nur select ausführen, wenn man Makro in APIMakro Tabelle ist, oder kann dort auch Insert / Update ausgeführt werden ?

**Comment by Micha-Richter** [comment]
Die Makros in der APIMakro-Tabelle können alle Operationen ausführen.

Beispiel:
```
insert into APIMACRO(Name, Text)
Values(
  'setzeLeistungsdatum',
  '
  Update Beleg 
    Set Leistungsdatum = :leistungsdatum
  Where 
    Belegtyp = :belegtyp And Belegnummer = :belegnummer;
  '
)
```
