### ISSUE TITLE
Kunde mit Nummer existiert nicht im Mandanten

### ISSUE THREAD

**Issue by Torchok19081986** [selectline-software/selectline-api#250]
Hallo, ich habe ein Problem mit der API und zwar betrifft es folgende Methode "CustomerReadCustomersAsync". Diese liefert eine liste, aus einem Mandanten für Benutzer. Wenn man dazu einen Nummer mitübergibt mit Linq wie z.B. Where(k=>k.Nummer == nummer.Text), liefert o.g. Merthode immer 0, obwohl Kunde mit Nummer existiert bereits.  Ich habe auch alle anderen Methode für CustomerApi ausprobiert und  Ergebnis ist immer der Gleiche. Ich kann mit keiner Methode feststellen, ob Kunde by nummer in einem anderen Mandanten existiert. Kann mir jemand an dieser stelle helfen? 
Ich weiß nicht mehr weiter, wie ich mit der API feststellen kann, ob Kunde By Nummer existiert oder nicht.

**Comment by motionnow** [comment]
Hallo,

müsste es nicht k=>k.number ... sein?
Also zumindest laut Swagger Doku sollte es so sein.

**Comment by Torchok19081986** [comment]
hallo, sorry, habe mich verschrieben. Im code ist es , wie Sie es geschrieben haben.

**Comment by motionnow** [comment]
Hallo,

hast du auf den Async Call der Funktion mittels await gewartet? sodass im Objekt zu dem Zeitpunkt schon alle Kunden sind?

**Comment by Torchok19081986** [comment]
jap. mit await davor. Hat leider nichts gebracht.

**Comment by Micha-Richter** [comment]
Kommt denn der gesuchte Kunde im Ergebnis mit, wenn du das Where(...) weglässt?

**Comment by Torchok19081986** [comment]
Hallo, jap. Es kommt dann gewünschte Kunde mit Nummer. 
Ich habe auch festgestellt, dass es als async Task <T> und await sowohl bei unseren Testsystem als auch auf Kundenlivesystem nichts liefert und friert das app vollständig ein.

**Comment by Micha-Richter** [comment]
Was kommt heraus, wenn du statt des Where(..) ein Exists(..) oder Find(..) versuchst?

**Comment by Torchok19081986** [comment]
habe ich noch nicht ausprobiert. Nur mit Any() oder Count() Methoden.  Probiere ich gleich aus. Danke für den Tipp.

**Comment by Micha-Richter** [comment]
Lass uns noch mal sortieren: 
1. Der Aufruf 
```var customers = customerApi.CustomerReadCustomersAsync()```
enthält in `customers` den gesuchten Kunden?
1. Ein 
```war exists = customers.Exists(c => c.Number == kunde.Number)```
liefert dir aber `false`?
1. Und das 
```var customer = customers.Find(c => c.Number == kunde.Number)```
liefert ein NULL?

Klingt für mich ziemlich unwahrscheinlich, da Exists und Find Methoden der Standardbibliothek sind. Da drin erwarte ich jetzt keinen so einfachen Fehler ;)

kunde.Number enthält bei der Ausführung die korrekte Kundennummer?? Keine Leerzeichen/Sonderzeichen oder sowas drin?

Wenn du alles mit Ja beantwortest, lass eine einfache Schleife über die customers laufen und sieh dir im Debugger den Vergleich der Number's an. Dann kann's meiner Meinung nach nur noch dort stecken..

**Comment by Torchok19081986** [comment]
Ich kann alle Fragen mit "Ja" beantworten. Die Nummer sind alle korrekt. Das Debugger im Schleife muss noch machen . Vielen Dank.  
Eine letzte Frage habe ich noch: die o.g. Methode liefert eine Liste mit alle Kunden von jeweiligen Mandante bzw. angelemdeten API Benutzer. Diese hat mehrere Parameter und eine davon ist page. 
Kann es an dem Page sein? Wenn man aber die CustomerModel an das DataGridView als DataSource bindet, so kommen nur pro Page 11 bzw. 12 Elemente.

**Comment by Micha-Richter** [comment]
Ja, kann es. Wenn der Kunde in der gerade abgerufenen Page nicht enthalten ist.
Aber du hast die Frage 1 mit Ja beantwortet!?

Bei der Datenbindung an DataGridView und DataSource bin ich leider raus.

**Comment by Torchok19081986** [comment]
Hallo, in der Liste beim Abruf ist es enthalten. Will man aber es anzeigen, so werden nur die Elemente von 1. Page angezeigt.  WYSIWYG vllt ? Leider habe ich gerade keine Ahnung , wie man alle pages nach Kunden mit nummer durchsucht.
