### ISSUE TITLE
KontaktPerson wird mit anderen Nummer angelegt

### ISSUE THREAD

**Issue by Torchok19081986** [selectline-software/selectline-api#255]
Hallo, ich wollte in app die Kontaktpersonen anlegen. Wenn der Kontaktperson mit Number und Parentnumber nicht existiert soll es angelegt werden, sonst muss diese aktualisiert werden.  Die Abfrage zum Lesen der Kontaktperson liefert richtigen Ergebnis , aber wenn man diese dann anlegt , so wird das nächstfreie CRM_AdressenID genommen und NICHT die ausgelesene. 

für die Abfrage der Kontaktpersonen nutze ich 
```csharp
CustomerReadContactPersonsAsync(kunde.Number, null, 100, null, null, null, "(Parentnumber EQ " + kontaktperson.ParentNumber + ") AND (Number EQ " + kontaktperson.Number + ")") 
```
Method mit Parameter.

Für Aktualisierunug 
```csharp

CustomerUpdateContactPersonAsyncWithHttpInfo(kunde.Number, kontaktperson.Number, kontaktperson);

``` 

z.B, wenn der Kontaktperson aus Quellmandaten Number 18 hat und in Zielmandanten nicht existiert, dann bei der Anlagen der neuen Kontaktperson bekommt dieser Nummer nicht 18, sondern im meinen Fall, 19 oder 20. 

Muss ich etwas im WaWi umstellen oder wie kann selben Number mitübergeben ?

**Comment by Torchok19081986** [comment]
Morgen,  ich etwas Licht im Dunkel bringen. Laut der Beschreibung ist der ParentNumber "
Nummer der Person zu welcher der Kontakt gehört ". Nach dem Abruf des Kontaktpersonen wird der Kundennummer angezeigt. Ist das den so gewollt? Ist der ParentNumber nicht der Nummer der Adresse bzw. Hauptadresse ?

**Comment by MatthiasGuse** [comment]
Hallo,

so, wie in unsere API Dokumentation beschrieben, verlangen die Routen /Customers/{customerNumber}/ContactPersons die Kundennummer und nicht die CRM_Adressen_ID.

Viele Grüße
