### ISSUE TITLE
Beim seitenweisen Abruf der Kunden- und Artikelstammdaten werden ab Seite 770 die gleichen Datensätze zurückgemeldet

### ISSUE THREAD

**Issue by davidhommel** [selectline-software/selectline-api#256]
Hallo,

Einer unserer Kunden besitzt einen sehr großen Artikel- (~14000) und Kundenstamm (~23000). Beim API-Abruf dieser Stammdaten ohne Paging meldet die API eine leere Response. 

Wenn ich die Stammdaten mit Paging abrufe, bekomme ich ab der ~9. Seite auch eine leere Antwort, wenn die Anzahl der Datensätze/Seite größer als ~60 (Für Kundenstamm) bzw. größer als ~40 (bei Artikelstamm). 
Stelle ich die Anzahl DS/Seite kleiner ein, bekomme ich ab ca. Seite 30 eine leere Antwort. 
Nur wenn ich die Anzahl auf 30 (für Kunden) bzw. 20 (für Artikel) einstelle, kann ich das Paging sinnvoll nutzen - bis ich zu Seite ~770 komme, ab dann werden in der Antwort der API immer die gleichen Datensätze (in diesem Fall die von Seite 769) zurückgemeldet. 

In unserem Testsystem haben wir einen Artikelstamm mit 47.000 Datensätzen - Aufgrund des fehlerhaften Verhaltens der API kann ich nur bis zu 15400 Artikeldatensätze von der API abrufen. 

Die o.g. Grenzwerte kann ich nur ungefähr angeben, da sich das Verhalten der API je nach System immer etwas unterscheidet. 

Ich hänge eine Log-Datei meiner Software an, dort habe ich die API-Anfragen und Antworten mitgeschrieben. 
In Zeile 1874663 hole ich Seite 769 ab,
In Zeile 1877096 frage ich nach Seite 770, bekomme aber die gleiche Response wie bei Seite 769, bei den Anfragen für Seite 771,772,773 usw bekomme ich auch immer die Response von Seite 769.

[20220902.zip](https://github.com/selectline-software/selectline-api/files/9476508/20220902.zip)

**Comment by MatthiasGuse** [comment]
Hallo,

sorry, dass das so lange gedauert hat. 
Ohne Paging wird die maximale Größe des möglichen Response überschritten. Daher bleibt die Antwort leer.

Ich habe mir einen Artikelstamm mit mehr als 30t Artikel aufgebaut und habe die oben angegeben Grenzen ohne Probleme abfragen können. Ich konnte das Paging bis zum letzten Datensatz korrekt benutzen. Genutzt habe ich Postman.

Haben Sie mal versucht ob sich Swagger identisch verhält?

Viele Grüße

**Comment by davidhommel** [comment]
Hallo Herr Guse,
Habe es nochmal gestestet, der Swagger verhält sich ebenso.
Meiner Software gegenüber verhält sich die Api identisch dazu. 

Könnte vielleicht zu wenig Arbeitsspeicher dieses Verhalten auslösen?
Das System mit dem ich Teste hat 8GB RAM und eine 4x 2,2GHz CPU.

**Comment by MatthiasGuse** [comment]
Hallo,

an dem Testsystem ist soweit nichts auszusetzen. Ich selbst teste auf einer schmalen HyperV mit 4GB und nur 2 Kernen.
Wie mit @davidhommel direkt abgeklärt, führte das neu Aufbauen der Indizes und der Statistiken auf dem SQL Server zu gewünschten Ergebnis und beseitigten die geschilderten Probleme.

Viele Grüße
