### ISSUE TITLE
Kunden-/Artikeljournale können nicht gezielt abgerufen werden

### ISSUE THREAD

**Issue by davidhommel** [selectline-software/selectline-api#257]
Beim Abruf von Journalen werden Kundenjournale über den Blobkey und die CRM_ADRESSEN_ID mit dem Kunden verknüpft. Allerdings bekomme ich die CRM_ADRESSEN_ID des Kunden nirgendwo geliefert.

Wenn ich die Kunden via /Customers abrufe, bekomme ich diese ID nicht und kann somit auch keine Journale zu diesem Kunden abrufen, da ich beim Stammdatenabruf nicht die ID zurückgemeldet bekomme, anhand derer ich Journale Filtern bzw. überhaupt sinnvoll zuordnen könnte.

Das gleiche Problem gibt es auch bei den Artikeln.

**Comment by MatthiasGuse** [comment]
Hallo,

ich habe ein Workitem für die Weiterentwicklung der API erfasst.

Viele Grüße

**Comment by MatthiasGuse** [comment]
Wir freuen uns Ihnen mitteilen zu können, dass wir mit der Version 23.1 zwei neue API Routen zur Verfügung gestellt haben, mit der Ihre Anforderung erfüllt werden kann. Es stehen Ihnen für das Abfragen der Journale von Artikeln, Kunden, Lieferanten, Interessenten und Mitarbeitern neue Routen zur Verfügung.

Beste Grüße
