### ISSUE TITLE
Verbesserungsvorschlag: Inkonsistente Abrufkette für Belegjournale

### ISSUE THREAD

**Issue by davidhommel** [selectline-software/selectline-api#258]
Verbesserungsvorschlag:

Bekanntlich ist es ja möglich, Belegjournale über /Documents/xxxxx/Journals einzusehen. (Ist ja aktuell auch das einzige sinvoll nutzbare Vorgehen 😃)

Leider kann ich über die Abrufkette Dokumente -> Dokument x -> Journale zu Dokument x die Anhänge nicht abrufen, sondern muss dafür den Umweg über die /Journals-Verzweigung gehen. Vielleicht könnte man die Attachments-Methode noch zum /Documents/...-Zweig hinzufügen?

**Comment by MatthiasGuse** [comment]
Hallo,

wir haben das im Team diskutiert und sind der Meinung, dass der Weg über die ID des Journals funktional ausreicht. Eine Umsetzung des Wunsches würde zudem zu deutlich mehr Routen an verschiendensten Stellen führen, was wir gerne vermeinden möchten.

Viele Grüße
