### ISSUE TITLE
MetaDaten für Journale werden unterschiedlich oder garnicht ausgegeben

### ISSUE THREAD

**Issue by davidhommel** [selectline-software/selectline-api#259]
Hallo zusammen, ich nochmal.

Mir ist beim Entwickeln einer Funktion für den Abruf von Belegjournalen und deren Anhängen etwas aufgefallen:

- **/Documents/xxxx** liefert mir den zugehörigen Nutzer/Mitarbeiter unter `MetaData->CreationUserToken`.
- **/Documents/xxxx/Journals** gibt den Tag `MetaData` aus, der Wert ist allerdings immer `NULL`. Einzige Zuordnungsmöglichkeit hier ist das Feld `ResponsiblePerson`.
- **/Journals/yyyy** bringt auch einen leeren `MetaData`-Tag 
- **/Journals/yyyy/Attachments** verhält sich gänzlich anders, denn hier wird der Tag `AngelegtVon` zurückgegeben. 

Hier sollte vielleicht eine klare und konsequente Linie geschaffen werden

**Comment by SophiaWeise** [comment]
Hallo,

das von Ihnen beschriebene Verhalten konnten wir nachvollziehen. Wir haben zwei Workitems zu Ihrem Beitrag angelegt.
Das eine beschäftigt sich mit den Null-Werten der MetaData, das andere mit dem Angleichen der Rückgabewerte.

Beste Grüße, 
Sophia Weise

**Comment by MatthiasGuse** [comment]
Siehe auch #219

**Comment by MatthiasGuse** [comment]
Der Fehler wurde mit der kürzlich veröffentlichten Version 23.1.0 behoben.

Beste Grüße
