### ISSUE TITLE
Abruf der Artikel Bilder

### ISSUE THREAD

**Issue by Lars-Mue** [selectline-software/selectline-api#26]
Hallo,

ist es möglich die jeweiligen Artikel Bilder über die SelectLine API abzurufen?

Mit freundlichen Grüßen

Lars Münzer

**Comment by Lars-Mue** [comment]
Hallo,

dieses Thema ist uns aktuell sehr wichtig. Ich bräuchte hier bald eine klare Antwort.

Mit freundlichen Grüßen

**Comment by jprause1234** [comment]
Hallo,

nein, das geht derzeit nicht mit der API. Diese Information kann man übrigens auch gut über die Suchfunktion (ab Version 20.1) auf der API Hilfeseite herausfinden.

Viele Grüße
Jan Prause
