### ISSUE TITLE
JournalLink-Informationen weichen je nach Request-Typ voneinander ab

### ISSUE THREAD

**Issue by davidhommel** [selectline-software/selectline-api#261]
Moinmoin,

Wenn ich mit **_POST_ /Journals** einen Journaleintrag anlege, kann ich als Journal-Link z.B. angeben:
`  "JournalLinkInformation": {
    "LinkType": "document",
    "DocumentType": "A",
    "DocumentNumber": "AK101"
  }`

Hole ich mir diesen Journaleintrag dann mit **_GET_ /Journals/xxxx** bekomme ich folgende LinkInformationen:
`  "JournalLinkInformationList": [
    {
      "RecordId": 108,
      "JournalID": "b832aa02-eb85-4608-a308-a0eab377ba25",
      "Blobkey": "QA",
      "YearMonth": null,
      "TargetRecordId": 6281,
      "TakenFromPreviousYear": false,
      "IsMasterRecord": true
    }
  ]`

Es wäre echt toll, wenn der Link auch wieder so ausgegeben würde wie er eingetragen wurde. So wie es jetzt ist, kann ich entweder beim Anlegen die Infos zwischenspeichern oder ich muss beim Abrufen entweder mit **/Documents/xxxx/Journals** rekursiv über alle Journale (ggf. auch noch über alle Belege) gehen, um den ursprünglichen Link nachvollziehen zu können - oder ein API-Makro dafür schreiben. 
Ich finde beide Ansätze relativ unschön und würde mir eine einheitliche Ausgabe der JournalLinks (Am besten eine Kombination aus BEIDEN Responses) wünschen.

**Comment by davidhommel** [comment]
Gibt es hier Neuigkeiten zu?

**Comment by MatthiasGuse** [comment]
Die Journallink Informationen wurden entfernt, da sie nicht gebräuchlich waren. Die Umsetzung des Wunsches wird in #245 weiter verfolgt. Aktuell ist hier aber noch kein Zeithorizont erkennbar.

Viele Grüße
