### ISSUE TITLE
POST/Documents/{documentKey}/Successors mit Folgebelegnummer verwenden?

### ISSUE THREAD

**Issue by AM-Sartissohn** [selectline-software/selectline-api#262]
Hallo,
wir versuchen, über die API einen Beleg in einen Folgebeleg zu übergeben und dabei auch die Belegnummer des Folgebelegs mitzugeben. In der Dokumentation finde ich dazu aber keinen Hinweis:
- für POST/Documents/{documentKey}/Successors ist als Parameter nur der Belegtyp dokumentiert, nicht die Belegnummer - diese wird hier automatisch entsprechend der letzten Schlüsselnummer vergeben
- über POST/documents kann als Parameter Number die Belegnummer übergeben werden, die Verknüpfung mit dem Vorgängerbeleg ist dann aber nicht möglich, da die Positionen neu angelegt werden. Alternativ ist ein "Beleg übernehmen von" in den Folgebeleg auch nicht möglich, sondern nur ein "Beleg übergeben in"

Haben wir hier eine API-Funktion oder einen Parameter übersehen, ist die Dokumentation unvollständig, oder gibt es hier tatsächlich keine Möglichkeit, die Belegnummer bei der Belegübergabe zu übergeben?

**Comment by MatthiasGuse** [comment]
Hallo,

ich habe ein Workitem für die Weiterentwicklung der API erfasst.

Viele Grüße

**Comment by AM-Sartissohn** [comment]
Hallo,

können Sie mir hier einen (unverbindlichen, groben) Zeitrahmen für die Umsetzung geben? Wir müssten für die Umsetzung beim Kunden grob abschätzen können, ob die Funktion kurzfristig verfügbar sein wird oder erst mittel- oder langfristig geplant wird.

Vielen Dank.

**Comment by MatthiasGuse** [comment]
Hallo,

ich kläre, ob wir hier einen Zeitrahmen nennen können.

Viele Grüße

**Comment by MatthiasGuse** [comment]
Hallo,

es gibt passend zu Ihrer Anforderung einen Uservoice Wunsch "Beleg übernehmen von ... ", den Sie auch bereits unterstützen. Wir erwägen zur nächsten Version die Bereitstellung einer Funktion zur Übernahme von Positionen aus einem Beleg (analog "Beleg übernehmen von"). Um Ihre oben genannte Anforderung zu erfüllen, müssten Sie damit lediglich zwei Schritte durchführen - Beleg anlegen und anschließend die Positionen übernehmen. Ich denke damit gibt es vielfältigere Möglichkeiten für zukünftige API Anwendungen. 

Viele Grüße

**Comment by MatthiasGuse** [comment]
Mit der Version 22.3 haben wir eine API Funktion zum "Beleg übernehmen von" bereitgestellt. Siehe [Doku](https://demo.slmobile.de/demoApi/Help/Api/PUT-Documents-destinationDocumentKey-Predecessors-sourceDocumentKey).

Viele Grüße
