### ISSUE TITLE
Artikelgruppen

### ISSUE THREAD

**Issue by motionnow** [selectline-software/selectline-api#263]
Der filter in der Route /ArticleGroups wird ignoriert. Das setzen der Pageeigenschaft sorgt dafür das kein Ergebnis ausgeliefert wird.
Zudem wird in der Route [/Articles] das ArticleGroupLabel nicht gefüllt

**Comment by MatthiasGuse** [comment]
Hallo,

dies ist uns bekannt und bereits als Fehler erfasst.

Viele Grüß

**Comment by MatthiasGuse** [comment]
Der Fehler wurde mit der kürzlich veröffentlichten Version 23.1.0 behoben.

Beste Grüße
