### ISSUE TITLE
GET /Documents/...../Journals ignoriert Filter-Statements

### ISSUE THREAD

**Issue by davidhommel** [selectline-software/selectline-api#264]
Wenn ich Belegjournale mittels der GET-Abfrage `/Documents/.../Journals?filter=CategoryLabel EQ 'Intern'` **vorgefiltert** abrufen möchte, bekomme ich trotzdem alle Journaleinträge. Der Filter wird konsequent ignoriert.

**Comment by MatthiasGuse** [comment]
Hallo,

die Fehlerbehebung ist abgeschlossen und steht Ihnen mit der zukünftigen Version 22.3 zur Verfügung.

Viele Grüße
