### ISSUE TITLE
Print-Funktion der SelectLine API findet neuen Drucker nicht

### ISSUE THREAD

**Issue by FionNoir** [selectline-software/selectline-api#265]
Wir versuchen über die Route POST /Documents/{documentKey}/Print ([doku](https://demo.slmobile.de/demoApi/Help/Api/POST-Documents-documentKey-Print)) der SelectLine API einen Beleg auszudrucken. Das funktioniert mit unserem bisherigen Drucker, dem eine Druckvorlage zugeordnet ist problemlos. Nun haben wir einen neuen Etikettendrucker gekauft und hierfür eine neue Vorlage angelegt. 
**Aus SelectLine heraus (über die UI) funktioniert der Druck**, jedoch nicht über die Web/Mobile API.

Der Request zum Drucken unterscheidet sich vom alten Drucker nur über den Vorlagenname. Dennoch funktioniert nur der alte Drucker, nicht der Neue. 
Es gibt keine Fehlermeldung. 

`["ResponseType"]=> "OK"  `

Details zum Request den wir probiert haben:

POST https://host/slmobileApi/Documents/FAU-1234567/Print
Authorization: LoginId ...

`{"MasterName":"NEU_DE_123","NumberOfCopies":1,"PrintTarget":0}`

Muss der neue Drucker für die API noch irgendwie freigegeben werden?
Kann ich irgendwo sehen was Selectline mit meinen POST Requests macht? Log?

**Comment by MatthiasGuse** [comment]
Hallo,

der Drucker muss von dem Computer aus erreichbar sein, auf dem die mobilen Anwendungen (also die API) installiert sind. In der Druckvolage muss das Druckziel "Drucker" eingestellt sein:
![grafik](https://user-images.githubusercontent.com/31447000/191958995-d51e76f6-2ae4-47ec-a009-e4a06e542641.png)

Ebenfalls macht es Sinn nach dem Anlegen der Druckvorlage den Benutzer an der API einmal korrekt abzumelden, damit das Backend korrekt neugestartet wird. Alternativ den Backendmanager beenden und neustarten oder einfach den Server mal neustarten.

Viele Grüße

**Comment by Geoffrey-Fish** [comment]
Hi,
wäre cool gewesen wenn OP noch gesagt hätte, ob es so funktioniert hat.
