### ISSUE TITLE
OLE DB error occurred. Code 800703FAh

### ISSUE THREAD

**Issue by Logic-Bits** [selectline-software/selectline-api#268]
Hallo,

beim hinzufügen einer Belegposition kommt folgender Fehler einmal (hat Tage / Wochen funktioniert):
{

  "StatusCode": "InternalServerError",
  "ResponseCode": "42-000",
  "ResponseId": 0,
  "ResponseIdDescription": "Undefined",
  "Message": "OLE DB error occurred. Code 800703FAh",
  "Details": {
    "iid": "00000000-0000-0000-0000-000000000000",
    "ErrorCode": "-2147023878",
    "OLEDBErrorCode": "-2147023878",
    "MessageWide": "OLE DB error occurred. Code 800703FAh",
    "ExceptionName": "EOLEDBError"
  }
}

eine Idee? (v. 22.1.6)

Vielen Dank

**Comment by MatthiasGuse** [comment]
Hallo,

ist das zufällig der gleiche Anwender wie bei #248 ?

Viele Grüße

**Comment by Logic-Bits** [comment]
Hallo, Nein, ein anderer.
Der gleiche Fehler jetzt bei einem anderen Kunden (22.1.6):

(bei Position hinzufügen)

{
  "StatusCode": "InternalServerError",
  "ResponseCode": "42-000",
  "ResponseId": 0,
  "ResponseIdDescription": "Undefined",
  "Message": "OLE DB error occurred. Code 800703FAh",
  "Details": {
    "iid": "00000000-0000-0000-0000-000000000000",
    "ErrorCode": "-2147023878",
    "OLEDBErrorCode": "-2147023878",
    "MessageWide": "OLE DB error occurred. Code 800703FAh",
    "ExceptionName": "EOLEDBError"
  }
}

**Comment by MatthiasGuse** [comment]
Wie schon in #248 geschrieben, gehen wir hier von Verbindungsproblemen zum SQL Server aus.

Bitte versuchen Sie folgende Fragen zu beantworten:
1. Wie häufig tritt dieser Fehler auf?
2. Ist der Fehler reproduzierbar?
3. Aus was für einer Anwendung wird der Aufruf ausgeführt?
4. Welche Route wird aufgerufen?
5. Welche URL-Parameter werden gesetzt?
6. Welche Body-Daten werden mitgeschickt?
7. Wurden in dem Zeitraum Log-Einträge gemacht?
8. Welche Version ist im Einsatz?
9. Sieht im Mobilemanager alls i.O. aus?
10. Wurde etwas an Hard- oder Software geändert?
11. Sind die API und der SQL Server auf dem gleichen System installiert?

**Comment by Logic-Bits** [comment]
Hallo Herr Guse,

es tritt wieder auf (1x), vermutlich da ein Fenster geöffnet wird?
Aber normal sollte ja die API Fehlermeldung einen Code dafür haben.
Nach einem Neustart des Backendmanager hats dann mit einem erneuten Test geklappt.
Können Sie etwas aus der Fehlermeldung lesen?

```

{"Name":"SelectLine.API.Backend","TimeStamp":"2022-11-16T09:01:20.468Z","ServerTimeStamp":"2022-11-16T09:01:20.470Z","Host":{"Name":"SRV-1039246-1","Version":"Windows Server 2016 Server Standard (64-bit), Version 1607, Build 14393.5501","UserName":"CTS"},"Process":{"FileName":"C:\\Program Files (x86)\\SelectLine Software\\Mobile Anwendungen\\SelectLine API Backend\\SelectLine.API.Backend.exe","Name":"SelectLine.API.Backend.exe","ProcessId":"2460","ThreadId":"2324","Runtime":"13:46:09.4710000","MemoryPrivateBytes":25341952},"LogLevel":"Error","Message":"EUiElementCreatingInServerModeException wird geworfen","Program":{"BenutzerKuerzel":"xx","MandantName":"xxx","Version":"22.1.6.0"}}
{"Name":"SelectLine.API.Backend","TimeStamp":"2022-11-16T09:01:20.500Z","ServerTimeStamp":"2022-11-16T09:01:20.502Z","Host":{"Name":"SRV-1039246-1","Version":"Windows Server 2016 Server Standard (64-bit), Version 1607, Build 14393.5501","UserName":"CTS"},"Process":{"FileName":"C:\\Program Files (x86)\\SelectLine Software\\Mobile Anwendungen\\SelectLine API Backend\\SelectLine.API.Backend.exe","Name":"SelectLine.API.Backend.exe","ProcessId":"2460","ThreadId":"2324","Runtime":"13:46:09.5030000","MemoryPrivateBytes":25485312},"LogLevel":"Error","Message":"unbekannt, TTimer","Exception":{"Type":"EUiElementCreatingInServerModeException","Message":"Die Aktion wurde abgebrochen, weil versucht wurde ein Fenster zu \u00F6ffnen. \"TDlgFehlerProt\""},"Program":{"BenutzerKuerzel":"xx","MandantName":"xxx","Version":"22.1.6.0"}}
{"Name":"SelectLine.API.Backend","TimeStamp":"2022-11-16T09:01:20.515Z","ServerTimeStamp":"2022-11-16T09:01:20.517Z","Host":{"Name":"SRV-1039246-1","Version":"Windows Server 2016 Server Standard (64-bit), Version 1607, Build 14393.5501","UserName":"CTS"},"Process":{"FileName":"C:\\Program Files (x86)\\SelectLine Software\\Mobile Anwendungen\\SelectLine API Backend\\SelectLine.API.Backend.exe","Name":"SelectLine.API.Backend.exe","ProcessId":"2460","ThreadId":"2324","Runtime":"13:46:09.5180000","MemoryPrivateBytes":25571328},"LogLevel":"Error","Message":"unbekannt, TApplication","Exception":{"Type":"EHinweisDialogInServerModeException","Message":"Hinweis"},"Program":{"BenutzerKuerzel":"xx","MandantName":"xxx","Version":"22.1.6.0"}}
{"Name":"SelectLine.API.Backend","TimeStamp":"2022-11-16T23:00:31.325Z","ServerTimeStamp":"2022-11-16T23:00:31.327Z","Host":{"Name":"SRV-1039246-1","Version":"Windows Server 2016 Server Standard (64-bit), Version 1607, Build 14393.5501","UserName":"CTS"},"Process":{"FileName":"C:\\Program Files (x86)\\SelectLine Software\\Mobile Anwendungen\\SelectLine API Backend\\SelectLine.API.Backend.exe","Name":"SelectLine.API.Backend.exe","ProcessId":"2460","ThreadId":"2324","Runtime":"-1.03:45:20.3280000","MemoryPrivateBytes":16953344},"LogLevel":"Error","Message":"EUiElementCreatingInServerModeException wird geworfen","Program":{"BenutzerKuerzel":"xx","MandantName":"xxx","Version":"22.1.6.0"}}
{"Name":"SelectLine.API.Backend","TimeStamp":"2022-11-16T23:00:31.350Z","ServerTimeStamp":"2022-11-16T23:00:31.352Z","Host":{"Name":"SRV-1039246-1","Version":"Windows Server 2016 Server Standard (64-bit), Version 1607, Build 14393.5501","UserName":"CTS"},"Process":{"FileName":"C:\\Program Files (x86)\\SelectLine Software\\Mobile Anwendungen\\SelectLine API Backend\\SelectLine.API.Backend.exe","Name":"SelectLine.API.Backend.exe","ProcessId":"2460","ThreadId":"2324","Runtime":"-1.03:45:20.3530000","MemoryPrivateBytes":17059840},"LogLevel":"Error","Message":"unbekannt, TTimer","Exception":{"Type":"EUiElementCreatingInServerModeException","Message":"Die Aktion wurde abgebrochen, weil versucht wurde ein Fenster zu \u00F6ffnen. \"TDlgFehlerProt\""},"Program":{"BenutzerKuerzel":"xx","MandantName":"xxx","Version":"22.1.6.0"}}

```

**Comment by MatthiasGuse** [comment]
Hallo,

Können Sie uns alle Logs dazu zur Verfügung stellen?

Wie sind bei Ihnen die Programmeinstellungen für die Meldungen gesetzt?
![grafik](https://user-images.githubusercontent.com/31447000/202624636-24c8419d-2d53-43e2-a1d0-28012bd836e3.png)

**Comment by Logic-Bits** [comment]
Hallo,

wie bei Ihnen auch, soll ich das umstellen auf Punkt 2?

Danke!

**Comment by MatthiasGuse** [comment]
Nein, die EInstellung kann so bleiben.

Können Sie uns alle Logs dazu zur Verfügung stellen?

**Comment by MatthiasGuse** [comment]
Logs angeschaut. Wie schon in #248 angemerkt, deuten alle Einträge in den Logs auf Verbindungsprobleme mit dem SQL Server hin. Sämtliche Programmteile loggen diese Fehler. Das Problem liegt also augenscheinlich außerhalb unserer Anwendungen.

Mehr Unterstützung können wir Ihnen vorerst dazu nicht bieten.

Viele Grüße

**Comment by Logic-Bits** [comment]
Gibt es eine Möglichkeit den Backendmanager regelmäßig Neuzustarten? (Aufgabeplanung o.ä?)
Wenn die Software das nicht Intelligent lösen kann / will, dann müssen wir eine frische Verbindung erzwingen.
Fast jede Woche verschwende ich Zeit bei verschiedenen Kunden den Backendmanager Neuzustarten, das kann ja nicht die Lösung sein.

**Comment by ThePholph** [comment]
Hallo,

gibt es evtl. eine Gemeinsamkeit bei den Kunden? Wir haben auch viele Kunden mit eigenen Anwendungen auf Basis der API und bisher nur 1 Mal ähnliche Probleme gehabt, die sich jedoch nach einem Update der API bzw. MDE, vor einiger Zeit, erledigt haben. 

Wir arbeiten über eine eigenen Middleware, die solchen Fällen entgegenwirkt (automatische Neuanmeldung etc.), dies aber protokolliert. Auch hier kommt es ab und an zu Verbindungsfehlern, die sich bisher jedoch alle aufklären ließen und durch unsere Lösung nicht auf den Anwender auswirken (evtl. dauert der Request mal 0,5 bis 1 Sek. länger). Da die API auf dem Backend-Manager bzw. einer WaWi-Instanz basiert, ist uns auch bewusst, dass die SL.API gewisse technisch bedingte Nachteile mit sich bringt, die wir aber bisher mit der Middleware gut händeln können.

Ein regelmäßiger Neustart wäre in meinen Augen auch nicht hilfreich, da es sein kann, dass während eines API-Request einfach die Verbindung gekappt wird und dieser läuft dann ebenfalls in einen Fehler der behandelt werden muss.

Wir hoffen auch, dass die Entwicklung der API voranschreitet und diese evtl. irgendwann auch die Basis der WaWi darstellen wird, sodass die meisten Funktionen auch uns Partnern zur Verfügung stehen (in ein paar Jahren vielleicht) 😅

Grüße

Daniel

**Comment by Logic-Bits** [comment]
Hallo, 
danke für den Input.
Wir arbeiten auch mit einer eigenen Middleware (machen auch nur das nötigste mit der API), das "lustige" ist ja dass die Beleganlage funktioniert (Neuer Beleg auch in SL => Ergo SQL Verbindung muss ja da klappen), und beim hinzufügen der Position dann angeblich ein SQL Problem auftritt (millisekunden später).
Das die Neustart Lösung nicht optimal ist, ist klar. Aber 1000 mal besser als manuell jedesmal den Backendserver neuzustarten.
Für bessere Lösungsvorschläge die man "heute" umsetzen kann wären wir natürlich sehr dankbar.

**Comment by Logic-Bits** [comment]
"StatusCode": "InternalServerError",
  "ResponseCode": "42-000",
  "ResponseId": 0,
  "ResponseIdDescription": "Undefined",
  "Message": "OLE DB error occurred. Code 800703FAh",
  "Details": {
    "iid": "00000000-0000-0000-0000-000000000000",
    "MessageWide": "OLE DB error occurred. Code 800703FAh",
    "ErrorCode": "-2147023878",
    "OLEDBErrorCode": "-2147023878",
    "ExceptionName": "EOLEDBError"
  }

v 22.2.5

**Comment by MatthiasGuse** [comment]
Hallo,

auch hier besteht die Möglichkeit das Logging der API selbst für einen gewissen Zeitraum auszuweiten.

Bitte legen Sie dazu im Installationsverzeichnis unter `...\SelectLine Software\Mobile Anwendungen\LokaleDaten\WebApi` eine Datei `SelectLine.Erp.WebApi.WebHost.logini` mit folgendem Inhalt an:
```
[*]
Level=Debug
Trace=Off
```
Im Anschluss bitte die Webseite neu einrichten. Nach erneutem Auftreten des Problems bitte den ungefähren Zeitpunkt und das gesamte Verzeichnis "Logs" zur Verfügung stellen (falls gewünscht an den Support senden). Dann bitte die Datei wieder entfernen oder umbenennen und die Webseite nochmal neu einrichten.

Viele Grüße

**Comment by Logic-Bits** [comment]
Neue erweiterte Logs wieder ans Postfach geschickt.

**Comment by MatthiasGuse** [comment]
Das Startverhalten und die Stabilität der API, insbesondere in Bezug auf die Backendprozesse,
wurden mit der Version 23.1.0 optimiert und Fehler korrigiert. Sollten Sie Probleme mit der Verfügbarkeit des
Backendmanagers haben, empfehlen wir Ihnen nach einem Update auf diese Version die Funktion
„Datenbank einrichten“ im Mobile Manager auf der Seite „Datenbank“ erneut auszuführen.

Viele Grüße
