### ISSUE TITLE
Bestandsabgleich

### ISSUE THREAD

**Issue by Bernie5400** [selectline-software/selectline-api#269]
Hallo 

Wir nutzen die SelectLine Rest-API zur Bespielung einer Schnittstelle zu unserem Fullfillment Partner. Der Partner sendet täglich den aktuellen Bestand der bei ihm eingelagerten Artikel. Diesen Bestand möchten wir wo nötig (also bei Abweichung) in das System übernehmen.
Laut API-Doku finden wir diese Möglichkeit nur über Inventories. Gibt es keine weitere Möglichkeit den Bestand zu pflegen (direkt über die Lager)?
Falls nein: Wie genau muss das Inventory aufgesetzt sein, damit es dauerhaft genutzt werden kann und der Bestand jeweils übernommen wird?)

Noch eine weitere Rückfrage:
Wir versuchen den Wert des Feld CustomField.Text1 bei den Documents auf gleich NULL zu filtern. Laut https://demo.slmobile.de/demoApi/Help/FilterQueryLanguageHelp sollte dies mit IS NULL funktionieren.
Allerdings erhalten wir folgende Fehlermeldung:
{
    "StatusCode": "InternalServerError",
    "ResponseCode": "42-000",
    "Message": "Falsche Syntax in der Nähe von '@b1703b014a9b412cac9fb9754488554c'.\r\nFalsche Syntax in der Nähe des OR-Schlüsselworts.\r\nFalsche Syntax in der Nähe des OR-Schlüsselworts.\r\nFalsche Syntax in der Nähe des OR-Schlüsselworts.\r\nFalsche Syntax in der Nähe des OR-Schlüsselworts.",
    "Details": null
}
Wenn wir es zusammenschreiben also ISNULL erhalten wir "Message": "ISNULL not allowed. Expect eq, noteq, ct, notct, sw, notsw, ew, notew, gt, ge, lt, le, is",
hier ist IS NULL nicht als gültiger Operator aufgeführt. 
Auch der Versuch mit EQ NULL klappt nicht. (liefert nicht die erwarteten Sätze mit Text1 gleich null)

Wie wird hier korrekt auf NULL gefiltert?

Danke für die Hilfe

lg
Bernie

**Comment by MatthiasGuse** [comment]
Hallo,

bitte achten Sie zukünftig darauf, dass Sie für jede Funktion / jeden Fehler / jeden Wunsch ein eigenes Issue hier im Github anlegen.

Das Problem zu den NULL Werten werden wir überprüfen.

Zum Bestandandsabgleich ist eine Inventur recht ungeeignet, da die Bestände erst angepasst werden, wenn Sie die Inventur abgeschlossen wird und zwischenzeitliche Bestandsänderungen hier mit berücksichtigt werden müssten. Mein Vorschlag wäre es hier die Differenz in einer manuellen Lagerung zu erfassen. 

Viele Grüße

**Comment by SophiaWeise** [comment]
Hallo,

den beschriebenen Sachverhalt bezüglich der NULL Werte habe ich nachvollzogen und zur Fehlerbehebung aufgenommen.

Beste Grüße

**Comment by MatthiasGuse** [comment]
Der Fehler wurde mit der kürzlich veröffentlichten Version 23.1.0 behoben.

Beste Grüße

**Comment by Bernie5400** [comment]
Super Danke für die Info Bernhard MüllerB&B IT-Solutions OGSikorastrasse 145400 Hallein
