### ISSUE TITLE
Paketnummer

### ISSUE THREAD

**Issue by Bernie5400** [selectline-software/selectline-api#270]
Hallo

Wir bekommen von einen externen Dienstleister eine Trackingnummer für die Pakete
Wie schaffe ich das das wir sie per API Schnittstelle retour in die Wawi bekommen 
Vl gibt es ja die möglichkeit das Feld Paketnummer in der Selectline zu befüllen

Danke

**Comment by MatthiasGuse** [comment]
Hallo,

hier gibt es seitens der API aktuell keine Standardfiunktion. Eine Lösung würde hier meines Erachtens nur über ein selbst erstelltes Makro möglich sein.

Viele Grüße

**Comment by Bernie5400** [comment]
Hallo

Danke für die Info
Gibt es für die Makros eine technische Hilfe bzw eine Funktionsübersicht

Viele Grüße
Bernie

**Comment by MatthiasGuse** [comment]
Hallo!
Für Makros gibt es von unserer Seite keinerlei Garantien für die Richtigkeit und die Zweckerfüllung des Makros. Probieren Sie die SQL-Anweisung erst an einer Testumgebung aus und machen Sie eine Sicherheitskopie der aktuellen Daten. Alles, was Sie mit einem Makro tun, geschieht auf Ihre eigene Gefahr hin.

Hier mal ein Beispiel, wie Sie bspw. ein API Makro in der Datenbank anlegen können (das ist im Makroassistenten der Warenwirtschaft auszuführen):

`insert into APIMACRO(Name, Text)
Values(
  'ErfassePaketnummer',
  'INSERT INTO [Paket]
	([Belegtyp], [Belegnummer], [Zaehler], [Paketnummer], [Gewicht])
	VALUES
	(N''F'', :Auftrag, 1, :Paketnr, :Gewicht)'
)`
In diesem Makro ("ErfassePaketnummer") ist der Belegtyp fest auf Auftrag ('F') festgelegt und es wird immer davon ausgegangen, dass es das erste Paket zu diesem Beleg ist (Zaehler = 1). Das heißt, dass nur ein Paket pro Beleg hinzugefügt werden kann. Wenn man mehr möchte, könnte man den Zaehler noch als Parameter mitgeben oder das Makro entsprechend schlau gestalten, dass der nächste Wert automatisch bestimmt wird.

Das Makro führt man dann im Swagger bspw. so aus:
![grafik](https://user-images.githubusercontent.com/31447000/197169953-81272161-df6d-4f9b-94e2-a465e034fd33.png)

Viel Erfolg damit!
