### ISSUE TITLE
Abrufen von Nicht-Belegjournalen ab API Version 23.2

### ISSUE THREAD

**Issue by davidhommel** [selectline-software/selectline-api#273]
Hallo,

im API-Updateportal ist die Route "Journals" als deprecated markiert mit dem Hinweis, das diese Route ab Version 23.2 entfernt wird.
Da wir über die API auch Journale, die keinem Beleg sondern z.B. einem Projekt/Artikel/Kunden/.... zugeordnet sind, abrufen brauche ich die Information, ob es in Version 23.2 eine andere Möglichkeit zum Abrufen dieser Journale geben wird.
![grafik](https://user-images.githubusercontent.com/72391062/200840700-cf95184b-5a0c-412a-ab5d-421304ee08f9.png)

**Comment by ThePholph** [comment]
Hallo,

ich bin von der Änderung auch nicht angetan, da ich die Funktion auch in vielen Anwendungen verwende, aber es ist lediglich die Methode POST betroffen. Das bedeutet, dass die Journale, wie gewohnt über GET /Journals abgerufen werden können, aber nicht mehr angelegt. Dies funktioniert dann nur noch über Documents/{documentKey}/Journals. 

Ich würde mir eine Erweiterung wünschen, sodass zu jedem Objekt (wie in der WaWi umgesetzt) Journale angelegt, geändert und gelesen werden können. Dies muss ich aktuell über eine eigene Lösung realisieren.

Ich hoffe, ich konnte helfen.

Viele Grüße

Daniel

**Comment by davidhommel** [comment]
Hey,

> Ich würde mir eine Erweiterung wünschen, sodass zu jedem Objekt (wie in der WaWi umgesetzt) Journale angelegt, geändert und gelesen werden können. Dies muss ich aktuell über eine eigene Lösung realisieren.

Sowas wäre natürlich ein absoluter Traum, aktuell bin ich auch dabei das mit einer eigenen Lösung umzusetzen.


> aber es ist lediglich die Methode POST betroffen

Ja stimmt, hatte das gar nicht registriert - dann ist der Wegfall ja verkraftbar und auch nur logisch, weil ja ohnehin nur Belegjournale angelegt werden können und der Pfad über Documents da wirklich sinnvoller ist
