### ISSUE TITLE
Bemerkungen in Lagerungen mit angeben

### ISSUE THREAD

**Issue by danix33** [selectline-software/selectline-api#274]
Ich sehe aktuell keine Möglichkeit zu einer Lagerung eine entsprechende Bemerkung mizugeben, wie es in der Warenwirtschaft aber möglich ist, siehe Bild. Gibt es oder wird es hier eine Möglichkeit geben?

![2022-11-09_16h13_28](https://user-images.githubusercontent.com/72063374/200867929-c5859867-6bf8-4990-ad5a-62156959f885.png)

**Comment by MatthiasGuse** [comment]
Hallo,

das Hinzufügen einer Bemerkung ist aktuell nicht vorgesehen und aktuell nicht in Planung. Als SelectLine Fachhändler besteht die Möglichkeit dies als Wunsch im Uservoice Wünscheforum einzureichen.

Viele Grüße
