### ISSUE TITLE
Nach dem Update auf  22.2.5 Mobile Version

### ISSUE THREAD

**Issue by Torchok19081986** [selectline-software/selectline-api#275]
Hallo, ich habe ein Problem nach dem Update auf die neue 22.5 Version. Nach dem Update vor 2 Tagen durchgeführt wurde, erscheint beim Verbinden auf die Seite von slMobileApi folgende Fehler: 
![SL Error](https://user-images.githubusercontent.com/25432729/200869731-71c2e5bd-8e92-40df-b382-7222fbd765b0.PNG)

Auch die erwähnte Datei ist im dieser Version im WebApi Verzeichnis vorhanden. Ist dieses Fehler von der Installation oder liegt es an der veraltete dll ??

WebApi Request wird nicht akzepziert und die Fehlermeldung ist gleiche. 

Ich habe noch etwas info für dieses Dll gefunden. Laut Stackoverflow ist das nun ein Teil des Microsoft.AspNet.WebApi.Client Packages.

**Comment by MatthiasGuse** [comment]
Hallo,

von welcher Version haben Sie den aktualisiert? 

Bitte prüfen Sie mal, ob .net 4.8 auf Ihrem System installiert ist.

Viele Grüße

**Comment by Torchok19081986** [comment]
Morgen, wir haben von der Version 22.24 auf 22.2.5 aktualisiert. .NET Framework 4.8 ist installiert.

**Comment by MatthiasGuse** [comment]
OK. Das erklärt das Verhalten nicht.

Was sagen die Tests im Mobilemanager? 
Mögliche Ansätze:
- Webseite neu einrichten
- IIS neustarten

Viele Grüße

**Comment by MatthiasGuse** [comment]
Zwischen den beiden genannten Versionen gab es nur marginale Änderugen. Nichts, was die Installation selbst betrifft. Es wird eine Datei in der Meldung genannt. Vielleicht ist diese beschädigt oder nicht vorhanden.

Mein Vorschlag wäre im Mobile Manager die Seite herunter zu nehmen ("Seite Konfigurieren"), den Backendmanager zu beenden und anschließend das Setup nochmal durchlaufen zu lassen.

Viele Grüße

**Comment by Torchok19081986** [comment]
Ok. Vielen Dank . Ich probiere es aus und berichte dann das Ergebnis. Reparatur Installation wurde gestartet.

**Comment by Torchok19081986** [comment]
Morgen, wir haben nun die Reparatur Installation laufen lassen und es hat was gebracht. Die SlmobileAPI Seite funktioniert wieder und Rest Request werden normal verarbeitet.  

Es wurde eine neue VM im Hyper-V angelegt und auf diese VM wurde die Installation umgezogen und dann update 22.2.5 eingespielt. Kann sein , dass die Assembly im Bild im GAC bei der Installation von Mobile Manager registiert wird und nach Update auf 22.2.5 dies nicht mehr war und somit die Mobile Manager API Seite nicht laden könnte?

**Comment by MatthiasGuse** [comment]
Hallo,
schön, dass dies das Problem beseitigt hat. Weshalb es dazu kam, können wir leider nicht beurteilen, da das bisher nicht weiter gemeldet wurde und wie schon genannt, es keine Änderungen an der Installation zwischen den beiden genannten Versionen gab.

Grüße
