### ISSUE TITLE
Abruf Wartungsverträge über API

### ISSUE THREAD

**Issue by timothy3001** [selectline-software/selectline-api#277]
Hallo,

wir möchten Wartungsvertrags-Belege und deren Positionen über die SelectLine REST API abrufen, mussten aber leider feststellen, dass dies scheinbar nicht unterstützt wird: https://demo.slmobile.de/demoApi/Help/ApiGroup?controllerName=Document 

Gibt es hier Pläne, dass diese Dokumentart zeitnah unterstützt wird? Oder gibt es Alternativen, um Wartungsvertragsinformationen und deren Positionsinformationen zu erhalten / Best Practices?

Viele Grüße
Timo

**Comment by MatthiasGuse** [comment]
Hallo,

hierfür gibt es bisher keine eigene Route. In Planung ist dazu ebenfalls nichts. 

Aktuell sehe ich nur die Möglchkeit sich das über ein Makro auszulesen. Siehe API Dokumentation oder mal hier im Github suchen.

Viele Grüße

**Comment by timothy3001** [comment]
Gibt es Möglichkeiten, dies mal weiterzugeben, sodass eine Unterstützung entwickelt wird? 

Es wundert mich etwas, dass man bei einer kostenpflichtig lizenzierten Schnittstelle mit Workarounds arbeiten muss für Wartungsverträge, die ansonsten in der SelectLine-Welt problemlos unterstützt werden. 

Wir entwickeln verschiedene Lösungen in Kombination mit SelectLine und leider mussten wir in jedem Projekt bisher mit Workarounds über die Datenbank oder Makros oder Ähnliches arbeiten.

**Comment by MatthiasGuse** [comment]
Hallo,

eine Schnittstelle, so wie unsere API es ist, kann immer nur so viel, wie der Hersteller es erlaubt. Mit dem Vorhandensein so einer Schnittstelle besteht ja per se kein Anspruch darauf, dass sämtliche Funktionen der eigentlichen Anwendung bereitgestellt werden, egal ob sie kostenpflichtig ist oder nicht.

Um über den Funktionsumfang hinaus eigene Anforderungen umsetzen zu können, gibt es die Makro Funktionalität, die auch über die API verfügbar ist.

Als SelectLine Fachhändler haben Sie die Möglichkeit Ihre Wünsche im Uservoice Wünscheforum einzureichen.

Viele Grüße

**Comment by dominiksaul** [comment]
@timothy3001
Guten Tag,
Wir haben dieselben Anforderungen und müssen ebenfalls Wartungsverträge via die API aufrufen, erstellen und bearbeiten können.
Wir haben nun hierfür eine idee auf dem Uservoice Forum erstellt: https://selectlinech.uservoice.com/forums/275151-selectline-api/suggestions/47626409-wartungsvertr%C3%A4ge-via-api-abrufen-erstellen-und-ve
Gerne können Sie dort Votes abgeben, damit die Idee mehr gewichtet wird.

Freundliche Grüsse,
Dominik Saul - EVOK
