### ISSUE TITLE
Aktualisieren eines Kontaktperson für einen Kunden

### ISSUE THREAD

**Issue by Torchok19081986** [selectline-software/selectline-api#278]
Hallo,  ich habe ein Problem mit dem Update eines Kontaktpersonen für einen Kunden. Laut der Beschreibung braucht man den Kundennummer, Kontaktpersonnummer und der Kontaktperson object selbst. Ich finde Kontaktpersonnummer im Model von Kontaktperson nicht. Der Parentnumber ist der Kundenummer , zu welcher Kunden dieser gehört und der Number ist der Nummer des Datensatzes, ID des Datensatzes. 
Ich verwende die letzte Beschreibung API vom Swagger nach dem Update auf 22.2.5.  Die Methode CustomerUpdateContactPersonAsyncWithHttpInfo() mit parameter schlägt immer fehl. Es kommt RessoureNotFoundException. 10-006. 
Wie kann ich den Kontaktperson , welche bereits im anderen Mandanten existiert, aktualisieren ?

**Comment by MatthiasGuse** [comment]
Hallo,

existiert denn die Kontaktperson in genau dem Mandanten an dem Sie angemeldet sind?

Wie sieht ihr API Aufruf aus? Inkl. Content?

Grüße

**Comment by Torchok19081986** [comment]
Hallo, die Kontaktperson existiert bereits im Mandanten für einen angemeldeten API Bentuzer. API Aufruf sieht wie gefolgt aus : 
als 1. versuche die mit folgenden Aufruf die Liste der Kontaktpersonen zu bekommen, in etwa so: 
```csharp

var liste = customerApi.CustomerReadContactPersonsAsync(kundennummer,0,0,null, null, null, "Number EQ " + kontaktperson.Number + " AND ParentNumber EQ " + kontaktperson.ParentNumber)

```

danach wird nun iteriert mit foreach schleife. Wenn der Kontaktperson existiert und dann wird mit folgenden Anweisung versucht , die  zu aktualiseren. Die Aufruf stellt fest, dass die Kontaktperson existiert, soweit läuft richtig. 

```csharp

 var response = customerApi.CustomerUpdateContactPersonAsyncWithHttpInfo(kundennummer, kontaktperson.Number, kontaktperson);

```

Genaue an dieser Stelle kommt 10-0006 RessourceNotFoundException.

**Comment by MatthiasGuse** [comment]
Hallo,

bitte schicken sie den konkreten API Request oder beschreiben Sie, wie das Verhalten im Swagger / Postman zu reproduzieren ist.

Viele Grüße

**Comment by Torchok19081986** [comment]
Hallo. Ich versuche es zu beschreiben, wie man es Swagger evtl. nachvollziehen kann. 

1. Logen Sie sich mit zwei API Benutzer im Swagger ein.  Es müssen immer zwei Benutzer angemeldet sein.
2. Lesen Sie die ContactPersons aus dem ersten Benutzer für einen beliebigen Kunden mit Nr.  Verwenden Sie die Route /Customers/{customerNumber}/ContactPersons
3. Nun stellen Sie fest, dass die Contactpersonen in beiden Mandanten extsiert . 
4. Nun versuchen Sie eine Kontaktperson zu aktualisieren. 
Die Route für Put  "/Customers/{customerNumber}/ContactPersons/{contactPersonNumber}" verlangt die contactPersonNumber und diese Eigenschaft existiert nicht. Die gelesene Contactperson aus ersten Mandanten hat **KEINE** contactpersonnumber Property. 
Wenn man für diese Property Number verwendet oder Parentnummer, erscheint Ausnahme: "RessourceNotFoundException".  Alle andere Properties kommen auch hier nicht in Frage, da es keine Nummer sind.

**Comment by ThePholph** [comment]
Hallo,

die Eigenschaft "Number" im Result von GET /Customers/{customerNumber}/ContactPersons entspricht dem Parameter "contactPersonNumber" für den Request Put /Customers/{customerNumber}/ContactPersons/{contactPersonNumber}.

Wenn ich es richtig verstanden habe, wird versucht eine Synchronisation mit den Daten aus Mandant1 in Mandant2 durchzuführen. Was Sie hier vorhaben, kann so nicht funktionieren, da die "Number" vom System vergeben wird und trotz Vorhandensein im Mandant1, mit einer Wahrscheinlichkeit von nahe zu 100%, im Mandant2 unter einer anderen "Number" geführt wird. So kann die API die Kontaktperson nicht finden.

Sie müssen die Eiegenschaft "Number" und den Parameter "contactPersonNumber" aus Mandant1 mit den Response-Daten aus Mandant2 ersetzen, dann sollte es funktionieren.

Wenn dies nicht die Lösung ist, würden die Requests sowie Response besser weiterhelfen.

Ich hoffe, ich konnte helfen.

Grüße

Daniel

**Comment by Torchok19081986** [comment]
Hallo, vielen Dank für die Info, Herr @ThePholph . 

Genau das ist das Verhalten, dass ich  im Programm umzusetzen versuche. Leider steht sowas nicht im Beschreibung, dass diese Nummer von den System vergeben wird und somit kommt das Missverständnis. 

Das heißt dann , dass ich von beiden Mandanten die ContactPersons für den selben Nummer lesen muss. 
Ich habe da nur eine Frage. Ich verwende die API Funktionen/Methods für das Lesen/Anlegen/Aktualsieren der Customer bzw. Supplier. Die Funktion
```csharp

customerApi.CustomerUpdateContactPersonAsyncWithHttpInfo

```
kann ich weiterhin verwenen, stimmt das ?

**Comment by ThePholph** [comment]
Hallo,

Sie müssen die Daten aus Mandant1 und Mandant2 laden, validieren und die "Number" aus dem Objekt des Mandant2 mit der "Number" des Objekts aus Mandant1 tauschen und das Objekt aus Mandant1 via API mit der entsprechenden Anmeldung an Mandant2 senden.

Ich nutze die automatisch generierten Klassen nicht, daher kann ich dazu nicht viel sagen, aber sie sollten die Funktion ohne weiteres dafür verwenden können.

Grüße

Daniel

**Comment by Torchok19081986** [comment]
Vielen Dank für die erneute Hilfe, @ThePholph .

**Comment by Torchok19081986** [comment]
Morgen, @ThePholph . Damit funktioniert es ohne Probleme.  Ich habe festgestellt, dass die Kontaktpersonen CRM Daten sind und diese Selectline CRM braucht eine Lizenz. Kann es sein, dass der Anlegen.- bzw.  Aktualisierungsvorgang für Kontaktpersonen eine CRM Lizenz vorausetzt ?
