### ISSUE TITLE
WaWi-Backend startet nicht / Backendmanager startet nicht

### ISSUE THREAD

**Issue by AM-Sartissohn** [selectline-software/selectline-api#279]
Hallo,
wir haben hier diverse Probleme mit dem Backend nach Serverneustarts, zusammenfassend gibt es dabei zwei verschiedene Fehlerbilder:

1. Nach dem Serverneustart sind im Mobile Manager alle Tests erfolgreich, die Dienste und Prozesse laufen alle. Trotzdem ist keine der API-Routen verfügbar. Nach Beenden und erneutem Starten des Backend-Managers ist die API wieder normal verfügbar. Der Fehler ist immerhin leicht zu beheben, tritt aber auf dem betroffenen System nach jedem Serverneustart auf. Das Problem ist hier, dass wir bisher keine Möglichkeit gefunden haben, über ein Monitoring-System o.ä. einen Unterschied zum Normalbetrieb festzustellen. Die einzige Möglichkeit, zu erkennen, ob das System läuft, ist eine Anmeldung an der API.
2. Auf einem anderen System ist die API nach einem Serverneustart nur teilweise verfügbar - einige Routen funktionieren problemfrei, andere schlagen fehl mit der Fehlermeldung "Es konnte keine Verbindung zur Backend-Wawi hergestellt werden.". Allgemein können Daten ohne Fehler ausgelesen werden, aber das Anlegen/Editieren von Datensätzen schlägt fehl. Der Fehler tritt nicht nach jedem Serverneustart auf, aber geschätzt in 80% der Fälle. Bisher scheint nur ein Neueinrichten der Datenbank im Mobile Manager das Problem halbwegs verlässlich zu beheben, aber auch nur bis zum nächsten Serverneustart. Neustarten des Backend-Managers oder anderer Prozesse hilft dagegen nicht. Auch in diesem Fall lässt sich der Fehlerzustand nur durch Verwendung der API-Routen erkennen, alle Dienste und Prozesse laufen oberflächlich normal.

Beide Fehler führen dazu, dass nach jedem Serverneustart manuell Hand angelegt werden muss, da die Fehlerzustände nicht erkennbar sind, bevor die API verwendet wird, und sich die Workarounds auch nicht automatisieren lassen, um die API wieder funktionsfähig zu machen.

Bei einem SelectLine-Server, welcher durch einen dritten IT-Dienstleister betreut wird, muss nach jedem Serverneustart zusätzlich ein Mitarbeiter von uns die SelectLine kontrollieren. Dies ist dem Kunden nur schwer zu vermitteln.
Wird der Server stattdessen jede Nacht heruntergefahren, was bei einem betroffenen System der Fall ist, ist an eine durchgehende Verwendung der API nicht zu denken, da wir nicht jeden Morgen manuell den Server pflegen können.

**Comment by ThePholph** [comment]
Hallo,

ist der SQL-Server auf dem gleichen System installiert? Das Verhalten sieht stark nach falscher Startreihenfolge aus. Wenn die Dienste der API starten und der SQL-Server ist noch nicht vollständig gestartet, kann das zu genannten Problemen führen. Es lohnt sich auf jeden Fall das erstmal zu prüfen, auch wenn der SQL-Server auf dem gleichen System läuft.

Wir konnten dies mit Hilfe der externen Partner meist gut abstimmen, da die meisten Systeme Probleme bekommen, wenn beim Start der SQL-Server nicht erreichbar ist.

Ich hoffe ich konnte helfen.

Vielen Grüße

Daniel

**Comment by AM-Sartissohn** [comment]
Hallo,

SQL-Server und BackendManager sind auf dem gleichen System installiert, ja. 

Wir hatten schon versucht, die Startreihenfolge zu korrigieren, indem wir die Aufgabe "BackendManager öffnen" erst 30 Minuten nach Systemstart ausführen lassen, das hat aber nicht geholfen. Gibt es da noch andere Dienste, die verzögert starten sollten, wen ja, welche?

Vielen Dank

**Comment by ThePholph** [comment]
Hallo,

viel was anderes fällt mir da nicht ein, außer evtl. noch Endpoint-Protection u. Firewall etc. prüfen. 

Sollte hier eine Endpoint-Protection laufen, dann die Empfehlungen von Microsoft für SQL-Server beachten! Das wird auch sehr oft von Infrastruktur-Partnern vernachlässigt, hier gilt sehr oft das Motto, dass Server einen Selbstzweck erfüllen.

Viele Grüße 

Daniel

**Comment by MatthiasGuse** [comment]
Hallo,

> 1. Nach dem Serverneustart sind im Mobile Manager alle Tests erfolgreich, die Dienste und Prozesse laufen alle. Trotzdem ist keine der API-Routen verfügbar. Nach Beenden und erneutem Starten des Backend-Managers ist die API wieder normal verfügbar. 

Dieser Punkt lässt sich so nicht erklären. Der Backendmanager hat nichts mit der generellen Verfügbarkeit der API zu tun. Wie starten Sie den denn neu? Ist denn in dem genannten Zustand die Mobile Webseite verfügbar?

> 2. Auf einem anderen System ist die API nach einem Serverneustart nur teilweise verfügbar - einige Routen funktionieren problemfrei, andere schlagen fehl mit der Fehlermeldung "Es konnte keine Verbindung zur Backend-Wawi hergestellt werden.". Allgemein können Daten ohne Fehler ausgelesen werden, aber das Anlegen/Editieren von Datensätzen schlägt fehl.

Hier ist die Fehlermeldung eindeutig und nachvollziehbar.

Welche Version setzen Sie bei den betroffenen Systemen ein?

Viele Grüße
Matthias

**Comment by Micha-Richter** [comment]
> Dieser Punkt lässt sich so nicht erklären. Der Backendmanager hat nichts mit der generellen Verfügbarkeit der API zu tun. 

🤔 Punkt 1 löse ich aber auch generell über den beschriebenen Weg!? Neustart des Backend-Managers ist ja meine einzige(?) Chance!? 
(abgesehen von Neustart der Website im IIS - der das Problem aber erfahrungsgemäß nicht beseitigt) 

Wobei ich annehme, dass die API an sich schon "verfügbar" ist, aber entweder Timeout oder einen kryptischen Fehler liefert, @AM-Sartissohn ?

**Comment by AM-Sartissohn** [comment]
Hallo,

> > 1. Nach dem Serverneustart sind im Mobile Manager alle Tests erfolgreich, die Dienste und Prozesse laufen alle. Trotzdem ist keine der API-Routen verfügbar. Nach Beenden und erneutem Starten des Backend-Managers ist die API wieder normal verfügbar.
> Dieser Punkt lässt sich so nicht erklären. Der Backendmanager hat nichts mit der generellen Verfügbarkeit der API zu tun. Wie starten Sie den denn neu? Ist denn in dem genannten Zustand die Mobile Webseite verfügbar?

In diesem Fall erhalten wir keinen Timeout oder kryptischen Fehler, sondern ganz einfach einen HTTP-Fehler 404.0 - Not Found
Der Neustart des BackendManagers erfolgt über die Oberfläche des SelectLine Mobile Managers - "Beenden", dann über gleichen Button "Starten". Dies behebt das Problem verlässlich.
![Backendmanager](https://user-images.githubusercontent.com/53219563/203315424-a29ac52f-130c-447d-a23e-76ce1dfe0787.png)
Ob die Mobile Webseite in dieser Situation verfügbar ist, habe ich bisher noch nicht getestet.
Betroffen ist hier die Version 22.1.4

> > 2. Auf einem anderen System ist die API nach einem Serverneustart nur teilweise verfügbar - einige Routen funktionieren problemfrei, andere schlagen fehl mit der Fehlermeldung "Es konnte keine Verbindung zur Backend-Wawi hergestellt werden.". Allgemein können Daten ohne Fehler ausgelesen werden, aber das Anlegen/Editieren von Datensätzen schlägt fehl.

Betroffen ist auch hier die Version 22.1.4

**Comment by ThePholph** [comment]
Hallo,

könnt Ihr die Logs vom Backend sowie vom IIS einstellen?

Danke.

Viele Grüße

Daniel

**Comment by MatthiasGuse** [comment]
Hallo,

mit der Version 22.1 haben wir Änderungen vorgenommen, die sich genau mit den Verhalten beim Neustart befassen. Insbesondere auch mit einer verzögerten Verfügbarkeit des SQL Servers oder des Netzwerkes. Daher ist es verwunderlich, dass Sie das Verhalten mit dieser Version so schildern. 

In Fall 1 wäre es daher wirklich wichtig zu wissen, ob denn der IIS in der Situation überhaupt erreichbar ist. Am einfachsten wahrscheinlich herauszufinden, durch das Aufrufen der SelectLine Mobile Webseite.

Sonst wie Daniel schon schreibt, wären die Logs um den Zeitpunkt des Auftretens hilfreich. Aus Datenschutzgründen gerne auch an unseren Support mit Verweis auf diesen Issue.

Viele Grüße

**Comment by MatthiasGuse** [comment]
Hallo, 

mit der Version 22.1 müssen die Logs im Installationsverezeichnis oder unter `C:\ProgramData` unter `...\SelectLine Software\Mobile Anwendungen\Logs` zu finden sein. 
Hier bitte das ganze Verzeichnis zur Verfügung stellen. Logs vom IIS sind für mich erstmal nicht relevant.

**Comment by AM-Sartissohn** [comment]
Hallo,
Fall 1 ist grade heute nach einem Serverneustart gestern wieder aufgetreten. Ich habe Ihnen die Logs über Servicenummer 120023 per ftp hochgeladen.

**Comment by MatthiasGuse** [comment]
Logs sind angekommen. Wir melden uns, wenn wir diese analysiert haben.

Viele Grüße

**Comment by MatthiasGuse** [comment]
Hallo,
wir haben die Logs ausgewertet und konnten zumindest Punkt 1 bei uns provozieren.

> 1. Nach dem Serverneustart sind im Mobile Manager alle Tests erfolgreich, die Dienste und Prozesse laufen alle. Trotzdem ist keine der API-Routen verfügbar. Nach Beenden und erneutem Starten des Backend-Managers ist die API wieder normal verfügbar.

Das Problem ist, dass der SQL Server beim Starten des IIS noch nicht zur Verfügung steht. Das hat zur Folge, dass die API nicht erreichbar ist und die Webseiten ebenfalls nicht korrekt funktionieren. Dies hat aber nichts mit dem Backendmanager zu tun! Allein das Öffnen des Mobilemanagers führt dazu, dass die Installation wieder korrekt funktioniert. 

Als Workaround ist es denkbar den IIS mit dem Start von Windows verzögert (WWW-Dienst) zu starten oder ihn verzögert nach einem Start per Befehlszeile neuzustarten.

Zur Version 23.1 (Termin noch offen) werden wir dafür eine Lösung bereitstellen.

Sollte Punkt 2 damit weiterhin auftreten, bitte nochmal Bescheid geben. Dann muss der Loglevel erhöht werden um mehr Informationen zu sammeln.

Viele Grüße

**Comment by ThePholph** [comment]
> Hallo, wir haben die Logs ausgewertet und konnten zumindest Punkt 1 bei uns provozieren.
> 
> > 1. Nach dem Serverneustart sind im Mobile Manager alle Tests erfolgreich, die Dienste und Prozesse laufen alle. Trotzdem ist keine der API-Routen verfügbar. Nach Beenden und erneutem Starten des Backend-Managers ist die API wieder normal verfügbar.
> 
> Das Problem ist, dass der SQL Server beim Starten des IIS noch nicht zur Verfügung steht. Das hat zur Folge, dass die API nicht erreichbar ist und die Webseiten ebenfalls nicht korrekt funktionieren. Dies hat aber nichts mit dem Backendmanager zu tun! Allein das Öffnen des Mobilemanagers führt dazu, dass die Installation wieder korrekt funktioniert.
> 
> Als Workaround ist es denkbar den IIS mit dem Start von Windows verzögert (WWW-Dienst) zu starten oder ihn verzögert nach einem Start per Befehlszeile neuzustarten.
> 
> Zur Version 23.1 (Termin noch offen) werden wir dafür eine Lösung bereitstellen.
> 
> Sollte Punkt 2 damit weiterhin auftreten, bitte nochmal Bescheid geben. Dann muss der Loglevel erhöht werden um mehr Informationen zu sammeln.
> 
> Viele Grüße

Hallo,

das Problem tritt inzwischen bei allen unserer API-Kunden auf inkl. unserer eigenen Entwicklungsumgebung. Zudem tritt das Problem auch ohne Neustart auf. Was bei allen aufgetretenen Problemen gemeinsam ist, ist, dass eine gewisse Zeit (< 24 Std.) die API nicht angesprochen wurde. Es betrifft nicht nur reine API-Kunden, sondern auch MDE- sowie BDE-Kunden. Wir bitten daher um schnellst mögliche Lösung.

Vielen Dank.

Viele Grüße

Daniel

Auszug aus Log:

```
{ "Name": "SelectLine.Erp.WebApi.WebHost", "TimeStamp": "2023-01-25T14:57:31.0431715Z", "ServerTimeStamp": "2023-01-25T14:57:31.0431715Z", "Host": {"Name":"EIC-DEV-AP02","Version":"Microsoft Windows NT 10.0.17763.0","UserName":"SelectLine","64Bit":true}, "Process": {"FileName":"c:\\windows\\system32\\inetsrv\\w3wp.exe","Name":"w3wp","64Bit":true,"ProcessId":7232,"ThreadId":80,"Runtime":"0:02:12:08.8078340","PrivateBytes":599207936}, "LogLevel": "Error", "Message": "Processing of the HTTP request resulted in an exception. Please see the HTTP response returned by the 'Response' property of this exception for details.", "Exception": {"Message":"Processing of the HTTP request resulted in an exception. Please see the HTTP response returned by the 'Response' property of this exception for details.","StackTrace":"   bei System.Web.Http.ModelBinding.FormatterParameterBinding.ReadContentAsync(HttpRequestMessage request, Type type, IEnumerable`1 formatters, IFormatterLogger formatterLogger, CancellationToken cancellationToken)\r\n   bei System.Web.Http.ModelBinding.FormatterParameterBinding.ReadContentAsync(HttpRequestMessage request, Type type, IEnumerable`1 formatters, IFormatterLogger formatterLogger)\r\n   bei System.Web.Http.ModelBinding.FormatterParameterBinding.<ExecuteBindingAsyncCore>d__18.MoveNext()\r\n--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---\r\n   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   bei System.Web.Http.Controllers.HttpActionBinding.<ExecuteBindingAsyncCore>d__12.MoveNext()\r\n--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---\r\n   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   bei System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()\r\n--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---\r\n   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   bei System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()\r\n--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---\r\n   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   bei System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__6.MoveNext()"}, "CallerStack": ["SelectLine.Erp.WebApi.Controllers.Attributes.CatchExceptionAttribute.OnException(System.Web.Http.Filters.HttpActionExecutedContext context)","System.Web.Http.Filters.ExceptionFilterAttribute.OnExceptionAsync(System.Web.Http.Filters.HttpActionExecutedContext actionExecutedContext,System.Threading.CancellationToken cancellationToken)","System.Web.Http.Filters.ExceptionFilterAttribute.ExecuteExceptionFilterAsyncCore(System.Web.Http.Filters.HttpActionExecutedContext actionExecutedContext,System.Threading.CancellationToken cancellationToken)"] }
{ "Name": "SelectLine.Erp.WebApi.WebHost", "TimeStamp": "2023-01-25T15:09:37.8096784Z", "ServerTimeStamp": "2023-01-25T15:09:37.8096784Z", "Host": {"Name":"EIC-DEV-AP02","Version":"Microsoft Windows NT 10.0.17763.0","UserName":"SelectLine","64Bit":true}, "Process": {"FileName":"c:\\windows\\system32\\inetsrv\\w3wp.exe","Name":"w3wp","64Bit":true,"ProcessId":7232,"ThreadId":91,"Runtime":"0:02:24:15.5587160","PrivateBytes":599207936}, "LogLevel": "Error", "Message": "Der BackendManager antwortete nicht beim Versuch eine Wawi für Mandant WAWI und Benutzer es zu starten.", "Exception": null, "CallerStack": ["System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()","System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)","System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()"] }
{ "Name": "SelectLine.Erp.WebApi.WebHost", "TimeStamp": "2023-01-26T08:06:58.9295572Z", "ServerTimeStamp": "2023-01-26T08:06:58.9295572Z", "Host": {"Name":"EIC-DEV-AP02","Version":"Microsoft Windows NT 10.0.17763.0","UserName":"SelectLine","64Bit":true}, "Process": {"FileName":"c:\\windows\\system32\\inetsrv\\w3wp.exe","Name":"w3wp","64Bit":true,"ProcessId":7232,"ThreadId":20,"Runtime":"0:19:21:36.6785948","PrivateBytes":599207936}, "LogLevel": "Error", "Message": "Processing of the HTTP request resulted in an exception. Please see the HTTP response returned by the 'Response' property of this exception for details.", "Exception": {"Message":"Processing of the HTTP request resulted in an exception. Please see the HTTP response returned by the 'Response' property of this exception for details.","StackTrace":"   bei System.Web.Http.ModelBinding.FormatterParameterBinding.ReadContentAsync(HttpRequestMessage request, Type type, IEnumerable`1 formatters, IFormatterLogger formatterLogger, CancellationToken cancellationToken)\r\n   bei System.Web.Http.ModelBinding.FormatterParameterBinding.ReadContentAsync(HttpRequestMessage request, Type type, IEnumerable`1 formatters, IFormatterLogger formatterLogger)\r\n   bei System.Web.Http.ModelBinding.FormatterParameterBinding.<ExecuteBindingAsyncCore>d__18.MoveNext()\r\n--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---\r\n   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   bei System.Web.Http.Controllers.HttpActionBinding.<ExecuteBindingAsyncCore>d__12.MoveNext()\r\n--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---\r\n   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   bei System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()\r\n--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---\r\n   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   bei System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()\r\n--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---\r\n   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   bei System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__6.MoveNext()"}, "CallerStack": ["SelectLine.Erp.WebApi.Controllers.Attributes.CatchExceptionAttribute.OnException(System.Web.Http.Filters.HttpActionExecutedContext context)","System.Web.Http.Filters.ExceptionFilterAttribute.OnExceptionAsync(System.Web.Http.Filters.HttpActionExecutedContext actionExecutedContext,System.Threading.CancellationToken cancellationToken)","System.Web.Http.Filters.ExceptionFilterAttribute.ExecuteExceptionFilterAsyncCore(System.Web.Http.Filters.HttpActionExecutedContext actionExecutedContext,System.Threading.CancellationToken cancellationToken)"] }
{ "Name": "SelectLine.Erp.WebApi.WebHost", "TimeStamp": "2023-01-26T08:08:42.7740611Z", "ServerTimeStamp": "2023-01-26T08:08:42.7740611Z", "Host": {"Name":"EIC-DEV-AP02","Version":"Microsoft Windows NT 10.0.17763.0","UserName":"SelectLine","64Bit":true}, "Process": {"FileName":"c:\\windows\\system32\\inetsrv\\w3wp.exe","Name":"w3wp","64Bit":true,"ProcessId":7232,"ThreadId":127,"Runtime":"0:19:23:20.5230987","PrivateBytes":599207936}, "LogLevel": "Error", "Message": "Processing of the HTTP request resulted in an exception. Please see the HTTP response returned by the 'Response' property of this exception for details.", "Exception": {"Message":"Processing of the HTTP request resulted in an exception. Please see the HTTP response returned by the 'Response' property of this exception for details.","StackTrace":"   bei System.Web.Http.ModelBinding.FormatterParameterBinding.ReadContentAsync(HttpRequestMessage request, Type type, IEnumerable`1 formatters, IFormatterLogger formatterLogger, CancellationToken cancellationToken)\r\n   bei System.Web.Http.ModelBinding.FormatterParameterBinding.ReadContentAsync(HttpRequestMessage request, Type type, IEnumerable`1 formatters, IFormatterLogger formatterLogger)\r\n   bei System.Web.Http.ModelBinding.FormatterParameterBinding.<ExecuteBindingAsyncCore>d__18.MoveNext()\r\n--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---\r\n   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   bei System.Web.Http.Controllers.HttpActionBinding.<ExecuteBindingAsyncCore>d__12.MoveNext()\r\n--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---\r\n   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   bei System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()\r\n--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---\r\n   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   bei System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()\r\n--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---\r\n   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   bei System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__6.MoveNext()"}, "CallerStack": ["SelectLine.Erp.WebApi.Controllers.Attributes.CatchExceptionAttribute.OnException(System.Web.Http.Filters.HttpActionExecutedContext context)","System.Web.Http.Filters.ExceptionFilterAttribute.OnExceptionAsync(System.Web.Http.Filters.HttpActionExecutedContext actionExecutedContext,System.Threading.CancellationToken cancellationToken)","System.Web.Http.Filters.ExceptionFilterAttribute.ExecuteExceptionFilterAsyncCore(System.Web.Http.Filters.HttpActionExecutedContext actionExecutedContext,System.Threading.CancellationToken cancellationToken)"] }
{ "Name": "SelectLine.Erp.WebApi.WebHost", "TimeStamp": "2023-01-26T08:09:15.6105884Z", "ServerTimeStamp": "2023-01-26T08:09:15.6105884Z", "Host": {"Name":"EIC-DEV-AP02","Version":"Microsoft Windows NT 10.0.17763.0","UserName":"SelectLine","64Bit":true}, "Process": {"FileName":"c:\\windows\\system32\\inetsrv\\w3wp.exe","Name":"w3wp","64Bit":true,"ProcessId":7232,"ThreadId":121,"Runtime":"0:19:23:53.3596260","PrivateBytes":599207936}, "LogLevel": "Error", "Message": "Der BackendManager antwortete nicht beim Versuch eine Wawi für Mandant WAWI und Benutzer es zu starten.", "Exception": null, "CallerStack": ["System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()","System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)","System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()"] }
{ "Name": "SelectLine.Erp.WebApi.WebHost", "TimeStamp": "2023-01-26T08:13:11.2026089Z", "ServerTimeStamp": "2023-01-26T08:13:11.2026089Z", "Host": {"Name":"EIC-DEV-AP02","Version":"Microsoft Windows NT 10.0.17763.0","UserName":"SelectLine","64Bit":true}, "Process": {"FileName":"c:\\windows\\system32\\inetsrv\\w3wp.exe","Name":"w3wp","64Bit":true,"ProcessId":7232,"ThreadId":123,"Runtime":"0:19:27:48.9516465","PrivateBytes":599207936}, "LogLevel": "Error", "Message": "Der BackendManager antwortete nicht beim Versuch eine Wawi für Mandant DKLDEV und Benutzer es zu starten.", "Exception": null, "CallerStack": ["System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()","System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)","System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()"] }
{ "Name": "SelectLine.Erp.WebApi.WebHost", "TimeStamp": "2023-01-26T08:13:26.2323515Z", "ServerTimeStamp": "2023-01-26T08:13:26.2323515Z", "Host": {"Name":"EIC-DEV-AP02","Version":"Microsoft Windows NT 10.0.17763.0","UserName":"SelectLine","64Bit":true}, "Process": {"FileName":"c:\\windows\\system32\\inetsrv\\w3wp.exe","Name":"w3wp","64Bit":true,"ProcessId":7232,"ThreadId":7,"Runtime":"0:19:28:03.9813891","PrivateBytes":599207936}, "LogLevel": "Error", "Message": "Der BackendManager antwortete nicht beim Versuch eine Wawi für Mandant DKLDEV und Benutzer es zu starten.", "Exception": null, "CallerStack": ["System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()","System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)","System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()"] }

```

**Comment by MatthiasGuse** [comment]
Hallo,

wir werden versuchen das beschriebene Verhalten zu reproduzieren.

Viele Grüße

**Comment by AM-Sartissohn** [comment]
Hallo,

könnten Sie mir bitte noch auf die beiden Fragen antworten?

> Zum Verständnis noch eine Frage: Es wird ja auch eine Aufgabe in der Aufgabenplanung angelegt, um den Backendmanager zu starten. Wir hatten hier auch versucht, diese verzögert zu starten. Habe ich das richtig verstanden, dass der IIS dann verzögert starten sollte, der Backendmanager aber möglichst nicht verzögert werden sollte? Oder muss auch der Start des Backend-Managers auf den SQL Server warten?
> 
> Ein Gedanke noch dazu: Wenn wir für die Dienste die Starteinstellungen anpassen, werden diese Einstellungen durch ein SL Mobile Update wieder überschrieben?

Freundliche Grüße

**Comment by MatthiasGuse** [comment]
Hallo, sorry.

Der Backendmanager wartet alleine. Der kann das schon ;-)  Hier würde die Änderung beim Einrichten durch den Mobilemanager auch wieder überschrieben werden.

Das Starten der Webdienste hat mit dem Mobile Manager nur etwas bei der allerersten Einrichtung zu tun. Daher sollten die Änderungen nicht durch ein Update beeinflusst werden.

Viele Grüße

**Comment by MatthiasGuse** [comment]
@ThePholph 
Wir konnten auch nach mehreren Tagen Inaktivität das Problem nicht nachstellen.

Um hier weiter nach Informationen suchen zu können, benötigen wir Unterstützung mit detaillierteren Logs.
Bitte legen Sie dazu im Installationsverzeichnis unter `...\SelectLine Software\Mobile Anwendungen\LokaleDaten\BackendManager` eine Datei `SelectLine.API.BackendManager.logini` mit folgendem Inhalt an:
```
[*]
Level=Debug
Trace=Off
```
Im Anschluss bitte den Backendmanager neustarten. Nach erneutem Auftreten des Problems bitte den ungefähren Zeitpunkt und das gesamte Verzeichnis "Logs" zur Verfügung stellen (falls gewünscht an den Support senden). Dann bitte die Datei wieder entfernen oder umbenennen und den Backendmanager nochmal neustarten.

Viele Grüße

**Comment by MatthiasGuse** [comment]
Das Startverhalten und die Stabilität der API, insbesondere in Bezug auf die Backendprozesse,
wurden mit der Version 23.1.0 optimiert und Fehler korrigiert. Sollten Sie Probleme mit der Verfügbarkeit des
Backendmanagers haben, empfehlen wir Ihnen nach einem Update auf diese Version die Funktion
„Datenbank einrichten“ im Mobile Manager auf der Seite „Datenbank“ erneut auszuführen.

Beste Grüße
