### ISSUE TITLE
Kopf- / Fusstext im Beleg

### ISSUE THREAD

**Issue by Grebi001** [selectline-software/selectline-api#28]
Hallo Gemeinde,

im Model für DocumentCreat sehe ich keine Möglichkeit, per API einen Kopf- bzw. Fusstext zu schreiben. Oder bin ich blind??

Grüße
Grebi

**Comment by VivienSchuboth** [comment]
Hallo,
derzeit ist es nicht möglich beim Anlegen oder Bearbeiten eines Beleges den Kopf- oder Fußtext anzugeben. Es befindet sich bereits ein Wunsch dazu im UserVoice Forum. Ob und wann diese Funktionalität unserseits eingeplant und umgesetzt wird, können wir nicht sagen.

Viele Grüße
Vivien Schuboth
