### ISSUE TITLE
PUT ​/SerialNumbers​/{serialNumberId} Ändern einer Seriennummer bzw. Charge

### ISSUE THREAD

**Issue by TheBlackPitcher** [selectline-software/selectline-api#280]
Hallo Zusammen,

entgegen der Swagger Beschreibung lässt sich in der Aktuellen 22.2.5 über die im Titel genannte Funktion nur die Bemerkung / Description anpassen.

Die anderen Parameter werden ignoriert.
Wird in der Swagger UI die Bemerkung nicht gefüllt erfolgt überhaupt keine Rückmeldung der API.
Zudem ist der Parameter SerialNumberID 2 mal vorhanden( einmal im Body und einmal in der URL).

**Comment by MatthiasGuse** [comment]
Vielen Dank für Ihren Hinweis. Hier ist ein Fehler im Model. Es ist korrekt, dass nur die Beschreibung geändert werden kann. Ich habe das zur Korrektur aufgenommen.

Viele Grüße

**Comment by MatthiasGuse** [comment]
Der Fehler wurde mit der kürzlich veröffentlichten Version 23.1.0 behoben.

Beste Grüße
