### ISSUE TITLE
Sie müssen sich einloggen, um diese Funktion zu nutzen - 42-002

### ISSUE THREAD

**Issue by Logic-Bits** [selectline-software/selectline-api#281]
Sehr geehrte Damen und Herren,

hier kommt es auch hin und wieder vor dass oben genanter Fehler passiert.
"Lustig" dass hier ja trotzdem der Beleg angelegt wird, was wiedersprüchlich der Fehlermeldung ist.
(CreateDocument)

![grafik](https://user-images.githubusercontent.com/2421123/203326459-5a88af58-fe7d-4be8-a5c5-b3d87d19b926.png)

![grafik](https://user-images.githubusercontent.com/2421123/203326619-03778ece-0770-461e-87b8-16e04c99090c.png)

Gibts es ähnliche Fälle oder eine Lösung?

Danke

v. 21.3.6

**Comment by ThePholph** [comment]
Hallo,

wie sieht der Request zur Response aus?

Viele Grüße

Daniel

**Comment by MatthiasGuse** [comment]
Hallo,

ist das reproduzierbar? Wenn ja, auch mit einer aktuellen 22.2?

Viele Grüße

**Comment by Logic-Bits** [comment]
Hallo, über CreateDocument (https://demo.slmobile.de/demoApi/swagger/ui/index#/Document/Document_CreateDocument).
wie schon erwähnt passiert es hin und wieder, somit nicht wirklich reproduzierbar. 
Es sollte jetzt 22.3 installiert sein, es ist aber bereits wieder aufgetreten.

**Comment by Logic-Bits** [comment]
Bei einem anderen Kunden (22.2.5) wird auch der Beleg angelegt, aber die API wirft einen Fehler zurück und somit werden keine Positionen mehr angelegt.
Der Fehler ist jetzt erst passiert.

**Comment by Logic-Bits** [comment]
![grafik](https://user-images.githubusercontent.com/2421123/211288218-fd741c24-fc36-491e-813c-a6fa2837256e.png)

Ich werde jetzt versuchen den Backendmanager alle 24h Neu zu starten und zu sehen ob damit das Problem "gelöst" ist (bis eine Lösung von der SelectLine kommt)

**Comment by MatthiasGuse** [comment]
Das Startverhalten und die Stabilität der API, insbesondere in Bezug auf die Backendprozesse,
wurden mit der Version 23.1.0 optimiert und Fehler korrigiert. Sollten Sie Probleme mit der Verfügbarkeit des
Backendmanagers haben, empfehlen wir Ihnen nach einem Update auf diese Version die Funktion
„Datenbank einrichten“ im Mobile Manager auf der Seite „Datenbank“ erneut auszuführen.

Viele Grüße
