### ISSUE TITLE
Zugriffsverletzung bei Macro Ausführung / MacroExecuteWawiMacroPerPipe

### ISSUE THREAD

**Issue by ascharfen** [selectline-software/selectline-api#283]
### Details
- Current version number:
22.1.6 Build 626574

- Previous version number (optional): 

- [ ] Test status checked in Mobile Manager
11:15:31 Datenbankverbindungstest gestartet.
11:15:31 SLDaten-Test ist gestartet.
11:15:31 BackendExe-Test ist gestartet.
11:15:31 Datenbankverbindung war erfolgreich.
11:15:31 Datenbankverbindungstest beendet.
11:15:31 SLDaten-Test ist beendet.
11:15:31 BackendExe-Test ist beendet.
11:15:31 [Backendmanager] Erfolgreichen Start des Backendmanagers überprüfen
11:15:31 [Backendmanager] Abfrage wurde beendet.
11:15:31 [Fehler] Beim Schließen der Backends ist ein Ausnahmefehler aufgetreten: Client.Send failed. See InnerException

- Function or route (request):  
MacroExecuteWawiMacroPerPipe

- Error (response):
{
  "StatusCode": "InternalServerError",
  "ResponseCode": "70-000",
  "ResponseId": 0,
  "ResponseIdDescription": "Undefined",
  "Message": "Zugriffsverletzung bei Adresse 01E0B429 in Modul 'SelectLine.API.Backend.exe'. Lesen von Adresse 00000310",
  "Details": {
    "ExceptionName": "EAccessViolation"
  }

**Comment by MatthiasGuse** [comment]
Hallo,

lässt sich der Fehler reproduzieren? 
Können Sie mir die Logs aus dem Verzeichnis der mobilen Anwendnungen an support@slectline.de zukommen lassen?

Viele Grüße

**Comment by ascharfen** [comment]
Hallo,

der Fehler besteht immer bei der Ausführung der Macros, wenn das Macro manuell in SelectLine gestartet wird läuft es problemlos durch. Fehler besteht seit dem Wechsel von Version 20.3 auf 21.3, vorher lief es ohne Probleme. In der Dokumentation haben wir keine Angaben zu wichtigen Änderungen in diesem Bereich gefunden. Logs sende ich Ihnen per Mail.

Grüße!

**Comment by MatthiasGuse** [comment]
Hallo,

danke für Ihre Informationen und die Logs. In den Logs kann die oben genannte Meldung nur in Einträgen aus dem September gefunden werden. In Logfiles aus dem November ist so ein Eintrag nicht vorhanden.

- Sie schreiben, dass das Makro seit dem Update auf die Version 21.3 nicht mehr ausgeführt werden kann. Mittlerweile haben Sie aber bereits die Version 22.1 installiert?
- Hat das Beenden und Neustarten des Backendmanagers dazu geführt, dass die Tests im Mobilemanager erfolgreich durchgeführt werden können?
- Kann das Makro über Swagger oder Postman ausgeführt werden?

Viele Grüße

**Comment by ascharfen** [comment]
Moin,

- Die Version 22.1 ist beim Kunden im EInsatz
- Trotz Neustart des Backendmanagers die Fehlermeldung: 
11:15:31 [Fehler] Beim Schließen der Backends ist ein Ausnahmefehler aufgetreten: Client.Send failed. See InnerException
- Makro über Swagger werden wir gleich testen.

Grüße!

**Comment by ascharfen** [comment]
Test mit Swagger, gleiches Fehlerbild:

![image](https://user-images.githubusercontent.com/75473062/205632470-3cbf0b45-5a99-4bb4-9780-32bcfe71d4bd.png)

**Comment by SophiaWeise** [comment]
Hallo,
 
aus Ihrem Bild entnehme ich, dass Sie eine Makro-Folge ausführen wollen.
Ich habe den Sachverhalt gerade sowohl mit dem Ausführen eines einfachen Makros über die API, als auch mit dem Ausführen einer Makro-Folge über die API getestet und kann die Zugriffsverletzung bei Letzterem nachstellen.

Können Sie uns bitte noch Ihre konkrete Konstellation schildern, so wie sie in der 20.3 noch funktionierte. Ich meine im speziellen den Aufbau der Makros Ihrer Makro-Folge und gerne auch den Aufbau des entsprechenden API-Requests.

Viele Grüße aus Magdeburg!

**Comment by ascharfen** [comment]
Moin, wir haben soweit ich es beurteilen kann, an der Folge und am API-Request nichts verändert. Es scheitert ja bereits am Aufruf der Folge. Grüße nach Magdeburg!

**Comment by MatthiasGuse** [comment]
Hallo,

sind denn die Test im Mobilemenager mittlerweile alle grün / erfolgreich?

Viele Grüße

**Comment by ascharfen** [comment]
Hi, die waren nie anders. Immer Grün und Erfolgreich. Bis auf die Fehlermeldung: "[Fehler] Beim Schließen der Backends ist ein Ausnahmefehler aufgetreten: Client.Send failed. See InnerException". Abgesehen davon konntet Ihr den Fehler nun doch nachstellen, oder?

**Comment by MatthiasGuse** [comment]
Das haben Sie so deutlich nie geschrieben. Es ist nicht ganz auszuschließen, dass der "[Fehler] Beim Schließen der Backends ist ein Ausnahmefehler aufgetreten: Client.Send failed. See InnerException" Ihnen doch in irgendeiner Art und Weise Probleme bereitet. Daher würde ich es empfehlen das Problem zu beseitigen, bspw. durch die Funktion "Datenbank einrichten" im Mobile Manager. Evtl. löst sich das damit.

Die API Dokumentation beschreibt das Ausführen von Makros, nicht das Ausführen von Makrofolgen. Wir konnten nachstellen, dass Makrofolgen nicht funktionieren. Nach unseren Erkenntnissen haben diese aber auch in der von Ihnen genannten Version 20.3 ebenfalls nicht funktioniert. Daher die Bitte nach der Bereitstellung weiterer Informationen:

> Können Sie uns bitte noch Ihre konkrete Konstellation schildern, so wie sie in der 20.3 noch funktionierte. Ich meine im speziellen den Aufbau der Makros Ihrer Makro-Folge und gerne auch den Aufbau des entsprechenden API-Requests.

Funktioniert denn das Ausführen von Makros (normales Makro - keine Folge)?

Viele Grüße

**Comment by ascharfen** [comment]
Hallo Herr Guse,

es tut mir leid das ich es nicht so deutlich beschrieben hatte. Ich dachte der Verlauf reicht aus und da alles andere soweit unproblematisch läuft und alle Systeme "grün" sind, hatte ich mir dazu auch keine weiteren Gedanken gemacht. Mich wundert auch, dass dies Relevant ist da Frau Weise den Fehler beim ausführen eine Folge nachstellen konnte.

Ich werde versuchen den Ursprung auf der Version 20.3 wieder herzustellen. Haben Sie es denn schon auf dieser Version prüfen können?

Eine Makrofolge ist doch eigentlich nichts anderes wie ein Makro, zumindest wird dies so in der SelectLine im Makroassistenten beschrieben. Von daher gehe ich davon aus, das auch die API eigentlich hier keine Unterscheidung machen dürfte. Das Makro sende ich Ihnen gleich einmal zu, das manuelle starten des Makros läuft in der SelectLine einwandfrei!

Das Ausführen von einzelnen Makros werde ich später prüfen, hilft mir allerdings nicht weiter, da ich ansonsten die Makros selbst  über die API in Folge im Prozess ansteuern müsste aber keine Rückmeldung zum erfolgreichen Prozessende erhalten kann.

**Comment by MatthiasGuse** [comment]
Makrofolgen und Importmuster sind angekommen. Wir gucken uns das nun an. 

Wie schon geschrieben, konnten wir mit unseren Tests bisher bereits feststellen, dass Makrofolgen mit der Version 20.3 nicht funktionierten. Hier kam nur keine Fehlermeldung. Wir gucken uns das jetzt mit Importmustern noch einmal an. Evtl. hat sich das ja anders verhalten. (Grundsätzlich ist das Ausführen von Makrofolgen per API bisher nicht vorgesehen.)

Viele Grüße

**Comment by ascharfen** [comment]
Hallo Herr Guse,

ich kann nicht ganz nachvollziehen, warum dieses Ticket geschlossen wurde. Wir haben hier einiges an Zeit und Aufwand in Entwicklungsarbeit gesteckt, welche auf diese Funktion gesetzt hat. Haben dazu auch einen Workshop gemeinsam mit SelectLine durchgeführt und jetzt wird diese Ticket ohne jeglichen Lösungsansatz geschlossen. Warum? Ich stehe hier jetzt etwas im Regen. Gruß, Arno Scharfen.
