### ISSUE TITLE
Belegübergabe funktioniert nicht

### ISSUE THREAD

**Issue by Logic-Bits** [selectline-software/selectline-api#284]
### Details
- Current version number: 22.2.5
- Previous version number (optional): 
- [X] Test status checked in Mobile Manager
- Function or route (request):  https://localhost/slmobileApi/Documents/L400545783/Successors
- Error (response):

#### Steps to replicate the behavior:

Hallo,

die Übergabe (leere Positions oder gefüllt) funktioniert leider nicht, es gibt keine Fehlermeldung.
Dokumente können angelegt werden.
Haben Sie eine Idee?

![TeamViewer_pcgW3mI5vr](https://user-images.githubusercontent.com/2421123/204820954-9aeda254-9e3a-4049-9465-8a00fe2a132b.png)

![TeamViewer_YOiU2FKkN5](https://user-images.githubusercontent.com/2421123/204820943-73aa9899-af12-4f69-8250-34daa59ff67d.png)

**Comment by MatthiasGuse** [comment]
Falls das Thema noch aktuell ist, bitte wieder öffnen.

Viele Grüße
