### ISSUE TITLE
Frage: Lesen von dem Mandantenname

### ISSUE THREAD

**Issue by Torchok19081986** [selectline-software/selectline-api#285]
Hallo, ich würde gern die Mandantenname lesen,  in welchen API Benutzer gerade eingeloggt ist. Gibt es solche Möglichkeit ? 
Die Idee ist, dem Benutzer die Name von dem Mandanten anzeigen. 
Ich benutze Version 22.2.5 WaWi und Mobile Manager 22.2.5

**Comment by MaikGoertz** [comment]
Hallo.
Die Eigenschaft "TenantDatabaseName" von dieser Route enthält die benötigte Informationen:
[GET Users/Current](https://demo.slmobile.de/demoApi/Help/Api/GET-Users-Current)
