### ISSUE TITLE
SL.Mobile 22.3 - ListFilter.Filter funktioniert nicht mehr bei Datumsfelder

### ISSUE THREAD

**Issue by MarkusKolhoff** [selectline-software/selectline-api#286]
### Details
- Current version number: 22.3.0
- Previous version number (optional): 22.2.5
- [X] Test status checked in Mobile Manager
- Function or route (request): in allen z.B.       
  /ProductionOrders/{productionOrderIdentifier}/ProductionSteps/{productionStepIdentifier}/WorkingHours?listFilter.filter=EndTime Is Null  
- Error (response): 
{
  "StatusCode": "InternalServerError",
  "ResponseCode": "72-000",
  "ResponseId": 0,
  "ResponseIdDescription": "Undefined",
  "Message": "Die Zeichenfolge wurde nicht als gültiges DateTime erkannt.",
  "Details": null
}

#### Steps to replicate the behavior:
![Bildschirmfoto 2022-12-01 um 16 42 45](https://user-images.githubusercontent.com/42321501/205275873-54fc5100-42e1-46cd-8352-916777a7a1db.png)

**Comment by MatthiasGuse** [comment]
Hallo,

beim Filter auf IS NULL gibt es bereits einen erfassten Fehler. Siehe #269 

Viele Grüße
