### ISSUE TITLE
BelegUebernahme - /Documents/{destinationDocumentKey}/Predecessors/{sourceDocumentKey} - Gliederungssummen

### ISSUE THREAD

**Issue by motionnow** [selectline-software/selectline-api#288]
### Details
- Current version number: 22.3
- [X] Test status checked in Mobile Manager
- Function or route (request): BelegUebernahme - /Documents/{destinationDocumentKey}/Predecessors/{sourceDocumentKey}

#### Steps to replicate the behavior:
Einen Beleg mit Gliederungssummen erstellen,
diesen dann Teilweise in übergeben oder in 2 verschiedenen Belegen Teilweise übergeben.

Die API erstellt hier dann die entsprechenden Belegen mit allen vorher vorhandenen Gliederungssummen.
Das bedeutet, das die Gliederungssummen zu denen ich keine Positionen übernehme ohne Unterposition leer angezeigt werden.
Hier übergibt die API wohl alle Gliederungssummen, egal ob Positionen aus diesen übernommen wurden.

**Comment by SophiaWeise** [comment]
Hallo,

ich habe mir den von Ihnen beschriebenen Sachverhalt angesehen und nachvollzogen.
Wann er zur Prüfung und ggf. Korrektur in der Entwicklung eingetaktet wird, kann ich noch nicht sagen, aber ich melde mich sobald es etwas Neues gibt.

Viele Grüße aus Magdeburg,
Sophia Weise

**Comment by SophiaWeise** [comment]
Hallo,

Im Zuge der Entwicklungen für die nächste Vollversion (23.1) lässt sich das Verhalten in unseren Entwicklungsumgebungen nicht mehr nachstellen, wenn die Option "Teil- und Zwischensummen übernehmen" im Dialog "Übernahmeoptionen" nicht gesetzt ist. Der Sachverhalt wird mit der Auslieferung von oben genannter Version also behoben sein.

Viele Grüße aus Magdeburg,
Sophia Weise

**Comment by MatthiasGuse** [comment]
Falls das Thema noch aktuell ist, bitte wieder öffnen.

Viele Grüße
