### ISSUE TITLE
Hersteller Artikelnummer in Positionen

### ISSUE THREAD

**Issue by Logic-Bits** [selectline-software/selectline-api#291]
### Details
- Current version number: live
- Previous version number (optional): 
- [ ] Test status checked in Mobile Manager
- Function or route (request): https://demo.slmobile.de/demoApi/swagger/ui/index#/Document/Document_CreateDocumentPositionWithArticleItemByDocumentKey
- Error (response):

Sehr geehrte Damen und Herren,

wann / wie kann man die Hersteller Artikelnummer via API in BelegP angeben?
https://demo.slmobile.de/demoApi/swagger/ui/index#/Document/Document_CreateDocumentPositionWithArticleItemByDocumentKey
in der Doku findet man nichts.

Vielen Dank

**Comment by MatthiasGuse** [comment]
Hallo,
das ist auf direktem Weg nicht möglich. Sie müssen zuerst die korrekte Artikelnummer ermitteln. Dazu können Sie bspw. über die Route `GET/Articles` auf das Feld `ManufacturerArticleNumber` filtern und sich alle zutreffenden Artikel anzeigen lassen. die Belegposition muss mit einer im Artikelstamm vorhandenen Artikelnummer angelegt werden.

Viele Grüße
