### ISSUE TITLE
Fehler Mehrdeutiger Spaltenname "Bestand"

### ISSUE THREAD

**Issue by itsieber** [selectline-software/selectline-api#292]
### Details
- Current version number: 22.1.5 Build 606882
- Function or route (request):  https://XXXXXXXX/slmobileApi/Articles?Items=50&Page=0Items=50&Page=0&OnlyStockedArticles=true
- Error (response): InternalServerError Mehrdeutiger Spaltenname \"Bestand\".

#### Steps to replicate the behavior:
 https://XXXXXXXX/slmobileApi/Articles?Items=50&Page=0Items=50&Page=0&OnlyStockedArticles=true

**Comment by MaikGoertz** [comment]
Hallo.
Der Fehler wurde korrigiert mit Version 22.3, siehe dazu auch #192.
