### ISSUE TITLE
Belege ohne Fibu Export filtern, ist nicht möglich 

### ISSUE THREAD

**Issue by s52512** [selectline-software/selectline-api#293]
Hallo, ich versuche nur die Rechnungen abzurufen, welche noch nicht in die Fibu exportiert wurden.
Das zu verwendende Filterkriterium hierfür scheint, meines Erachtens nach, das Datumsfeld 'Payment.FinancialAccountExportDate' zu sein, was nur gesetzt ist wenn ein Export erfolgte.
Es gelingt mir jedoch nicht einen geeigneten Filter zu formulieren der das gewünschte Ergebnis liefert.
Frage wäre hier wie filtert man ein Datum auf 'leer', bzw. in diesem Sonderfall steht ja  "0001-01-01T00:00:00+01:00" im Datenmodell wenn kein Export erfolgt ist, wie ist damit ggf. anders umzugehen?

habe folgende Varianten probiert:

- documentListFilter.filter=Payment.FinancialAccountExportDate EQ ''                               --> leere Ergebnismenge []
- documentListFilter.filter=Payment.FinancialAccountExportDate ISNULL                           --> ISNULL not allowed.

### Details
- Current version number: 22.3.0 Build 731289

#### Steps to replicate the behavior:
https://demo.slmobile.de/demoApi/Documents?documentListFilter.filter=Payment.FinancialAccountExportDate%20EQ%20''
https://demo.slmobile.de/demoApi/Documents?documentListFilter.filter=Payment.FinancialAccountExportDate%20IS%20NULL

Vielen Dank schon mal

**Comment by MatthiasGuse** [comment]
Hallo,

beim Filter auf IS NULL gibt es bereits einen erfassten Fehler. Siehe #269 

Viele Grüße
