### ISSUE TITLE
Auftragsanlage per API erzeugt keine Werkaufträge

### ISSUE THREAD

**Issue by AndreasKulueke** [selectline-software/selectline-api#297]
### Details
- Current version number: 22.3.1
- Previous version number (optional): --
- [x] Test status checked in Mobile Manager
- Function or route (request): POST /Documents/{documentKey}/ArticleItem
- Error (response): none

#### Steps to replicate the behavior:
Bei Anlage einer Auftragsposition durch die API wird trotz eingestellter Mandanteneinstellung „Werkaufträge beim Speichern von Auftragspositionen anlegen“ und Dispositionsart „Auftrag“ im Artikel die automatische Erzeugung eines Werkauftrages nicht durchgeführt!

**Comment by MatthiasGuse** [comment]
Hallo!

Ja, das ist korrekt so. Die API generiert keine Belege in Abhängigkeit der Dispositionsart.
Es ist auch nicht absehbar, dass das auf diesem Wege mal zur Verfügung gestellt wird. In der Wawi gibt es ja gewisse Interaktionen, die passieren, wenn man so einen Beleg anlegt oder anpasst. Das lässt sich so in der API nicht abbilden. Daher bleibt nur der Weg die Belege manuell anzulegen. Der Werkauftrag ist in der API allerdings nicht verfügbar (wird es auch nicht werden).

Viele Grüße
