### ISSUE TITLE
Artikeldaten schreiben

### ISSUE THREAD

**Issue by mfahs** [selectline-software/selectline-api#298]
Hallo! 
Ich bin mit meiner Frage vom Support hierhin verwiesen worden - sorry, wenn das doch völlig falsch sein sollte. 
Ich wüsste aber gerne, ob (und wenn ja "wann ungefähr") irgendwann die Möglichkeit geschaffen wird, über die API Artikeldaten _schreiben_ zu können (neu anlegen bzw. aktualisieren). Bisher habe ich dazu nirgendwo etwas finden können.
Gibt es dazu etwas auf der Roadmap bei der Weiterentwicklung der API?

Grüße aus Hamburg
Martin Fahs

**Comment by MatthiasGuse** [comment]
Hallo Herr Fahs,

Sie sind hier schon richtig ;-) 
Aktuell kann ich Ihnen zur Artikelanlage leider keine Auskunft geben. Aktuell ist das noch nicht eingeplant.

Viele Grüße

**Comment by MatthiasGuse** [comment]
Hierzu existiert ebenfalls ein Wunsch im SelectLine Uservoice. Hr. Fahs hat seine Stimmen hierzu bereits abgegeben.
