### ISSUE TITLE
Belegdruck setzt kein "gedruckt"-Flag

### ISSUE THREAD

**Issue by AM-Sartissohn** [selectline-software/selectline-api#299]
### Details
- Current version number:  22.3.1
- [ ja] Test status checked in Mobile Manager
- Function or route (request): POST .../Documents/{documentKey}/Print

#### Steps to replicate the behavior:

Wenn im SelectLine Client ein Beleg (ohne Bearbeitungsstatus) direkt mit dem Druckziel "Archiv" (in diesem Fall docuvita) gedruckt wird, erhält der Beleg ganz normal ein "gedruckt"-Flag und entsprechend auch einen Eintrag im Druckprotokoll. Wird der Archivdruck stattdessen über die API ausgelöst mit "PrintTarget":"5" oder "PrintTarget":"Archive", gibt es keinen Druckprotokoll-Eintrag und auch kein "gedruckt"-Flag.

Das Flag kann jetzt natürlich nachträglich über ein API-Makro gesetzt werden, schöner wäre es aber, wenn das Verhalten zwischen Client und API konsistent wäre.

**Comment by MatthiasGuse** [comment]
Hallo,

wir werden das überprüfen und uns dann dazu melden.

Viele Grüße

**Comment by SophiaWeise** [comment]
Hallo,

wir konnten den von Ihnen beschriebenen Sachverhalt nachvollziehen.
Die Fehlerbehebung steht Ihnen mit der kommenden Version 22.3.3 zur Verfügung.

Beste Grüße

**Comment by MatthiasGuse** [comment]
Die Version 22.3.3 steht zum Download zur Vefügung.
