### ISSUE TITLE
Cannot post document

### ISSUE THREAD

**Issue by m4rkyx** [selectline-software/selectline-api#3]
Hello guys,

I try to post documents for a while but still receive this error from the API demo.

`{
  "StatusCode": "Conflict",
  "ResponseCode": "42-024",
  "Message": "Es ist ein Konflikt beim Schreiben der Resource aufgetreten.",
  "Details": "DocumentKind  is not supported."
}`

I tried to post empty document and full setted document but this error is still showing.

Url for the post : https://demo.slmobile.de/demoapi/Documents
Application : PostMan

Can you explain me what I'm doing wrong please ? 
Thanks !

Michael

**Comment by SteveSteglitz** [comment]
Hello Michael,

i think you used the wrong KindFlag for the document.

If you like to create a document, please use the follow body of the post.
{
  "KindFlag": "F"
}

The KindFlag ist necessary to create a document. You see all possible values for the KindFlag in swagger. 

![image](https://user-images.githubusercontent.com/34538102/72796336-76164a80-3c3f-11ea-9561-aa48bcf52424.png)

Best regards
Steve

**Comment by m4rkyx** [comment]
Hello Steve,

I've already tried every "KindFlag" on the list and each attempt returned the same error.

After several tries, I noticed that there was a Content-Type problem in the header.
By correcting this, the POST request works correctly.

Thank you for taking the time to answer me.

Regards,

Michael

**Comment by SteveSteglitz** [comment]
Hello Michael,

the Content-Type must be "application/json". 

Nice that the problem is solved for you.

Best regards
Steve
