### ISSUE TITLE
Journal Einträge

### ISSUE THREAD

**Issue by Lars-Mue** [selectline-software/selectline-api#30]
Hallo,
aktuell ist über die API nur Möglich, Journaleinträge für Belege zu tätigen.
Gibt es aktuell schon einen Zeitraum, wann es möglich sein wird diese auch für Kunden/Lieferanten zu erstellen.

Viele Grüße

Lars Münzer

**Comment by VivienSchuboth** [comment]
Guten Morgen,

diese Thematik haben wir im Blick.
Aktuell können wir aber noch nicht sagen, wann und wie dieser Wunsch geplant und umgesetzt wird.

Falls Sie sich die Unterstützung der Journaleinträge in Kunden/Lieferanten wünschen, stimmen Sie für diesen Wunsch im Wünscheforum ab. https://selectline.uservoice.com

Viele Grüße,
Vivien Schuboth
