### ISSUE TITLE
POST /Documents/.../Print mit PrintTarget Email: "Fehler beim Drucken: Ungültige Zeigeroperation"

### ISSUE THREAD

**Issue by Micha-Richter** [selectline-software/selectline-api#300]
### Details
- Current version number: 22.3.0
- Previous version number (optional): 21.3.6
- [x] Test status checked in Mobile Manager
- Function or route (request): 
```
curl -X POST "https://.../slmobileApi/Documents/015028816/Print" -H  "accept: application/json" -H  "Authorization: LoginId ..." -H  "Content-Type: application/json" -d "{  \"NumberOfCopies\": 1,  \"MasterName\": \"MAIL\",  \"PrintTarget\": \"Email\“}“
```
- Error (response):
```
{
 "StatusCode": "InternalServerError",
 "ResponseCode": "42-000",
 "ResponseId": 0,
 "ResponseIdDescription": "Undefined",
 "Message": "Fehler beim Drucken: Ungültige Zeigeroperation",
 "Details": {
   "Details": "Fehlercode: 15",
   "Titel": "",
   "Fehler": "Fehler beim Drucken: Ungültige Zeigeroperation",
   "FehlerCode": "15",
   "ExceptionName": "EBelegDruckMitVorlageException"
 }
}
```

- Weitere Informationen:
Beim Aufruf derselben Druckvorlage direkt in der Wawi wird problemlos gedruckt bzw. die E-Mail versandt.

  Ich habe die Druckvorlage immer weiter abgespeckt bis zu einer völlig leeren Vorlage - der Fehler tritt beim Drucken über die API trotzdem auf (Backend-Manager wurde nach Änderung der Druckvorlage neu gestartet).
  Dann habe ich das Druckziel auf Clipboard geändert:
  ```
  curl -X POST "https://.../slmobileApi/Documents/015028816/Print" -H  "accept: application/json" -H  "Authorization: LoginId ..." -H  "Content-Type: application/json" -d "{  \"NumberOfCopies\": 1,  \"MasterName\": \"MAIL\",  \"PrintTarget\": \"Clipboard\"}"
  ```
  und das POST war erfolgreich...

  Kann es sein, dass es ein GENERELLES Problem mit dem Druckziel "Email" gibt!?!?

**Comment by motionnow** [comment]
Hallo Michael,

ich habe bei mir das selbe verhalten nicht getestet, aber bei deinem ersten Aufruf hast du andere Quotes benutzt ganz am ende.  \"Email\“}“<<-hier

**Comment by Micha-Richter** [comment]
Das war aber ganz genau hingesehen.. 😅👍

Die Beispiele sind aus dem Swagger-UI kopiert und eingefügt, da hat mein OS wohl die Anführungszeichen beim Einfügen angepasst. Bei der Ausführung in Swagger selbst spielen die keine Rolle.

**Comment by MatthiasGuse** [comment]
Hallo,

wir haben das Verhalten nachvollzogen und werden die Korrektur in den nächsten Hotfix 22.3.3 aufnehmen.

Viele Grüße

**Comment by MatthiasGuse** [comment]
Die Version 22.3.3 steht zum Download zur Verfügung.
