### ISSUE TITLE
Manuelle Lagerung mit mehr als 2 Nachkommastellen

### ISSUE THREAD

**Issue by Grewamor** [selectline-software/selectline-api#301]
Hallo,

eine Kunde hat uns auf der Problem aufmerksam gemacht, dass keine manuelle Lagerung mit mehr als 2 Nochkommastellen möglich ist.
Können Sie uns bitte helfen?

CURL
```
curl -X POST "https://sql03/slmobileApi/ManualStorages/22000028/Positions/Store" -H  "accept: application/json" -H  "Authorization: LoginId 5c841657-ecad-4674-b26d-0ea7b1203cf4" -H  "Content-Type: application/json" -d "[  {    \"ArticleNumber\": \"100019\",    \"Quantity\": 1.001,    \"Warehouse\": \"WEL\",    \"TargetWarehouse\": \"PROD\"  }]"
```

RESPONSE
```
{
  "StatusCode": "BadRequest",
  "ResponseCode": "33-032",
  "ResponseId": 32,
  "ResponseIdDescription": "StoreErrorException",
  "Message": "StoreError",
  "Details": [
    {
      "Key": "22000028",
      "ErrorCode": 102065,
      "Detail": "Fehler beim Lagern. Offene Menge: 0,00"
    }
  ]
}
```

Viele Grüße
Morris

**Comment by MatthiasGuse** [comment]
Hallo,

wir werden das überprüfen und uns dann dazu melden.

Viele Grüße

**Comment by MatthiasGuse** [comment]
Hallo,

sind denn die Einstellungen im Mandanten auf die gewünschte Anzahl an Nachkommastellen eingestellt?
![grafik](https://user-images.githubusercontent.com/31447000/219310372-61443ee1-86af-42d1-9795-121a14227548.png)
![grafik](https://user-images.githubusercontent.com/31447000/219310388-ecf78a6e-640a-42a0-ba65-487bf4e85a8a.png)

Nach einer Änderung an diesen Einstellungen bitte an der API vollständig abmelden und erneut anmelden.

Viele Grüße

**Comment by Grewamor** [comment]
Hallo Herr Guse,

danke, dies hat geholfen. Bitte entschuldigen Sie den Aufwand für die Prüfung.

VG M.Prinz
