### ISSUE TITLE
Backendmanager richtet sich nicht ein

### ISSUE THREAD

**Issue by Logic-Bits** [selectline-software/selectline-api#303]
### Details
- Current version number: 22.3.1
- Previous version number (optional): 
- [ ] Test status checked in Mobile Manager
- Function or route (request): 
- Error (response):

#### Steps to replicate the behavior:
![grafik](https://user-images.githubusercontent.com/2421123/211844506-986707a6-6ecd-4f96-b2d2-d31d0d6561c0.png)

"set up Database" sollte doch im Task Scheduler den Backendmanager einrichten oder?
Dass passiert hier aber leider nicht. Woran kann das liegen? Passwort wird richtig eingegeben, ohne Fehlermeldung.

(ich kann den Backendmanager manuel via doppelklick ausführen, dann funktioniert die API)

**Comment by MatthiasGuse** [comment]
Hallo,

was für ein Betriebssystem ist das? Welche Sprache verwenden Sie hier?

Hat der angemeldete Benutzer ausreichende Berechtigungen um eine Aufgabe anzulegen, die unabhängig von der Benutzeranmeldung ausgeführt werden darf?

Viele Grüße

**Comment by Logic-Bits** [comment]
Hallo,

Windows 11 Pro, Englisch. Ja, der einzige User / Admin hat das. Manuell kann ichs mit dem gleichen User machen.

Danke

**Comment by MatthiasGuse** [comment]
Hallo,

ich habe mir das Betriebssystem mal installiert und konnte die Einrichtugn damit erfolgreich durchführen. Vermutlich ein Berechtigungsproblem auf dem lokaeln System. Evtl. den Mobile Manager nochmal explizit als Administrator ausführen oder als Workaround die Aufgabe manuell anlegen bzw. von einem anderen System importieren.

Viele Grüße

**Comment by MatthiasGuse** [comment]
Dieses Verhalten tritt vermutlich dann auf, wenn der User unter dem die Installation und Einrichtung erfolgt, nicht ausreichende Berechtigungen auf dem System besitzt. Auch wenn dies der lokale Admin sein sollte, der mit der EInrichtung des Betriebssystems entstanden ist, ist das nicht zu 100% sichergestellt.

Um hier sicher zu sein:
- Mobile Manager deinstallieren
- Neuen Admin User anlegen
- Mobile Manager unter neuem Admin-User installieren und einrichten

Im obeb geschilderten Fall brachte dies Abhilfe.

Viele Grüße
