### ISSUE TITLE
Syntaxfehler bei Übergabe von String in Parameter Value für Wawi-Makro / ExecuteWawiMacroPerPipe

### ISSUE THREAD

**Issue by LandoWalter** [selectline-software/selectline-api#304]
### Details
- sl.mobile-Version: 22.1.5 Build 606882
- Function or route (request): 
Route: `/slmobileApi/Macros`
Body:
```
{ 
  "MacroName": "SQLlw015",
   "Parameters": [
        {
            "Name": "test",
            "Value": "Hallo Hier ist ein Langtext. Dieser Text ist sehr lang und besteht aus zwei Sätzen, getrennt durch Punkte."
        }
    ]
}
```
- Error (response):
```
{
    "StatusCode": "InternalServerError",
    "ResponseCode": "70-000",
    "ResponseId": 0,
    "ResponseIdDescription": "Undefined",
    "Message": "Beim Analysieren des Ausdruckes: \r\nHallo Hier ist ein Langtext. Dieser Text ist sehr lang und besteht aus zwei Sätzen, getrennt durch Punkte.\r\nist folgender Fehler aufgetreten:\r\nSyntaxfehler",
    "Details": {
        "Fehler": "Beim Analysieren des Ausdruckes: \r\nHallo Hier ist ein Langtext. Dieser Text ist sehr lang und besteht aus zwei Sätzen, getrennt durch Punkte.\r\nist folgender Fehler aufgetreten:\r\nSyntaxfehler",
        "DetailString": "",
        "Titel": "",
        "ExceptionName": "EAbortTT"
    }
}
```
#### Steps to replicate the behavior:
Ich habe ein Makro im Makroassistenten erstellt mit Inhalt:
`SELECT :[test] AS testString`
Der Parameter `test` ist als String definiert.
Das Ergebnis wird gedruckt in Datei. Druckvorlage enthält nur den Code:
``` 
 [V:0::DateiANSI:2:0::"\\DATEIPFAD\"+asfilename("test " + {System.System Datum/Uhrzeit} +  ".txt")]  [D:0::=:] 
 [T:0::test] 
```
Wenn ich das Makro über die API ausführe und in der Value für den Parameter `test` einen String eintrage, der zwei Punkte enthält, dann bekomme ich die Fehlermeldung mit Syntaxfehler. Wie in **Details** beschrieben.
(Beim Ausführen über den Makroassistent mit demselben String als Parameter bekomme ich keine Fehlermeldung, es funktioniert wie gewünscht.)

Auch bei:
```
{
  "MacroName": "SQLlw015",
   "Parameters": [
        {
            "Name": "test",
            "Value": ".."
        }
    ]
}
```
Kommt derselbe Fehler zurück:
```
{
    "StatusCode": "InternalServerError",
    "ResponseCode": "70-000",
    "ResponseId": 0,
    "ResponseIdDescription": "Undefined",
    "Message": "Beim Analysieren des Ausdruckes: \r\n..\r\nist folgender Fehler aufgetreten:\r\nSyntaxfehler",
    "Details": {
        "Fehler": "Beim Analysieren des Ausdruckes: \r\n..\r\nist folgender Fehler aufgetreten:\r\nSyntaxfehler",
        "DetailString": "",
        "Titel": "",
        "ExceptionName": "EAbortTT"
    }
}
```

Es scheint hier einen Fehler zu geben, wenn zwei oder mehr Punkte als Value übergeben werden. Ein Punkt ist nach meinen Tests möglich.

Im Original wollte ich einen String mit deutschem Datumsformat als Parameter an das Makro übergeben. Dieses hat mir den Fehler zum ersten Mal gegeben, da das Datum zwei Punkte enthielt. 
Als Workaround kann ich das Datum anders formatieren, bevor ich es als Parameter übergebe.

Dieser Fehler tritt **nicht** bei ExecuteMacro auf.
Mit dem hinterlegten API-Makro:
```
declare @MakroName nvarchar(255)
declare @MakroText nvarchar(max)

set @MakroName = 'TEST'

set @MakroText = 'SELECT :Eingabe'

-- Makro aktualisieren
if exists(select [Name] from [dbo].[APIMACRO] where [Name] = @MakroName)
    BEGIN
        UPDATE [dbo].[APIMACRO] set
            [Text] = @MakroText
        where [Name] = @MakroName
    END
ELSE
    BEGIN
        INSERT INTO [dbo].[APIMACRO] ([Name],[Text])
        VALUES (@MakroName,@MakroText)
    END
```
und dem Aufruf: `/slmobileApi/Macros/TEST`
Parameter:
```
[
    {
        "Name": "Eingabe",
        "Value": "Hallo Hier ist ein Langtext. Dieser Text ist sehr lang und besteht aus zwei Sätzen, getrennt durch Punkte."
    }
]
```
bekomme ich, wie erwartet, den String normal mit den zwei Punkten zurück:
```
{
    "ColumnNames": [
        ""
    ],
    "Rows": [
        {
            "ColumnValues": [
                "Hallo Hier ist ein Langtext. Dieser Text ist sehr lang und besteht aus zwei Sätzen, getrennt durch Punkte."
            ]
        }
    ]
}
```

Können Sie diesen Fehler nachstellen oder ist er bekannt?
Der Fehler scheint bei einer Analyse zu passieren, die vor dem Makro-Ausführen passiert. Kann die Analyse angepasst werden, dass wir in Zukunft Parameter-Values mitgeben können, die mehr als einen Punkt enthalten?

(Ich benötige im Moment keine Anpassung, da ich einen Workaround für meinen Fall mit dem Datum habe, allerdings kann es hier bei Langtexten oder Texten mit Punkten für Steuerzeichen o. ä. Probleme in der Zukunft geben.)

Vielen Dank.

**Comment by LandoWalter** [comment]
Update:
Ich teste gerade noch etwas mehr und die Analyse vor dem Ausführen macht mir noch einiges mehr an meinen Strings kaputt.

Mit Makro:
`SELECT :[test] AS testString`
mit `test` als String, gedruckt auf Datei und Druckvorlage:
Seitenkopf:
```
 [V:0::DateiANSI:2:0::"\\DATEIPFAD\"+asfilename("test " + {System.System Datum/Uhrzeit} +  ".txt")]  [D:0::=:] 
 [P:0::.test] 
```
Positionen:
```
 [P:0::testString] 
```
Hier Beispiele und unterschiedliche Rückmeldungen/Fehler:
1. Irgendein String gibt Fehler mit Syntax:
```
{
  "MacroName": "SQLlw015",
   "Parameters": [
        {
            "Name": "test",
            "Value": "TESTSTRING"
        }
    ]
}
```
```
{
    "StatusCode": "InternalServerError",
    "ResponseCode": "70-000",
    "ResponseId": 0,
    "ResponseIdDescription": "Undefined",
    "Message": "Beim Analysieren des Ausdruckes: \r\nTESTSTRING\r\nist folgender Fehler aufgetreten:\r\nSyntaxfehler",
    "Details": {
        "Fehler": "Beim Analysieren des Ausdruckes: \r\nTESTSTRING\r\nist folgender Fehler aufgetreten:\r\nSyntaxfehler",
        "DetailString": "",
        "Titel": "",
        "ExceptionName": "EAbortTT"
    }
}
```
2. String "F" gibt ungültiges Zahlenformat (obwohl "F" ein gültiger String sein sollte)
```
{
  "MacroName": "SQLlw015",
   "Parameters": [
        {
            "Name": "test",
            "Value": "F"
        }
    ]
}
```
```
{
    "StatusCode": "InternalServerError",
    "ResponseCode": "70-000",
    "ResponseId": 0,
    "ResponseIdDescription": "Undefined",
    "Message": "Beim Analysieren des Ausdruckes: \r\nF\r\nist folgender Fehler aufgetreten:\r\nUngültiges Zahlenformat",
    "Details": {
        "Fehler": "Beim Analysieren des Ausdruckes: \r\nF\r\nist folgender Fehler aufgetreten:\r\nUngültiges Zahlenformat",
        "DetailString": "",
        "Titel": "",
        "ExceptionName": "EAbortTT"
    }
}
```
3. Es werden bei manchen Strings Zahlen erkannt und als Aufgabe behandelt.
```
{
  "MacroName": "SQLlw015",
   "Parameters": [
        {
            "Name": "test",
            "Value": "2023-01-13"
        }
    ]
}
```
```
{
    "IsSuccessful": false,
    "AffectedRows": 0
}
```
In der Datei steht dann zweimal 2009. Es wird also nicht der String "2023-01-13" als Parameter übergeben, sondern mein originaler String wird umgewandelt in 2009, was wohl das Rechenergebnis aus 2023-1-13=2009 ist. Wenn ich als `Value` andere Zahlen als Rechenaufgabe eingebe, wird das auch ausgerechnet übergeben, wobei ich eigentlich erwarte, dass mir meine Parameter-Value genau als String übergeben wird.

Kann man dieses evaluate/untersuchen/analysieren der Parameter-Values umgehen/ausschalten?
Das macht mir doch ziemlich Probleme, dass ich meine Strings nicht Eins-zu-eins in das Wawi-Makro übergeben kann.

**Comment by MatthiasGuse** [comment]
Hallo,

danke für die detaillierte Beschreibung. Wir werden das überprüfen und uns dann dazu melden.

Viele Grüße

**Comment by LandoWalter** [comment]
Selber Fehler wie in: #57 
Bitte wie in dem vorherigen Issue auch schon angesprochen, die Dokumentation für diese Route anpassen.
Vielen Dank
