### ISSUE TITLE
Nach dem Update auf 22.3.2 in der WaWi kommt im Mobile Manager die Client.Send failed

### ISSUE THREAD

**Issue by Torchok19081986** [selectline-software/selectline-api#306]
### Details
- Current version number: 22.3.2
- Previous version number (optional): 22.3.1
- [x] Test status checked in Mobile Manager : Alle Tests sind grün
- Function or route (request): Login Request für Mobile Benutzer
- Error (response):  Forbidden für Mobile Benutzer

Ich konnte mich mit der Version 22.3.1 erfolgreich via Programm einloggen. Nach dem Update auf die neueste Version 22.3.2 geht das nicht mehr und im Mobile Manager erscheint Error : Client.Send Failed. 
Log eintrag : 

<Log>
    <Message>Beim Schließen der Backends ist ein Ausnahmefehler aufgetreten: Client.Send failed. See InnerException</Message>
    <GermanMessage>Beim Schließen der Backends ist ein Ausnahmefehler aufgetreten: Client.Send failed. See InnerException</GermanMessage>
    <ID>178fd059-2c44-4817-a176-3d390823a26c</ID>
    <CreateDate>2023-01-16T08:39:10.2272636+01:00</CreateDate>
    <Exception>
      <Message>Client.Send failed. See InnerException</Message>
      <StackTrace>   bei SelectLine.Messaging.Friend.FriendClient.&lt;SendInternalAsync&gt;d__26.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei SelectLine.Messaging.Friend.FriendClient.&lt;SendAsync&gt;d__23`1.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei SelectLine.Erp.BackendManager.Client.ErpAdministration.&lt;SendMessageToBackendManager&gt;d__11`1.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei SelectLine.Erp.BackendManager.Client.ErpAdministration.&lt;GetActiveUserCountAsync&gt;d__10.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei SelectLine.Mobile.MobileManager.Modules.Datenbank.DatenbankViewModel.&lt;GetActiveUserCount&gt;d__106.MoveNext()</StackTrace>
      <InnerException>
        <Message>Can't deserialize System.Int32</Message>
        <StackTrace>   bei SelectLine.Messaging.Friend.FriendClient.DeserializeContent(Type resultType, FriendClientMessage clientMessage)
   bei SelectLine.Messaging.Friend.FriendClient.&lt;SendInternalAsync&gt;d__26.MoveNext()</StackTrace>
      </InnerException>
    </Exception>
    <EventType>Error</EventType>
  </Log>

Mobile Manager Tests sind alle Grün und keine Login mehr möglich.

**Comment by MatthiasGuse** [comment]
Hallo,

der Fehler ist uns bekannt. Er tritt zufällig auf, hat aber keine Auswirkungen auf die Funktion der API. Wir haben ihn zur Behebung aufgenommen. 

Konnten Sie sich denn mittlerweile wieder korrekt anmelden? Die Fehlermeldung `Forbidden für Mobile Benutzer` sieht eher danach aus, dass der falsche LoginKind für den User verwendet wurde.

**Comment by Torchok19081986** [comment]
Morgen, leider nein. Benutzer wurde als Mobile Benutzer angelegt und konnte sich mit 22.3.1 erfolgreich einloggen.  Mit dem Update 22.3.2 geht das nicht mehr. Code wurde kein Stück verändert.  
Zusätzlich erscheint im Protokoll noch folgende Fehlermeldung, welche mit 22.3.1 nicht gegeben hat : 

<InnerException>
        <Message>Can't deserialize System.Int32</Message>
        <StackTrace>   bei SelectLine.Messaging.Friend.FriendClient.DeserializeContent(Type resultType, FriendClientMessage clientMessage)
   bei SelectLine.Messaging.Friend.FriendClient.&lt;SendInternalAsync&gt;d__26.MoveNext()</StackTrace>
      </InnerException>

Diese Meldung im Protokoll erscheint immer, wenn die Mobile Manager die Tests ausführt.

**Comment by MatthiasGuse** [comment]
Der Benutzer muss als API Benutzer in den Mobile Benutzereinstellungen angelegt werden. Sollten Sie sich als ganz normaler Mobile User erfolgreich angemeldet haben, war dies ein Fehler, den wir korrigiert haben. Ebenfalls sollten Sie Ihren Appkey bei der Anmeldung mitgeben.

Viele Grüße

**Comment by Torchok19081986** [comment]
Morgen,  Vielen Dank für die Info. 
Das Programm wurde entwickelt als die API Benutzer noch gar nicht gab, darum sind alle Benutzer als Mobile Benutzer mit entsprechenden Lizenz angelegt. 
Ich muss noch mit Endkunden sprechen,  ob er bereit ist , eine weitere Lizenz zu kaufen, da der APIKey was kostet.

**Comment by MatthiasGuse** [comment]
Ah ok. Das ist die alte Art der Verwendung der API, bei der nur gewisse Funktionen nutzbar sind. 

Ich habe mir das nochmal angeschaut, einen Nutzer vom Typ "Mobile" verwendet und auch genau den genannten Versionsstand genutzt. Login problemlos möglich.
![grafik](https://user-images.githubusercontent.com/31447000/213389265-37d99ff0-3728-4325-bfea-1918bd6b1354.png)

Bitte mal prüfen, ob die Anmeldung mit Swagger funktioniert.

Viele Grüße

**Comment by Torchok19081986** [comment]
hm.. Ok. Ich prüfe gerade, ob es im Swagger funktioniert, dann melde ich mich.

**Comment by Torchok19081986** [comment]
Hallo, ich kann evtl. etwas Licht im Dunkel bringen. 
in der Version 22.3.1 sieht die Benutzerverwaltung folgendermaßen aus : 
![SL Update 22 3 1](https://user-images.githubusercontent.com/25432729/213416757-0cc3e8a8-a5d2-4b13-8500-4af879e9f3a1.PNG)

nach dem Update is es aber nicht mehr da , und sieht so aus : 

![SL Update 22 3 2](https://user-images.githubusercontent.com/25432729/213416841-39b1f260-abf3-48df-915c-dac4d67f4c9c.PNG)

**Comment by MatthiasGuse** [comment]
Ja, das sieht nicht richtig aus. Ich vermute, dass hier ein Fehler in der Lizenzierung vorliegt.

Bitte schreiben Sie eine E-Mail an support@selectline.de und nehmen Bezug auf diesen Issue. Geben Sie an auf wen die verwendete Lizenz lizenziert ist. Diesen Inhalt brauche ich bitte:
![grafik](https://user-images.githubusercontent.com/31447000/213432850-7e0b3cdc-a9b0-4c40-ab4b-7a98f9f80411.png)

**Comment by Torchok19081986** [comment]
Hallo, danke für die Info. Email ist mit entsprechenden Information wurde gesendet.

**Comment by MatthiasGuse** [comment]
Hallo,

der Fehler im Mobile Manager ist zu ignorieren. Es ist so, dass die Mobile Installation mit einer Demo-Lizenz nicht korrekt funktioniert, wenn sich die Installationen in der Versionsnummer unterscheiden. Dies haben wir zur Kenntnis genommen. Da es zukünftig Änderungen geben wird, die das Problem prinzipiell beheben, werden wir hier keine Korrektur vornehmen.

Davon, eine Demo Installation zur Programmierung bzw. zum Test der API zu benutzen, ist abzuraten. Dazu haben Sie Ihre Fachhandelslizenz. Ab der Version 23.1. wird die Nutzung der API Funktionen ohne Appkey nicht mehr in der Demo enthalten sein und anhand der damals erworbenen Toolbox-Lizenz bestimmt.

Viele Grüße
