### ISSUE TITLE
Listenpreis Brutto holen

### ISSUE THREAD

**Issue by babicu2d** [selectline-software/selectline-api#307]
Wie kann ich den Listenpreis von einem Artikel aus SelectLine holen?
In der json habe ich nur das unter "Payment" z.B:
"ListPrice": 39.25
Aber das ist nur der Nettopreis. Brutto wäre 41.53. 
Danke im Voraus.

**Comment by Micha-Richter** [comment]
Ich befürchte, das wird nur über ein (API-)Makro gehen, da sich die Steuerschlüssel scheinbar nicht per API abfragen lassen. 
Oder halt im Client die Steuerschlüssel und -sätze selbst noch mal vorhalten und mit denen rechnen.. 😏

Ehrlicherweise muss man aber auch sagen, dass der Bruttopreis ja auch noch davon abhängt, an wen/wohin man verkauft, oder?

**Comment by babicu2d** [comment]
Also es hängt schon ab aber für mich ist es wichtig den genauen Listenpreis Brutto zu holen. 
Da habe ich mehrere Werte z.B. in AWAWI Mandant habe ich ein 120001 Artikel mit Listenpreis Netto 39.25.
Listenpreis Brutto(das, was ich brauche) ist 41.53 und einen Steuerschlüssel 3 (20%) mit den Bruttopreis 47.10.
Aber alles, was ich in dem json habe sind die vordefinierte Felder ListPrice (39.25) und CalculationPrice.
Könnte man irgendwie den Preis 41.53 von der Oberfläche in SelectLine auslesen? Oder direkt aus der Datenbank, da es da unter ListenPreis Brutto vorhanden ist.

**Comment by Micha-Richter** [comment]
Mit dem API-Makro kannst du den Wert direkt aus der Datenbank auslesen.
(wenn dein Backend direkten Zugriff auf die DB hat, kannst du natürlich auch an der API vorbei die Datenbank abfragen; das sollte dann deutlich schneller sein)

**Comment by MatthiasGuse** [comment]
Die API bietet derzeit keine direkte Möglichkeit die Preise so abzufragen. Es bleibt nur der Vorschlag über ein Makro.
Im SelectLine Wünscheforum existiert bereits ein Wunsch dazu. Hier können Sie als Fachhändler Ihre stimmen dazu abgeben.

Viele Grüße
