### ISSUE TITLE
Rechnungsadresse eines Beleges via API abrufen

### ISSUE THREAD

**Issue by s52512** [selectline-software/selectline-api#308]
Hallo Zusammen,

ich habe die Notwendigkeit, die Rechnungsadresse eines Beleges über die API abzurufen. Ich habe dafür den Beleg mittels /Documents/{documentKey} abgerufen und bekomme im Property "BillingAddress" keinen Wert obwohl im Selectline an dem Beleg eine Rechnungsadresse hinterlegt ist.

Mir ist auch aufgefallen, dass es nur sich lediglich um eine String - Property handelt und daher stellt sich mir die allgemeine Frage was dort für ein Wert geliefert werden soll und wie ich zur eigentlichen Rechnungsadresse komme. Ich würde hier eher eine Objekt - Property analog zur DeliveryAddress erwarten, wobei diese in meinen Tests auch nicht gefüllt wird, wenn eine Lieferadresse am Beleg angegeben ist.

Vielen Dank schon einmal

**Comment by Micha-Richter** [comment]
Die Informationen stehen im Response unter "BusinessPartner":
```
  "BusinessPartner": {
    "BusinessPartnerReferenceNumber": "",
    "ReferenceAddressNumber": "2080000",
    "BusinessPartnerContract": null,
    "BusinessPartnerContractDate": "2023-01-24T00:00:00+01:00",
    "ContactPersonId": 0,
    "LastName": "Richter",
    "Company": " ",
    "Salutation": "",
    "FirstName": "Michael",
    "Address": {
      "Number": "2080000",
      "Street": "Lindenstraße 22a",
      "City": "Burgstall/OT Dolle",
      "ZipCode": "39517",
      "CountryId": "DE",
      "AdditionalInformation1": "",
      "AdditionalInformation2": "",
      "AdditionalInformation3": "+4915164509495"
    }
}
```

**Comment by MatthiasGuse** [comment]
Falls das Thema noch aktuell ist, bitte wieder öffnen.

Viele Grüße
