### ISSUE TITLE
Belegposition mit mehr als 2 Nachkommastellen im Einzelpreis

### ISSUE THREAD

**Issue by Grewamor** [selectline-software/selectline-api#309]
Hallo liebes SL-API-Team,

bei der Erstellung einer Belegposition werden leider nur 2 Nachkommastellen beim Einzelpreis berücksichtigt.
Könnt ihr bitte das Verhalten überprüfen?

Vielen Dank
Morris

CURL
```
curl -X POST "https://sql03/slmobileApi/Documents/F1/ArticleItem" -H  "accept: application/json" -H  "Authorization: LoginId 50ec5490-b57d-4ff7-b29b-b47a5f3aaf3a" -H  "Content-Type: application/json" -d "{  \"ArticleNumber\": \"ItemA2\",  \"UnitPrice\": 89.9912345,  \"AdditionalDescription\": \"Schaukelstuhl, blau, breite Armlehnen\",  \"CalculatedQuantityValue\": 4}"
```

Response:
```
{
  "DocumentKey": "F1",
  "DocumentKind": "F",
  "DocumentNumber": "1",
  "PositionIdentifier": "CF41237C-FD0C-4112-8F7B-C965B4AFAD9E",
  "Kennung": "CF41237C-FD0C-4112-8F7B-C965B4AFAD9E",
  "AdditionalAction": null,
  "SuccessAdditionalActions": "Die zusätzliche Aktion  war erfolgreich."
}
```

![image](https://user-images.githubusercontent.com/18594343/214286825-5aeb3403-e1b9-4f49-a1e7-40374455517e.png)

**Comment by MatthiasGuse** [comment]
Hallo,

wir werden das überprüfen und uns dann dazu melden.

Viele Grüße

**Comment by MatthiasGuse** [comment]
Hallo,

sind denn die Einstellungen im Mandanten auf die gewünschte Anzahl an Nachkommastellen eingestellt?
![grafik](https://user-images.githubusercontent.com/31447000/219327214-f796e522-fd2d-46b5-a4fa-a58524aaa518.png)

Nach einer Änderung an diesen Einstellungen bitte an der API vollständig abmelden und erneut anmelden.

Viele Grüße

**Comment by Grewamor** [comment]
Hallo Herr Guse,

das hat in der Tat geholfen. Ich bedanke mich für Ihre Hilfe und entschuldige mich für meine dumme Frage :-D

VG M.Prinz
