### ISSUE TITLE
"Die Aktion wurde abgebrochen, weil versucht wurde ein Fenster zu öffnen."

### ISSUE THREAD

**Issue by clinkwitz** [selectline-software/selectline-api#31]
Belege abrufen und bearbeiten war z.B. kein Problem, ich habe jetzt versucht, einen Beleg anzulegen, bekomme allerdings nur folgendes zurück, unabhängig davon, was genau ich versuche per POST hinzuschicken.

![image](https://user-images.githubusercontent.com/29201383/88796864-b3393780-d1a2-11ea-99b0-3c3965f4e929.png)

Über die Response-Codes konnte ich auflösen, dass beim Auflegen des Belegs ein Fehler aufgetreten ist - allerdings ist mir nicht ersichtlich, wieso die API versucht, ein Fenster zu öffnen, geschweige denn, was ich dagegen tun kann.

Ruft die API zufällig im Hintergrund die COM-Schnittstelle auf?

**Comment by SteveSteglitz** [comment]
Hallo,
können Sie uns einmal den Body von einem POST der bei Ihnen nicht funktioniert hier einfügen? Dann können wir uns ein besseres Bild machen, woran es vielleicht liegen könnten. Des Weiteren würde ich Sie bitte, dieselbe Aktion, die nicht funktioniert (z.B. die Belegübergabe oder eine Lageraktion) in der Warenwirtschaft selbst zu probieren und ein mal darauf zu achten, ob bei den Schritten ein Fenster (Hinweis, Fehler, Eingabedialog, Lagerdialog etc. ) hoch kommt.  Wenn ja, dann wird das vermutlich auch das Fenster sein, was bei dem API Call die Probleme macht. Hier spielen hin und wieder auch Mandanteneinstellungen eine Rolle. Wir sind bestrebt alle möglichen Aktionen, die eine Interaktion erfordern, zu unterbinden und dem Entwickler mit einem konkreten ErrorCode zu helfen. Für alle existierenden Aktionen ist das allerdings derzeit noch nicht möglich. 

Viele Grüße
Steve

**Comment by clinkwitz** [comment]
Guten Morgen,
Die Daten haben ich per GET aus einem anderen A-Beleg herausgeholt und die Werte dann in das POST-Format übernommen. Diese sollten dann zumindest in meiner Denkweise ja dann gültig sein. 
Folgende Nutzdaten schicke ich zur API hin, sind Dummydaten aus einem Testmandanten.

`{
  "Number": "AG10001",
  "KindFlag": "A",
  "Date": "2020-07-31T07:34:21.578Z",
"BusinessPartner": {
    "LastName": "Mustermann",
    "Company": "Mustermann AG",
    "Salutation": "Herr ",
    "FirstName": "Max",
    "Address": {
      "Number": "1",
      "Street": "Musterstraße 2",
      "City": "Musterstadt",
      "ZipCode": "11111",
      "CountryId": "",
      "AdditionalInformation1": "",
      "AdditionalInformation2": "",
      "AdditionalInformation3": ""
    },
    "BusinessPartnerReferenceNumber": "",
    "ReferenceAddressNumber": "1",
    "BusinessPartnerContract": null,
    "BusinessPartnerContractDate": "2019-11-22T00:00:00+01:00",
    "ContactPersonId": 0
  },
  "Payment": {
    "BankingDetailsId": 0,
    "BankAccount": "",
    "IsCashSale": false,
    "PaymentTerm": "",
    "PaymentTermLabel": null,
    "PaymentPeriod": 0,
    "PaymentPeriodLabel": "innerhalb von 0 Tagen zum 05.12.2019",
    "PaymentPeriodKind": 0,
    "PaymentDocumentReferenceNumber": null,
    "FinancialAccountNumber": "1",
    "BankAccountGroup": "",
    "BankAccountGroupLabel": null,
    "CostCenterNumber": "",
    "CostCenterLabel": null,
    "FinancialAccountExportDate": "0001-01-01T00:00:00+01:00",
    "FinancialAccountClause": null,
    "IsPaymentLock": false
  },
  "IsPrinted": false,
  "EmployeeNumber": "",
  "EmployeeLabel": " ",
  "SalesmanNumber": "",
  "SalesmanLabel": " ",
  "WarehouseNumber": "",
  "WarehouseLabel": null,
  "CurrencyCode": "EUR",
  "CurrencyLabel": "Eurowährung",
  "CurrencyExchangeRate": 1,
  "DeliveryTermNumber": "",
  "DeliveryTermLabel": null,
  "DeliveryText": "",
  "DeliveryText2": "",
  "PriceGroupNumber": "0",
  "PriceGroupLabel": null,
  "PriceKindFlag": "N",
  "DiscountGroupNumber": "",
  "DiscountGroupLabel": null,
  "DiscountAmount": 0,
  "CashDiscountDays": 0,
  "CashDiscountDaysKind": 0,
  "CashDiscountPercent": 0,
  "CashDiscountLabel": "innerhalb von 0 Tagen zum 05.12.2019 (0,00 %)",
  "CashDiscount2Days": 0,
  "CashDiscount2DaysKind": 0,
  "CashDiscount2Percent": 0,
  "CashDiscount2Label": "innerhalb von 0 Tagen zum 05.12.2019 (0,00 %)",
  "AlternativeWirCurrencyAmount": 0,
  "AlternativeWirCurrencyPercent": 0,
  "AlternativeWirCurrencyKind": "B",
  "DeliveryDate": "2019-12-15T00:00:00+01:00",
  "StatusLabel": "Offen",
  "OurReference": "Werner Beckmann",
  "LanguageCode": "",
  "LanguageLabel": null,
  "DeliveryDocumentNumber": null,
  "MaintenanceContractReference": -1,
  "DefaultPrintTemplate": "BECKMANNGMBH",
  "BillingAddress": "",
  "RateKind": 1,
  "FixedRate": 1,
  "EuropeanCountryCode": "",
  "TrafficRouteKind": "3",
  "TrafficRouteKindLabel": "Straßenverkehr",
  "InternationalLocationNumber": "",
  "NativeInvoiceRecipientNumber": "1",
  "EdiStatusKind": "O",
  "EdiStatusLabel": "unbekannt",
  "WarehouseLocationNumber": "01",
  "WarehouseLocationLabel": "Vorgabestandort",
  "PositionTotalRoundNearest": 100,
  "TotalRoundNearest": 100,
  "AssociationRegulatorNumber": "",
  "DelcrederePercent": 0,
  "StockTransferCode": null,
  "DisplayName": "Mustermann AG",
  "ReturnMerchandiseAuthorizationNumber": null,
  "ReportCountryCode": null,
  "CustomField": {
    "Text1": null,
    "Text2": null,
    "Number1": null,
    "Number2": null,
    "Number3": null,
    "Number4": null,
    "Date1": null,
    "Date2": null,
    "Flag1": false,
    "Flag2": false,
    "Flag3": false,
    "Flag4": false
  },
  "StatusFlag": "string",
  "DeliveryAddress": null,
  "PaymentReference": "string"
}`

**Comment by SteveSteglitz** [comment]
Hallo, 
Sie geben die Belegnummer in dem POST mit. Falls diese bereits vergeben ist, kann es zu einem Fehler kommen. Alternativ können Sie diese Angabe auch weglassen, dann würde die automatische Nummernvergabe ziehen. 
Versuchen Sie einmal das Anlegen des Beleges auf ein Minimum zu reduzieren. 
`{
	"KindFlag": "F",
	"BusinessPartner":
		{
			"Address":
			{
			"Number": "10001"
			}
		}
}`
Alternativ können Sie über Ihre Installation und der SelectLine API Hilfeseite auch die Abfragen mittels Swagger testen. 

Viele Grüße
Steve

**Comment by sichert** [comment]
Hallo clinkwitz,

mit folgender Abfrage, die ich mit Python 3.8, requests und commentjson durchgeführt habe, klappt es auch in der SL-API-Demoumgebung.

Alle fehlerträchtigen Stellen sind mit # auskommentiert. Das lässt commentjson für json-Inhalte zu. Die Zeilen müssen in anderen Fällen (Postman etc.) einfach gelöscht werden.

@SteveSteglitz: Das Beispiel könnte auch in die Help mit aufgenommen werden, da man dann wenigstens ein offizielles Beispiel hätte, welches auch funktioniert (auch https://github.com/selectline-software/selectline-api/issues/36 wäre dann zur Hälfte schon beantwortet).:

{
    "KindFlag": "A",
    # wenn die folgende Nummer ein 2. mal abgefragt wird, dann kommt 'Die Aktion wurde abgebrochen, weil versucht wurde ein Fenster zu öffnen.'    
    "Number": "AG10001", 
    "Date": "2020-07-31T07:34:21.578Z",
    "BusinessPartner": {
        "LastName": "Mustermann",
        "Company": "Mustermann AG",
        "Salutation": "Herr ",
        "FirstName": "Max",
        "Address": {
            "Number": "1",
            "Street": "Musterstraße 2",
            "City": "Musterstadt",
            "ZipCode": "11111",
            "CountryId": "",
            "AdditionalInformation1": "",
            "AdditionalInformation2": "",
            "AdditionalInformation3": ""
        },
        "BusinessPartnerReferenceNumber": "",
        "ReferenceAddressNumber": "1",
        "BusinessPartnerContract": null,
        "BusinessPartnerContractDate": "2019-11-22T00:00:00+01:00",
        "ContactPersonId": 0
    },
    "Payment": {
        "BankingDetailsId": 0,
        "BankAccount": "",
        "IsCashSale": false,
        "PaymentTerm": "",
        "PaymentTermLabel": null,
        "PaymentPeriod": 0,
        "PaymentPeriodLabel": "innerhalb von 0 Tagen zum 05.12.2019",
        "PaymentPeriodKind": 0,
        "PaymentDocumentReferenceNumber": null,
        "FinancialAccountNumber": "1",
        "BankAccountGroup": "",
        "BankAccountGroupLabel": null,
        "CostCenterNumber": "",
        "CostCenterLabel": null,
        "FinancialAccountExportDate": "0001-01-01T00:00:00+01:00",
        "FinancialAccountClause": null,
        "IsPaymentLock": false
    },
    "IsPrinted": false,
    "EmployeeNumber": "",
    "EmployeeLabel": " ",
    "SalesmanNumber": "",
    "SalesmanLabel": " ",
    # "WarehouseNumber": "", # sonst Fehlermeldung 'Das Lager existiert nicht in den Lagerstammdaten.'
    "WarehouseLabel": null,
    "CurrencyCode": "EUR",
    "CurrencyLabel": "Eurowährung",
    "CurrencyExchangeRate": 1,
    # "DeliveryTermNumber": "", # sonst Fehlermeldung 'Die Lieferbedingung existiert nicht in den Stammdaten.'
    "DeliveryTermLabel": null,
    "DeliveryText": "",
    "DeliveryText2": "",
    "PriceGroupNumber": "0",
    "PriceGroupLabel": null,
    "PriceKindFlag": "N",
    "DiscountGroupNumber": "",
    "DiscountGroupLabel": null,
    "DiscountAmount": 0,
    "CashDiscountDays": 0,
    "CashDiscountDaysKind": 0,
    "CashDiscountPercent": 0,
    "CashDiscountLabel": "innerhalb von 0 Tagen zum 05.12.2019 (0,00 %)",
    "CashDiscount2Days": 0,
    "CashDiscount2DaysKind": 0,
    "CashDiscount2Percent": 0,
    "CashDiscount2Label": "innerhalb von 0 Tagen zum 05.12.2019 (0,00 %)",
    "AlternativeWirCurrencyAmount": 0,
    "AlternativeWirCurrencyPercent": 0,
    "AlternativeWirCurrencyKind": "B",
    "DeliveryDate": "2019-12-15T00:00:00+01:00",
    "StatusLabel": "Offen",
    "OurReference": "Werner Beckmann",
    "LanguageCode": "",
    "LanguageLabel": null,
    "DeliveryDocumentNumber": null,
    "MaintenanceContractReference": -1,
    "DefaultPrintTemplate": "BECKMANNGMBH",
    "BillingAddress": "",
    "RateKind": 1,
    "FixedRate": 1,
    "EuropeanCountryCode": "",
    "TrafficRouteKind": "3",
    "TrafficRouteKindLabel": "Straßenverkehr",
    "InternationalLocationNumber": "",
    "NativeInvoiceRecipientNumber": "1",
    "EdiStatusKind": "O",
    "EdiStatusLabel": "unbekannt",
    # "WarehouseLocationNumber": "01", # sonst Fehlermeldung 'Der Standort 01 existiert nicht in den Stammdaten.'
    "WarehouseLocationLabel": "Vorgabestandort",
    "PositionTotalRoundNearest": 100,
    "TotalRoundNearest": 100,
    "AssociationRegulatorNumber": "",
    "DelcrederePercent": 0,
    "StockTransferCode": null,
    "DisplayName": "Mustermann AG",
    "ReturnMerchandiseAuthorizationNumber": null,
    "ReportCountryCode": null,
    "CustomField": {
        "Text1": null,
        "Text2": null,
        "Number1": null,
        "Number2": null,
        "Number3": null,
        "Number4": null,
        "Date1": null,
        "Date2": null,
        "Flag1": false,
        "Flag2": false,
        "Flag3": false,
        "Flag4": false
    },
    # "StatusFlag": "string", # sonst Fehlermeldung 'Das Feld [Status] darf nicht geändert werden.'
    "DeliveryAddress": null,
    "PaymentReference": "string"
}
