### ISSUE TITLE
Vorgabewerte Schlüssel

### ISSUE THREAD

**Issue by BeetzIT** [selectline-software/selectline-api#310]
Hallo Zusammen, 

ich bin gerade dabei das wir ein Tool entwickeln das auch Bestellungen automatisch anlegt. 

mein Problem, wo finde ich die letzte Nummer bzw nächste und wie kann ich die um eins erweitern?

Danke für eure Hilfe. 

Gruß 
Thomas

**Comment by Micha-Richter** [comment]
Hallo Thomas,

die aktuellen Schlüssel werden für alle Tabellen/Blobkeys in der Tabelle KEY gehalten (in der Mandanten-DB oder der SL_Daten).

Im Bild siehst du einen Auszug aus einer Mandanten-KEY-Tabelle, und aus den Spaltennamen und Daten ergibt sich schon, was da in der SL beim Schlüsselhandling so abgeht.. 
Die Schlüssel können z.B. auch alphanumerisch sein und die SL wird die Buchstaben "hochzählen" (s. Blobkey AR), außerdem gibt es mit PREVKEY einen Mechanismus beim Löschen des letzten Datensatzes (Schlüssel stimmt mit LASTKEY überein), so dass der PREVKEY wieder zum LASTKEY wird usw. usf.

<img width="654" alt="image" src="https://user-images.githubusercontent.com/12509902/214639104-7d102875-83df-4afb-8a28-30e2701c3e23.png">

Beim Posten deiner neu angelegten Bestellung unbedingt einen "Doppelter Schlüssel"-Fehler von der DB auswerten und mit einem neuen Schlüsselwert erneut speichern. Irgendwer kann immer dazwischenfunken..


Aber vielleicht kannst du die Bestellung ja per API anlegen, dann wäre das Schlüsselthema erledigt!?

**Comment by MatthiasGuse** [comment]
Hallo,

mein Vorschlag wäre ebenfalls einfach den Beleg per `POST\Documents` anzulegen und die Belegnummer automatisch vergeben zu lassen.
Der Inhalt der Anfrage sähe im einfachsten Fall so aus:
`{"KindFlag":"B","BusinessPartner":{"Address":{"Number":"70003"}}}`
Die Belegnummer kommt dann mit der Antwort.

Problem damit erledigt?

Viele Grüße

**Comment by BeetzIT** [comment]
Guten Morgen euch allen, 

ich bedanke mich bei euch, für die Rasche Antwort ich teste es gleichmal aus und gebe nochmal bescheid.

Danke manchmal sieht man den Wald vor lauter Bäumen nicht mehr.

**Comment by BeetzIT** [comment]
Danke euch genau das war es was ich gebraucht hatte, ich bin so oft über diese Tabelle gefallen, aber irgendwie die Punkte übersehen, Sag ja man sieht den Wald vor lauter Bäumen nicht. 

Danke Nochmal für die schnelle Hilfe
