### ISSUE TITLE
Belegübergabe ohne Automatische Mengenanpassung mit Internal Server Error 

### ISSUE THREAD

**Issue by AM-Sartissohn** [selectline-software/selectline-api#311]
### Details
- Current version number:  22.3.1
- Previous version number (optional): 
- [y] Test status checked in Mobile Manager
- Function or route (request): POST /Documents/{documentKey}/Successors
- Error (response): 500 Internal Server Error

#### Steps to replicate the behavior:

1. Beleg Auftrag (ausgangsseitig) Anlegen
2. Position anlegen mit einer nicht lagernden Handelsstückliste, in der lagernde Stücklistenunterpositionen enthalten sind
3. einer der Artikel in der Handelsstückliste muss einen negativen Lagerbestand aufweisen
4. Mandanteneinstellungen  "Negativ lagern zulassen", keine Warnung bei negativer Lagerung
5. manuelle Mangenanpassung in der Belegübergabe deaktivieren
6. Request zur Belegübergabe in Belegtyp Rechung mit Positionen im Body (Property Positions, Model DocumentPositionStoreInformationUpdate) übergeben. Wir übergeben in diesem Fall für die Positions jeweils die Properties ArticleNumber, Identifier, PriceQuantity, Quantity, QuantityUnit, StoragePlaceIdentifier, TargetStoragePlaceIdentifier, TargetWarehouse, Warehouse

-> die Belegübergabe gibt einen Internal Server Error zurück. Der Beleg wird zwar angelegt, jedoch nur bis zur Position mit der Handelsstückliste

### Zur Eingrenzung des Problems:
- Wenn KEINE automatische Mengenanpassung eingestellt ist, führen Positionen mit negativem Bestand zu einem Internal Server Error (gewünscht wäre hier, dass die Positionen einfach komplett übernommen werden)
- Wenn die Positionen im Auftrag einen ausreichenden Bestand aufweisen, wird die Belegübergabe in die Rechnung mit den korrekten Mengen übergeben (unabhängig von der Mengenanpassung)
- Wenn die automatische Mengenanpassung in der Belegübergabe eingestellt ist, werden die Mengen wie gewünscht angepasst (die Funktion ist aber vom Kunden nicht gewünscht)
- Das Problem tritt sowohl mit als auch ohne Option "Belegübernahmeoptionen anzeigen" aus den Mandanteneinstellungen/Belege/Übernahme/Statistik auf. Es ist hier auch egal, ob für den mit dem SL.Mobile API-Benutzer verknüpften SelectLine-Benutzer eigene Belegübernahmeoptionen gespeichert sind oder nicht.

Ich weiß nicht, ob die Handelsstückliste hier relevant ist oder das Problem auch mit normalen Artikelpositionen auftreten würde, dies habe ich nicht getestet.

**Comment by MatthiasGuse** [comment]
Hallo,

wir werden das überprüfen und uns dann dazu melden.

Viele Grüße

**Comment by AM-Sartissohn** [comment]
Hallo, haben Sie hierzu inzwischen neue Informationen? Können Sie das Problem reproduzieren?

**Comment by MatthiasGuse** [comment]
Hallo,

das beschriebene Verhalten lässt sich bei uns nicht nachstellen.
![grafik](https://user-images.githubusercontent.com/31447000/219295020-d8932c52-2d53-4bb4-bad1-9cec428f4b9d.png)
Der Auftrag wird korrekt übergeben.

Der Inhalt der Übergabe sah in dem Fall so aus:
```
{
     "DocumentKindDestination" : "R",
     "Positions": [
         {
             "Identifier": "72C95498-BA48-4C39-9CC0-24C5A044B003",
             "ArticleNumber": "100007",
             "Quantity": 1,
             "Warehouse": "200"
         },
         {
             "Identifier": "A625E138-4DCE-443E-B747-69C40FF165AE",
             "ArticleNumber": "100001",
             "Quantity": 4,
             "Warehouse": "100"
         },
         {
             "Identifier": "935CD0B3-FB4E-4523-8CB5-503519729EFC",
             "ArticleNumber": "100003",
             "Quantity": 1,
             "Warehouse": "100"
         }
     ]
}

```
Bezug nehmend zu 6.:
> Request zur Belegübergabe in Belegtyp Rechung mit Positionen im Body (Property Positions, Model DocumentPositionStoreInformationUpdate) übergeben. Wir übergeben in diesem Fall für die Positions jeweils die Properties ArticleNumber, Identifier, PriceQuantity, Quantity, QuantityUnit, StoragePlaceIdentifier, TargetStoragePlaceIdentifier, TargetWarehouse, Warehouse

Es sollten Properties übergeben werden, die für die jeweilige Aktion auch notwendig sind. TargetWarehouse und TargetStoragePlaceIdentifier sind nicht nötig. Ebenfalls sollte Warehouse oder StoragePlaceIdentifier angegeben werden.

Sollten Sie das Problem weiterhin haben, stellen Sie uns bitte ein konkretes Beispiel inkl. Request anhand des Mustermandanten zur Verfügung.

Viele Grüße

**Comment by AM-Sartissohn** [comment]
Hallo,
wir haben die Fehlerquelle hier jetzt feststellen können - Ursache war, dass im Auftrag ein Chargenartikel enthalten war und wir bei der Übergabe keine Chargennummer angegeben haben. Der Fehler konnte uns dazu nicht richtig angezeigt werden, da in den Details der API-Response die Property FehlerNr. mit falschem Namen zurückgegeben wird:

{
    "StatusCode": "InternalServerError",
    "ResponseCode": "42-000",
    "ResponseId": 0,
    "ResponseIdDescription": "Undefined",
    "Message": "Chargennummer fehlt.",
    "Details": {
        "SQLFehlerNr": "0",
        "SQLTmpID": "0",
        "ehlerNr": "102058",
        "ExtMessage": "",
        "ExceptionName": "ELagerungException"
    }
}

Mit Übergabe einer Chargennummer werden die Positionen jetzt auch korrekt in den Folgebeleg übergeben. Die Frage ist jetzt aber, warum hier im Auftrag eine Chargennummer angegeben werden muss: Die API sollte ja die Bedienung des Clients abbilden. Im Auftrag sind noch keine Chargennummern festgelegt, da dort ja nur reserviert wird, aber nicht ausgelagert.

Bei der Belegübergabe eines Auftrags in einen auslagernden Beleg mit dem WaWi-Client wird dabei die Chargennummer anhand der Lagerstrategie automatisch ausgewählt bzw. bei fehlendem Lagerbestand eine neue Chargennummer entsprechend der Mandanteneinstellungen generiert. Warum ist dies bei der Belegübergabe mit der API nicht der Fall? muss hier noch irgendein weiterer Parameter beim Request mitgegeben werden?

**Comment by MatthiasGuse** [comment]
Hallo,
die API erwartet in der Regel immer vollständige Lagerungsinformationen. Automatismen, wie die bspw. Lagerungsvorschlag anhand der Lagerstrategie sind nicht nach außen gelegt. Sie müssen also immer die vollständigen Informationen mitgeben.

Viele Grüße
