### ISSUE TITLE
Rücklagern bzw Minusbuchen bei "Post /Documents/{documentKey}/ArticleItem" nicht mehr möglich

### ISSUE THREAD

**Issue by diekloope** [selectline-software/selectline-api#314]
### Details
- Current version number: 22.3
- Previous version number (optional): 21.2.3
- [ ] Test status checked in Mobile Manager
- Function or route (request): Post /Documents/{documentKey}/ArticleItem
- Error (response):  500 Meldung:  {
  "StatusCode": "InternalServerError",
  "ResponseCode": "42-000",
  "ResponseId": 0,
  "ResponseIdDescription": "Undefined",
  "Message": "Fehler beim Lagern. Offene Menge: 1",
  "Details": {
    "SQLFehlerNr": "0",
    "SQLTmpID": "0",
    "ehlerNr": "102004",
    "ExtMessage": "",
    "ExceptionName": "ELagerungException"
  }
}
#### Steps to replicate the behavior:
In der o.g. vorherigen Version konnten wir im Beleg noch "Minus-Buchen" bzw. Rückbuchen. In der 22.3-Version-Version klappt es leider nicht mehr. Ich nutze für den Post folgenden JSON:
{
  "ArticleNumber": "7180940",
  "UnitPrice": 89.99,
  "AdditionalDescription": "Schaukelstuhl, blau, breite Armlehnen",
  "CalculatedQuantityValue": 2,
  "StoreInformation": [
    {
      "ArticleNumber": "7180940",
      "Warehouse": "5073",
      "Quantity": 2
    }
  ]
}

Wenn CalculatedQuantityValue und CalculatedQuantityValue jetzt als -2 übergebe, kommt die o.g. Fehlermeldung. Muss ich es in der alktuellen Version anders übergeben?

**Comment by MatthiasGuse** [comment]
Hallo,

das beschriebene Verhalten lässt sich bei uns nicht nachstellen. Es gab keine Änderung an dieser Funktionalität.
Bitte beachten Sie, dass ein Vorzeichenwechsel nicht möglich ist. Die Position darf also durch die Aktion nicht von einer positiven in eine negative Menge gebucht werden.

Sollten Sie das Problem weiterhin haben, stellen Sie uns bitte ein konkretes Beispiel inkl. Request anhand des Mustermandanten zur Verfügung.

Viele Grüße

**Comment by diekloope** [comment]
In der SelectLine-Anwendung ist es jetzt auch noch möglich. Siehe Screenshot
![Ruecklagern_1](https://user-images.githubusercontent.com/58892526/220037164-e1e155ea-c1d4-45ec-890c-1becbabeed0b.png)

Über die API war es vorher so möglich. Sehr einfach und effektiv :)
Route: 
slmobileApi/Documents/D" + documentnumber + "/ArticleItem"
JSON:
documentitem = models.OutsourcingDocumentitem{
			CalculatedQuantityValue: amount,
			ArticleNumber:           articleNumber,
			WarehouseId:             storeplaceNumber,
}

**Comment by MatthiasGuse** [comment]
Wie bereits geschrieben, können wir das beschriebene Verhalten nicht nachvollziehen. Das Erstellen von Positionen mit negativer Menge ist über die Route "Post /Documents/{documentKey}/ArticleItem" mit der genannten Version möglich.

Sie nutzen offenbar einen selbstdefinierten Beleg. Was hat der Beleg für Eigenschaften?

Wie rufen Sie die Funktion auf? Haben Sie den Aufruf mit Swagger oder Postman getestet?

Wenn Sie weitere Unterstützung wünschen, stellen Sie bitte ein Beispiel anhand des Mustermandanten mit konkretem Inhalt und vollständigem Request zur Verfügung.

Viele Grüße

**Comment by diekloope** [comment]
Danke. Ich habe das Problem gefunden. Es gibt aber noch ein anderes Problem. Ich hoffe, dass ich es in diesem Ticket einbringen darf, Wenn ich eine oben genannte Lagerung mache, dann klappt es jetzt. Siehe JSON:
{
  "ArticleNumber": "7501012",
  "UnitPrice": 89.99,
  "AdditionalDescription": "Schaukelstuhl, blau, breite Armlehnen",
  "CalculatedQuantityValue": -2,
  "StoreInformation": [
    {
      "ArticleNumber": "7501012",
      "Warehouse": "S11,1,9,5",
      "Quantity": -2
    }
  ]
}
Übergebe ich den Wert S11_2,22,1,1 bei Warehose, dann bekomme ich die Meldung, dass nur  max 10 Zeichen zugelassen sind.
In der SelectLine-Anwendung kann ich im Feld Lager diesen String (Lager, Regal,Fach, Ebene) übergeben.
Wie kann ich es in der API machen?

**Comment by MatthiasGuse** [comment]
Hallo,

idealerweise immer eine neues Ticket öffnen.
Die Angabe des Lagerplatzes ist direkt nicht möglich. in "Warehouse" kann ausschließlich das Lager angegeben werden, also alles vor dem ersten Komma. Wenn Sie einen Lagerplatz angeben möchten, nutzen Sie bitte die Lagerplatz ID und geben Sie diese in "StoragePlaceIdentifier" an. "Warehouse" kann in dem Fall entfallen.
Die Lagerplatz IDs können Sie für ein Lager bspw. mit `GET /Warehouses/{warehouseNumber}/StoragePlaces` abfragen, sofern Sie diese Info nicht bereits haben.

Viele Grüße
