### ISSUE TITLE
Validierung LoginId 

### ISSUE THREAD

**Issue by Laecherlich** [selectline-software/selectline-api#315]
Hey, gibt es eine Möglichkeit per request rauszufinden, ob die LoginId noch valide ist?

**Comment by Micha-Richter** [comment]
Mit jedem Call, der eine gültige LoginId verlangt.. ;)
Spaß beiseite: ist die einzige mir bekannte Methode, um das zu "prüfen".

Aber: wozu sollte das geprüft werden? Feuer doch gleich den "richtigen Request" ab und reagier auf den Fehler, falls die LoginId ungültig ist!?

**Comment by Laecherlich** [comment]
Das dachte ich mir schon :). 
Ich wollte die LoginId im sessionStorage persistieren und wenn die Seite (auf der das Login ist) geöffnet wird überprüfen, ob diese Id noch gültig ist und wenn nicht eine neue neue holen.

Kurz zum Hintergrund: Es handelt sich um eine React App die mit der SelectLine Api kommuniziert.

**Comment by Micha-Richter** [comment]
Ok, den Gedanken kann ich verstehen.

Zum Hintergrund: Die App ist eine interne Anwendung im lokalen Netzwerk, die ausschließlich von maximal 1 Person gleichzeitig ausgeführt wird? ;)

**Comment by MatthiasGuse** [comment]
Hallo,

ich bin da bei @Micha-Richter. Theoretisch kann die LoginID, direkt nachdem sie abgefragt wurde ungültig werden und damit der eigentliche Request in einen Fehler laufen. Damit ist es ja notwendig ein Fehlerhandling dafür zu schaffen.

Wenn man wirklich nur die Gültigkeit prüfen möchte, ist praktisch jede GET Route geeignet (bspw. GET/Users/Current). Ausnahme: GET/Info - die geht immer.

Grüße

**Comment by MatthiasGuse** [comment]
Falls das Thema noch aktuell ist, bitte wieder öffnen.

Viele Grüße
