### ISSUE TITLE
Kein Archiveintrag bei /Documents/{documentKey}/PrintPdf

### ISSUE THREAD

**Issue by burgt** [selectline-software/selectline-api#316]
Hallo,

ich habe das Problem das bei PrintPdf offenbar kein Archiveintrag erzeugt wird. Wenn ein falscher Eintrag in der Archivkonfiguration vorhanden ist, führt dies zwar zu einem Fehler in der API, aber bei korrektem Eintrag wird kein Archiveintrag hinterlegt. Es scheint auch keine Rolle zu spielen ob die Konfiguration aus der Druckvorlage selbst oder aus der übergeordneten Instanz der Druckvorlagen kommt.

Gruß,
Thorsten Burg

**Comment by MatthiasGuse** [comment]
Hallo,

auf welche Version bezieht sich Ihre Anfrage?

Evtl. ist das Problem bereits mit Version 22.3.3 bereits gelöst. Siehe #299.

Der Änderungstext lautet: "Die API-Route zum Erstellen eines Beleg-PDFs kann mit aktivierter Archivierung wieder erfolgreich aufgerufen werden."

Viele Grüße

**Comment by MatthiasGuse** [comment]
Falls das Thema noch aktuell ist, bitte wieder öffnen.

Viele Grüße
