### ISSUE TITLE
ExtraFields in Customers

### ISSUE THREAD

**Issue by Stiefel0001** [selectline-software/selectline-api#317]
Wir haben Extrafelder im Kunden.
Gibt es eine Entsprechung für die ExtraFields im Beleg, die auch in der Resource Customers funktioniert?

**Comment by MatthiasGuse** [comment]
Hallo,

leider nein. Bisher sind Extrafelder im Kunden nicht verfügbar. Wenn es nur um das Lesen geht, wäre die Nutzung von Makros in der API evtl. eine Alternative.

Viele Grüße

**Comment by MatthiasGuse** [comment]
Falls das Thema noch aktuell ist, bitte wieder öffnen.

Viele Grüße
