### ISSUE TITLE
Belegpositionen mit negativer Menge werden falsch verarbeitet

### ISSUE THREAD

**Issue by davidhommel** [selectline-software/selectline-api#319]
Hallo zusammen, 

wenn ich versuche über POST Documents/X/Articleitem eine Position mit negativer Menge (Feld CalculatedQuantityValue) zu erstellen. Wird die Position immer mit Menge 1 angelegt. 

Ist das ein Fehler? Wie kann ich per API z.B. auf einem Lieferschein eine Position mit negativer Menge anlegen, bspw. wenn der Kunde mir bei Auslieferung Leergut oder Ware zurückgibt?

**Comment by Micha-Richter** [comment]
Ist das evtl. #193 ?

**Comment by davidhommel** [comment]
> Ist das evtl. #193 ?

Sorry hatte mich beim Schreiben des Eintrags mit dem Feld vertan. Ich schreibe die Info in CalculatedQuantityValue.

**Comment by davidhommel** [comment]
Das zusätzliche Übergeben von Lagerinformationen ist mir in diesem Fall datentechnisch nicht möglich, da die Endanwendung ,,keine Ahnung" vom SelectLine Lager hat. Die betreffenden Artikel haben aber alle ein Standardlager und eine Lagerstrategie hinterlegt.

**Comment by MatthiasGuse** [comment]
Hallo,

bei einem lagernden Beleg sind die Lagerinformationen erforderlich. Siehe #314 - mit StoreInformation.

Viele Grüße

**Comment by MatthiasGuse** [comment]
Falls das Thema noch aktuell ist, bitte wieder öffnen.

Viele Grüße
