### ISSUE TITLE
400 - 20-039 when calling Characteristics, AccessoryDetails & SurchargeDetails on single article.

### ISSUE THREAD

**Issue by SKarema** [selectline-software/selectline-api#320]
Hi everyone!
I'm tried calling all endpoints described [here](https://demo.slmobile.de/demoApi/Help/ApiGroup?controllerName=Article). The ones mentioned below are throwing errors and the message doesn't really make sense to me.

FYI: I tried waiting up to 10 seconds between login and calling the endpoint and I tried calling other endpoints before and after the ones listed below, and those endpoints do not throw any errors.

Any ideas what I could try next?
___
### Details
- Current version number: 22.3.0
- Function or route (request): 
   - GET: /Articles/{articleNumber}/Characteristics
   - GET: /Articles/{articleNumber}/AccessoryDetails
   - GET: /Articles/{articleNumber}/SurchargeDetails

- Error (response):
> 400 - "{\r\n \"StatusCode\": \"BadRequest\",\r\n \"ResponseCode\": \"20-039\",\r\n \"ResponseId\": 39,\r\n \"ResponseIdDescription\": \"AppKeyInvalidException\",\r\n \"Message\": \"Der AppKey ist ungültig.\",\r\n \"Details\": \"The AppKey is not longer valid. Please log in again with a valid AppKey. \"\r\n}"
___
#### Steps to replicate the behaviour:
1. Authenticate using /Login
2. Call endpoint using token -> Error

**Comment by ThePholph** [comment]
Hi,

see at the Message in the Response. You have to send an AppKey with the Login Request. If you are a SelectLine Partner you can get the Appkey from Selectline or you are a customer you get an Appkey via your Selectline partner.

I hope, I could help you.

greetings 

Daniel

**Comment by SKarema** [comment]
Hi Daniel,

thanks for your answer.

Some of the requests work without an AppKey and some require an AppKey at login that gives this specific Access Token the right to access the requested resource?

Thanks again for your support.

Best

**Comment by MatthiasGuse** [comment]
Hello,

all Customers which buyed the SelectLine Toolbox until Version 19.2 can use a small set of API functions for free. All API functions where released from version 19.3, will need an AppKey.

To use the full functionality of the API, you will need an AppKey too. Please contact your SelectLine Partner to get more Informations about.

Best regards

**Comment by SKarema** [comment]
@MatthiasGuse thanks for your reply. It helped a lot.
