### ISSUE TITLE
500er bei POST auf /Prospects

### ISSUE THREAD

**Issue by timothy3001** [selectline-software/selectline-api#321]
### Details
- Current version number: SL mobile: 22.3.5 (SL WaWi 22.3.7)
- Previous version number (optional): 
- [x] Test status checked in Mobile Manager
- Function or route (request): `curl -X POST "https://vm-sl-tk/slmobileApi/Prospects" -H  "accept: application/json" -H  "xxx" -H  "Content-Type: application/json" -d "{  \"FirstName\": \"Timo2023\",  \"LastName\": \"TK2023\"}"`
- Error (response): 
```
{
  "StatusCode": "InternalServerError",
  "ResponseCode": "12-000",
  "ResponseId": 0,
  "ResponseIdDescription": "Undefined",
  "Message": "Das Ausführungstimeout ist abgelaufen. Der Timeoutzeitraum wurde überschritten, bevor der Vorgang beendet wurde, oder der Server antwortet nicht.",
  "Details": null
}
```

### Beschreibung

Wir haben momentan in unserer Testinstanz das Problem, dass wir keine Prospects mehr anlegen können. Dies ging vor ein paar Wochen noch, auf einmal geht es nicht mehr und wir werden mit der genannten Fehlermeldung begrüßt.

Ich vermute, dass etwas mit unserem System / Datenbank nicht in Ordnung ist und daher auch ein 500er Fehler kommt. Leider hilft uns die Fehlermeldung nicht wirklich weiter.

Könntet ihr mir kurz sagen ob und wie ich mehr Log-Infos bekomme? Evtl. mit TRACE-Log, sodass man die DB-Queries sieht und vielleciht den Timeout identifizieren kann?

Das Anlegen eines Prospects über die Warenwirtschaft ist noch problemlos möglich.

Den Backendmanager habe ich gecheckt, mehrfach neugestartet, auch den MSSQL und den ganzen Server. Außerdem habe ich zwischenzeitlich auch Updates / Reorganisationen gemacht. Der Mobile Manager zeigt alles grün.

#### Steps to replicate the behavior:

Prospect über die API anlegen.

**Comment by MatthiasGuse** [comment]
Hallo,

handelt es sich um eine reguläre Fachhandels- oder Kundenllizenz oder kommt hier eine Demo zum Einsatz? Bitte mal prüfen, was auf der Lizenzseite der Mobile Webseite angezeigt wird.

Falls es an der DB liegt, wäre ein Ansatz auf der Mandantendantenbank, sowie auf SL_Daten die Statistiken neu aufbauen. Dazu im Managementstudio auf der jeweiligen DB `EXEC sp_updatestats` ausführen. Je nach Datenumfang kann das etwas Zeit in Anspruch nehmen. 

Viele Grüße

**Comment by timothy3001** [comment]
Es ist keine Demolizenz, es handelt sich um eine Händlerlizenz. Ist bei uns aber nur als "Testsystem" bzw. Entwicklersystem aufgesetzt.

Offensichtlich lag es aber tatsächlich an den `MSSQL statistics`, nachdem ich die beiden Befehle ausgeführt habe, kann ich Prospects wieder anlegen.

Vielen Dank für die schnelle Hilfe!
