### ISSUE TITLE
Falsches Response Model für POST /Customers/{customerNumber}/ContactPersons

### ISSUE THREAD

**Issue by AM-Sartissohn** [selectline-software/selectline-api#324]
### Details
- Current version number: 22.3.3
- Previous version number (optional): 
- [x] Test status checked in Mobile Manager
- Function or route (request): POST /Customers/{customerNumber}/ContactPersons
- Error (response): Datenmodel Response in Swagger falsch angegeben

#### Steps to replicate the behavior:

Für die Route POST /Customers/{customerNumber}/ContactPersons gibt die Swagger-Definition als Response Model _CustomerCreated_ an - dies kann ja nicht korrekt sein und sollte vermutlich _CustomerContactPersonCreated_ o.ä. lauten - dieses Datenmodel ist aber in der SelectLine.API.json gar nicht enthalten.

Zum Vergleich:
POST /Suppliers/{supplierNumber}/ContactPersons hat Rückgabewert _SupplierContactPersonCreated_
POST /Prospects/{prospectNumber}/ContactPersons hat Rückgabewert _ProspectContactPersonCreated_

**Comment by MaikGoertz** [comment]
Vielen Dank für diesen Hinweis, die Doku wird mit der kommenden 23.1 korrigiert.
