### ISSUE TITLE
Timeout bei API-Makro-Ausführung

### ISSUE THREAD

**Issue by Micha-Richter** [selectline-software/selectline-api#325]
### Details
- Current version number: 22.3.5
- SQL Server 2019, Standard Edition
- Previous version number (optional): 
- [x] Test status checked in Mobile Manager
- Function or route (request): POST /slmobileapi/Macros/liesSperrzeitraum
- Error (response): 
```
data: {
     StatusCode: 'InternalServerError',
     ResponseCode: '70-000',
     ResponseId: 0,
     ResponseIdDescription: 'Undefined',
     Message: 'Das Ausführungstimeout ist abgelaufen. Der Timeoutzeitraum wurde überschritten, bevor der Vorgang beendet wurde, oder der Server antwortet nicht.\r\n' +
       'Die Anweisung wurde beendet.',
     Details: null
}
```

#### Steps to replicate the behavior:
Unbekannt. Das POST läuft wochenlang durch ohne Probleme, plötzlich wird einmalig der Fehler geworfen und zieht damit für ?? Minuten die ganze API in den Abgrund: auf das POST folgende (andere) API-Calls scheitern innerhalb eines bestimmten Zeitraums mit ResponseCode 42-000.

Das Makro selbst ist ein simples Select:
```
select Eintrag, Wert from inifiles
where IniFileName = 'MANDANT.INI' and Block = 'MANDANT' and Eintrag like 'FreiesDatum%'
```

Meine Frage lautet deshalb auch, was an dem Makro geändert werden kann, um Datenbank-Timeouts zu vermeiden? 
Verwendet die Wawi selbst vielleicht Datenbank-Locks, die zu dem Verhalten führen könnten? 
Kann ich das Makro umschreiben, um solche Sperren zu umgehen?

**Comment by MatthiasGuse** [comment]
Hallo Micha,

hast du zufällig die Logs zur Verfügung, die um den Fehler herum entstanden sind? Ich denke nicht, dass das was mit deinem Makro zu tun hat.

Grüße

**Comment by Micha-Richter** [comment]
Hallo Matthias,

welche Logs brauchst du, wo finde ich die und wo soll ich sie hinschicken?

**Comment by MatthiasGuse** [comment]
Hallo Micha,
die Logs sollten im Installationsverezeichnis oder unter C:\ProgramData unter ...\SelectLine Software\Mobile Anwendungen\Logs zu finden sein. Bitte nenne auch mal einen ungefähren Zeitpunkt dazu.
Hier bitte das ganze Verzeichnis zur Verfügung stellen und gepackt an den Support schicken. Einfach den Githubkontext nennen.

**Comment by Micha-Richter** [comment]
Hallo Matthias,

danke für deine Hilfe, hab die Logs gefunden.
Meine Neugier hat mich die dann durchsuchen lassen und letztlich zur Ursache geführt: der SQL Server ist aktualisiert und neugestartet worden.. 🙈
Sorry 🤷‍♂️
