### ISSUE TITLE
Can't add a line item in document when quantity is defined

### ISSUE THREAD

**Issue by ccfrusano** [selectline-software/selectline-api#326]
### Details
- Current version number: 22.3.1
- Previous version number (optional): 
- [x] Test status checked in Mobile Manager
- Function or route (request): POST slmobileApi/Documents/L400568015/ArticleItem
- Error (response): 
```
{
    "StatusCode": "InternalServerError",
    "ResponseCode": "42-000",
    "ResponseId": 0,
    "ResponseIdDescription": "Undefined",
    "Message": "Die Lagerungsmenge ist größer als der verfügbare Bestand.",
    "Details": {
        "SQLFehlerNr": "0",
        "SQLTmpID": "0",
        "ehlerNr": "102027",
        "ExtMessage": "",
        "ExceptionName": "ELagerungException"
    }
}
```
#### Steps to replicate the behavior:

To replicate it, I use the following parameters:
```{ 
  "ArticleNumber": "11535098",
    "UnitPrice": "2.99",
    "CalculatedQuantityValue": 2,
    "WarehouseId": "2",
    "StoreInformation": 
    [     {       
        "ArticleNumber": "11535098",
        "Warehouse": "2",       
        "Quantity": 2  
        }      
     ]    
}
```

On the other hand, when I pass quantity 0, it works:
```
{   "ArticleNumber": "11535098",
    "UnitPrice": "2.99",
    "CalculatedQuantityValue": 0,
    "WarehouseId": "2",
    "StoreInformation": 
    [     {       
        "ArticleNumber": "11535098",
        "Warehouse": "2",       
        "Quantity": 0
        }      
     ]    
}
```
![image](https://user-images.githubusercontent.com/106327327/232765852-86c39b06-1bc5-40b8-a525-37da7ac1c951.png)
Added with no quantity:
![image](https://user-images.githubusercontent.com/106327327/232765994-ee23e83a-8570-4c88-a4c3-30fa3ab377da.png)

Of course, I've checked the stock of the item, and there is:
![image](https://user-images.githubusercontent.com/106327327/232766124-a10ebe29-ca15-4e3e-85c7-2e18d0c514fb.png)

I don't get why this is not working.
Thanks
Carlos

**Comment by MatthiasGuse** [comment]
Hello,

please remove Line 4 "WarehouseID" in your request body. This is not needed in this case.
Also check the value for "Warehouse" in Line 8. This should be your own storagenumber.
![grafik](https://user-images.githubusercontent.com/31447000/233258503-5468808f-4099-4f0b-ae38-87844a4a83f8.png)

Best regards

**Comment by ThePholph** [comment]
Hi,

have you checked the settings in the tenant? Because you can set the option, that no Article can be added to Delivery Note if you do not have stock for the item.

Greetings 

Daniel

**Comment by MatthiasGuse** [comment]
Please check the settings of the stock:
![grafik](https://user-images.githubusercontent.com/31447000/234889769-6c465d0f-9e36-47ae-b9a5-b1a761dcfff8.png)
If the first checkbox is set, i can confirm the behavior.
