### ISSUE TITLE
PriceQuantityUnit klappt nicht

### ISSUE THREAD

**Issue by Logic-Bits** [selectline-software/selectline-api#329]
### Details
- Current version number: 23.1.0
- Previous version number (optional): 
- [x] Test status checked in Mobile Manager
- Function or route (request):  {{url}}/Documents/FANF230287/ArticleItem
- Error (response):

Hallo,

{
  "ArticleNumber": "100001",
  "UnitPrice": 4.05,
  "CalculatedQuantityValue": 100,
  "PriceQuantityUnit": 10 
}

gibt es einen Trick damit man die Preiseinheit setzen kann?

![grafik](https://user-images.githubusercontent.com/2421123/235166963-9132a906-8ea5-48f8-b794-bd8d61e071ef.png)

Vielen Dank

**Comment by MatthiasGuse** [comment]
Hallo,

das gesuchte Element heißt "PriceUnitFactor".

Viele Grüße
