### ISSUE TITLE
Kopf/Fußtext

### ISSUE THREAD

**Issue by Lars-Mue** [selectline-software/selectline-api#33]
Hallo,

es ist aktuell nicht möglich, beim erstellen eines Belegs Kopf & Fußtext einzutragen, ist das korrekt?
Über eine schnelle Antwort würde ich mich freuen

Grüße

**Comment by SteveSteglitz** [comment]
Hallo, 
derzeit ist es nicht möglich beim Anlegen oder Bearbeiten eines Beleges den Kopf- oder Fußtext anzugeben. Es befindet sich bereits ein Wunsch dazu im UserVoice Forum. Ob und wann diese Funktionalität unserseits eingeplant und umgesetzt wird, können wir nicht sagen. 

Viele Grüße
Steve
