### ISSUE TITLE
Create Manual Storage with custom document number

### ISSUE THREAD

**Issue by chucky2002** [selectline-software/selectline-api#330]
### Details
- Current version number: 23.1
- Previous version number (optional): 22.3
- [X] Test status checked in Mobile Manager
- Function or route (request): POST ManualStorages

In the change information for SelectLine 23.1 it was stated that the API now supports the creation of manual warehouses with specification of the document number. I cannot find this route in the documentation. 

Question: How can I create manual storage with default document number in SelectLine 23.1?

**Comment by MaikGoertz** [comment]
You can create a manual storage by using POST /ManualStorages and send the property "Number" with body content.
Check out the documentation
https://demo.slmobile.de/demoApi/Help/Api/POST-ManualStorages

**Comment by chucky2002** [comment]
It works. Thank you for fast answer
