### ISSUE TITLE
POST/Documents/{documentKey}/Successors does not transfer the document

### ISSUE THREAD

**Issue by ccfrusano** [selectline-software/selectline-api#333]
### Details
- Current version number: 23.1
- [x] Test status checked in Mobile Manager
- Function or route (request): /Documents/{documentKey}/Successors
- Error (response): 
{
    "DocumentKey": "L",
    "DocumentKind": "L",
    "documentKind": "L",
    "DocumentNumber": "",
    "documentNumber": ""
}
#### Steps to replicate the behavior:
The problem is that I get "Status: 201 - Created", but there's no document transfered nor created.
If I pass the "Positions" parameter as an empty array, I expect that the document gets transfered with the article items as 0 in the quantity:
![image](https://github.com/selectline-software/selectline-api/assets/106327327/62979317-3e86-4629-ba42-27c5717917b8)
Instead, there's no transfer.

If I pass the Positions array filled, I get another error:
![image](https://github.com/selectline-software/selectline-api/assets/106327327/5795c7ba-be3b-40a5-9700-5c19f9c45292)

I can manually transfer the document to a delivery note without any problem.
Does anybody know why this happens? I can, of course, login and get documents without any problem.
I can provide more details if needed.
Best,

**Comment by MatthiasGuse** [comment]
Hi,

i have no idea, why you get an empty document number.

You can try an other way:

- create an empty deliverynote by using POST /Documents
- transfer the positions by uising PUT /Documents/{destinationDocumentKey}/Predecessors/{sourceDocumentKey}

Regards

**Comment by ccfrusano** [comment]
Hi,
After some trial and error testing, we've noticed that it works only with those parameters:

`{
  "DocumentKindDestination": "L",
  "Positions":[
    {
     "ArticleNumber": "4260137743126de-DE",  
        "Identifier": "08bef183-412d-48d0-8fc9-962669089f2e",
        "Quantity":1.0

    },
    {
     "ArticleNumber": "SET0000750015",  
        "Identifier": "d7deb05a-1304-49d7-81af-dbc68ccf2bda",
        "Quantity":1.0

    }
]
}`

So, now it works.
I'm gonna close the issue.
Thanks.
Carlos
