### ISSUE TITLE
PUT /Documents/{documentKey} Response State-Code is undocumented

### ISSUE THREAD

**Issue by heba-datensysteme** [selectline-software/selectline-api#335]
### Details
- Current version number: 23.1.0 und 22.3.7
- Previous version number (optional): 
- [ ] Test status checked in Mobile Manager
- Function or route (request): PUT: /Documents/{documentKey}
- Error (response): 200 Undocumented

#### Steps to replicate the behavior:

The Response State-Code from this route is not documented in Swagger !

in Swagger documentation, the successful response code for function (PUT: /Documents/{documentKey}) is 204 without Content.
But practically, the successful response code for this function is 200 with Content.
That cause a problem because of undocumented Response State-Code

![Api Undocumented response](https://github.com/selectline-software/selectline-api/assets/64256667/4b80f5ec-51cd-4ae2-91d9-3a3801bc4550)

**Comment by MatthiasGuse** [comment]
Hello,

we've added the behavior to fix it.

Best Regards

**Comment by SophiaWeise** [comment]
Hello, 

the problem will be fixed in the upcoming version 23.2.0.

Regards, 
Sophia Weise
