### ISSUE TITLE
PHP-Beispiel geht nicht, wenn man auf eigene Installation der API (HTTPS) umstellt

### ISSUE THREAD

**Issue by sichert** [selectline-software/selectline-api#34]
PHP-Beispiel geht nicht, wenn man auf eigene Installation der API (da ab 20.x nur noch HTTPS möglich) umstellt.

(Dirty) Fix ist möglich in der index.php mit:

47    curl_setopt($curl, CURLOPT_URL, $url);
48    curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);

hier ergänzen um (jedoch unsicher!):

49	curl_setopt($curl, CURLOPT_SSL_VERIFYHOST, 0);
50	curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, 0);

Bitte beachten: https://stackoverflow.com/questions/56176718/scraping-with-client-certificate-request-with-php-and-curl

Bitte im Code vermerken/ ändern.
Danke!

P.S.:
Ich kann auch gerne einen Pull senden, sehe aber, dass diese aktuell wohl recht vernachlässigt werden.

**Comment by SteveSteglitz** [comment]
Hallo,
danke für den Hinweis! Wir werden das Beispiel entsprechend aktualisieren. 
Wie bei den anderen Beispielen auch, dienen diese lediglich zum beispielhaften Ausprobieren der SelectLine REST API. Natürlich sollten in Produktivumgebungen immer mit Zertifikaten gearbeitet werden. So kommunizieren wir dies auch immer auf den API Schulungen. 
Danke!
Viele Grüße
Steve
