### ISSUE TITLE
Druck mit dem Druckziel Email nicht möglich wenn der ERechnungstyp XRechnung ist

### ISSUE THREAD

**Issue by cv-prod-github** [selectline-software/selectline-api#340]
### Details
- Current version number: Dateiversion: 23.1.2 Build 867028
- Previous version number (optional): 
- [X ] Test status checked in Mobile Manager
- Function or route (request): Post [/Documents/{documentKey}/Print]
- Error (response):
```
{
  "StatusCode": "BadRequest",
  "ResponseCode": "42-076",
  "ResponseId": 76,
  "ResponseIdDescription": "PrintDocumentEmailException",
  "Message": "Beim Belegdruck mit dem Druckziel Email ist ein Fehler aufgetreten.",
  "Details": {
    "AdditionalInformation": "Es wurde kein Empfänger angegeben."
  }
}
```

#### Steps to replicate the behavior:
Lege einen Kunden an mit einer Rechnungsemailadresse vom Typ XRechnung.
Versuche über die API diesen zu versenden.

**Comment by MatthiasGuse** [comment]
Hallo,

funktioniert es denn mit einem anderen E-Rechnungstypen?
Wird die Rechnung in der Warenwirtschaft ohne Anziege des E-Mail-Fensters automatisch versendet?

Grüße

**Comment by cv-prod-github** [comment]
Hallo,

ja, alle anderen Rechnungen mit PDF E-Mail als ERechnungstyp werden normal versendet.

Im Programm wird das CRM Modul mit den Einstellungen Sofortversenden benutzt.
Ob hier noch ein Fenster aufgeht beim manuellen Versenden kann ich gerade nicht prüfen, werde aber den Kunden dazu befragen und Ihn bitten darauf zu achten.

Eine weitere Information die ich heute gesehen/bekommen habe ist, das im Druckprotokoll bei manuellem Druck->Ziel(Email) mit dem XRechnungstypen kein Formular im Druckprotokoll angezeigt wird.
Das ist aufgefallen weil ich vor der API immer prüfe ob eine Rechnung eine ERechnungsemailadresse hat und ob diese bereits mit dem Formular der Rechnung durch den Rechnungsdruck mit dem Ziel Email gegangen ist.

Grüße

**Comment by MatthiasGuse** [comment]
Ah ok. Das ist der Hinweis. Das kann nicht funktionieren. Die Print Route bezieht sich auf die Belegausgabe mit einem Formular. Nur in dem Formular können Sie die E-Mail vorbelegen. Da XRechnung kein Formular nutzt und nur eine XML Datei erstellt, schließt sich diese Funktionalität hier von selbst aus. Demzufolge würde ich erwarten, dass auch immer der E-Mail Dialog aufgeht.

Zusammengefasst: XRechnung per API per Mail versenden so nicht möglich.
Evtl. kann ja auf ZUGFeRD zurückgegriffen werden.

**Comment by cv-prod-github** [comment]
Hallo Herr Guse,

gibt es eine andere Möglichkeit an die XRechnung per API zu kommen und diese zu versenden?

Grüße
