### ISSUE TITLE
TotalPrice / Gesamtpreis wird nicht in Position richtig übernommen

### ISSUE THREAD

**Issue by Logic-Bits** [selectline-software/selectline-api#341]
### Details
- Current version number: 23.1.1
- Previous version number (optional): 
- [ ] Test status checked in Mobile Manager
- Function or route (request): 
- Error (response):

Hallo,

leider kommt nicht das raus, was man eingibt:

![grafik](https://github.com/selectline-software/selectline-api/assets/2421123/516e162f-f155-4469-a2ce-be181edd77a1)

siehe Summe:

![grafik](https://github.com/selectline-software/selectline-api/assets/2421123/8b6b1251-385a-4f62-bb56-9fbbf349210f)

Hier Artikelinfo:

![grafik](https://github.com/selectline-software/selectline-api/assets/2421123/4926ac64-4733-44f6-80ec-39932311c903)

Ist leider bei COM und API der Fall...

**Comment by MatthiasGuse** [comment]
Hallo,

das scheint durch die Verwendung von nur zwei Nachkommastellen im Beleg zustande zu kommen. Mein Vorschlag wäre den Einzelpreis anstelle des Gesamtpreises zu füllen.

Grüße

**Comment by Logic-Bits** [comment]
Hallo,

sind Sie sich da sicher?

![grafik](https://github.com/selectline-software/selectline-api/assets/2421123/00162203-e2d7-4d7a-ab7a-db0bb144378f)
![grafik](https://github.com/selectline-software/selectline-api/assets/2421123/8b7c768c-d75e-4fcc-8aa5-5650ab3c0970)
![grafik](https://github.com/selectline-software/selectline-api/assets/2421123/80c8b1a0-988b-4d0f-ad6f-d5014996310f)

ich kann nicht meh Nachkommastellen einstellen.

**Comment by MatthiasGuse** [comment]
In Ihrem oben geziegten Sreenshot waren nur zwei Nachkommastellen angezeigt. Wenn Sie die Einstellung nachträglich geändert haben, muss das Backend neu gestartet werden, damit die Änderung per API Anwendung findet.

**Comment by Logic-Bits** [comment]
AH ok, gibt das für alle Mandanteneinstellungen?

**Comment by MatthiasGuse** [comment]
Ja, das betrifft so ziemlich jede Mandanten oder Belegeinstellung. Alle Clients lesen die Einstellungen nach der Anmeldung ein.
