### ISSUE TITLE
Error POST ./Macros | 23.1.0

### ISSUE THREAD

**Issue by ThePholph** [selectline-software/selectline-api#342]
### Details
- Current version number: 23.1.1
- Previous version number (optional): 22.3.3
- [X ] Test status checked in Mobile Manager
- Function or route (request): ./Macros
- Error (response): "Der Typ des Makros wird derzeit nicht unterstützt."

Ausführen von Programmfunktionen, im Beispiel "Beleg: Preisneuberechnung".
Wurde von Anfang an unterstützt und ab Version 23.1.0 bekommen wir den Fehler.

Problem ist, dass es bei mehreren Kunden-Installationen zum Einsatz kommt.

Vermutung liegt nahe, dass es an folgender Änderung liegt:

"Es wird eine korrekte Fehlermeldung beim Ausführen eines Nicht-Abfrage-Makros über die API ausgegeben. [GitHub #283](https://github.com/selectline-software/selectline-api/issues/283)"

Die Programmfunktion wurden bisher jedoch korrekt und ohne Probleme ausgeführt! Wie können wir hier verfahren?

Vielen Dank.

#### Steps to replicate the behavior:

POST ./Macros
```
{
	"MacroName": "TBXxx001",
	"Parameters": [
		{
			"Name": "belegTyp",
			"Value": "0"
		},
		{
			"Name": "belegNummerVon",
			"Value": "1913279"
		},
		{
			"Name": "belegNummerBis",
			"Value": "1913279"
		},
		{
			"Name": "hauptArtikel",
			"Value": "1"
		},
		{
			"Name": "rabatt100aktualisieren",
			"Value": "1"
		},
		{
			"Name": "steuer",
			"Value": "1"
		},
		{
			"Name": "fibuKonto",
			"Value": "1"
		},
		{
			"Name": "gedruckt",
			"Value": "1"
		},
		{
			"Name": "fehlerAnzeige",
			"Value": "0"
		}
	]
}
```

**Comment by MatthiasGuse** [comment]
Hallo,

das kann ich so bestätigen. Ich muss das intern klären und melde mich dann dazu.

Grüße

**Comment by MatthiasGuse** [comment]
Die genannte Route ist ausschließlich dafür vorgesehen Makros vom Typ "Abfrage" auszuführen.

Viele Grüße
