### ISSUE TITLE
Stammdatenanlage 

### ISSUE THREAD

**Issue by rudolf-hi** [selectline-software/selectline-api#344]
Hallo,
unser Kunde fragt, ob es möglich ist per API
•	Artikel
•	Erlöskonten
•	Erlöskontengruppen
•	Steuerschlüssel
•	Steuerschlüsselpositionen
anzulegen?
Viele Grüße
Rudolf Höhner

**Comment by MatthiasGuse** [comment]
Hallo,

das ist bisher nicht möglich. Sie können gerne einen Wunsch dazu in unserem Wünscheforum platzieren.

In der Hilfe der API sind alle Funktionen beschrieben: [Link](https://github.com/selectline-software/selectline-api/wiki/API-Online-Hilfe)

Viele Grüße
