### ISSUE TITLE
Beleganlage über Postman gemäß Beispiel bringt Fehlermeldung

### ISSUE THREAD

**Issue by sichert** [selectline-software/selectline-api#35]
Beleganlage über Postman gemäß Beispiel bringt Fehlermeldung "The AppKey is not longer valid. Please log in again with a valid AppKey. "
Mehrfaches vorheriges unmittelbares Einloggen ist wirkungslos. Die Abfrage z.B. der Artikel mit dem selben Token geht aber problemlos.

Siehe Screenshot:

![image](https://user-images.githubusercontent.com/13850309/89298790-18d76900-d666-11ea-952a-bfeeb0fdb137.png)

**Comment by SteveSteglitz** [comment]
Hallo, 
bitte prüfen Sie noch einmal, ob Sie einen gültigen AppKey beim Login mitgeben. Die Route für Belege funktioniert nur mit gültigem AppKey. Die Route mit Artikel z.B. läuft auch mit einer früheren Toolbox-Lizenz (Gold glaub ich). 

Viele Grüße
Steve

**Comment by sichert** [comment]
Der AppKey wird mitgegeben. Siehe die Routine in Git, die ich unverändert teste.
![image](https://user-images.githubusercontent.com/13850309/89301734-4a523380-d66a-11ea-8ce1-7824df1ec7ea.png)

**Comment by SteveSteglitz** [comment]
Was meinen Sie mit die "Routine in Git", die Sie unverändert testen?
Ich habe gerade mit Postman ein POST auf Documents ausprobiert und zuvor das Login mit den DEMO Zugangsdaten (https://github.com/selectline-software/selectline-api) vorgenommen, mit Erfolg.

Viele Grüße
Steve

**Comment by sichert** [comment]
Hallo Steve,

ich führe {{url}}/Login aus und erhalte dann als Response 
{
  "AccessToken": "21b3f91a-d674-4a8c-98bc-a0661d63433e",
  "TokenType": "LoginId"
},
anschließend gehe ich in {{url}}/Documents, erhalte dann aber
{
  "StatusCode": "BadRequest",
  "ResponseCode": "42-039",
  "Message": "AppKeyInvalidException",
  "Details": "The AppKey is not longer valid. Please log in again with a valid AppKey. "
}
In meinem Body steht:
{
	"KindFlag": "F",
	"BusinessPartner":
		{
			"Address":
			{
			"Number": "10033"
			}
		}
}

und in meinen Headers steht:
![image](https://user-images.githubusercontent.com/13850309/89394274-27785b80-d70c-11ea-870c-7a9950e33915.png)

Meine Umgebung ist:
![image](https://user-images.githubusercontent.com/13850309/89394346-44149380-d70c-11ea-9b3e-83b6203bb1da.png)

Habe ich hier ein Verständnisproblem?
Wie gesagt, bei {{url}}/Articles funktioniert es aber.

Danke & Gruß,
Harald

**Comment by sichert** [comment]
Übrigens: 
In meinem Python-Code, den ich auch gerne zur Verfügung stelle, funktioniert es:
![image](https://user-images.githubusercontent.com/13850309/89396682-2563cc00-d70f-11ea-8831-f8dd40b6fc5a.png)

Kann es eine Fehlbedienung bzw. Fehler in Postman sein? Haben Sie eine Idee?

Danke & Gruß,
Harald

**Comment by SteveSteglitz** [comment]
Sie setzten beim Login den Appkey gar nicht. Dieser muss im Post vom Login angegeben werden. Wenn Sie die Postman-Collection verwenden sollte auch eine Abfrage "Login with AppKey" vorhanden sein.  In Ihrer Python-Umgebung werden Sie vermutlich das Login mit dem AppKey durchführen, weshalb es dann auch funktioniert.

Viele Grüße
Steve

**Comment by sichert** [comment]
Bingo!
Ich muss aufrufen "Login with AppKey", nicht "Login". Dann klappt es auch.
Tipp: Entfernen Sie das Beispiel nur mit "Login", da gibt ja gar keinen Sinn und dlässt andere auch nur in ein Fettnäpfchen treten.
Ja, in Python setze ich den AppKey natürlich.

Issue kann geschlossen werden, Danke!

**Comment by SteveSteglitz** [comment]
Es gibt noch alte Lizenzkonstellation die einen beschränktem Funktionsumfang haben ohne für die kein App-Key notwendig ist. Daher werden wir weiterhin beide Varianten in der Collection zur Verfügung stellen.
