### ISSUE TITLE
Mobile API LoginKind Enum

### ISSUE THREAD

**Issue by Torchok19081986** [selectline-software/selectline-api#351]
### Details
- Current version number:  23.1.6
- Previous version number (optional):  22.3.8

####

Nach dem Update auf die Version 23.1.6 von Mobile Mananger und Einspielen von neuen IO.Swagger.dll Mobile API LoginKind Enum : 
MobileAPI, Bde usw.  existieren nicht mehr in Bibliothek. Ist das gewollt oder warum wurde es aus der Classe entfernt ?

In der Version 22.3.8 von Mobile API in Manager war es noch enthalten.  

```csharp

SelectLineErpAdministrationModuleModelsCredentials.LoginKindEnum.MobileApi //existiert nicht mehr in der Version 23.1.6.

```

**Comment by MaikGoertz** [comment]
Hallo.
Dieser Parameter war schon immer optional und wird für die Anmeldung nicht benötigt. Aus diesem Grund ist auch das Enum nicht mehr in der Dokumentation enthalten.

Gruß
Maik
