### ISSUE TITLE
POST und PUT für Article

### ISSUE THREAD

**Issue by Bitlanech** [selectline-software/selectline-api#352]
Aktuell kann SelectLine API nur Artikeldaten lesen. 
Es wäre sehr praktisch, wenn der Artikelendpunkt um POST erweitert wird, damit Artikel angelegt werden können, bzw. mit PUT angepasst werden können.

Beste Grüsse

**Comment by MatthiasGuse** [comment]
Hallo,

dieser Wunsch ist bereits in unserem Wünscheforum erfasst. Daher schließe ich diesen Issue.
Aktuell ist eine Umsetzung noch nicht absehbar.

Danke für Ihre Beteiligung.

Viele Grüsse
