### ISSUE TITLE
ExtraTable POST/PUT: how to specify null / empty value?

### ISSUE THREAD

**Issue by capc0** [selectline-software/selectline-api#353]
### Details
- Current version number:  23.1.1 Build 858419
- Function or route (request): `POST /ExtraTable`
- Error (response): `Die parametrisierte Abfrage (...) erwartet den @param_KUNDE-Parameter, der nicht bereitgestellt wurde.`

#### Steps to replicate the behavior:

POST mit Body

```json
{
    "Fields": {
        "_TEXT": "Test",
        "_KUNDE": null
    }
}
```

---

How can I specify an empty value (`null`)?
When I omit the field, it will be saved as empty/null, however when there already is a current value and I want to overwrite it with an empty value, I cannot do that. An empty `""` string kinda works, but is different than `null`.

**Comment by MatthiasGuse** [comment]
Hello,

it ist not possible to set an value to `NULL` by the API. In our applications, we do not make differences between empty `""` and `NULL`. That shouldn't be relevant. 

Regards

**Comment by capc0** [comment]
thanks for the info
