### ISSUE TITLE
Printed status NOT set to 1 when printing an invoice

### ISSUE THREAD

**Issue by ccfrusano** [selectline-software/selectline-api#354]
### Details
- Current version number: 23.1.6 9 Build 910889
- Previous version number (optional): 
- [x] Test status checked in Mobile Manager
- Function or route (request): POST Documents/R24280846/Print
- Error (response): 204 - No content

#### Steps to replicate the behavior:
-The issue is that when printing an invoice, the status of "Printed" is still set to 0. So, it does not change to 1, eventhough the invoice gets actually printed correctly. It only happens with invoices. With packing slips or delivery notes, everything works perfect.

Json body request: 
`{"NumberOfCopies":1,
"MasterName":"FRUSANO_ES",
"PrintTarget":"Printer"
}`

Does anybody have the same problem?

Thanks

**Comment by MatthiasGuse** [comment]
Hello,

from our side it works correctly. Maybe you use the Document processing status for the invoice. In this case the status must be "completed", to set the print status correctly.

Regards

**Comment by ccfrusano** [comment]
Hello Mathias,

From our side, this option is disabled:

![image](https://github.com/selectline-software/selectline-api/assets/106327327/62b5b5b8-3bc7-4296-97e3-9729fbe65776)

Is there any other possible thing causing this issue?
Best,
Carlos
