### ISSUE TITLE
Die Änderungen am Models für Login, Customer und Supplier in der Swagger Beschreibung 23.2

### ISSUE THREAD

**Issue by Torchok19081986** [selectline-software/selectline-api#357]
Hallo, wir haben nun unseren Testsystem auf die Version 23.2 aktualisiert und nun versuchen wir die Änderungen im Mobile API nachzuvollziehen. 
Aufgefallen ist, dass o.g. Models keine Model beim Abrufen von Methoden / Funktionen zurückgeben, sondern die geben "void" zurück, als Beispiel LoginModel, diese gab bis zu dieser Version, AccessTokenModel. 

Welche Methode soll ich nun verwenden , um z.B. die AccessTokenModel als Response zu bekommen ? Die Erweiterungsmethoden mit Async und mit AsyncHttpInfo geben zwar Task<ApiResponse<object>> zurück, aber ich habe diese nie verwendet, da es bis heute keine Notwendigkeit bestand.

**Comment by MaikGoertz** [comment]
Moin.

Hierbei handelt es sich um einen Fehler in der Dokumentation.
Wir werden diesen Fehler im nächsten Hotfix korrigieren.

**Comment by Torchok19081986** [comment]
Morgen, Vielen Dank für die Info. Ich habe auch unsere Programm mit Task<ApiResonse<object>> soweit hinbekommen. Die Data Property muss ins passenden Object Convertiert werden. 

Darf ich es so behalten, weil ich nicht gewusst habe, ob es Bug ist oder wurde es absichtlich soweit verändert.

**Comment by MaikGoertz** [comment]
Funktionieren wird die Anpassungen. Das ist genau das was der generierte Code intern macht.
Falls es doch mal Anpassungen geben wird, bekommt der manuelle geschriebene Quellcode jedoch nichts mit davon.
Meine Empfehlung ist es auf die Korrektur der 23.2.1 zu warten und danach den Quellcode neu zu generieren.

**Comment by Torchok19081986** [comment]
Vielen Dank für die Info. Dann muss ich wohl danach noch mal Programm anpassen, da ich nächste Woche Programm update und 23.2 auf dem Produktivsystem aufspielen muss. 🤨🤨🤨🤨

**Comment by Torchok19081986** [comment]
Morgen, ich würde gern wissen, ob es einen ungefähre Datum für 23.2.1 gibt. Erscheint es noch in diesem Jahr oder wird es auch 2024 verschoben  ?

**Comment by MaikGoertz** [comment]
Moin.
Die 23.2.1 ist heute veröffentlich worden.

**Comment by Torchok19081986** [comment]
Ok. Vielen Dank für die Info. Ich teste die neue Swagger API Description und würde mich dann melden.
