### ISSUE TITLE
Übertrag von Artikel Kalkulation Schemata

### ISSUE THREAD

**Issue by Torchok19081986** [selectline-software/selectline-api#359]
Morgen, ich versuche gerade die Article Daten via Macro zu übertragen. Da Artikel aus mehreren Teilen besteht, muss man die Daten für die Vollständigkeit auch mitübertragen. 
Ich habe gerade festgestellt, dass die Article Kalkulation Schemata nicht in der API vorhanden ist. Gibt es die Möglichkeit diese zu übertragen und was muss man dabei beachten ? 

### Details
- Current version number:  23.2.1
- Previous version number (optional):  22.3
- Function or route (request):  Article via Macro übertragen und auch die Daten aus ARKALK

**Comment by MatthiasGuse** [comment]
Hallo,

hier können wir Ihnen leider keine Unterstützung liefern, da es sehr viele Abhängigkeiten gibt. Für das Anlegen von Artikeln per API gibt es bereits einen Wunsch in unserem Wünscheforum, den Sie gerne unterstützen können.

Viele Grüße
