### ISSUE TITLE
Request-Beispiel fehlerhaft: https://demo.slmobile.de/demoApi/Help/Api/POST-Documents; Pflichtfelder?

### ISSUE THREAD

**Issue by sichert** [selectline-software/selectline-api#36]
Das Request-Beispiel in https://demo.slmobile.de/demoApi/Help/Api/POST-Documents ist fehlerhaft und wirft folgende, mehrfache, Fehler zurück:

{'Details': {'document.AlternativeWirCurrencyKind': ['Das Feld '
                                                     '"AlternativeWirCurrencyKind" '
                                                     'muss eine Zeichenfolge '
                                                     'mit einer maximalen '
                                                     'Länge von 1 sein.'],
             'document.AssociationRegulatorNumber': ['Das Feld '
                                                     '"AssociationRegulatorNumber" '
                                                     'muss eine Zeichenfolge '
                                                     'mit einer maximalen '
                                                     'Länge von 10 sein.'],
             'document.BillingAddress': ['Das Feld "BillingAddress" muss eine '
                                         'Zeichenfolge mit einer maximalen '
                                         'Länge von 13 sein.'],
             'document.BusinessPartner.Address.CountryId': ['Das Feld '
                                                            '"CountryId" muss '
                                                            'eine Zeichenfolge '
                                                            'mit einer '
                                                            'maximalen Länge '
                                                            'von 6 sein.'],
             'document.BusinessPartner.Address.Number': ['Das Feld "Number" '
                                                         'muss eine '
                                                         'Zeichenfolge mit '
                                                         'einer maximalen '
                                                         'Länge von 13 sein.'],
             'document.BusinessPartner.Address.ZipCode': ['Das Feld "ZipCode" '
                                                          'muss eine '
                                                          'Zeichenfolge mit '
                                                          'einer maximalen '
                                                          'Länge von 10 sein.'],
             'document.BusinessPartner.ReferenceAddressNumber': ['Das Feld '
                                                                 '"ReferenceAddressNumber" '
                                                                 'muss eine '
                                                                 'Zeichenfolge '
                                                                 'mit einer '
                                                                 'maximalen '
                                                                 'Länge von 13 '
                                                                 'sein.'],
             'document.CurrencyCode': ['Das Feld "CurrencyCode" muss eine '
                                       'Zeichenfolge mit einer maximalen Länge '
                                       'von 3 sein.'],
             'document.DeliveryAddress.Address.CountryFlag': ['Das Feld '
                                                              '"CountryFlag" '
                                                              'muss eine '
                                                              'Zeichenfolge '
                                                              'mit einer '
                                                              'maximalen Länge '
                                                              'von 6 sein.'],
             'document.DeliveryAddress.Address.ZipCode': ['Das Feld "ZipCode" '
                                                          'muss eine '
                                                          'Zeichenfolge mit '
                                                          'einer maximalen '
                                                          'Länge von 10 sein.'],
             'document.DeliveryAddress.PostOfficeBox.CountryId': ['Das Feld '
                                                                  '"CountryId" '
                                                                  'muss eine '
                                                                  'Zeichenfolge '
                                                                  'mit einer '
                                                                  'maximalen '
                                                                  'Länge von 6 '
                                                                  'sein.'],
             'document.DeliveryAddress.PostOfficeBox.ZipCode': ['Das Feld '
                                                                '"ZipCode" '
                                                                'muss eine '
                                                                'Zeichenfolge '
                                                                'mit einer '
                                                                'maximalen '
                                                                'Länge von 10 '
                                                                'sein.'],
             'document.DeliveryTermNumber': ['Das Feld "DeliveryTermNumber" '
                                             'muss eine Zeichenfolge mit einer '
                                             'maximalen Länge von 6 sein.'],
             'document.DiscountGroupNumber': ['Das Feld "DiscountGroupNumber" '
                                              'muss eine Zeichenfolge mit '
                                              'einer maximalen Länge von 6 '
                                              'sein.'],
             'document.EdiStatusKind': ['Das Feld "EdiStatusKind" muss eine '
                                        'Zeichenfolge mit einer maximalen '
                                        'Länge von 1 sein.'],
             'document.EmployeeNumber': ['Das Feld "EmployeeNumber" muss eine '
                                         'Zeichenfolge mit einer maximalen '
                                         'Länge von 6 sein.'],
             'document.EuropeanCountryCode': ['Das Feld "EuropeanCountryCode" '
                                              'muss eine Zeichenfolge mit '
                                              'einer maximalen Länge von 2 '
                                              'sein.'],
             'document.KindFlag': ['Das Feld "KindFlag" muss eine Zeichenfolge '
                                   'mit einer maximalen Länge von 1 sein.'],
             'document.LanguageCode': ['Das Feld "LanguageCode" muss eine '
                                       'Zeichenfolge mit einer maximalen Länge '
                                       'von 6 sein.'],
             'document.Number': ['Das Feld "Number" muss eine Zeichenfolge mit '
                                 'einer maximalen Länge von 10 sein.'],
             'document.Payment.BankAccount': ['Das Feld "BankAccount" muss '
                                              'eine Zeichenfolge mit einer '
                                              'maximalen Länge von 2 sein.'],
             'document.Payment.BankAccountGroup': ['Das Feld '
                                                   '"BankAccountGroup" muss '
                                                   'eine Zeichenfolge mit '
                                                   'einer maximalen Länge von '
                                                   '6 sein.'],
             'document.Payment.CostCenterNumber': ['Das Feld '
                                                   '"CostCenterNumber" muss '
                                                   'eine Zeichenfolge mit '
                                                   'einer maximalen Länge von '
                                                   '15 sein.'],
             'document.Payment.FinancialAccountClause': ['Das Feld '
                                                         '"FinancialAccountClause" '
                                                         'muss eine '
                                                         'Zeichenfolge mit '
                                                         'einer maximalen '
                                                         'Länge von 15 sein.'],
             'document.Payment.FinancialAccountNumber': ['Das Feld '
                                                         '"FinancialAccountNumber" '
                                                         'muss eine '
                                                         'Zeichenfolge mit '
                                                         'einer maximalen '
                                                         'Länge von 15 sein.'],
             'document.Payment.PaymentTerm': ['Das Feld "PaymentTerm" muss '
                                              'eine Zeichenfolge mit einer '
                                              'maximalen Länge von 2 sein.'],
             'document.PriceGroupNumber': ['Das Feld "PriceGroupNumber" muss '
                                           'eine Zeichenfolge mit einer '
                                           'maximalen Länge von 1 sein.'],
             'document.PriceKindFlag': ['Das Feld "PriceKindFlag" muss eine '
                                        'Zeichenfolge mit einer maximalen '
                                        'Länge von 1 sein.'],
             'document.ReportCountryCode': ['Das Feld "ReportCountryCode" muss '
                                            'eine Zeichenfolge mit einer '
                                            'maximalen Länge von 2 sein.'],
             'document.ReturnMerchandiseAuthorizationNumber': ['Das Feld '
                                                               '"ReturnMerchandiseAuthorizationNumber" '
                                                               'muss eine '
                                                               'Zeichenfolge '
                                                               'mit einer '
                                                               'maximalen '
                                                               'Länge von 10 '
                                                               'sein.'],
             'document.SalesmanNumber': ['Das Feld "SalesmanNumber" muss eine '
                                         'Zeichenfolge mit einer maximalen '
                                         'Länge von 6 sein.'],
             'document.StockTransferCode': ['Das Feld "StockTransferCode" muss '
                                            'eine Zeichenfolge mit einer '
                                            'maximalen Länge von 12 sein.'],
             'document.TrafficRouteKind': ['Das Feld "TrafficRouteKind" muss '
                                           'eine Zeichenfolge mit einer '
                                           'maximalen Länge von 1 sein.'],
             'document.WarehouseLocationNumber': ['Das Feld '
                                                  '"WarehouseLocationNumber" '
                                                  'muss eine Zeichenfolge mit '
                                                  'einer maximalen Länge von '
                                                  '10 sein.'],
             'document.WarehouseNumber': ['Das Feld "WarehouseNumber" muss '
                                          'eine Zeichenfolge mit einer '
                                          'maximalen Länge von 10 sein.']},
 'Message': 'Das Model ist ungültig. Nähere Informationen sind in den Details '
            'enthalten.',
 'ResponseCode': '42-005',
 'StatusCode': 'BadRequest'}

Kann das Beispiel so gefüllt werden, dass es funktioniert?

Welche Felder sind als Pflichtfelder zu betrachten? Darüber finde ich keine Angaben.

**Comment by VivienSchuboth** [comment]
Guten Tag,
wir werden uns demnächst intensiver mit diesen Beispielen beschäftigen und sicherstellen, dass sich diese ohne Probleme ausführen lassen.

Mit freundlichen Grüßen,
Vivien Schuboth
