### ISSUE TITLE
Demo API Access

### ISSUE THREAD

**Issue by dariow** [selectline-software/selectline-api#360]
Geschätztes Entwickler Team

Ich erhalte leider beim Versuch mit Postman mich auf Ihrer Demo Umgebung einzuloggen auf dem Endpoint /login eine Fehlermeldung:

{
    "StatusCode": "Forbidden",
    "ResponseCode": "02-002",
    "ResponseId": 2,
    "ResponseIdDescription": "UnauthorizedAccessException",
    "Message": "Authentifizierung fehlgeschlagen.",
    "Details": null
} 

Endpoint: https://demo.slmobile.de/demoapi/Login

Body:
{
    "username": "{{user}}",
    "password": "{{password}}",
    "AppKey": "{{appKey}}"
}

Header
Content-Type: application/json
Accept: application/json

Es wird keine spezifische Authorisierung zusätzlich zum Body im Header gemacht bei diesem Endpoint.

Die Variablen username, password und AppKey sind gem. github im Environment hinterlegt.
Habe es auch schon ohne Variablen mit den Werten direkt im Body versucht, leider alles erfolglos.

Sind die Daten ggf. nicht mehr aktuell?
username: APIDemo
password: Ap1Dem0
AppKey: App-Demo20191122

**Comment by MatthiasGuse** [comment]
Danke für den Hinweis. Wir haben das Problem behoben.

Die Anmeldung funktioniert wieder.
