### ISSUE TITLE
TenantAPI lifert nur erste 7 Items

### ISSUE THREAD

**Issue by Torchok19081986** [selectline-software/selectline-api#361]
Morgen,
wir haben ein Update auf die Version 23.2.1 von SL Mobile und Mobile API beim Kunden eingespielt. Nun, wenn wir versuchen alle Mandanten für einen Benutzer übers TenantAPI zu lesen, werden nur erste 7 Items bzw. Mandanten von TenantAPI zurückgeliefert. 
Benutzer hat alle  Rechte auf alle Mandanten. 

```csharp

 TenantApi tenantApi = new TenantApi();
 tenantApi.TenantReadTenantList();
```
Ist das Bug in der API oder was muss angeben, damit alle Mandanten in der Liste erscheinen ? Hinweise : es sollen zwischen 10 und 20 Stück zurückkommen. 

Vielen Dank für die Info.

**Comment by MatthiasGuse** [comment]
Hallo,

Ich bekomme (wie erwartet) initial 10 angezeigt. Bei entsprechender Anpassung der Anzahl oder Aufruf einer weiteren Seite alle weiteren.

Hat das denn vor dem Update funktioniert?
Wird die Paginierung korrekt mitgegeben? --> https://demo.slmobile.de/demoApi/Help/HowToUse

Viele Grüße

**Comment by Torchok19081986** [comment]
hm. ok. Benutzer hat in der WaWi Zugriff auf 15 Mandaten und wenn man code von mir verwendet, dann werden nur erste 7 Mandanten angezeigt. Vor dem Update war das "alte" Model verwendet, ohne AppKey. Hier waren alle Mandanten korrekt zurückgegeben.  Wir haben diesen Kunden nun auch auf die Model mit AppKey umgestellt. Diese Methode hat etliche Filter und ich habe nun im 2. Parameter eine festdefnierte Anzahl von 50 mitgegeben und dann erscheinen alle 15 Mandandaten aus dem WaWi in der Liste korrekt. 

Eine Sache wäre da zu klären , warum man ohne Filter Parameter nicht alles bekommt, sondern man muss es mitgeben ? Umgekehrte Logik in der Swagger . Hier bedarf ich die Erklärung.

**Comment by MatthiasGuse** [comment]
Die API liefert standardmäßig nur 10 Datensätze aus, um nicht eine ganze Tabelle der Datenbank auszuliefern. Das betrifft ja alle Routen, die Listen zurückgeben. Daher ist das einheitlich und auch im Swagger so gelöst.
