### ISSUE TITLE
CustomerReadCustomerByNumberAsync

### ISSUE THREAD

**Issue by git828** [selectline-software/selectline-api#362]
### Details
- Current version number:  23.2.0
- Previous version number (optional): 21.3.0

#### Steps to replicate the behavior:
Wieso wurden diverse Modelle mit Async eingestellt?

Beispiel:
Version 21.3.0
`public SelectLineErpCustomerModuleModelsCustomer CustomerReadCustomerByNumberAsync(string customerNumber)
        {
            ApiResponse<SelectLineErpCustomerModuleModelsCustomer> apiResponse = CustomerReadCustomerByNumberAsyncWithHttpInfo(customerNumber);
            return apiResponse.Data;
        }`

Version 23.2.0
` public void CustomerReadCustomerByNumberAsync(string customerNumber)
        {
            CustomerReadCustomerByNumberAsyncWithHttpInfo(customerNumber);
        }`

Jetzt gibt es kein Model SelectLineErpCustomerModuleModelsCustomer zur Rückgabe.

**Comment by MaikGoertz** [comment]
Moin.
Hierbei handelte es sich ein Fehler in der API Dokumentation, wie er auch schon in #357 erwähnt wurde und ist mit der Version 23.2.1 behoben worden.

**Comment by git828** [comment]
Vielen Dank
Habe soeben 23.2.2 übersetzt.
Habe noch ein paar andere Funktionen die nicht laufen.
Beispiel:
ALT: 
      public object DocumentDeleteDocument(string documentKey)
        {
            ApiResponse<object> apiResponse = DocumentDeleteDocumentWithHttpInfo(documentKey);
            return apiResponse.Data;
        }
NEU:
        public void DocumentDeleteDocument(string documentKey)
        {
            DocumentDeleteDocumentWithHttpInfo(documentKey);
        }
ALT:
        public object DocumentUpdateDocumentPositionByDocumentKey(string documentKey, string documentPositionIdentifier, SelectLineErpDocumentModuleModelsDocumentPositionUpdateModel position)
        {
            ApiResponse<object> apiResponse = DocumentUpdateDocumentPositionByDocumentKeyWithHttpInfo(documentKey, documentPositionIdentifier, position);
            return apiResponse.Data;
        }
NEU:		
   public void DocumentUpdateDocumentPositionByDocumentKey(string documentKey, string documentPositionIdentifier, SelectLineErpWebApiModelsDocumentDocumentPositionUpdateModel position)
        {
            DocumentUpdateDocumentPositionByDocumentKeyWithHttpInfo(documentKey, documentPositionIdentifier, position);
        }
    
ALT:
        public object CustomerUpdateCustomerAsync(string customerNumber, SelectLineErpCustomerModuleModelsCustomer customer)
        {
            ApiResponse<object> apiResponse = CustomerUpdateCustomerAsyncWithHttpInfo(customerNumber, customer);
            return apiResponse.Data;
        }   
NEU:		
		public void CustomerUpdateCustomerAsync(string customerNumber, SelectLineErpCustomerModuleModelsCustomer customer)
        {
            CustomerUpdateCustomerAsyncWithHttpInfo(customerNumber, customer);
        }		
ALT:
        public object DocumentUpdateDocument(string documentKey, SelectLineErpDocumentModuleModelsDocumentUpdateModel document)
        {
            ApiResponse<object> apiResponse = DocumentUpdateDocumentWithHttpInfo(documentKey, document);
            return apiResponse.Data;
        }
NEU:
        public void DocumentUpdateDocument(string documentKey, SelectLineErpDocumentModuleModelsDocumentUpdateModel document)
        {
            DocumentUpdateDocumentWithHttpInfo(documentKey, document);
        }		

werden die auch noch korrigiert oder muss Ich die umschreiben?

**Comment by MaikGoertz** [comment]
Moin.

Bei den aufgeführten Routen ist die Änderung beabsichtigt. DELETE und PUT Routen geben per Konvention NoContent (204) als Response StatusCode. Dies wurde nun auch in der Swagger Dokumentation so korrigiert.
