### ISSUE TITLE
Handelssstücklisten funktionieren nicht im Lieferschein

### ISSUE THREAD

**Issue by Logic-Bits** [selectline-software/selectline-api#363]
Im zB. Angebot kein Problem, aber im Lieferschein geht das nicht:

slmobileApi/swagger/ui/index#/Document/Document_CreateDocumentPositionWithArticleItemByDocumentKey

{
    "StatusCode": "NotFound",
    "ResponseCode": "42-017",
    "ResponseId": 17,
    "ResponseIdDescription": "ParameterValueNotSupportedException",
    "Message": "Der übermittelte Parameterwert wird nicht unterstützt: articleNumber",
    "Details": {
        "failure": "Diese Art von Stücklisten wird in dieser Funktion nicht unterstützt. Erlaubte Stücklisten hierfür sind K,P,R,Z"
    }
}

**Comment by MatthiasGuse** [comment]
Es wäre schön, wenn Sie die Issue Vorlage nutzen würden und uns somit gleich mitteilen, welche Version und welche Route Sie nutzen. Nutzen Sie diese Route? 
https://demo.slmobile.de/demoApi/Help/Api/POST-Documents-documentKey-SalesBOMPosition 

Viele Grüße

**Comment by Logic-Bits** [comment]
Hallo,

Version ist aktuell, 23.2.2.
Die Swagger Route die ich geschickt habe war in der Tat die falsche.
Man kommt also nicht drum herum vor jeder Positionsanlage erstmal den Artikel abzurufen, bevor man in anlegen kann (da man unterschiedliche Routen verwenden muss).
