### ISSUE TITLE
EBillEMail  und EtypId Stammdaten / Kunden / Lieferanten / Belegausgabe

### ISSUE THREAD

**Issue by git828** [selectline-software/selectline-api#365]
### Details
- Current version number:  23.2.0 Build 980860
- Previous version number (optional): 21.3.10
- [ ] Test status checked in Mobile Manager
- Function or route (request): POST customer in swagger
- Error (response): EbillEMail wird nicht angelegt.

#### Steps to replicate the behavior:
Beim anlegen eines Kunden under Mitgabe von 
  "EBillEMail": "email@gugus.me",
  "ETypId": 1,

wird im _Stammdaten / Kunden / Lieferanten / Belegausgabe_ nichts angelegt.

Braucht es hier eine abgeändertes Model?

**Comment by MatthiasGuse** [comment]
Hallo,

hier werden seitens der API die Daten nicht korrekt geschrieben. Mit dem kommenden Hotfix 23.2.3 wird dies korrigiert und die genannten Werte schrieben korrekt die Daten der Belegausgabe für den Belgtyp Rechnung. Für alle anderen Belegtypen unter der Belegausgabe wird es in einer späteren Version neuen Funktionen geben.

Viele Grüße

**Comment by MatthiasGuse** [comment]
Die Version 23.2.3 steh nun zur Verfügung.
