### ISSUE TITLE
Postman Example liefert keine PDF zurück

### ISSUE THREAD

**Issue by Geoffrey-Fish** [selectline-software/selectline-api#370]
Hi,
ich möchte gezielt zu einzelnen Aufträgen PrintPdf nutzen. Zu Testzwecken verwende ich eure bereitgestellten Postman Daten. In Postman selbst ist in der Katergorie diese Uri voreingestellt: {{url}}/Documents/FAU345/PrintPdf
Die jedoch nichts zurück liefert. Das gleiche gilt für sämtliche Beispielbelege.
Ein anderes Issue zur Thematik meinte jedoch dass Postman das nun enthalten würde.
Falsches Denken meinerseits? Ist das eher gedacht um es mit Daten  vom Kunden/Testkunden zu probieren?

**Comment by MatthiasGuse** [comment]
Hallo,

wenn Sie mit "eure bereitgestellten Postman Daten" den Demo-Server meinen, ist es möglich, dass dort nicht alle Bewegungsdaten vorhanden sind. Die Beispiele in der Collection beziehen sich eher auf den Wawi Mustermandanten. Es sollte aber helfen zu prüfen, ob der in der Route genannte Beleg auch vorhanden ist. Grunsätzlich ist die Collection ein Hilfsmittel für den Entwickler, wobei wir ein gewisses Verständnis für die Daten der Warenwirtschaft voraussetzen.

Viele Grüße
