### ISSUE TITLE
[Solved] Error when setting payment block adding document

### ISSUE THREAD

**Issue by abdullahbaa5** [selectline-software/selectline-api#371]
### Details
- Current version number: 22.3.5 Build 799497
- Function or route (request): post /Documents
- Error (response):
InternalServerError {
  "StatusCode": "InternalServerError",
  "ResponseCode": "42-000",
  "ResponseId": 0,
  "ResponseIdDescription": "Undefined",
  "Message": "Das Feld [Fibuexport] darf nicht geändert werden.",
  "Details": {
    "ExceptionName": "EBelegImportPufferException"
  }
}

#### Steps to replicate the behavior:
when creating a document with payment block specified i get the error above but if i set the payment block as null it works?

![image](https://github.com/selectline-software/selectline-api/assets/38984510/c261e7e0-5df2-46a6-8108-bec1685b2adc)

**Comment by MatthiasGuse** [comment]
Hi,

i think the date "FinancialAccountExportDate" is not necessary. Also the value in your screenshot is invalid.
Please only use the values you need.

Regards

**Comment by abdullahbaa5** [comment]
> Hi,
> 
> i think the date "FinancialAccountExportDate" is not necessary. Also the value in your screenshot is invalid. Please only use the values you need.
> 
> Regards

it was a few of those values. The issue was that I had a whole class with all DocumentDetailPayment and the json serializer was giving the values default value of null, 0 or "".

for example in above screenshot there is not PaymentTerm but in the json sent to the api, it was set as "", hence one of the properties that was not allowed to be changed/edited/set was send too which i did not define at all, so i completely removed all variables that i do not need.

Before:
![image](https://github.com/selectline-software/selectline-api/assets/38984510/79ec4e02-bbde-42c1-a0e3-f256f6c4ab5c)

After:
![image](https://github.com/selectline-software/selectline-api/assets/38984510/68329f7d-ae24-422b-9ea9-b71b53a347c7)
