### ISSUE TITLE
Bei Login versuch Fehler 02-002 

### ISSUE THREAD

**Issue by QS-Stang** [selectline-software/selectline-api#372]
### Details
- Current version number:   23.1.7 Build 940032
- Previous version number (optional): 
- [x] Test status checked in Mobile Manager
- Function or route (request): /Login
- Error (response):  
{
  "StatusCode": "Forbidden",
  "ResponseCode": "02-002",
  "ResponseId": 2,
  "ResponseIdDescription": "UnauthorizedAccessException",
  "Message": "Authentifizierung fehlgeschlagen.",
  "Details": null
}
#### Steps to replicate the behavior:
In Swagger die Route "/Login" aufrufen  mit Username,Password, {Appkey}

**Comment by QS-Stang** [comment]
Hallo, 
Problem hat sich auch von allein gelöst, nachdem das Backend neugestartet wurde.

**Comment by MatthiasGuse** [comment]
Zur Sicherheit würde ich es empfehlen die Datenbankverbindung erneut über den Mobile Manager einzurichten. Das Verhalten klingt so, als ob das Backend noch nach altem Versionsstand eingerichtet ist.
Viele Grüße
