### ISSUE TITLE
Keine Rückmeldung der Belegnummer beim Weiterführen per API

### ISSUE THREAD

**Issue by davidhommel** [selectline-software/selectline-api#373]
Wenn ich per POST /Documents/xx/Successors einen Auftragsbeleg (Typ F) in einen Lieferschein (Typ L) weiterführe, enthält die Rückmeldung der API **keine Belegnummer** des erstellten Folgebeleges.

Ich konnte das Verhalten nun schon auf mehreren Systemen, welche die 23.3.1 einsetzen replizieren.
Die Funktion zum Weiterführen von Belegen ist in unserer Partnerlösung besoMobile essentiell wichtig, und die unvollständige Rückmeldung der SelectLine API beim Weiterführen macht diese gänzlich inkompatibel mit Version 23.3.x

Den Aufruf, den Body des Aufrufs und die Response habe ich im Details-Block eingetragen. Bei der Reproduktion ist es unerheblich, ob das Weiterführen mit oder ohne Positionen ausgeführt wird.

### Details
- Current version number: 23.3.1 Build 1035563
- Previous version number (optional): 
- [ ✔ ] Test status checked in Mobile Manager

- Function or route (request): POST /Documents/xx/Succesors
- Body: {
     "DocumentKindDestination" : "L",
     "Positions": []
}

- response: {
	"DocumentKey": "L",
	"DocumentKind": "L",
	"DocumentNumber": ""
}

**Comment by MatthiasGuse** [comment]
Hallo,

haben Sie das auch nochmal getestet? Wir können dieses Verhalten nicht bestätigen.

Viele Grüße

**Comment by davidhommel** [comment]
Funktionierte bei mir jetzt auch. Keine Ahnung woher das kam... Vielleicht war mein Postman verwirrt.
