### ISSUE TITLE
Leere Rückmeldungen bei GET /Documents/xx/Successors 

### ISSUE THREAD

**Issue by davidhommel** [selectline-software/selectline-api#374]
Wenn ich per API die Folgebelege eines Beleges abrufen möchte, erhalte ich ein leeres JSON-Array als Response.
Dies passiert nur, wenn es den abgefragten Hauptbeleg auch gibt. Ansonsten kommt (korrekterweise) eine 404 Response.

### Details
- Current version number: 23.3.1 Build 1035563
- Previous version number (optional): 
- [ ✔ ] Test status checked in Mobile Manager
- Function or route (request): GET /Documents/xx/Successors
- Error (response):

#### Steps to replicate the behavior:
- Auftrag in WaWi anlegen
- Auftrag zB in Lieferschein weiterführen
- o.g. API Abfrage auf den Auftragsbeleg
- Leere Response

**Comment by MatthiasGuse** [comment]
Hallo,
erfolgte die Belegübergabe mit Positionen?
Wie ist der Status des Folgebeleges (Lieferschein) in der Warenwirtschaft in diesem Fall?

Grüße

**Comment by davidhommel** [comment]
Moin,

hat sich tatsächlich übers Wochenende erledigt. Funktioniert nun, obwohl ich am Mittwoch Backend-WaWi, IIS und die ganze Maschine neu startete um genau sowas auszuschließen.
