### ISSUE TITLE
How to get company's discount group's discount value

### ISSUE THREAD

**Issue by abdofallah** [selectline-software/selectline-api#375]
I have looked through the api and still not able to find which api function to use to get the discount data for the Customer.Payment.DiscountGroupNumber

thank you.

**Comment by abdullahbaa5** [comment]
https://demo.slmobile.de/demoApi/Help/Api/GET-Articles-articleNumber-Sales-Prices-customerNumber
https://demo.slmobile.de/demoApi/Help/Api/GET-Articles-articleNumber-Purchasing-Prices-supplierNumber

both are throwing the following error on (22.3.5 Build 799497)

`NotFound <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>404 - File or directory not found.</title>
<style type="text/css">

</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>404 - File or directory not found.</h2>
  <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>
 </fieldset></div>
</div>
</body>
</html>`

**Comment by MatthiasGuse** [comment]
Hello,

actually there is no function to get the data for the DiscountGroupNumber. Using the price functions - named above, is the better way to get an correct price for the customer.

Probalby this functions are available in a later version of the api (23.1). See here: https://apiupdate.selectline.de/
In your local installation of the documentation and Swagger you can see the existing functions, according to your version. 

Best regards
