### ISSUE TITLE
Post request to  /Documents/{documentKey}/Positions/Store not working

### ISSUE THREAD

**Issue by eeinsiedler** [selectline-software/selectline-api#378]
### Details
- Current version number:  23.2.3 Build 1008324
- Function or route (request): 

Body des Post Reqeusts /Documents/{documentKey}/Positions/Store
```
[{
"Identifier":"7057CD6B-CDF8-43AA-8A0F-1B19C8C06575",
"ArticleNumber": "13133",
"PriceQuantity":  "0.0",
"Quantity":  "-1.0",
"QuantityUnit":"ST",
"StorageFlag": "A",
"StoragePlaceIdentifier" :  20,
"SerialNumber":"17100UN20286398",
"Warehouse":"A12"
}]
```
 
- Error (response):

204. "The customer tries to create a new storage via the API interface. He receives a response with the code number 204 and an empty JSON array. Unfortunately, nothing is written to the SL other than an empty document."

#### Steps to replicate the behavior:

"Send POST request to API."

**Comment by MatthiasGuse** [comment]
Hello,

the function you use, is designed to edit the storage of an existing position. Not to create a new position. 
Maybe you are looking for POST /Documents/{documentKey}/ArticleItem ?

Greetings

**Comment by eeinsiedler** [comment]
Thanks for your response. Sorry, maybe we are talking of two different things.
In the documentation they say https://demo.slmobile.de/demoApi/Help/Api/POST-Documents-documentKey-Positions-Store
_"Creates a new storage for an existing item using the storage information provided."_ and that's exactly we want to do. The only problem is that with a serialnumber article nothing happens in the end.

**Comment by eeinsiedler** [comment]
Hello,
obviously the problem has been solved. I think there was an issue related to the correctness of the data.
