### ISSUE TITLE
Befüllung von Extrafeldern

### ISSUE THREAD

**Issue by mbuhl11** [selectline-software/selectline-api#38]
Ich bin aktuell dabei mithilfe der API Aufträge in der Selectline-Warenwirtschaft anzulegen. 
Nun habe ich aber das Problem, dass der Inhalt für mein dort angelegtes Extrafeld nicht übernommen wird. 

Ich habe das Feld _EMAIL vom Typ WideString 255 erstellt und in der Tabelle Beleg angelegt und mit dem Maskeneditor neben den Adressdaten eingefügt. 
Das Ganze sieht dann in meinem JSON-Body folgendermaßen aus: 

`{"KindFlag":"F","ExtraFields":{"_EMAIL":"beispiel@adresse.de"},[...]}` 

Fehler bekomme ich nicht zurück, alle anderen Felder werden Ordnungsgemäß und wie erwartet gefüllt, nur mit dem Extrafeld mag es nicht klappen. 

Selectline-Version: 20.2.0 Build 186919

**Comment by ThePholph** [comment]
Hallo,

wurde der BackendManger seitdem neu gestartet? Wenn dies nicht der Fall ist kennt die Instanz evtl. das ExtraFeld noch nicht.
Den Fehler haben wir am Anfang auch gemacht.

VG

Daniel

**Comment by mbuhl11** [comment]
> Hallo,
> 
> wurde der BackendManger seitdem neu gestartet? Wenn dies nicht der Fall ist kennt die Instanz evtl. das ExtraFeld noch nicht.
> Den Fehler haben wir am Anfang auch gemacht.
> 
> VG
> 
> Daniel

Vielen Dank, genau das war das Problem! 
Hat mir definitiv den Tag gerettet!
