### ISSUE TITLE
Error when adding an item with BOM type D to a delivery note

### ISSUE THREAD

**Issue by ccfrusano** [selectline-software/selectline-api#380]
### Details
- Current version number: 23.3.0 Build 1026576
- Previous version number (optional): 
- [ ] Test status checked in Mobile Manager
- Function or route (request): POST /Documents/{documentKey}/SalesBOMPosition
- Error (response): No error, but wrong output.

I have this item V500219, which contains 2 subitems inside:
![image](https://github.com/selectline-software/selectline-api/assets/106327327/7bb73b10-061c-4475-8532-d3bb557ca82c)

When I add this item to a document, I expect both subitems to be added. Instead, this happens:
![image](https://github.com/selectline-software/selectline-api/assets/106327327/1dc628cf-2641-4518-aa66-a1ca650cd0a0)

The lines 12 and 13 are correct, but I don't know why a SET is added. This makes that two pieces of stock of each item gets substracted. Does anybody know why?
Thanks

**Comment by MatthiasGuse** [comment]
Hello,

the function you use is desinged for "SalesBOMPosition" and not for "Sample BOM". 
You can use POST /Documents/{documentKey}/ArticleItem to add your list.

Regards

**Comment by ccfrusano** [comment]
Hello Matthias,
This item is of type "M". If we try to use the function you mention, we get the error:
"Article line: "failure": "Diese Art von Stücklisten wird in dieser Funktion nicht unterstützt. Erlaubte Stücklisten hierfür sind K,P,R,Z".
![image](https://github.com/selectline-software/selectline-api/assets/106327327/6dae2efd-79ea-4a44-b6bf-6ca142130e5e)

As you can see, it has 2 subitems.
 That's why we tried the "SalesBOMPosition" function. How can we insert lines in documents for items type "M"?
Thanks!
Best,

**Comment by MatthiasGuse** [comment]
Hello,

in your first post, you used an other type. For both types it is only possible to add the positions by "POST /Documents/{documentKey}/ArticleItem" in non storing document types.

It is only possible to transfer a document with such position types to an storing document.

Regards
