### ISSUE TITLE
Leider Dringlich... Returncode 02-039 "Der verwendete AppKey ist nicht gültig."

### ISSUE THREAD

**Issue by mfahs** [selectline-software/selectline-api#388]
Hallo zusammne!

Ich habe eine Anwendung (in meiner Entwicklungsumgebung mit unserem Appkey läuft sie natürlich herzallerliebst...), die ich nun bei einem Kunden (mit ganz neu lizenzierter API) installieren und ausführen möchte. Die API wird auch gefunden, allerdings kann ich mich nicht anmelden - der Login wird mir mit dem Returnode 02-039 (AppKeyInvalidException / Der verwendete AppKey ist nicht gültig.) quittiert. Ich habe ca. 1000 mal die Anmeldedaten verglichen, schreibe ein Log mit, in dem ich auch nochmals die an die API übergebenen Login-Daten protokolliere - ich kann beim besten Willen keinen Fehler finden. Die Anmelderoutine ist die von uns immer verwendete, die auch bei anderen Kunden ohne Probleme funktioniert...
Nach einem Anruf im Support habe ich SL.mobile neu installiert - ebenfalls ohne Erfolg.

Wer kann mir einen Tipp geben, damit meine an sich funktionsfähige Anwendung endlich den Login hinbekommt?

Grüße und schon mal ein "Dankeschön"
Martin Fahs

**Comment by Torchok19081986** [comment]
Hallo, 2 Fragen . Erste Frage, wurde die neue AppKey von der SL für Kunden freigeschaltet ? AFAIK , muss dieser von SL freigeschaltet werden und diese wird für Kunden hinterlegt. Nur dann kann man mit AppKey für die Anwendung anmelden. Zweite Frage, ist dieser neue Appkey in der SL WaWi zu sehen ? Gehen Sie dazu in WaWi und in der Lizensierung, muss dieser AppKey zu sehen sein. Ist er nicht vorhanden, so kann auch keine Anmeldung / Anwendung API konsumieren.

**Comment by mfahs** [comment]
Das Partner-Management sagt, dass der Appkey einwandfrei lizenziert ist und funktionieren müsste. Von einer notwendigen "Freischaltung" habe ich noch nie etwas gehört und hat der Support auch nichts gesagt - da ich aber mittlerweile schon einige Telefonate mit SL hatte, wäre da sicherlich schon jemand druf gekommen (hoffe ich).
In der Wawi ist der AppKey auch exakt so zu sehen, wie ich ihn verwende. 
Es sieht also alles richtig aus - ich bin völlig ratlos.

**Comment by Torchok19081986** [comment]
hm.. sehr dubios. Hatte noch nie sowas gehabt.  Wenn der AppKey beantragt wurde, so mussten Sie auch eine Rechnung dafür gekriegt haben. Dort steht Name des Kunden und Appkey, welche in Ihrem application angegeben werden musste. Haben Sie sowas bekommen ?

**Comment by mfahs** [comment]
Selbstverständlich. Sonst wäre die Lizenz ja niemals ausgestellt worden... Die Daten finde ich auch im Partnerportal unter "Lizenzen" - das sieht alles richtig aus und wurde ja auch von dem Kollegen in MD bestätigt. Ich vermute eher ein technisches "Problem" mit dem AppKey.

**Comment by Torchok19081986** [comment]
Welche Version der API von swagger verwenden Sie ? Wir haben gerade ein Einsatz 23.3.5 und hier läuft alles einwandfrei.

**Comment by Micha-Richter** [comment]
Hallo Herr Fahs,

ich gehe mal davon aus, dass die "einfachen" Checks alle gelaufen sind:
- Lizenz wird in SLMobile auch angezeigt (Administration/Lizenz)
- AppKey funktioniert auch mit anderem Benutzer nicht
- Login funktioniert weder aus Ihrem Programm heraus noch per Swagger
- Normale SLMobile-Benutzer können sich anmelden (keine API-Benutzer)
?

Haben Sie den AppKey kopiert oder abgeschrieben? Kann es sowas schräges wie L und I sein!? 🤷‍♂️
Kann SL mal testweise einen anderen APPKey ausstellen!?

**Comment by MatthiasGuse** [comment]
Hallo Herr Fahs,

Sorry für die Umstände und danke für Ihre Geduld. Wir werden sicherstellen, dass solche Eingaben zukünftig nicht mehr vorkommen. Bis zur PK dann.

Danke auch an alle Mitwirkenden hier im Github.

Viele Grüße
