### ISSUE TITLE
IhrAuftrag 

### ISSUE THREAD

**Issue by Lars-Mue** [selectline-software/selectline-api#39]
Hallo ,

sehe ich das richtig, dass bei dem Beleg erstellen 
das Feld Ihr Auftrag nicht gefüllt werden kann? 
Bitte um eine schnelle Antwort

Viele Grüße

**Comment by ThorstenPoppe** [comment]
Hallo Lars,

doch, das geht, nutzen wir selbst.
Im Document Model ist das im Unterbereich BusinessPartner -> BusinessPartnerReferenceNumber zu finden.

Viele Grüße,
Thorsten

**Comment by ThorstenPoppe** [comment]
Sorry, das ist nicht BusinessPartnerReferenceNumber (= Ihr Zeichen), sondern **BusinessPartnerContract** (=IhrAuftrag)!

**Comment by Lars-Mue** [comment]
Hallo Thorsten ,


vielen Dank, muss ich übersehen haben.
