### ISSUE TITLE
No Add/Put API Endpoint for /Documents/{documentNumber}/DeliveryAddresses

### ISSUE THREAD

**Issue by abdullahbaa5** [selectline-software/selectline-api#391]
Currently there is only GET endpoint available for retrieving the delivery addresses in a document but none for adding one:

![image](https://github.com/selectline-software/selectline-api/assets/38984510/f820abdf-0142-40de-b524-9d80d0f593c8)

Could an endpoint for adding delivery address be added? Thank you.

**Comment by MatthiasGuse** [comment]
Hi,

You can use https://demo.slmobile.de/demoApi/Help/Api/PUT-Documents-documentKey - "DeliveryAddress" to add or change the address to a document.

Regards

**Comment by abdullahbaa5** [comment]
> DeliveryAddress

DeliveryAddress in a document is a different field than adding additional Delivery Addresses. Please try it for yourselves and call the get endpoint vs the get document.

the delivery address retrieved by /Documents/XYZ/DeliveryAddress is different than (/Documents/XYZ) Document.DeliveryAddress
