### ISSUE TITLE
Predefined Comments for Documents in the API?

### ISSUE THREAD

**Issue by abdullahbaa5** [selectline-software/selectline-api#392]
in the Selectline Application there is an option to add predefined comments in the document, how ever i was not able to find an api endpoints that retrieves these comments (only retrieving is required by my usecase)

Process in app:
![image](https://github.com/selectline-software/selectline-api/assets/38984510/cdf78523-a409-4cb7-baec-f7729e0e335a)

![image](https://github.com/selectline-software/selectline-api/assets/38984510/4015cb1d-2a30-44a3-a539-8ffa706bd938)

![image](https://github.com/selectline-software/selectline-api/assets/38984510/58dc98e3-0748-4391-856d-49d0bdb6f68c)

**Comment by MatthiasGuse** [comment]
Hello, 

this is not possible at the moment. Please post a wish at the SelectLine Uservoice.

Regards
