### ISSUE TITLE
Postman-Kollektion für 23.3

### ISSUE THREAD

**Issue by MPIT-Eckart** [selectline-software/selectline-api#394]
Guten Tag,

seit der Version 23.3 gibt es neue Pfade, bspw. zur Journalanlage.
Die Postman-Kollektion ist jedoch noch auf der Version für die SelectLine 23.1

Können Sie die Kollektion für die 23.3 bereitstellen?

mit freundlichen Grüßen
Phillip Eckart

**Comment by MaikGoertz** [comment]
Moin.

Ich habe die Postman Collection auf Stand 23.3 aktualisiert.

Gruß
