### ISSUE TITLE
Route Documents und Parameter DeliveryDocumentNumber - Leerzeichen in der Übergabe gibt Error zurück

### ISSUE THREAD

**Issue by diekloope** [selectline-software/selectline-api#399]
### Details
- Current version number: 23.3.5 Build 1073686
- [ x ] Test status checked in Mobile Manager
- Function or route (request): slmobileApi/Documents
- Error (response):
{
  "StatusCode": "InternalServerError",
  "ResponseCode": "42-000",
  "ResponseId": 0,
  "ResponseIdDescription": "Undefined",
  "Message": "1132 not allowed. Expect ), and, andnot, or, ornot",
  "Details": null
}

#### Steps to replicate the behavior:
Siehe Screenshot vom Swagger:
![Swagger_20240625](https://github.com/selectline-software/selectline-api/assets/58892526/2a52c084-4fcd-4a22-b307-b5031b28ba6b)

**Comment by MaikGoertz** [comment]
Moin.
Zeichenketten werden mit `'` umschlossen, bspw. `... EQ '123 456 789'`.
Gruß 
Maik

**Comment by diekloope** [comment]
> Moin. Zeichenketten werden mit `'` umschlossen, bspw. `... EQ '123 456 789'`. Gruß Maik

Moin, hat geklappt. Bedankt und Gruß Volker
