### ISSUE TITLE
Date deserialization issue while posting a document

### ISSUE THREAD

**Issue by m4rkyx** [selectline-software/selectline-api#4]
Hello guys,

It's me again ;)

During the process of posting document, I saw a problem with the date deserialization from the API system.

I created a document with the JSON below with this date :

![image](https://user-images.githubusercontent.com/1868168/73546086-e3468e80-443c-11ea-8cfd-37f2c105840c.png)

But when I'm retrieving the freshly created document, I saw that the date is not correct :

![image](https://user-images.githubusercontent.com/1868168/73546329-57813200-443d-11ea-902a-210334cb7333.png)

I one time saw a same problem while using RestSharp and created a custom JSON serializer to avoid that kind of problem with date deserialization.

Also, let me know if I'm doing something wrong.

Regards,

**Comment by jprause1234** [comment]
Hi,

we will inspect the problem soon and will give you further informations then.

Regards,
Jan

**Comment by VivienSchuboth** [comment]
Hello,

we solved the problem with the next version 20.1 which will be released soon.

Best regards,
Vivien
