### ISSUE TITLE
UStID fehlt in GET /Documents/{documentKey}

### ISSUE THREAD

**Issue by aameyer** [selectline-software/selectline-api#40]
Guten Tag,
das Feld UStID aus der Tabelle BELEG ist in GET /Documents/{documentKey} nicht enthalten. Aus den Kundenstammdaten kann die UStID zwar über GET /customers/{customerNumber} als TaxIdentifierNumber ausgelesen werden, aber dieser Wert ist nicht zwingend identisch mit der UStID im Belegkopf.

Können Sie dieses Feld zeitnah mit der API übergeben, oder müssen wir hier auch mittelfristig den Umweg über ein Api-Makro gehen?

Mit freundlichen Grüßen
Alexander Meyer

**Comment by VivienSchuboth** [comment]
Guten Tag Herr Meyer,
wir werden versuchen, in den letzten Wochen bis zur Auslieferung der Version 20.3, dieses Feld ebenfalls mit anzubieten.

Mit freundlichen Grüßen,
Vivien Schuboth

**Comment by VivienSchuboth** [comment]
Guten Tag Herr Meyer,
dieses Feld steht Ihnen mit der Version 20.3 zur Verfügung.

Mit freundlichen Grüßen,
Vivien Schuboth

**Comment by ThorstenPoppe** [comment]
Hallo zusammen,

ich muss diesen Fall nochmal öffnen.
Leider steht das Feld nicht für die Anlage eines Belegs über POST zur Verfügung, das wäre auch sehr wichtig.
Bitte hier nochmal nachbessern!

Viele Grüße, Thorsten Poppe

**Comment by MatthiasGuse** [comment]
Hallo Herr Poppe,

dieser Eintrag bezieht sich auf die "GET" Funktion und ist damit abgeschlossen. Bitte eröffnen Sie einen neuen Issue für "POST", sonst geht das hier unter.

Viele Grüße
