### ISSUE TITLE
VPN notwendig?

### ISSUE THREAD

**Issue by DAKO-IT-MP** [selectline-software/selectline-api#403]
Hallo liebes SL-API-Team,
 
ich würde Sie gern mal um Ihre Meinung bitte, da diese bei uns im Team etwas auseinander geht:
 
Wir möchten ein Projekt angehen, wo wir die SL-API im Internet zur Verfügung stellen, damit außerhalb des Unternehmens damit gearbeitet werden kann.
Ist ein VPN zwingend notwendig, oder ist es vertretbar, auf diesen zu verzichten?
 
Was meinen Sie? :-)

**Comment by MaikGoertz** [comment]
Hallo.
Pauschal kann man das nicht beantworten, wie so oft ist auch hier die Antwort "kommt darauf an". ;)

Ein VPN _kann_ die Sicherheit erhöhen sofern es richtig konfiguriert und gewartet wird. 
In Szenarien wo der Endanwender jedes Mal manuell zuerst die VPN Verbindung aufbauen muss, bevor die eigentliche Arbeit beginnen kann, ist dies oft zu umständlich und wird eher als störend empfunden. 

Der branchenübliche Standard sind _echte_ Zertifikate mit denen ein Man-in-the-middle verhindert wird.
Dies empfehlen wir **zwingend** wenn die API aus dem Internet erreichbar ist.

Gruß 
Maik

**Comment by DAKO-IT-MP** [comment]
Hallo Maik,

vielen Dank für die Rückmeldung. Mit einer Antwort dieser Art habe ich gerechnet :-)

VG Morris
