### ISSUE TITLE
42-033 - DocumentSuccessorErrorException

### ISSUE THREAD

**Issue by abdullahbaa5** [selectline-software/selectline-api#407]
Version: 23.3.5.0

When trying to transfer an offer document (created using selectline app) to an order document using the api, we are getting the following error:

```
{
  "StatusCode": "BadRequest",
  "ResponseCode": "42-033",
  "ResponseId": 33,
  "ResponseIdDescription": "DocumentSuccessorErrorException",
  "Message": "Der Nachfolgebeleg kann nicht angelegt werden.",
  "Details": {
    "ResponseDetails": "<Tabelle Version=\"1.0\"><DESCRIPTION><Fehlerklasse DisplayName=\"Fehlerklasse\">int</Fehlerklasse><Status DisplayName=\"Status\">nvarchar(20)</Status><fName0 DisplayName=\"Belegtyp\">nvarchar(1)</fName0><fName1 DisplayName=\"Belegnummer\">nvarchar(10)</fName1><fName2 DisplayName=\"Bezeichnung\">nvarchar(30)</fName2><fName3 DisplayName=\"Bemerkung\">nvarchar(200)</fName3><_CBK_fName0 DisplayName=\"_CBK_fName0\">nvarchar(50)</_CBK_fName0><_CBK_fName1 DisplayName=\"_CBK_fName1\">nvarchar(50)</_CBK_fName1><_CBK_fName2 DisplayName=\"_CBK_fName2\">nvarchar(50)</_CBK_fName2><_CBK_fName3 DisplayName=\"_CBK_fName3\">nvarchar(50)</_CBK_fName3></DESCRIPTION><DATEN><Fehler><Fehlerklasse><![CDATA[3]]></Fehlerklasse><Status><![CDATA[Fehler]]></Status><fName0><![CDATA[A]]></fName0><fName1><![CDATA[240235469]]></fName1><fName2><![CDATA[Offerte Kunde]]></fName2><fName3><![CDATA[Kunde (135835) fehlt in den Stammdaten.]]></fName3><_CBK_fName0><![CDATA[]]></_CBK_fName0><_CBK_fName1><![CDATA[]]></_CBK_fName1><_CBK_fName2><![CDATA[]]></_CBK_fName2><_CBK_fName3><![CDATA[]]></_CBK_fName3></Fehler></DATEN></Tabelle>",
    "ResponseType": "SuccessorsFailed"
  }
}
```

The request looks like the following:
![image](https://github.com/user-attachments/assets/495f5f76-3e6b-4d76-9cee-75c73b804347)
![image](https://github.com/user-attachments/assets/4cbb5322-1162-405b-a291-db93832b0e64)

the position "bb392631-26f6-4c62-a48b-f2322524c74a" is a comment, if i add it or not, i get same error.

if i try to keep the array empty as following:
![image](https://github.com/user-attachments/assets/4ee0b311-b464-4a2a-906f-7fc4d6bba93e)
I get the same error:
```
{
  "StatusCode": "BadRequest",
  "ResponseCode": "42-033",
  "ResponseId": 33,
  "ResponseIdDescription": "DocumentSuccessorErrorException",
  "Message": "Der Nachfolgebeleg kann nicht angelegt werden.",
  "Details": {
    "ResponseDetails": "<Tabelle Version=\"1.0\"><DESCRIPTION><Fehlerklasse DisplayName=\"Fehlerklasse\">int</Fehlerklasse><Status DisplayName=\"Status\">nvarchar(20)</Status><fName0 DisplayName=\"Belegtyp\">nvarchar(1)</fName0><fName1 DisplayName=\"Belegnummer\">nvarchar(10)</fName1><fName2 DisplayName=\"Bezeichnung\">nvarchar(30)</fName2><fName3 DisplayName=\"Bemerkung\">nvarchar(200)</fName3><_CBK_fName0 DisplayName=\"_CBK_fName0\">nvarchar(50)</_CBK_fName0><_CBK_fName1 DisplayName=\"_CBK_fName1\">nvarchar(50)</_CBK_fName1><_CBK_fName2 DisplayName=\"_CBK_fName2\">nvarchar(50)</_CBK_fName2><_CBK_fName3 DisplayName=\"_CBK_fName3\">nvarchar(50)</_CBK_fName3></DESCRIPTION><DATEN><Fehler><Fehlerklasse><![CDATA[3]]></Fehlerklasse><Status><![CDATA[Fehler]]></Status><fName0><![CDATA[A]]></fName0><fName1><![CDATA[240235469]]></fName1><fName2><![CDATA[Offerte Kunde]]></fName2><fName3><![CDATA[Kunde (135835) fehlt in den Stammdaten.]]></fName3><_CBK_fName0><![CDATA[]]></_CBK_fName0><_CBK_fName1><![CDATA[]]></_CBK_fName1><_CBK_fName2><![CDATA[]]></_CBK_fName2><_CBK_fName3><![CDATA[]]></_CBK_fName3></Fehler></DATEN></Tabelle>",
    "ResponseType": "SuccessorsFailed"
  }
}
```

**Comment by MaikGoertz** [comment]
Hello.
If you take a closer look at the error message, it says "Kunde (135835) fehlt in den Stammdaten." which means "Customer (135835) is missing in the master data". 
Please check the data in the document.

**Comment by abdullahbaa5** [comment]
> Hello. If you take a closer look at the error message, it says "Kunde (135835) fehlt in den Stammdaten." which means "Customer (135835) is missing in the master data". Please check the data in the document.

I have searched the selectline API for customer with 135835 number

And it does exist when searched through the API search company route
![image](https://github.com/user-attachments/assets/bdaef6a0-dc96-4d9a-8352-98ef0b2dc7c2)

what could be the reason that the transfer route thinks it is missing?

**Comment by abdullahbaa5** [comment]
I have tried with a different document and different company but it still doesn't work

```
{
  "StatusCode": "BadRequest",
  "ResponseCode": "42-033",
  "ResponseId": 33,
  "ResponseIdDescription": "DocumentSuccessorErrorException",
  "Message": "Der Nachfolgebeleg kann nicht angelegt werden.",
  "Details": {
    "ResponseDetails": "<Tabelle Version=\"1.0\"><DESCRIPTION><Fehlerklasse DisplayName=\"Fehlerklasse\">int</Fehlerklasse><Status DisplayName=\"Status\">nvarchar(20)</Status><fName0 DisplayName=\"Belegtyp\">nvarchar(1)</fName0><fName1 DisplayName=\"Belegnummer\">nvarchar(10)</fName1><fName2 DisplayName=\"Bezeichnung\">nvarchar(30)</fName2><fName3 DisplayName=\"Bemerkung\">nvarchar(200)</fName3><_CBK_fName0 DisplayName=\"_CBK_fName0\">nvarchar(50)</_CBK_fName0><_CBK_fName1 DisplayName=\"_CBK_fName1\">nvarchar(50)</_CBK_fName1><_CBK_fName2 DisplayName=\"_CBK_fName2\">nvarchar(50)</_CBK_fName2><_CBK_fName3 DisplayName=\"_CBK_fName3\">nvarchar(50)</_CBK_fName3></DESCRIPTION><DATEN><Fehler><Fehlerklasse><![CDATA[3]]></Fehlerklasse><Status><![CDATA[Fehler]]></Status><fName0><![CDATA[A]]></fName0><fName1><![CDATA[240235642]]></fName1><fName2><![CDATA[Offerte Kunde]]></fName2><fName3><![CDATA[Kunde (123656) fehlt in den Stammdaten.]]></fName3><_CBK_fName0><![CDATA[]]></_CBK_fName0><_CBK_fName1><![CDATA[]]></_CBK_fName1><_CBK_fName2><![CDATA[]]></_CBK_fName2><_CBK_fName3><![CDATA[]]></_CBK_fName3></Fehler></DATEN></Tabelle>",
    "ResponseType": "SuccessorsFailed"
  }
}
```

for this one it says the company is missing again `Kunde (123656) fehlt in den Stammdaten.`

**Comment by abdullahbaa5** [comment]
More Information:

If I take the same document details, and make it an Order document, and transfer it to "L" - Delivery Note, it works just fine.

This issue only happens when transferring Offer to "B" Order

**Comment by abdullahbaa5** [comment]
@MaikGoertz  any idea?

**Comment by MaikGoertz** [comment]
What kind of document is the original document?
Can the document transfer be done in the ERP software?

**Comment by abdullahbaa5** [comment]
> What kind of document is the original document? Can the document transfer be done in the ERP software?

Through API:
- Offer to Order | Does not work
- Order to Delivery Note | Works
- Order to Supplier Order | Works

Through ERP Software:
- Offer to Order | Works
- Order to Delivery Note | Works
- Order to Supplier Order | Works

**Comment by MatthiasGuse** [comment]
Hello, 
please check the document types. Document transfers are not possible from the input side to the output side and vice versa. The document types are not in alphabetical order. For example, a transfer from "A" to "B" is not possible. Only the transfers that also work in the desktop program work in the API. 

Regards

**Comment by abdullahbaa5** [comment]
> Hello, please check the document types. Document transfers are not possible from the input side to the output side and vice versa. The document types are not in alphabetical order. For example, a transfer from "A" to "B" is not possible. Only the transfers that also work in the desktop program work in the API.
> 
> Regards

but the ERP software allows for connection between the offer and the order document.

**Comment by digitaldynamikch** [comment]
Guten Tag @MaikGoertz und @MatthiasGuse

@abdullahbaa5 hat in meinem Auftrag eine App für einen Schweizer Kunden entwickelt, die mit der SelectLine API verbunden ist. Aus dem heraus hat sich der von ihm gemeldete Issue ergeben.

Im SelectLine Desktop-Programm des Kunden funktionieren folgende Belegübergaben (siehe Screenrecording [HIER](https://drive.google.com/file/d/1a4R99tpjFnjK1-Qsk2zIchaW6OqDUeBT/view?usp=sharing)):
Offerte > Auftrag (Vermerk in der Infobox: «vom Vorgängerbeleg übernommen») 
Auftrag > Lieferschein (Vermerk in der Infobox:  «vom Vorgängerbeleg übernommen»)
Auftrag > Bestellung (Vermerk in der Infobox: «Querverweis auf Auftrag […]»)

Über die API funktioniert **nur** folgende Belegübergabe:
Auftrag > Lieferschein

Über die API funktionieren folgende Belegübergaben **nicht**:
Offerte > Auftrag
Auftrag > Bestellung

@MatthiasGuse Du hast geschrieben "Only the transfers that also work in the desktop program work in the API."
Wie von uns gemeldet, ist dies jedoch nicht der Fall. Haben wir etwas übersehen?

Ich wäre sehr dankbar für eine zügige Rückmeldung. Unser Kunde wartet mittlerweile schon lange auf die Berichtigung.

Freundliche Grüsse,
Severin Spirig

**Comment by MatthiasGuse** [comment]
Hallo, 

bitte nicht auf die Bezeichnungen gucken und von diesen aus auf die Belegtypen schließen.
In dem oben genannten Beispiel wurde versucht einem Angebot (Offer for customer - Belgtyp 'A') in eine Bestellung (Purchase order - Belegtyp 'B') zu übergeben. Konkret wurde versucht ein Angebot für einen Kunden an eine Bestellung bei einem Lieferanten zu übergeben. Das funktioniert so nicht. 'A' zu 'F' wäre vermutlich gewünscht.
In der Belegdefinition kann man gut abgucken:
![grafik](https://github.com/user-attachments/assets/c5e2e3dc-ccdf-4df2-867a-70958a126269)

Viele Grüße

**Comment by digitaldynamikch** [comment]
Guten Tag @‌MatthiasGuse, danke für den Input!

Ich habe noch eine Frage:
Angenommen wir haben einen bestehenden Auftrag (F) mit der Nummer 24-84030 und eine bestehende Bestellung (B) mit der Nummer 21-74939.
Welche(n) API Call(s) müssen wir machen, um einen Querverweis zwischen den zwei Dokumenten anzulegen?
Ich wäre mega dankbar, wenn Du mir den/die Call(s) schicken könntest, mit allen nötigen Werten.

Dynamische Grüsse,
Severin

**Comment by digitaldynamikch** [comment]
Guten Tag @ThePholph, vielen Dank für den Input!

**Comment by Thunkkk** [comment]
Hi,

ich würde das hier gerne als Feature-Request vermerken. Ich habe den gleichen usecase, wo ich die Wawi-Funktion "Komplettbestellung" bzw. "Geteilte Bestellung" gerne per API nutzen würde.

Kann man natürlich per Makro lösen, werde ich auch, aber ich glaube das Feature wäre auch für mehr Leute durchaus sinnvoll.

LG
Lukas

**Comment by SirGamsay** [comment]
@ThePholph

Moin,

Wo genau ist das in der API Dokumentation zu finden, dass es dazu keine API Funktion gibt?
Sie haben leider damals versäumt den direkten Link zur Dokumentation anzugeben.

Oder schicken Sie mich jetzt auch zu einem Workshop?

Liebe Grüße
Meiko

**Comment by ThePholph** [comment]
> [@ThePholph](https://github.com/ThePholph)
> 
> Moin,
> 
> Wo genau ist das in der API Dokumentation zu finden, dass es dazu keine API Funktion gibt? Sie haben leider damals versäumt den direkten Link zur Dokumentation anzugeben.
> 
> Oder schicken Sie mich jetzt auch zu einem Workshop?
> 
> Liebe Grüße Meiko

Hi,

das geht implizit hervor, da nicht beschrieben wird, wie Verweise von Aufträgen zu Bestellungen angelegt werden können.

Viele Grüße 

Daniel
