### ISSUE TITLE
Demo API - Authentication failed

### ISSUE THREAD

**Issue by dariow** [selectline-software/selectline-api#408]
Dear SelectLine team

I can not access the demo api, obtaining the following http answer:

{
    "StatusCode": "Forbidden",
    "ResponseCode": "02-003",
    "ResponseId": 3,
    "ResponseIdDescription": "AuthenticationException",
    "Message": "Authentifizierung fehlgeschlagen.",
    "Details": null
}

I used postman with your collection and your environment.
Thank you for your help or credential updates.

**Comment by MatthiasGuse** [comment]
Hello,
we no longer provide the demo API. Please use the API in your local installation with your Appkey.

Best regards
