### ISSUE TITLE
Durchführung einer Umlagerung über die API

### ISSUE THREAD

**Issue by LukWlbr** [selectline-software/selectline-api#41]
Hallo zusammen,

ich habe aktuell das Problem, dass ich es nicht schaffe über die API eine Umlagerung durchzuführen. 
Ich möchte einen Artikel vom Quelllager in ein Ziellager umlagern. 
Dies versuche ich über den API-Endpoint **{{url}}/Documents/{{docnr}}/ArticleItem**. 

Laut der Dokumenation gibt es das Attribut "TargetWarehouse (Gibt die Nummer für das Ziellager zu einer Umlagerung an)", welches ich aber aktuell nicht anzuwenden weiß.
Leider weiß ich nicht wie ich die Daten anzugeben habe, da alle meine Versuche bisher fehlgeschlagen sind. 

Mein letzter Versuch sieht wiefolgt aus:
```
{
  "CalculatedQuantityValue": 2,
  "ArticleNumber": "700004",
  "WarehouseLabel": "902",
  "StoreInformation": [
    {
      "ArticleNumber": "700004",
      "Warehouse": "100",
      "TargetWarehouse": "902",
      "Quantity": 2
    }
  ]
}
```

Ich kriege immer die Fehlermeldung "Fehler beim Lagern. Offene Menge: -2,00".

Wichtig dazu: Ich habe einen eigenen Belegtyp angelegt und mich bewusst gegen die manuelle Lagerung entschieden.

Es wäre super, wenn mir jemand sagen könnte wie ich dies anzugeben habe bzw. ob dies überhaupt ohne manuelle Lagerung durchführbar ist.

Vielen Dank im Voraus.

**Comment by VivienSchuboth** [comment]
Guten Tag,
es tut uns leid für dieses Missverständnis.
Die SelectLine API unterstützt die Manuelle Lagerung, jedoch keine selbstdefinierten Umlagerungsbelege. 
Diese Information findet man ebenfalls auf der [Hilfe-Seite der SelectLine API.](https://demo.slmobile.de/demoApi/Help/ApiGroup?controllerName=Document)

Das Property "TargetWarehouse" gilt, wie von Ihnen bereits vermutet, nur für manuelle Lagerungsbelege.
Wir haben bereits begonnen, die Funktionalität der normalen Belegkette und der Manuellen Lagerung zu separieren.
Demnächst werden wir in diesem Zuge auch die Models dementsprechend trennen. 
Wir hoffen somit, solche Missverständnisse in Zukunft zu vermeiden.

Mit freundlichen Grüßen,
Vivien Schuboth
