### ISSUE TITLE
PaymentRequired - Anzahl Produktivmandanten überschreitet Lizenz (402 ProductionTenantCountNotLicensed)

### ISSUE THREAD

**Issue by Entaigner** [selectline-software/selectline-api#413]
### Details
- Current version number: 24.2
- [X] Test status checked in Mobile Manager
- Function or route (request): Egal
- Error (response): 
  - AuthenticationException
  - PaymentRequired (02-003)
  - Anzahl Produktivmandanten überschreitet Lizenz (402 ProductionTenantCountNotLicensed)

#### Steps to replicate the behavior:
Mit einer Händlerlizenz versuchen irgendeine Anfrage auszuführen.
Soweit ich weiß sollten Händlerlizenzen uneingeschränkt Mandanten anlegen können und in der Lizenz ist deshalb keine Anzahl hinterlegt.

**Comment by MaikGoertz** [comment]
Moin.
Hierbei handelt es sich um einen Fehler in der 24.2.0 wir werden dies korrigieren.

**Comment by MaikGoertz** [comment]
Moin.

Der Fehler ist in der aktuell ausgelieferten 24.2.1 korrigiert.

Gruß
Maik
