### ISSUE TITLE
/ArticleItem - Diese Art von Stücklisten wird in dieser Funktion nicht unterstützt.

### ISSUE THREAD

**Issue by LK-ML** [selectline-software/selectline-api#414]
### Details
Current version number: 23.2.3 Build 1008324
Previous version number (optional):
 Test status checked in Mobile Manager
**Function or route (request):** /documents/[key]/ArticleItem

/slmobileApi/Documents/P10100107/ArticleItem

ArticleNumber	"260012.L8"
CalculatedQuantityValue	1
StoreInformation	[…]
0	{…}
ArticleNumber	"260012.L8"
Quantity	1
SerialNumber	"handel"

**Error (response):**

Response:

/slmobileApi/Documents/P10100107/ArticleItem

StatusCode	"NotFound"
ResponseCode	"42-017"
ResponseId	17
ResponseIdDescription	"ParameterValueNotSupportedException"
Message	"Der übermittelte Parameterwert wird nicht unterstützt: articleNumber"
Details	Object { failure: "Diese Art von Stücklisten wird in dieser Funktion nicht unterstützt. Erlaubte Stücklisten hierfür sind K,P,R,Z" }

#### Steps to replicate the behavior

Im Backend ist es möglich, Artikel mit Stückliste Handel auf Packzettel zu setzen. 
Bei Zufügen dieser Artikel über /ArticleItem wird jedoch der obige Fehler zurückgegeben. 
Könnten Sie uns helfen zu verstehen, wie wir diese Artikel auf Packzettel setzen?

Vielen Dank :).

**Comment by ThePholph** [comment]
Siehe Doku:

POST ./Documents/{documentKey}/SalesBOMPosition 
POST ./Documents/{documentKey}/SalesBOMPosition/{documentPositionIdentifier}/BillOfMaterialItem

**Comment by bartoto** [comment]
Wir haben dasselbe Problem, allerdings bei Eingangsbelegen (Belegtyp E — Eingangsrechnung).

Im Desktop-Client kann der Stücklistenartikel problemlos als Position hinzugefügt werden — er wird automatisch als Zeilentyp A (normale Artikelposition) angelegt, da Eingangsbelege keine Stücklistenauflösung durchführen.

Über die API POST /Documents/{documentKey}/ArticleItem wird der Artikel jedoch mit demselben Fehler abgelehnt:
42-017: "Diese Art von Stücklisten wird in dieser Funktion nicht unterstützt.
Erlaubte Stücklisten hierfür sind K,P,R,Z"

Die API prüft offenbar die Stücklistenart des Artikels, bevor sie den Belegtyp berücksichtigt. Bei Eingangsbelegen sollte diese Prüfung entfallen, da H-Artikel hier ohnehin als A behandelt werden.

Betroffen: Eingangsbelege, Stücklistenart H
