### ISSUE TITLE
Fehlermeldung beim Wechsel des Mandanten

### ISSUE THREAD

**Issue by Torchok19081986** [selectline-software/selectline-api#415]
### Details
- Current version number: 24.2.1
- Previous version number (optional):  24.1
- [x] Test status checked in Mobile Manager 
- Function or route (request):  PUT /Users/Current
- Error (response): ERROR 2024-11-04 11:05:22 - [1] WriteError(): ERROR VTEDataTransfer.Log4NetClass - Errormessage -> Fehlermeldung : CustomerUebergeben Method IO.Swagger.Client.ApiException: Error calling UserUpdateCurrentUser: {
  "StatusCode": "InternalServerError",
  "ResponseCode": "04-000",
  "ResponseId": 0,
  "ResponseIdDescription": "Undefined",
  "Message": "HTTP 400 - BadRequest - 'PUT /api/SessionManagement/SessionInformation'\r\n\r\n -  ( )",
  "Details": null
}
   bei IO.Swagger.Api.UserApi.UserUpdateCurrentUserWithHttpInfo(SelectLineErpEntitiesWebApiUserUpdateModel userUpdateModel)
 
IO.Swagger.Client.ApiException: Error calling UserUpdateCurrentUser: {
  "StatusCode": "InternalServerError",
  "ResponseCode": "04-000",
  "ResponseId": 0,
  "ResponseIdDescription": "Undefined",
  "Message": "HTTP 400 - BadRequest - 'PUT /api/SessionManagement/SessionInformation'\r\n\r\n -  ( )",
  "Details": null
}
   bei IO.Swagger.Api.UserApi.UserUpdateCurrentUserWithHttpInfo(SelectLineErpEntitiesWebApiUserUpdateModel userUpdateModel)
   
DEBUG 2024-11-04 11:05:29 - [1] Log4NetClass->WriteDebugInfo(): DEBUG Log4NetClass 
INFO  2024-11-04 11:05:32 - [1] Log4NetClass->WriteInfo(): INFO Log4NetClass - Infomessag : Alle Benutzer werden von Mobile API abgemeldet.
[End]

Ändern der Benutzer zu ausgewählten Datenbank nicht mehr seit Update auf 24.2.1 Mobile Manager möglich. 
```csharp
userApi.UserUpdateCurrentUserWithHttpInfo(user);
```

**Comment by QS-Stang** [comment]
Als eine ergänzug, da ich vermute das gleiche Problem zu haben 
Habe es über Swagger getestet.

Im Feld des Bodys bei AllowedTenantList erhalte ich einen NULL wert, auch wenn über den SelectLine Server der User für mehrere Mandanten die API rechte hat. 

Wenn ich übeder die API Route zwischen den Mandanten wechsle wird der Wechsel des Mandanten erst übernommen wenn ich mit dem API User mich nochmal neu Authentifiziere.
Das gleiche verhalten wenn ich den wechsel zwischen den Mandanten über den SelectLine Server anstoße.

**Comment by Torchok19081986** [comment]
Hallo @QS-Stang. Vielen Dank für die Info und Bestätigung. Ich habe nur ein kleines Problemchen hier. Ich melde zwei Benutzer gleichzeitig und einer ist fest und andere ist dynamisch. Dieser Wechsel findet nicht statt. Benutzer sind bereits authentifiziert. Warum noch mal Authentifizierungsanforderung senden ?

**Comment by MaikGoertz** [comment]
Moin.

Mit welchem Wert wird `TenantDatabaseName` befüllt?
Aktuell erwarten wir einen vollständigen Datenbanknamen, wie bspw. "SL_MWAWI".
Wir werden das aktuelle Verhalten wiederherstellen, dass auch nur der Mandantenbezeichner, wie "WAWI", eingetragen werden kann.

Gruß
Maik

**Comment by Torchok19081986** [comment]
Hallo, TentantDatabaseName is mit WAWI und WUNDF aus Muster Mandanten befüllt, für Beispiel. Auch die Abfrage per API liefert diese Namen zurück.

**Comment by QS-Stang** [comment]
@Torchok19081986 tut mir leid, ich hatt die Nachricht übersehen, mir ist nur aufgefallen das bei erneuten Login des Users per API der Wechsel doch erfolgreich war aber warum, kann ich nicht nachvollziehen,


@MaikGoertz 
 über Swagger erhalte ich bei der Abfrage den Body
 { ....
  "TenantDatabaseName": "SL_MTEST",
  "TenantDatabaseVersion": null,
  "YearDatabaseName": "",
  "UserKind": "MobileApi",
  "UserName": "Administrator",
  "WawiUserToken": "AB",
  "AllowedTenantList": null,
.....
}

und nach einem wechsel zum Mandanten WAWI und einem erneuten Login per API 
  {...
"TenantDatabaseName": "SL_MWAWI", ...
  "AllowedTenantList": null,
...}

**Comment by Torchok19081986** [comment]
Hallo QS-Stang, ich habe auch im swagger getestet. Auch hier hatte ich Fehlermledung 04-000 von API als Response.  API liefert nur den Name von Mandanten, aber nicht wie Herr @MaikGoertz geschrieben hat, vollständigen Namen mit vorangegangen SL_M prefix. Keine Ahnung warum es vorher anders war.  Deshalb konnte ich auch per API Mandnaten bzw. User wecheseln.

**Comment by Torchok19081986** [comment]
Morgen,  wir haben gerade unsere Testsystem mit 24.2.2 aktualisiert. Ist dieses Verhalten nun in neuste Version gefixt oder müssen wir noch auf ein weiteres Updateversion warten ?

**Comment by MaikGoertz** [comment]
Moin.
Nein, die Korrektur hat es leider nicht in diese Version geschafft.

**Comment by Torchok19081986** [comment]
Vielen Dank für schnelle Antwort. Ich habe bereits in der 24.2.2 getestet. Danke für die Info. Ich warte auf weitere Version.

**Comment by MaikGoertz** [comment]
Die Korrektur ist in der heute ausgelieferten 24.2.3 enthalten.
