### ISSUE TITLE
Update von RestSharp.dll von 105.1.0 zu 111.X

### ISSUE THREAD

**Issue by Torchok19081986** [selectline-software/selectline-api#416]
### Details
- Current version number: 24.2.3
- Previous version number (optional): 24.2.2

Nach dem Generieren von neuen dlls aus Swagger Editor und C# für Client, bekommt man von RestSharp.dll die Version 105.1.0.0, und Update auf die Version 111.X bricht die Restsharp.dll wegen Änderungen in der neuesten Version. Laut der Website müssen die Änderungen in der RestClient durchgeführt werden.  Migrationslink : https://restsharp.dev/migration 
Hier habe ich ein paar Fragen: 
1. warum bekommt man nicht mehr die neuesten ReshSharp.dll aus Swagger? 
2. Wenn man die Änderungen im Sourcecode durchgeführt, kann es sein, dass die API von SL Mobile dann nicht mehr funktioniert? Und erwartet die ReshSharp Client in der Version 105.1.0.0 ? 

Torchok.

**Comment by MaikGoertz** [comment]
Moin.
Da der von Ihnen verwendete Code Generator nicht von uns entwickelt wurde, können wir dazu keine Auskunft geben.
Am besten Sie wenden sich an die Supportkanäle des Code Generators.

Gruß 
Maik
