### ISSUE TITLE
Beleg Status ändern 

### ISSUE THREAD

**Issue by QS-Stang** [selectline-software/selectline-api#419]
Relevantes Issue:
 #398

### Details
- Current version number: 24.2.4.0
- [x] Test status checked in Mobile Manager
- Function or route (request):  /Documents/{documentKey}/Status
- Error (response):
-  {
    "Details": "The permission 'Belege' (Funktion.Erp.39061b35-76c0-42a0-b0e2-7f0d28b593af) is for another application.",
    "Fehler": "Sie besitzen nicht das Recht \"Übernahmestatus manuell ändern\" für die Option \"Belege\".",
    "Title": "Rechteverwaltung",
    "ExceptionName": "ERechtException"
  }

#### Steps to replicate the behavior:
Im Swagger 
auf dem WAWI Mandanten mit der API Route versuchen einen Auftrag-Beleg ohne Bearbeitungsstatus 
mit {"Value":3, "Name": "CompletedManually"} auf manuell erledigt setzen,

beim Rechnung (mit Bearbeitungsstatus)
Ändern des Status auf 0 oder 5 funktioniert aber bei ändern auf status 0-> 3 
kommt die Response 204, aber der Status wird nicht geändert.

###

mit dem gleichen User auf dem gleichen Beleg geht es über die SelectLine den Status zwischen 0 und 3 hin und her zu wechseln,
![grafik](https://github.com/user-attachments/assets/471674ae-1f23-445d-910d-bc2a4274c513) ![grafik](https://github.com/user-attachments/assets/ce689957-9e76-4a19-8e2a-571deed91df7)

**Comment by ThePholph** [comment]
Hallo,

der Fehler soll in der 24.2.7 gefixt sein, laut Support.

VG Daniel

**Comment by QS-Stang** [comment]
Hallo ,
konnte es gestern kurz Testen und kann bestätigen es funktioniert jetzt in der Version 24.2.7
