### ISSUE TITLE
Preisstaffeln, Rabattstaffeln, Kundenpreise über API ausgeben lassen

### ISSUE THREAD

**Issue by Balram-Git** [selectline-software/selectline-api#43]
Hallo Leute ich möchte mir Preisstaffeln, Rabattstaffeln, Mengenstaffeln und Kundenpreise über API ausgeben lassen. Habe den /Articles GET ausprobiert, aber dort wird nichts in der Hinsicht ausgegeben.
Vielen Dank im Voraus!
Gruß Balram

**Comment by Balram-Git** [comment]
Wie bekomme ich z.B. die Daten aus der Tabelle arpreis

**Comment by VivienSchuboth** [comment]
Guten Tag,
diese Funktionalität wird über die SelectLine API noch nicht angeboten.
Falls Sie sich diese Funktionalität dennoch wünschen, stellen Sie einfach einen Eintrag in unser UserVoice-Forum ein oder falls bereits vorhanden, stimmen Sie für diesen Wunsch ab.
Diese Stimmen beeinflussen die Reihenfolge, in der wir die Themen bearbeiten.

Mit freundlichen Grüßen,
Vivien Schuboth

**Comment by Balram-Git** [comment]
Hallo Vivien, alles klar! Vielen dank für die schnelle Antwort.
