### ISSUE TITLE
Paketnummer Transportdienstleister und Sendungsverfolgung mit der API abfragen

### ISSUE THREAD

**Issue by mbuhl11** [selectline-software/selectline-api#44]
Hallo! 
Wie schon aus dem Titel ersichtlich, versuche ich gerade eine Möglichkeit zu finden, die Sendungsverfolgung eines Belegs mit der API abzurufen, für den Anfang wäre ich auch mit der Paketnummer und dem Transportdienstleister zufrieden. 
Jedoch habe ich dazu nichts in der Dokumentation oder in meinen Response-Strings gefunden. 
Extrafelder würden mir an dieser Stelle auch nichts nützen, da man diese ja leider nicht mit einem einzigen GET für mehrere Belege abrufen kann

**Comment by ThorstenPoppe** [comment]
Das ist wohl derzeit nur über ein Macro (API-Makro, nicht WaWi Makro) möglich.
Die Daten sind ja in der Tabelle PAKET zu finden.

**Comment by mbuhl11** [comment]
Danke für die Antwort. 
Wir hatten uns dann auch für den direkten Weg über SQL entschieden, das Problem wurde also gelöst.
