### ISSUE TITLE
Swagger Model Doku fehlerhaft

### ISSUE THREAD

**Issue by ThorstenPoppe** [selectline-software/selectline-api#46]
Hallo,

leider ist die aktuelle Model Doku fehlerhaft, so dass mit dem Swagger-Codegen entsprechend fehlerhafter Code generiert wird.
Das betrifft die aktuelle Version 20.2.3 und z.B. das Model "Article". Im untergeordneten Model Payment (ArticleDetailPayment) wird angemeckert, dass das Property ProfitAccountGroupLabel eine max Länge von 6 Zeichen haben darf - hierbei handelt es sich aber um das Label und nicht um die Nummer (ProfitAccountGroupNumber).
[ArticleDetailPayment](https://demo.slmobile.de/demoApi/Help/ResourceModel?modelName=ArticleDetailPayment) 

Wie ist hier generell die Intension, wird die Swagger Api-Beschreibung gewissenhaft aktualisiert, so dass man damit bei neuen Version auch einen aktuellen Code für einen Client erzeugen kann? Das wäre sehr hilfreich, um den eigenen Client entsprechend mit allen Models und Routen aktuell zu halten.

Viele Grüße,
Thorsten Poppe

**Comment by VivienSchuboth** [comment]
Guten Tag,

diese Swagger-Modelle werden auf Basis unserer generellen API-Modelle generiert. Daher können Sie davon ausgehen, dass die Modelle aus dem Swagger-Codegen jederzeit mit den erwarteten Modellen der API übereinstimmen.

Die fehlerhafte Limitierung der Zeichen ist ein davon unabhängiger, allgemeiner Fehler der API, welchen wir demnächst korrigieren werden.
Der Nummer stehen maximal 13 Zeichen zu. Das Label kann 80 Zeichen beinhalten.

Mit freundlichen Grüßen,
Vivien Schuboth

**Comment by VivienSchuboth** [comment]
Guten Tag,

noch eine Ergänzung dazu: 
Das Feld für die Bezeichnung der Erfolgskontengruppe _ProfitAccountGroupLabel_ kann aktuell nur gelesen werden.

Falls Sie sich das Schreiben dieses Feldes wünschen, stellen Sie gern dazu einen Wunsch im Wünscheforum ein. https://selectline.uservoice.com

Mit freundlichen Grüßen,
Vivien Schuboth

**Comment by VivienSchuboth** [comment]
Die fehlerhafte Limitierung der Zeichen ist mit der nächsten Version (21.1) behoben.

MfG
Vivien Schuboth
