### ISSUE TITLE
Binärdaten per API-Makro in die Datenbank schreiben

### ISSUE THREAD

**Issue by chucky2002** [selectline-software/selectline-api#47]
Über die Makro-API soll auf die BILD-Tabelle lesend und schreibend zugegriffen werden. 

Das Auslesen funktioniert bereits mit select 1 * from bild. Die Daten aus der Spalte "BILD" werden in BASE64 codiert zurück gegeben was ich wunderbar in meiner Anwendung auswerten kann.
Doch wie kann ich die Daten im Binärformat in der BILD-Tabelle per INSERT oder UPDATE einfügen? Ziel soll es sein das ich per API Daten in die BILD-Tabelle schreiben kann, die dann in der WAWI im Artikelstamm auch angezeigt werden können

**Comment by VivienSchuboth** [comment]
Guten Tag,

aktuell wissen wir nicht ob und wie sie Daten dort einfügen oder aktualisieren können.

Falls Sie sich das Schreiben bzw. Bearbeiten von Daten in die BILD-Tabelle direkt über die API wünschen, stellen Sie doch gerne einen Wunsch in das UserVoice-Forum ein. https://selectline.uservoice.com

Mit freundlichen Grüßen,
Vivien Schuboth

**Comment by chucky2002** [comment]
Welche Details benötigen Sie um die Frage zu beantworten?

Gibt es irgendwo ein Beispiel welches beschreibt wie man Binärdaten über die MAcro API in der Datenbank ablegt?

Es reicht nicht aus die Funktion nur für die Bild-Tabelle bereit zu stellen.

**Comment by VivienSchuboth** [comment]
Uns steht selbst kein Beispiel zur Verfügung, indem Binärdaten über die Macro API in die Datenbank abgelegt werden können.
Bei einer kurzen Recherche konnten wir leider auch keine Lösung finden.

Was würde Ihnen bei dieser Variante fehlen?

Mit freundlichen Grüßen,
Vivien Schuboth

**Comment by ThePholph** [comment]
Hallo,

ich nutze die WaWi-Makros für viele Dinge, die nicht über die API-Funktionen realisiert werden können (siehe /slmobileApi/Help/Api/POST-Macros). Hier einfach ein Makro erstellen und die notwendigen Daten als Parameter via Post an den Endpunkt /Macros übergeben.

Bsp.:
```
{
  "MacroName": "AddPicture",
  "Parameters": [
    {
      "Name": "Picture",
      "Value": "Converted Image to VARBINARY"
    }
  ]
}
```

Wie Bilder in VARBINARY konvertiert werden, ist im Netz gut dokumentiert. Jedoch weiß ich nicht, ob solch lange Zeichenketten als Makro-Parameter von der API verarbeitet werden. Hier kommt es auf einen Versuch an.

Vielleicht hilft es ja weiter.

Viele Grüße

Daniel

**Comment by chucky2002** [comment]
Dazu folgendes Beispiel.

Vorausgesetzt wird ein Artikel mit der Artikelnummer "1" im Artikelstamm, sowie folgendes Beispielbild: ![testbild](https://user-images.githubusercontent.com/3708455/94673213-b376c000-0316-11eb-9cd9-3aa45ff3931c.png) 

Wenn ich das Tesbild über den Artikelstamm der SelectLine WAWI an den Artikel "1" anfüge, wird mir dieses im Artikelstamm angezeigt ![Artikelstamm 1](https://user-images.githubusercontent.com/3708455/94673280-c9848080-0316-11eb-9ed9-a8a2c7f6902b.png) .

Die Abfrage der Bild-Daten über
`select bild from bild where blobkey = 'AR1'`

liefert mir folgenden Datenstrom zurück.
`0x89504E470D0A1A0A0000000D494844520000000A0000000A0802000000025058EA000000017352474200AECE1CE90000000467414D410000B18F0BFC6105000000097048597300000EC300000EC301C76FA8640000002949444154285375C741090000080430FBC7309D250EFCCA40D86795A47A5E1E1E1E1E1E1E1E1EFEEA59939C9B56A1588C1F0000000049454E44AE426082`


Wenn ich folgendes Statement in der Datenbank ausführe, wird das Bild korrekt in die Datenbank geschrieben
```/* Artikelbild löschen */
delete from bild where blobkey = 'AR1'

/* Artikelbild einfügen */
insert into bild(blobkey, Dateiname, Ordnung, Bild)
select 'AR1', '', 0, 0x89504E470D0A1A0A0000000D494844520000000A0000000A0802000000025058EA000000017352474200AECE1CE90000000467414D410000B18F0BFC6105000000097048597300000EC300000EC301C76FA8640000002949444154285375C741090000080430FBC7309D250EFCCA40D86795A47A5E1E1E1E1E1E1E1E1EFEEA59939C9B56A1588C1F0000000049454E44AE426082
```


Wenn ich das Bild mit folgenden Statemen in die Datenbank schreibe, bekomme ich einen Fehler im Artikelstamm 
```/* Artikelbild löschen */
delete from bild where blobkey = 'AR1'

/* Artikelbild einfügen */
insert into bild(blobkey, Dateiname, Ordnung, Bild)
select 'AR1', '', 0, cast('0x89504E470D0A1A0A0000000D494844520000000A0000000A0802000000025058EA000000017352474200AECE1CE90000000467414D410000B18F0BFC6105000000097048597300000EC300000EC301C76FA8640000002949444154285375C741090000080430FBC7309D250EFCCA40D86795A47A5E1E1E1E1E1E1E1E1EFEEA59939C9B56A1588C1F0000000049454E44AE426082' as varbinary(max))
```

![Artikelstamm 2](https://user-images.githubusercontent.com/3708455/94673458-0d778580-0317-11eb-985b-b9122ca1b3ce.png)


Num zum Test um Binärdaten über die REST-API zu schreiben

Beim Aufruf über die REST-API habe ich in der Tabelle "APIMACRO" ein Makro wie folgt eingefügt
```
/* sicherstellen das das Makro nicht existiert */
delete from SL_MGOLTZ.dbo.APIMACRO where name = 'setbild'

/* Makro einfügen */
INSERT INTO SL_MGOLTZ.dbo.APIMACRO (Name, Text) VALUES (N'setbild', N'/* Artikelbild löschen */
delete from bild where blobkey = ''AR1''

/* Artikelbild einfügen */
insert into bild(blobkey, Dateiname, Ordnung, Bild)
select ''AR1'', '''', 0, :param1');
```

Danach sende ich folgenden POST-Request an die Datenbank
```
### einfacher Makro-Aufruf
POST {{host}}/Macros/setbild
Accept: application/json
Authorization: LoginId {{AccessToken}}

[
  {
    "Name": "param1",
    "Value": "0x89504E470D0A1A0A0000000D494844520000000A0000000A0802000000025058EA000000017352474200AECE1CE90000000467414D410000B18F0BFC6105000000097048597300000EC300000EC301C76FA8640000002949444154285375C741090000080430FBC7309D250EFCCA40D86795A47A5E1E1E1E1E1E1E1E1EFEEA59939C9B56A1588C1F0000000049454E44AE426082"
  }
]
```

und bekomme folgenden Fehler zurück:
> POST https://vm-sql-win10/slmobileApi/Macros/setbild
> 
> HTTP/1.1 500 Internal Server Error
> Cache-Control: no-cache
> Pragma: no-cache
> Content-Type: application/json; charset=utf-8
> Expires: -1
> Server: Microsoft-IIS/10.0
> X-AspNet-Version: 4.0.30319
> X-Powered-By: ASP.NET
> Date: Wed, 30 Sep 2020 10:12:02 GMT
> Content-Length: 265
> 
> {
>   "StatusCode": "InternalServerError",
>   "ResponseCode": "70-000",
>   "Message": "Die implizite Konvertierung vom nvarchar-Datentyp in varbinary(max) ist nicht zulässig. Verwenden Sie die CONVERT-Funktion, um diese Abfrage auszuführen.",
>   "Details": null
> }
> 
> Response code: 500 (Internal Server Error); Time: 205ms; Content length: 263 bytes

**Comment by ThePholph** [comment]
Hallo,

es gibt hierbei zwei Probleme:

1. Beim ersten SQL-Aufruf wurde nicht berücksichtigt, dass Daten in einer VARBINARY-Spalte als Bytes gespeichert (8-Bit-Mengen ohne Vorzeichen) werden. Daher ist es notwendig in diesem Fall eine 0 anzufügen. Funktioniert jedoch nur im Editor direkt ohne Parameter.

2. Die Parameter von Makros werden nicht 1 zu 1 übergeben, sondern immer schon vorher interpretiert, sodass hier z.B. immer varchar(max) als Resultat entsteht. Dies führt dazu, dass keine saubere Konvertierung via SQL durchgeführt werden kann. 

Als Lösungsansatz wäre evtl. ein eigener Service zwischen bzw. neben SL.API und Client einzusetzen, der die Files via Upload entgegennimmt und in der DB via .Net-Framework oder SQL-Skript bzw. Makro ablegt.

Beispiel SQL-Skript nach Datei-Upload durch Service:

```
/* Artikelbild einfügen */
insert into bild(blobkey, Dateiname, Ordnung, Bild)
SELECT 'AR1', '', 0, BulkColumn 
FROM Openrowset(Bulk '{Freigabe oder lokales Verzeichnis}\Bild.png', Single_Blob)
```

Ich hoffe, ich konnte helfen.

Viele Grüße

Daniel

**Comment by jprause1234** [comment]
Hallo,

jetzt möchte ich doch nochmal die Frage in die Runde werfen, ob die Anbindung der Bild Tabelle per API nicht die Lösung wäre? Darüber würde man dann, analog zu den Attachements eines Journals, die Bilder direkt per API in die Bild Tabelle schreiben.

Viele Grüße
Jan Prause

**Comment by ThePholph** [comment]
@jprause1234 Das wäre die ideale Lösung 👍 

Ich weiß ja nur nicht welcher Zeithorizont bei @chucky2002 vorgesehen ist.

Viele Grüße

Daniel

**Comment by chucky2002** [comment]
@jprause1234  Das hinterlegen von Binärdaten nur in der Bild-Tabelle zu ermöglichen ist zu kurz gedacht. Einerseits gibt es neben der BILD-Tabelle auch andere, in welchen Binärdaten hinterlegbar sind (das Journal fällt mir dazu ein). Und andererseits muss es auch möglich sein in selbst angelegten Tabellen Binärdaten zu speichern.

Inzwischen konnte ich das ganze lösen. Ich gehe beim Speichern der Daten nun wie folgt vor.

1.  Leeren Datensatz in der Bild-Tabelle anlegen
```
declare @param_blobkey nvarchar(38);
declare @param_ordnung int;
            
set @param_blobkey = convert(nvarchar(38), :blobkey);
set @param_ordnung = convert(Integer, :ordnung);
                        
insert into bild(blobkey, Ordnung, bild)
select @param_blobkey, @param_ordnung, convert (varbinary(max),'',2);
```

2.  Ich kodiere den Datenstrom nach Base64 und unterteile ihn Zeichenketten mit einer Maximallänge von 4000000-Zeichen.
Für jede der Zeichenketten wird dann folgendes Makro aufgerufen:
```
declare @param_blobkey nvarchar(38);
declare @param_ordnung int;
declare @param_data nvarchar(max)

set @param_blobkey = convert(nvarchar(38), :blobkey);
set @param_ordnung = convert(Integer, :ordnung);
set @param_data = cast(:base64data as nvarchar(max));
            
            
declare @encoded varchar(max);
declare @decoded varbinary(max)
set @encoded = @param_data;
set @decoded =  cast('' as xml).value('xs:base64Binary(sql:variable("@encoded"))', 'varbinary(max)');                                   

update bild
set bild = isnull(bild, convert (varbinary(max),'',2)) + @decoded 
where blobkey = @param_blobkey
  and ordnung = @param_ordnung 
```

Dies sorgt dafür das bei jedem Aufruf der Datenstrom der 4000000 an einen bereits existierenden Bild-Datensatz angehangen wird. Da die Daten in Base64 Codierung an die API übertragen werden, erfolgt zudem noch eine Rückconvertierung nach varbinary in die Variable `@decoded`.

Das ganze funktioniert für meinen Verwendungszweck praktikabel.
- Durch die Verwendung von Base64 ist es mir möglch die Binärdaten in JSON-Format an die SL.API zu übergeben.  
- Das Chunking ermöglicht mir beliebig große Datenmengen zu übertragen. 
- Durch die Verwendung der Macros-Resource kann ich beliebige Tabellen ansprechen.

**Comment by ThePholph** [comment]
@chucky2002 Das sieht sehr gut aus 👍 Ist eine schöne praktikable Lösung. 

Trotzdem würde ich eine Lösung via API immer bevorzugen, auch in Bezug auf Gewährleistung und Datenbankkonsistenz.

Viele Grüße 

Daniel

**Comment by jprause1234** [comment]
Danke @chucky2002 für das Teilen der Lösung.

Was die Binärdaten angeht, aktuell werden Journalanhänge, die Beleg Unterschriften und die Artikelbilder in der Datenbank abgelegt. Für die Journalanhänge und die Unterschriften gibt es bereits eigene Routen. Somit fehlen nur noch die Artikelbilder. In Extratabellen können keine Binärdatenfelder per Wawi angelegt werden.
Daher meine ursprüngliche Frage, wozu die Funktionalität noch benötigt wird.

Viele Grüße
Jan

**Comment by chucky2002** [comment]
@jprause1234  
- Nützlich ist die Funktion für Zusatzprogrammierungen die ihre Daten zwar in der SelectLine Datenbank ablegen möchten, wo die Nutzdaten aber nicht in die Datenbankstruktur passt. Wir können das auch gern noch nächste Woche Donnerstag zur Schulung im Detail vertiefen

- Wie hoch ist das Limit der Upload-Datei bei den bereits implementierten Routen?

**Comment by jprause1234** [comment]
Ich habe zu dem Thema Dateigröße folgenden Eintrag bei Stackoverflow gefunden:
![grafik](https://user-images.githubusercontent.com/26381693/97845221-9bff6e00-1cec-11eb-9ec9-110919918bcf.png)
