### ISSUE TITLE
Wie kann ich eine Belegposition vom Zeilentyp "K" einfügen?

### ISSUE THREAD

**Issue by ws-doubleus** [selectline-software/selectline-api#48]
... bzw. gibt es eine Möglichkeit einen kompletten Beleg zu kopieren?

**Comment by VivienSchuboth** [comment]
Guten Tag,
das Anlegen von Kommentaren steht Ihnen ab der nächsten Version, der 20.3, zur Verfügung.

Das Kopieren von reinen Belegdaten ist derzeit nur manuell möglich.
Wenn dieser manuelle Weg für Sie nicht ausreicht, stellen Sie gern dazu einen Wunsch im [Wünscheforum](https://selectline.uservoice.com)  ein. 

Mit freundlichen Grüßen,
Vivien Schuboth
