### ISSUE TITLE
PUT funktioniert nicht im PHP Beispiel

### ISSUE THREAD

**Issue by danix33** [selectline-software/selectline-api#49]
Hallo zusammen, 

leider ist es mir nicht gelungen PUT mit dem genannten PHP Beispiel zu nutzen.

Beispiel:
https://192.168.144.117:444/slmobileApi/Documents/GG-20200004/Positions/6D7CC468-A99F-46CB-82A5-34778707F9B2

$returnValue = CallSLMAPI("PUT", $BaseUri."Documents/".$documentkey."/Positions/6D7CC468-A99F-46CB-82A5-34778707F9B2", $authorizationString, '{"UnitPrice": 1}', true);

Es entsteht folgender Fehler: 
{ "StatusCode": "BadRequest", "ResponseCode": "42-007", "Message": "Es wurde kein Parameter übermittelt. Nähere Informationen sind in den Details enthalten.", "Details": null }

Lässt man sich dort aber $data ausgeben, ist sehr wohl Inhalt vorhanden:
{"UnitPrice": 1}

Ist das Problem schon bekannt?

**Comment by ThePholph** [comment]
Hallo,

das Beispiel enthält einen Fehler in Zeile 40. Hier wird das Objekt $data nicht übergeben, sondern lediglich eine 1.

Falsch:

```
switch ($method)
{
    case "POST":
        curl_setopt($curl, CURLOPT_POST, 1);
        if ($data)
            //curl_setopt($curl, CURLOPT_POSTFIELDS, "{'UserName':'APIDemo','Password':'Ap1Dem0'}");
            curl_setopt($curl, CURLOPT_POSTFIELDS, $data);
         break;
    case "PUT":
         curl_setopt($curl, CURLOPT_PUT, 1);
         break;
    default:
        if ($data)
            $url = sprintf("%s?%s", $url, http_build_query($data));
}
```

Richtig:

```
switch ($method)
{
    case "POST":
        curl_setopt($curl, CURLOPT_POST, 1);
        if ($data)
            //curl_setopt($curl, CURLOPT_POSTFIELDS, "{'UserName':'APIDemo','Password':'Ap1Dem0'}");
            curl_setopt($curl, CURLOPT_POSTFIELDS, $data);
         break;
    case "PUT":
         curl_setopt($curl, CURLOPT_PUT, $data);
         break;
    default:
        if ($data)
            $url = sprintf("%s?%s", $url, http_build_query($data));
}
```

Ich hoffe, ich konnte helfen.

Viele Grüße

Daniel

**Comment by danix33** [comment]
Hi Daniel, vielen Dank. Das hatte ich leider auch schon probiert, dann kommt aber komischerweise folgender Fehler dabei raus:

https://192.168.144.117:444/slmobileApi/Documents/GG-20200004/Positions/6D7CC468-A99F-46CB-82A5-34778707F9B2
{ "Message": "The requested resource does not support http method 'GET'." }

bei der Anfrage:
$returnValue = CallSLMAPI("PUT", $BaseUri."Documents/".$documentkey."/Positions/6D7CC468-A99F-46CB-82A5-34778707F9B2", $authorizationString, '{"UnitPrice": 1}', true);

**Comment by ThePholph** [comment]
Hallo,

sry, ich bin nicht der PHP-Guru, daher ist mir ein Fehler unterlaufen.

Versuch es so:

```
switch ($method)
{
    case "POST":
        curl_setopt($curl, CURLOPT_POST, 1);
        if ($data)
            //curl_setopt($curl, CURLOPT_POSTFIELDS, "{'UserName':'APIDemo','Password':'Ap1Dem0'}");
            curl_setopt($curl, CURLOPT_POSTFIELDS, $data);
         break;
    case "PUT":
         curl_setopt($curl, CURLOPT_CUSTOMREQUEST, 'PUT');
		 if ($data)
			curl_setopt($curl, CURLOPT_POSTFIELDS, $data);
         break;
    default:
        if ($data)
            $url = sprintf("%s?%s", $url, http_build_query($data));
}
```

Hoffe nun funktioniert es.

Viele Grüße

Daniel

**Comment by danix33** [comment]
Super, Daniel. Es funktioniert das wars :-) manchmal sieht man den Wald vor lauter Bäumen nicht mehr :-) ähnlich hatte ich es auch schon einmal probiert, aber den CUSTOMREQUEST nicht auf dem Schirm gehabt. Danke nochmal
