### ISSUE TITLE
GET... /documents is missing ExtraFieldsWithType

### ISSUE THREAD

**Issue by aameyer** [selectline-software/selectline-api#5]
Using SelectLine V19.3.10. 
I've created some extra fields in table BELEG, but a GET.../Documents request only returns "ExtraFieldsWithType": [],
It did work with table BELEGP and GET.../Documents/{documentKey}/Positions, so I assume it should be the same here.

**Comment by VivienSchuboth** [comment]
Hello,
we are sorry for the trouble.
That feature isn't currently on our development roadmap. But we will fix this mistake in our documentation soon. It's only possible to read "ExtraFieldsWithType" of single documents or positions at the moment.

Best regards,
Vivien
