### ISSUE TITLE
Ein/Auslagerung Manueller Beleg

### ISSUE THREAD

**Issue by Lars-Mue** [selectline-software/selectline-api#50]
Hallo zusammen, 

ist das möglich über die API eine Einlagerung oder Auslagerung in einem manuellen Beleg buchen?
Ich habe hierzu leider nichts in der Swagger Dokumentation gefunden. 

Vielen Dank im Voraus für eine Antwort.

Viele Grüße

**Comment by jprause1234** [comment]
Hallo,

ja, das geht, das wird auch in SelectLine MDE entsprechend verwendet. Die passenden Routen dazu sind in eine eigene Ressource "Manual Storage" gewandert (https://demo.slmobile.de/demoApi/Help/Api/POST-ManualStorages-manualStorageNumber-Positions-Store).
Die Beschreibung der API Funktion ist leider nicht gut. Das passen wir an.
Für eine Einlagerung ist die Mengenangabe positiv und für eine Auslagerung negativ anzugeben. Für diese beiden Lageraktionen darf auch nur StoragePlaceIdentifier oder Warehouse angegeben werden.
Für eine Umlagerung ist die Mengenangabe positiv anzugeben und sowohl StoragePlaceIdentifier/Warehouse als auch TargetStoragePlaceIdentifier/TargetWarehouse anzugeben.
Ich hoffe das hilft weiter.

Viele Grüße
Jan
