### ISSUE TITLE
Belegübergabe in den Packzettel 

### ISSUE THREAD

**Issue by Lars-Mue** [selectline-software/selectline-api#51]
Hallo zusammen, 

wir haben leider seit der 20.3 das Problem , dass folgender Endpunkt nicht mehr richtig funktioniert. 
/Documents/{documentKey}/Successors

Der Beleg wird soweit richtig übergeben.  Die Belegpoistionen werden leider Ohne Menge übergeben. 
Hier mein Body:
{
   "DocumentKindDestination":"P",
   "positions":[
      {
         "identifier":"759EBE9D-D4B9-4901-B526-D66096C441F3",
         "articleNumber":"BB-BU-250",
         "quantity":3.0
      },
      {
         "identifier":"115B0BF8-B106-43B8-9B33-3210D53025FF",
         "articleNumber":"MO-CA-250",
         "quantity":2.0
      },
      {
         "identifier":"C54A24F2-AE5A-4F4E-A303-94308C8319CF",
         "articleNumber":"DE-GUL-500",
         "quantity":2.0
      },
      {
         "identifier":"AD9B479C-3F5B-451A-ADA2-DE22215729E3",
         "articleNumber":"DE-BS-80",
         "quantity":2.0
      },
      {
         "identifier":"5D56396C-5F21-4335-A13A-3A5BBBA0CB0E",
         "articleNumber":"BB-CC-430",
         "quantity":2.0
      },
      {
         "identifier":"675D1125-64B1-445C-AACC-F1F9231A7F69",
         "articleNumber":"DE-SA-90",
         "quantity":1.0
      },
      {
         "identifier":"4A08EE42-E6A1-4939-96CA-620A05285295",
         "articleNumber":"VER",
         "quantity":1.0
      },
      {
         "identifier":"746D6A54-23B1-4E61-BF4D-D1328DF82EFA",
         "articleNumber":"VP",
         "quantity":1.0
      }
   ]
}

Was mache ich hier falsch? 

Vielen Dank und grüße

**Comment by Lars-Mue** [comment]
Hallo, 

dieses Thema ist uns extrem wichtig. Die API welche bei unserem Kunden bis  zur Version 2.2 Problemlos gelaufen ist macht bei dem oben aufgeführten Endpunkt nun Massive Schwierigkeiten. 
Ich bitte um baldige Rückmeldung

**Comment by VivienSchuboth** [comment]
Guten Tag,
wir haben den Fehler bei uns intern nachstellen können und werden diesen beheben.

Mit freundlichen Grüßen,
Vivien Schuboth

**Comment by ThePholph** [comment]
Hallo, 
ist schon bekannt in welcher Version das Problem behoben ist? Da wir die Funktion ebenfalls im Einsatz haben.

Vielen Dank.

Viele Grüße

Daniel

**Comment by VivienSchuboth** [comment]
Guten Tag,
der Fehler wurde mit der V20.3.2 behoben.

Mit freundlichen Grüßen,
Vivien Schuboth

**Comment by ThePholph** [comment]
Hallo,

ich habe dazu noch eine Bitte: Wäre es möglich, dass in der Liste "Neuerungen und Korrekturen" (changelog) die Issue-Nummer (in dem Fall #51), wie die Vorgangs / Servicenummer, aufgeführt wird? Da aus den Beschreibungen nicht immer klar hervorgeht, welcher Fehler im einzelnen Behoben wurde.

Vielen Dank.

Viele Grüße

Daniel

**Comment by VivienSchuboth** [comment]
Das ist eine sehr gute Idee! Ich werde diesen Wunsch gerne weitertragen.

Viele Grüße,
Vivien
