### ISSUE TITLE
Belegübergabe - Unbekannter Fehler

### ISSUE THREAD

**Issue by Grewamor** [selectline-software/selectline-api#52]
Ich habe beim Kunden das Problem einen Beleg per API in ein anderen zu übergeben.
Mit der Mandantensicherung in unserer Händler-Umgebung geht es problemlos. Auch beim Kunden direkt in der SL gibt es keine Probleme. Es springen keine Fenster auf.
Backendmanager wurde neu gestartet und auch die Webseite neu eingerichtet.
Hier ist das Resultat direkt vom Swagger:

![1 (1)](https://user-images.githubusercontent.com/18594343/95842943-71eb0980-0d47-11eb-9abe-931384f1a208.PNG)
![2 (1)](https://user-images.githubusercontent.com/18594343/95843320-da39eb00-0d47-11eb-9059-aeed8ac5b1d6.PNG)

SelectLine 20.2.10
SL.mobile 20.2.3
 
Haben Sie eine Idee?

**Comment by VivienSchuboth** [comment]
Guten Tag,
könnten Sie bitte prüfen, ob in dem Programmdatenpfad der Warenwirtschaft die JSON-Datei "api_standardwerte_vorgabe" vorliegt?
Bis zur Version 20.2 der SelectLine Warenwirtschaft wird diese Datei noch zwingend dort erwartet. Fehlt diese, könnte das die Ursache sein.

Mit freundlichen Grüßen,
Vivien Schuboth

**Comment by Grewamor** [comment]
> Guten Tag,
> könnten Sie bitte prüfen, ob in dem Programmdatenpfad der Warenwirtschaft die JSON-Datei "api_standardwerte_vorgabe" vorliegt?
> Bis einschließlich der Version 20.2 der SelectLine Warenwirtschaft wird diese Datei noch zwingend dort erwartet. Fehlt diese, könnte das die Ursache sein.
> 
> Mit freundlichen Grüßen,
> Vivien Schuboth

Ja, die Datei ist mit folgenden Inhalt vorhanden:
```json
{
	"SollQuerverweiseEntfernen": false,
	"IstDestSatzBeiNullMengeLoeschenErlaubt": false,
	"SollAbbrechenBeiAuslaufartikel": false,
	"SollAbbrechenBeiInaktiv": false,
	"SollFertigenUndReservierenAnMengenAnpassen": false,
	"ToleranteLagerungBeiOffenerMenge": false,
	"SteuersatzAutomatischAnpassen": true
}
```

**Comment by VivienSchuboth** [comment]
Guten Tag,
könnten Sie sich bitte noch einmal über die SelectLine API anmelden und prüfen, ob sich im Mobile Manager unter Datenbank die Anzahl der laufenden Backend-Prozesse erhöht?

![image](https://user-images.githubusercontent.com/34538107/97001539-cefd7100-1538-11eb-9aa3-e6f89195930f.png)

Könnten Sie uns zudem die Log-Dateien des Kunden (unter _...\ProgramData\SelectLine Software\logs_)
zukommen lassen? Das könnte die Suche beschleunigen.
Dafür nutzen Sie bitte den, Ihnen vom Support zugewiesenen, FTP-Server. 
Schicken Sie dem Support bitte eine Email und verweisen auf die Entwicklungsabteilung oder auch gern speziell auf mich.


Mit freundlichen Grüßen,
Vivien Schuboth

**Comment by VivienSchuboth** [comment]
Guten Tag,

könnten Sie bitte prüfen, ob die SelectLine.API.Backend.exe im Verzeichnis der "Mobiles"-Installation (_..\SelectLine Software\Mobile Anwendungen\SelectLine API Backend\SelectLine.API.Backend.exe_) ebenfalls die Version 20.2.10 darstellt.
Dafür öffnen Sie den o.g. Pfad zur Datei, öffnen deren Eigenschaften und wechseln zu "Details".

![image](https://user-images.githubusercontent.com/34538107/97406768-0766cb80-18fa-11eb-9e1c-1059759a4b92.png)

Anschließend prüfen Sie bitte, ob auf dem Server, auf dem das "Mobiles"-Setup installiert wurde, unter Programme und Features ein Native Client gelistet ist.

![image](https://user-images.githubusercontent.com/34538107/97407009-5d3b7380-18fa-11eb-8ac1-21232662cedf.png)

Mit freundlichen Grüßen,
Vivien Schuboth

**Comment by Grewamor** [comment]
Vom Kunden habe ich dazu folgende Antwort:

> die „SelectLine.API.Backend.exe“  weist in der Dateiversion und Produktversion jeweils die 20.2.10 auf (siehe Anhang). Gefunden habe ich die Datei unter  „…\Program Files\SelectLine Software\SL.mobile\SelectLine API Backend\“

![EigenschaftenVon_SelectLine API Backend exe](https://user-images.githubusercontent.com/18594343/97898869-c4ad5500-1d38-11eb-8614-566fdca91a21.png)

> Der Native Client ist auch installiert (siehe Snapshot aus der Systemsteuerung). Allerdings wird mir der Bereich „Apps & Feature“ in den Einstellungen nicht geladen daher der Snap aus der Systemsteuerung.

![Systemsteuerung_SQL-ServerNativeClient](https://user-images.githubusercontent.com/18594343/97898887-caa33600-1d38-11eb-9219-d508cc07905e.PNG)

**Comment by VivienSchuboth** [comment]
Guten Tag,

dann würde ich empfehlen, eine Verlinkung zur SelectLine Warenwirtschaft auf dem Desktop anzulegen.
Danach öffnen Sie bitte die Eigenschaften dieser Verlinkung.

![image](https://user-images.githubusercontent.com/34538107/98664062-2cbbf680-234a-11eb-9ade-285cdafd7618.png)

Dort gibt es eine Eigenschaft "Ziel", in der auf die SelectLine Warenwirtschaft verwiesen wird. 
In dieses Feld tragen sie bitte noch folgende Werte ein: 
Bsp.: **servermode** **m**:wawi **kuerzel**:sv **passwort**:

'm': Der Name des Mandanten, Bsp. für den Mustermandanten, siehe oben
'kuerzel': Das Kürzel des WAWI-Benutzers
'passwort': Das zugehörige Passwort, falls vorhanden 

![image](https://user-images.githubusercontent.com/34538107/98664426-a6ec7b00-234a-11eb-8cdb-03291f32c108.png)

Übernehmen Sie danach die Änderung und öffnen Sie nun die Anwendung erneut.
Treten dabei Fehlermeldungen auf?

Bei Fragen melden Sie sich gerne.

Mit freundlichen Grüßen,
Vivien Schuboth

**Comment by Grewamor** [comment]
Vielen Dank für die Hilfe. Mittlerweile haben wir beim Kunden das System neu aufgesetzt. Nun klappt alles.
