### ISSUE TITLE
Zahlungsinformationen

### ISSUE THREAD

**Issue by dahormez** [selectline-software/selectline-api#53]
Wir entwickeln derzeit ein kleines Tool das auf SelectLine aufsetzt und die API der Software verwendet.
Das klappt auch alles wunderbar, dennoch habe ich eine kleine Rückfrage.

Wir rufen Kunden in SelectLine ab und benötigen Zahlungsinformationen, sowohl zum Abrufen als auch zum Aktualisieren.
Leider habe ich keine Resource gefunden die mir diese Daten, außer eine FinancialAccountId, liefert.

 Ist es möglich über die API IBAN, BIC und unser zugehöriges Bankkonto an Kunden zu pflegen?
- Falls ja, wie sieht in diesem Fall der Request aus?

**Comment by VivienSchuboth** [comment]
Guten Tag,
das Pflegen dieser Daten ist mit der SelectLine API derzeit nicht möglich.
Falls Sie sich diese Funktionalität für die SelectLine API wünschen, stellen Sie gern dazu einen Wunsch im Wünscheforum ein. https://selectline.uservoice.com

Mit freundlichen Grüßen,
Vivien Schuboth
