### ISSUE TITLE
Chargenzuordnung nicht möglich

### ISSUE THREAD

**Issue by danix33** [selectline-software/selectline-api#54]
Kann es sein, dass es keine Möglichkeit gibt mit der API eine Zuordnung einer Serien/Chargennummer zu einer Position vorzunehmen, wie in der Warenwirtschaft?
![2020-10-15_21h23_39](https://user-images.githubusercontent.com/72063374/96176597-dd420080-0f2c-11eb-902d-1fe0c49761d4.png)

**Comment by VivienSchuboth** [comment]
Guten Tag,
aktuell steht für diese Zuordnung keine Funktionalität in der SelectLine API zur Verfügung.
Falls Sie sich diese Funktionalität für die SelectLine API wünschen, stellen Sie gern dazu einen Wunsch im Wünscheforum ein. https://selectline.uservoice.com

Mit freundlichen Grüßen,
Vivien Schuboth
