### ISSUE TITLE
Belegdruck nicht möglich für Lieferscheine (L)

### ISSUE THREAD

**Issue by ondrejpokorny** [selectline-software/selectline-api#55]
Ich habe ein ähliches Problem wie #12

POST Documents/LL205374/Print
{
"NumberOfCopies":1,
"MasterName":"LIEFERSCHEIN1_POST",
"PrintTarget":"File"
}

Liefert:
500: Internal Server Error
{
  "StatusCode": "InternalServerError",
  "ResponseCode": "42-000",
  "Message": "Client.Send failed. See InnerException",
  "Details": null
}

Die URL des Dokuments ist richtig (GET Documents/LL205374 liefert das JSON-Objekt des Lieferscheins).
Der gleiche Aufruf über die alte COM-Schnittstelle erstellt die PDF-Datei problemlos.

Wie kann ich schauen, was falsch ist ("See InnerException")?

**Comment by VivienSchuboth** [comment]
Guten Tag,
haben Sie die Druckvorlage für Ihren Lieferschein bereits dementsprechend eingerichtet?
Den Namen der Zieldatei für den Belegdruck muss dort bereits vermerkt sein. 
_Beispiel: [V:0::DateiPDF:2:0::"lieferscheinXYZ.pdf"]_
Per API ist es nicht möglich diese Information mitzuschicken.

Genauere Informationen sollten Ihnen, wenn möglich, in "Details" zur Verfügung stehen. 
Leider ist dies bei Ihnen nicht der Fall. 
Die Alternative wäre, Ihre Logs auszuwerten bzw. von uns auswerten zu lassen. 
Diese liegen im Programmdatenpfad der Mobiles-Installation: _...\ProgramData\SelectLine Software\logs_

Mit freundlichen Grüßen,
Vivien Schuboth

**Comment by ondrejpokorny** [comment]
Guten Tag und danke für die schnelle Antwort,

ja, das DateiPDF-Feld ist in der Vorlage definiert und somit ist auch der Dateiname definiert.

Wie ich schon gesagt habe, der Druck über die COM-Funktion
`DruckeBelegMitVorlage(const Belegtyp: WideString; const Belegnummer: WideString; const Vorlage: WideString; VorlageTyp: Integer; const Optionen: WideString): Integer`
funktioniert einwandfrei. Über die COM-Schnittstelle wird ja der Dateiname auch nicht mitgeschickt.

Das ist der Log-Eintrag aus "C:\ProgramData\SelectLine Software\logs\SelectLine.Api\SelectLine\SelectLine.Erp.WebApi.WebHost.slog":
{ "Name": "SelectLine.Erp.WebApi.WebHost", "TimeStamp": "2020-10-22T10:11:14.0263557Z", "ServerTimeStamp": "2020-10-22T10:11:14.0263557Z", "Host": {"Name":"SELECTLINE-AUTO","Version":"Microsoft Windows NT 6.3.9600.0","UserName":"SelectLine","64bit":true}, "Process": {"FileName":"c:\\windows\\system32\\inetsrv\\w3wp.exe","Name":"w3wp","64bit":true,"ProcessId":6508,"ThreadId":20,"Runtime":"0:21:09:10.3011870","PrivateBytes":344846336}, "LogLevel": "Error", "Message": "Client.Send failed. See InnerException", "Exception": {"Message":"Client.Send failed. See InnerException","InnerException":{"Message":"Eine Ausnahme vom Typ \"SelectLine.Messaging.NamedPipe.NamedPipeClientCancellationException\" wurde ausgelöst.","StackTrace":"   bei SelectLine.Messaging.NamedPipe.NamedPipeClient.<SendAsync>d__10.MoveNext()\r\n--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---\r\n   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   bei SelectLine.Messaging.Friend.FriendClient.<SendInternalAsync>d__26.MoveNext()"}}, "CallerStack": ["SelectLine.Erp.WebApi.Controllers.Attributes.CatchExceptionAttribute.OnException(System.Web.Http.Filters.HttpActionExecutedContext context)","System.Web.Http.Filters.ExceptionFilterAttribute.OnExceptionAsync(System.Web.Http.Filters.HttpActionExecutedContext actionExecutedContext,System.Threading.CancellationToken cancellationToken)","System.Web.Http.Filters.ExceptionFilterAttribute.ExecuteExceptionFilterAsyncCore(System.Web.Http.Filters.HttpActionExecutedContext actionExecutedContext,System.Threading.CancellationToken cancellationToken)"] }

**Comment by VivienSchuboth** [comment]
Ok. Ja, es scheint ein Problem mit ihrem Backend-Prozess zu sein. Dieser wird zwingend benötigt.
Folgende Fragen, um diesem Problem auf die Schliche zu kommen:
- Welche Version haben Sie im Einsatz?
- Ist Ihr Mobile Manager korrekt eingerichtet? 
- Sind die SelectLine API und die SelectLine Warenwirtschaft auf derselben Version?
- Ist der Backendmanager gestartet?
- Existiert die Datei "api_standardwerte_vorgabe.json" unter dem Programmdatenpfad Ihrer Warenwirtschaft? (nur relevant für Version kleiner 20.3)
- Schauen Sie bitte ebenfalls nach, ob, während Ihrer Anfrage an die API und nach einem erfolgreichen Login, in Ihrem Task-Manager (unter Details) ein Prozess namens "SelectLine.API.Backend.exe" zur Verfügung steht.

Können Sie sich noch die Logs unter ...\logs\SelectLine.API.Backend ansehen?
Um Ihre Daten nicht hier offen zu legen, schicken Sie bitte Ihre Log-Dateien gesammelt an den Support und verweisen auf das GitHub-Forum und mich.
Über die Support-Abteilung gelangen die Log-Dateien dann an mich, also an die Entwicklungsabteilung.
Ich werde mir diese Dateien ansehen.

Mit freundlichen Grüßen,
Vivien Schuboth

**Comment by VivienSchuboth** [comment]
Guten Tag,
leider sind bei mir keine E-Mail oder Log-Dateien eingegangen.
Hat sich dieser Vorgang bereits von selbst geklärt?

Mit freundlichen Gruß,
Vivien Schuboth

**Comment by ondrejpokorny** [comment]
Ja, danke für die Unterstützung. Ich habe die API aktualisiert (sie war nicht ganz aktuell) und dann habe ich bessere Logs bekommen. Das Problem war darin, dass die Dateien auf ein Netzwerklaufwerk exportiert worden sind, auf den die Rest-API keinen Zugriff gehabt hat. Ich nehme an, dass es so ist, weil die API als Dienst läuft. Die COM-Schnittstelle hat den Zugriff auf das Netwerklaufwerk. Ich habe es mit einer einfachen Änderung der Vorlage gelöst, wo ich einfach den kompletten Netzwerk-Pfad verwendet habe.
