### ISSUE TITLE
Belegposition lässt sich über /Documents/{documentKey}/Positions/Store nicht anlegen

### ISSUE THREAD

**Issue by chucky2002** [selectline-software/selectline-api#56]
Tritt in Version 20.3 auf. 
Über die Ressource  /Documents/{documentKey}/Positions/Store kann ich keine neuen Belegpositionen hinzufügen
.

Bei folgenden Aufruf 
`curl -X POST "https://vm-sql-win10/slmobileApi/Documents/FAB20-05367/Positions/Store" -H  "accept: application/json" -H  "Authorization: LoginId c60b11a9-3235-4254-a0c9-735fa9e3803f" -H  "Content-Type: application/json" -d "[  {    \"Identifier\": \"FBA831D0-13EC-4E7E-B598-BA97B38CE059\",    \"ArticleNumber\": \"0000000002\",    \"Quantity\": 1  }]"`

addiert er nur die Menge zur Position, wenn eine Belegposition mit der Kennung exisitert. Lösche ich die Belegposition bekomme ich die Fehlermeldung: 
```
{
  "StatusCode": "BadRequest",
  "ResponseCode": "42-032",
  "Message": "StoreError",
  "Details": [
    {
      "Key": "FBA831D0-13EC-4E7E-B598-BA97B38CE059",
      "ErrorCode": 0,
      "Detail": "Die Position wurde im Beleg nicht gefunden."
    }
  ]
}
```

Wenn ich keinen Identifier mitgebe
`curl -X POST "https://vm-sql-win10/slmobileApi/Documents/FAB20-05367/Positions/Store" -H  "accept: application/json" -H  "Authorization: LoginId c60b11a9-3235-4254-a0c9-735fa9e3803f" -H  "Content-Type: application/json" -d "[  {    \"ArticleNumber\": \"0000000002\",    \"Quantity\": 1  }]"`
bringt mir die API folgenden Fehler:
```
{
  "StatusCode": "BadRequest",
  "ResponseCode": "42-032",
  "Message": "StoreError",
  "Details": [
    {
      "Key": "00000000-0000-0000-0000-000000000000",
      "ErrorCode": 0,
      "Detail": "Die Position wurde im Beleg nicht gefunden."
    }
  ]
}
```

Auf Grund der oben beschriebenen Fehler lässt sich über die Funktion keine neue Belegposition anlegen, obwohl die Ressource doch genau dafür da ist, oder?

Wenn ich mit der alten Ressource eine Position anlege, funktioniert das ohne Probleme.
`curl -X POST "https://vm-sql-win10/slmobileApi/Documents/FAB20-05367/Positions" -H  "accept: application/json" -H  "Authorization: LoginId c60b11a9-3235-4254-a0c9-735fa9e3803f" -H  "Content-Type: application/json" -d "{  \"PositionKind\": \"A\",  \"ArticleNumber\": \"0000000002\"}"`

**Lösung:** 
Die Position muss über `/Documents/{documentKey}/ArticleItem` angelegt werden. 
Unabhängig davon ist dennoch die Ressource  `/Documents/{documentKey}/Positions/Store` fehlerhaft. Denn in der Dokumentation steht das darüber eine Position angelegt wird, was aber so nicht funktioniert.

**Comment by VivienSchuboth** [comment]
Guten Tag,

danke für diese Information. 
Diese fehlerhafte Beschreibung der API-Funktionalität rührt noch aus der Vermischung der "normalen" Belegkette mit der manuellen Lagerung. 
Diese Beschreibung ist für die "normale" Belegkette nie treffend gewesen, sondern nur für die manuelle Lagerung.

Entschuldigen Sie die Verwirrung.
Wir werden die Beschreibung mit der 21.1 anpassen. :-)

Mit freundlichen Grüßen,
Vivien Schuboth
