### ISSUE TITLE
WAWI-Makro kann nicht ausgführt werden

### ISSUE THREAD

**Issue by chucky2002** [selectline-software/selectline-api#57]
Ziel ist es dem Makro zwei String-Parameter mitzugeben, die dann im Druckformular verwendet werden sollen. Wenn ich das tue, bekomme ich einen Fehler beim Aufruf der Ressource 
`https://192.168.119.128/slmobileApi/Macros:` 
mit dem Body 
`{"MacroName":"SQLTEST1","Parameters":[{"Name":"myDateiname","Value":"out2.pdf"},{"Name":"myDateipfad","Value":"Cemp"}]}` 

Fehlermeldung:
```
{
  "StatusCode": "InternalServerError",
  "ResponseCode": "70-000",
  "Message": "[EAbortTT] Beim Analysieren des Ausdruckes: \r\nCemp\r\nist folgender Fehler aufgetreten:\r\nUngültiges Zahlenformat",
  "Details": null
}
```

Es wird dazu die aktuelle SL.API 20.3.2 und WAWI 20.3.2 verwendet. Das zugehörige Makro habe ich angefügt.
Wenn ich im Makro keine Parameter abfrage und auch keine mitgebe, lässt sich das Makro ohne Probleme über die SL.API ausführen und speichert wie gewünscht das PDF unter `C:\temp\out.pdf`

[SQLTEST1.zip](https://github.com/selectline-software/selectline-api/files/5448443/SQLTEST1.zip)

**Comment by SFasel** [comment]
Guten Tag,
so wie es aussieht, kann "Cemp" nicht als Dateipfad gesetzt werden, da es keine gültige Pfadangabe ist. Probieren Sie den Parameter doch einmal mit einem gültigen Pfad, dann sollte das Makro auch korrekt ausgeführt werden.

Mit freundlichen Grüßen
Sebastian Fasel

**Comment by ThePholph** [comment]
Guten Morgen,

das sieht nach einem typischen Fehler beim Aufruf von Makros aus. Für String-Parameter beim Makro-Aufruf, müssen immer zusätzliche Anführungszeichen "" gesetzt werden, da anscheinend keine implizite Konvertierung oder Prüfung der Parameter durch SelectLine durchgeführt wird. Die Anführungszeichen dienen meiner Meinung nach dazu, dass ein String erkannt wird. 

Hier das Beispiel:

```
{
    "MacroName": "SQLTEST1",
    "Parameters": [{
            "Name": "myDateiname",
            "Value": ""out2.pdf""
        }, {
            "Name": "myDateipfad",
            "Value": ""Cemp""
        }
    ]
}
```


Ich hoffe, ich konnte helfen.

Viele Grüße

Daniel

**Comment by VivienSchuboth** [comment]
Guten Tag,

bitte achten Sie in der Druckvorlage darauf, diesen Wert zu aktivieren. 
Wir werden dies in der nächsten Version genauer dokumentieren!
![image](https://user-images.githubusercontent.com/34538107/97411152-2f592d80-1900-11eb-9963-89c781008782.png)

Daniels Tipp ist ebenfalls sehr hilfreich!
Hier mein Beispiel mit dem ich das Makro korrekt ausführen konnte.
![image](https://user-images.githubusercontent.com/34538107/97411337-6af3f780-1900-11eb-9f4f-43aa6f24e03d.png)

Falls das geklappt hat, schließen Sie bitte selbstständig diesen "issue".

MfG
Vivien Schuboth

**Comment by chucky2002** [comment]
@VivienSchuboth  @ThePholph 
Danke für die schnelle Hilfe. Mit den beiden Hinweisen konnte ich den Aufruf zum laufen bringen.
