### ISSUE TITLE
Anlegen von Belegposition mit negativer Menge nicht möglich

### ISSUE THREAD

**Issue by h2-Systems** [selectline-software/selectline-api#58]
Anlegen von einer Belegposition in einem selbst definierten Beleg (Lageraktion Einlagern, erlaubt negative Mengenangaben)
Das unten aufgeführte Beispiel funktioniert ohne Probleme mit einer positiven Menge und das manuelle Anlegen einer identischen Belegposition in der WaWi mit negativer Menge gibt es keine Probleme.

Die Funktion ist Documents/{dokumentKey}/ArticleItem
Die Fehlermeldung, die gegeben wird ist "Fehlender oder ungültiger Arbeitsplatz."

Bsp.
{
"StoreInformation": [
{
"ArtikelNumber": "16303",
"StoragePlaceIdentifier": 1742,
"Quantity": -1,
"PriceQuantity": 1
}],
"Artikelnummer": "16303",
"UnitPrice" : 123.00
}

**Comment by VivienSchuboth** [comment]
Guten Tag,

ausschlaggebend hierfür sollte das Feld "CalculatedQuantityValue" sein. 
Versuchen Sie einmal das folgende Beispiel:
{
  "ArticleNumber": "16303",
  "CalculatedQuantityValue": -2,
  "StoreInformation": [
      {
        "ArticleNumber": "16303",
        "StoragePlaceIdentifier": "1742",
        "Quantity": -2
      }
  ]
}

Mit freundlichen Grüßen,
Vivien Schuboth

**Comment by VivienSchuboth** [comment]
Guten Tag,
hat diese Variante den erwünschten Erfolg gebracht?

Gruß
Vivien Schuboth

**Comment by diekloope** [comment]
Guten Tag Frau Schuboth,
ich würde gerne die Minus-Menge ohne Storageinformationen entnehmen. 
Bisher habe ich es über den POST ../Documents/{documentKey}/Positions bei der  Plus-Menge wie folgt gemacht. Bei Minus kommt allerdings eine Fehlermeldung.
Beispiel documentitem := models.OutsourcingDocumentitem{	
        PositionKind: "A",
        CalculatedQuantityValue: amount,
        ArticleNumber: articleNumber,
       }

Kann ich es bei der neuen Function Documents/{dokumentKey}/ArticleItem bei Plus- und Minus-Mengen auch so machen oder wird hier zwingend eine StoreInformation benötigt?

**Comment by VivienSchuboth** [comment]
Guten Tag,

die Angabe des Positionstypen entfällt mit der Nutzung der neuen Funktionalität. 
Die Route zum "ArticleItem" entspricht (automatisch) dem PositionKind = "A", "Comment" entspricht PosititonKind = "K" usw.

Für die Route POST Documents/{dokumentKey}/ArticleItem, wäre ebenfalls diese Angabe für eine Minus-Menge ausreichend:
`{
  "ArticleNumber": "100005",
  "CalculatedQuantityValue": -3
}`

Für lagernde Belege sollten jedoch die Lagerinformationen ("StoreInformation") mitgegeben werden. Über diese Lagerinformationen erfolgt die Zuordnung zu einem Lager und ggf. zu Seriennummern, Verfallsdaten, abweichenden Mengeneinheiten und ähnlichem.  

Mit freundlichen Grüßen,
Vivien Schuboth

**Comment by h2-Systems** [comment]
Hallo Frau Schuboth
Ich bin endlich zum testen ihrers Vorschlages gekommen und es hat funktioniert.

Mit Freundlichen Grüßen,
Jonas Tuppatsch
