### ISSUE TITLE
Workaround for relocating items in warehouse

### ISSUE THREAD

**Issue by ThorstenPoppe** [selectline-software/selectline-api#6]
Do you have more information for article relocation via the API?
I tried to create a document with kind "M" and put an article-item into it.
By posting the article-item to Url `/Documents/M109346/ArticleItem` with body message 
`{"CalculatedQuantityValue":2,"ArticleNumber":"155-05","StoreInformation":[{"Warehouse":"1","TargetWarehouse":"3","Quantity":2}]}`
the article-item was created.
But the storage in the warehouse was only one receipt with quantity 2 in warehouse 1...
For my understanding there must be one departure for this article-item in warehouse 1 with quantity 2 and one receipt in warehouse 3 with quantity 2.
Do i get this wrong (Warhouse -> TargetWarehouse)?

**Comment by VivienSchuboth** [comment]
Hello,
thanks for letting us know about your problem.
We will inspect this problem soon. 

Until then you could use the following lines as a workaround:
```
POST ../Documents/{documentKey}/Positions/Store
[
  {
    "ArticleNumber": "155-05",
    "Warehouse": "1",
    "Quantity": 2,
    "TargetWarehouse": "3"
  }
]
```
Additionally we will correct the description of this route:
_POST ../Documents/{documentKey}/Positions/Store_
It can also be used to create a position which will be stored.

Best regards
Vivien

**Comment by ThorstenPoppe** [comment]
Hallo Vivien,

thank you very much, that solved my problem!

Thorsten
