### ISSUE TITLE
Certificate signed by unknown authority

### ISSUE THREAD

**Issue by diekloope** [selectline-software/selectline-api#60]
Nach der Umstellung auf 20.3 und https bekommen wir folgende Fehlermeldung:
.../slmobileApi/Info: x509: certificate signed by unknown authority

Im Browser kommt die Meldung, dass ein Sicherheitsrisiko vorhanden ist. Ich denke, dass das Zertifikat unsicher ist und dadruch die Meldung im Programm bzw. Quellcode kommt

**Comment by SteveSteglitz** [comment]
Hallo, 
was für ein Zertifikat wurde denn im Mobil Manager ausgewählt? Ein selbst erstelltes bzw. selbst signiertes?

Viele Grüße
Steve

**Comment by diekloope** [comment]
Hallo,
wir haben im Mobil Manager ein neues Zertifikat "SL.Mobile Service Zertifikat" erstellt.
Das Zertifikat zeit allerdings folgende Eigenschaft an:
"Dieses Zertifizierungsstellen-Stammzertifikat ist nicht vertrauenswürdig, da es sich nicht in dem Speicher vertrauenswürdiger Stammzertifizierungsstellen befindet."
Hat es da etwas mit zu tun und können wir es beeinflussen?

**Comment by SteveSteglitz** [comment]
Hallo, bei den erstellten Zertifikaten handelt es sich um selbst-signierte Zertifikate. Browser zeigen dieses Fehler bzw. den Warnhinweis immer dann an, wenn es sich dabei nicht um ein Zertifikat handelt, welches von einer vertrauensvollen Zertifizierungsstelle ausgestellt worden ist. 
Hierfür kann ein Zertifikat von einer, der vielen vorhandenen, Zertifizierungsstellen erworben werden. 

Viele Grüße
Steve

**Comment by diekloope** [comment]
Hallo,
können Sie uns einen  Hinweis geben, wie wir es am besten machen können. Im Moment kommen wir da nicht weiter und würden uns über eien Hilfestellung freuen,

Vielen Dank im Voraus.
Volker

**Comment by jprause1234** [comment]
Gültige Zertifikate bekommt man z.B. bei Let's Encrypt (https://letsencrypt.org/de/).
Dort gibt es auch Erklärungen und Hilfetexte zum Thema Zertifikate (z.B. https://letsencrypt.org/de/getting-started/)

Viele Grüße
Jan Prause
