### ISSUE TITLE
Bei Belegübergabe wird Lager nicht berücksichtigt

### ISSUE THREAD

**Issue by Grewamor** [selectline-software/selectline-api#61]
SelectLine: 20.3.4
SL-Mobile: 20.3.3
**Fehler tritt auf, seit SL-Update von  20.1.10 auf 20.3.4, vorher ging es.**

![image](https://user-images.githubusercontent.com/18594343/99780687-1adf0e00-2b17-11eb-989b-edda7cc03cf7.png)
![image](https://user-images.githubusercontent.com/18594343/99778574-25e46f00-2b14-11eb-884c-2aa928072e5b.png)
![image](https://user-images.githubusercontent.com/18594343/99778658-40b6e380-2b14-11eb-8e54-0101aa146c3b.png)

Von Beleg:
![image](https://user-images.githubusercontent.com/18594343/99778703-53c9b380-2b14-11eb-9b76-c3d6ba26cdbd.png)

Zu Beleg:
![image](https://user-images.githubusercontent.com/18594343/99778738-5e844880-2b14-11eb-9399-939bcb20e921.png)

**Comment by jprause1234** [comment]
Hallo,

ich habe es eben versucht nachzustellen und konnte den Fehler so nicht nachstellen.
Was bedeutet denn die "2" bei Warehouse, ist das die "LAGER_ID" oder das "Lager"?
Hier muss das "Lager" geschrieben werden.
![grafik](https://user-images.githubusercontent.com/26381693/99797969-7b2e7980-2b30-11eb-9ae1-b4874149a838.png)

Viele Grüße
Jan

**Comment by Grewamor** [comment]
Vielen Dank für die schnelle Antwort.
Die 2 ist das Lager nicht die ID.

**Comment by VivienSchuboth** [comment]
Guten Tag,
ist dieses "falsche" Lager (mit der Id = 2) dasselbe Lager, welches Sie in der Vorgängerposition finden? 

Gruß, 
Vivien Schuboth

**Comment by Grewamor** [comment]
Hallo,

nein, im Vorgänger (ein auslagernder Beleg) ist ein anderes Lager. Es soll im Nachfolger (ein einlagernder Beleg) die Ware an einen anderen Standort und Lager wieder eingelagert werden.

**Comment by VivienSchuboth** [comment]
Guten Morgen,
ok verstanden. Dann halte ich noch einmal fest: HL_01 ist also das Lager des Vorgänger, welches auch im Folgebeleg noch erhalten bleibt - trotz Angabe eines anderen Lagers.

Der Fehler ist auch bei uns reproduzierbar.
Wir werden diesen Fehler aufnehmen und Bescheid geben, in welcher Version dieser korrigiert wird.

Mit freundlichen Grüßen,
Vivien Schuboth

**Comment by Grewamor** [comment]
Korrekt.
Super, und vielen Dank.

**Comment by VivienSchuboth** [comment]
Guten Tag,
die Fehlerbehebung wurde für die Version 21.2 eingeplant.
Bei Neuigkeiten melde ich mich hierüber noch einmal zurück.

Beste Grüße,
Vivien Schuboth

**Comment by MatthiasGuse** [comment]
Mit der Version 21.3 verhält sich die Einlagerung wie gwünscht und lagert in das angegebene Lager wieder ein.

Viele Grüße
