### ISSUE TITLE
Passwortrichtline und Session-Timeout anpassen

### ISSUE THREAD

**Issue by Grewamor** [selectline-software/selectline-api#62]
Ist es möglich die Passwortrichtlinie und das Session-Timeout für API-Nutzer anzupassen?

Auf MDE-Geräten mit Hardware-Tastatur ist es sehr aufwendig ein solch komplexes Passwort einzugeben. Weiterhin sollte ein Admin die Entscheidung treffen dürfen, mit welchen Passwort ein Nutzer sich anmelden muss. 

Das Session-Timeout ist ebenfalls ungünstig.

**Comment by VivienSchuboth** [comment]
Guten Tag,
wie lange ein Login und deren zugehörige LoginId in der SelectLine API gültig ist, lässt sich über die Konfigurationsdatei der SelectLine API bestimmen. Der Standard sind hierfür 14 Tage. 
SelectLine MDE verhält sich in diesem Szenario analog.

Im Installationsverzeichnis der Mobilen Anwendungen befindet sich in dem Ordner „Webapi“ eine Konfigurationsdatei (Web.config). Derzeit steht in dieser Datei, neben anderen Einstellungen, nur eine einzelne Option zur Konfiguration der API zur Verfügung. Der Wert und die Option sind in der Datei unter dem Schlüssel „LoginIdValidityPeriod“ zu finden.
Diese Information befindet sich mit der kommenden Version (V21.1) ebenfalls in dem Einrichtungsdokument der SelectLine API, MDE und BDE.

Zu der Passwortrichtlinie: Hiermit meinen Sie die Anforderung an das Passwort - mindestens eine Zahl, Sonderzeichen und ähnliches, oder? Wünschen Sie sich, dass Sie als Admin diese Richtlinie an- und abschalten können - pro Benutzer oder für alle gleichermaßen?

Mit freundlichen Grüßen,
Vivien Schuboth

**Comment by Grewamor** [comment]
Vielen Dank für die Ausführliche Antwort!

> Wünschen Sie sich, dass Sie als Admin diese Richtlinie an- und abschalten können - pro Benutzer oder für alle gleichermaßen?

Für alle würde reichen. Pro Benutzer wäre natürlich noch besser.

**Comment by VivienSchuboth** [comment]
Guten Tag,

wir können Ihre Problematik verstehen. 
Das ständige Eingeben von Passwörtern, die dieser Passwortrichtlinie gerecht sind, erscheint im ersten Moment sicherlich als lästig, dient jedoch dem Schutz Ihrer betrieblichen Daten. Daher ist es für uns keine Option, die Passwortrichtlinie dahingehend anzupassen.

Als Alternative könnten Sie die Passwörter Ihrer Benutzer in einen Barcode umwandeln und diesen Barcode im Passwortfeld der SelectLine MDE einscannen. So würden Sie die direkte Eingabe der Passwörter über das Gerät umgehen.

Wenn Sie sich bereits mit der SelectLine BDE auseinandergesetzt haben, wissen Sie sicherlich, dass dort mit dem sogenannten "UserTag" gearbeitet werden kann. Dieser stellt ebenfalls eine Alternative zu der herkömmlichen Passworteingabe dar.
Es wäre für uns vorstellbar, dieses Modell für andere Benutzertypen zu übernehmen. 
Da es bis jetzt nur für BDE-Benutzer angedacht war, müssten wir diese Funktionalität dahingehend erst einmal erweitern.
Daher wäre hierfür ein Eintrag in das [UserVoice-Forum](https://selectline.uservoice.com) notwendig.

Mit freundlichen Grüßen,
Vivien Schuboth

**Comment by Grewamor** [comment]
Vielen Dank für Ihre Rückmeldung. Leider kann ich die Argumentation nicht teilen.

> dient jedoch dem Schutz Ihrer betrieblichen Daten.

Ich denke das Unternehmen oder der Admin sollte selbst entscheiden dürfen, wo welche Passwortrichtlinien greifen. In der SelectLine selbst, gibt es auch keine Richtlinie. Wo ist da der Schutz unsere betrieblichen Daten? :-P
