### ISSUE TITLE
HTTP Codes stimmen nicht in der Doku

### ISSUE THREAD

**Issue by Logic-Bits** [selectline-software/selectline-api#63]
https://demo.slmobile.de/demoApi/swagger/ui/index#/Document/Document_CreateDocument
erwartet: 200 => echt: 201

v. 20.3.0

edit: Sehr wichtig da die Code Generierung sonst nicht klappt - Fehler wirft (korrekt)

**Comment by VivienSchuboth** [comment]
Guten Tag,
danke für die Info! Wir werden diesen Fehler bei uns aufnehmen und in unsere Planung eintakten.
Wir werden Ihnen hierüber noch mitteilen, zu wann Sie mit der Behebung des Fehlers rechnen können.

Gruß,
Vivien

**Comment by Logic-Bits** [comment]
Hallo ... wir warten seit 5 Monaten auf eine Doku Änderungen die die Software brauchbar macht. Gibt es ein Update?

**Comment by VivienSchuboth** [comment]
Guten Tag,
Danke für Ihre Geduld.
Wir haben uns den Fehler zur V 21.3 eingetaktet.

Beste Grüße

**Comment by Logic-Bits** [comment]
Dankeschön,

ich geh davon aus dass so mit "den Fehler" alle sesponse codes meinen (die evtl. falsch sind) und nicht nur den aus meinem Beispiel?

Danke fürs Feedback.

**Comment by VivienSchuboth** [comment]
Guten Tag,
natürlich werden wir zusätzlich weitere Stellen überprüfen.
Falls Ihnen noch etwas auffällt, melden Sie sich gerne noch einmal.

Beste Grüße

**Comment by Logic-Bits** [comment]
Hallo,

gibt es hierfür immer noch kein fix?

[ProducesResponseType(StatusCodes.Status201Created)]

könnt Ihr nicht im Interface setzen?
Dann würde die Doku stimmen (und auch autom. erzeugte Swagger Clients).

Gruß

**Comment by MatthiasGuse** [comment]
Hallo,

die Fehlerbehebung ist abgeschlossen und steht Ihnen mit der aktuellen Version 22.2 zur Verfügung.

Viele Grüße
