### ISSUE TITLE
DocumentReadModelWithExtraFields / DocumentReadModel

### ISSUE THREAD

**Issue by Logic-Bits** [selectline-software/selectline-api#64]
https://demo.slmobile.de/demoApi/swagger/ui/index#/Document/Document_ReadDocumentsAsync
https://demo.slmobile.de/demoApi/swagger/ui/index#/Document/Document_ReadDocumentByKindAndNumberAsync

Wieso werden hier unterschiedliche Typen zurückgegeben?
Sollen die Extrafelder nicht bei der Liste auftauchen?

**Comment by VivienSchuboth** [comment]
Guten Tag,

Extrafelder sollen bei der Abfrage aller Belege nicht abgerufen werden.

Extrafelder könnten als Belegdetails bezeichnet werden und werden nicht immer benötigt.
Zusätzlich erfordert die Abfrage von Extrafeldern eine zusätzliche Datenbankabfrage und kostet damit Performance.
Bei der Abfrage von mehreren Belegen macht das einen deutlichen Unterschied.
Aus diesen Gründen haben wir uns gegen eine Bereitstellung von Extrafeldern in der Abfrage aller Belege entschieden. 

Gruß,
Vivien

**Comment by Logic-Bits** [comment]
Danke,

Vorschlag: Swagger besser ausnutzen damit man die Generierten Klassen besser verwenden kann:
https://swagger.io/docs/specification/data-models/inheritance-and-polymorphism/
