### ISSUE TITLE
Property Namen ändern sich bei der Document POST Antwort

### ISSUE THREAD

**Issue by Logic-Bits** [selectline-software/selectline-api#65]
![image](https://user-images.githubusercontent.com/2421123/100884505-d7d75000-34b1-11eb-8b28-eb52408a891d.png)

Wieso wird hier "documentKind" geschrieben wenn in der Doku "DokumentKind" steht?
https://demo.slmobile.de/demoApi/swagger/ui/index#/Document/Document_CreateDocument

**Comment by VivienSchuboth** [comment]
Guten Tag,
es ist richtig, dass wir "KindFlag" bei der Beleganlage erwarten und als Response denselben Wert als "documentKind" zurückgeben.

Leider verstehe ich Ihre daraus resultierende Frage nicht ganz. 
Könnten Sie diese bitte noch einmal mit anderen Worten formulieren?

Gruß,
Vivien

**Comment by Logic-Bits** [comment]
Danke für die Antwort.

Wenn Ihr natürlich i-welche Felder zurückgeben möchtet spielt es keine Rolle (ist ja auch nicht mal in der Doku definiert -https://demo.slmobile.de/demoApi/swagger/ui/index#/Document/Document_CreateDocument).
Ich bin davon ausgegeben dass hier die 2 Felder von dem DocumentReadModel zurück gegeben werden.

Gibt es einen Grund dass die Felder nichts mit dem Document Model zu tun haben?
Ansonsten kann dann der Issue geschlossen werden.

Danke

**Comment by VivienSchuboth** [comment]
Guten Tag,

dies sind keine Felder, die wir zufällig zurückgeben. Es sind die Felder aus dem DocumentReadModel, jedoch mit einer anderen Bezeichnung, unter Anderem um den Kontext der Response greifbarer zu machen.

![image](https://user-images.githubusercontent.com/34538107/101134844-467bf100-360b-11eb-8111-2ae75e3182ce.png)

siehe:
https://demo.slmobile.de/demoApi/swagger/ui/index#/Document/Document_ReadDocumentsAsync

Diese zwei Felder definieren den Belegtyp (documentKind) und die zugehörige Belegnummer (documentNumber) des von Ihnen angelegten Beleges. Mit diesen Werten, zusammengesetzt als sogenannter "documentKey", können Sie als Entwickler dann ebenfalls weiterarbeiten, um Positionen anzulegen, den Belegbearbeitungsstatus zu setzen oder Ähnliches.

Wir werden uns intern noch einmal zusammensetzen, um zu prüfen, inwiefern wir die Benamungen der Felder optimieren können.

Mit freundlichen Grüßen,
Vivien Schuboth

**Comment by Logic-Bits** [comment]
Danke für die Antwort - "documentKind" existiert nicht im DocumentReadModel.

D.h. die Antwort von dem Create Document kann ich nicht in ein DocumentReadModel parsen, da die Felder die zurück kommen nicht in dem DocumentReadModel existieren.

bsp:
DocumentReadModel doc = DummyCreateDocument();

jetzt würden wir ja erwarten dass dass doc.Number, sowie doc.KindFlag verfügbar ist.
doc.documentKind können wir ja nicht abgreifen, da es kein Feld in dem DocumentReadModel ist.

Hoffe Sie verstehen das Problem.

Danke

**Comment by VivienSchuboth** [comment]
Guten Tag,
nein, so ist das auch nicht gedacht.
Sie legen sich ein Beleg an und bekommen dann die Werte zur eindeutigen Identifikation zurück.
`var result = DummyCreateDocument();`

Im Ergebnis finden Sie den Belegtyp und die Belegnummer, wie oben beschrieben.
Mithilfe der beiden Strings aus dem result besitzen Sie den "documentKey" zur eindeutigen Identifikation des Beleges.
`var documentKey = $"{Belegtyp}{Belegnummer}";`

Jetzt können Sie Ihren Beleg abrufen über die Route: GET {{url}}/Documents/{{documentKey}}
`DocumentReadModel beleg = GetBelegMitDocumentKey();`

Mit freundlichen Grüßen,
Vivien Schuboth
