### ISSUE TITLE
API Berechtigungen

### ISSUE THREAD

**Issue by Logic-Bits** [selectline-software/selectline-api#66]
Hallo,

die API / Mobile Berechtigungen werden ja von dem SL Benutzer abgeleitet... kann ich damit dem API Benutzer soweit Begrenzen dass er AUSSCHLIEßLICH Belege / Belegpositionen anlegen kann?

Vielen Dank im Voraus!

**Comment by VivienSchuboth** [comment]
Guten Tag,

diese Begrenzung ist nicht möglich. 
Die Rechte eines SelectLine API-Benutzers hängen grundsätzlich an den Rechten aus der Benutzerverwaltung der SelectLine Mobile.
Zusätzlich werden einige Rechte der SelectLine Warenwirtschaft geprüft, sofern auf die entsprechende Funktionalität der Warenwirtschaft zugegriffen wird. Ein Beispiel ist hierfür das Anlegen von Belegen oder deren Positionen. 

Mit freundlichen Grüßen,
Vivien Schuboth

**Comment by Logic-Bits** [comment]
Dankeschön - gibt es eine Übersicht die ich den Kunden zur Verfügung stellen kann?

**Comment by VivienSchuboth** [comment]
Guten Tag,
eine Übersicht gibt es derzeit noch nicht dafür. 
Ich nehme den Wunsch in unsere weitere Planung mit auf.

Die Frage, welche Rechte erlaubt bzw. nicht erlaubt sind, kann ich nach meiner Recherche trotzdem beantworten.

Die folgenden Rechte wurden für einen SelectLine API-Benutzer verboten:
- Dashboard anzeigen
- Chefübersicht anzeigen
- Administrator
- Persönliche Einstellungen vornehmen

Für alle anderen Rechte besitzt ein SelectLine API-Benutzer die Erlaubnis.

Mit freundlichen Grüßen,
Vivien Schuboth

**Comment by Logic-Bits** [comment]
Danke!

Zur Info - wir wollen hier die Möglichkeit schaffen dass ein Großkunde Bestellung selbst auslösen kann - aber ohne Rechte ist das leider sicherheitstechnisch nicht Umsetzbar.

Falls Sie hier keine weiteren Infos haben kann der Issue geschlossen werden.

Danke

**Comment by MatthiasGuse** [comment]
Wie bereits per E-Mail kommuniziert hier nochmal abschließend dokumentiert:

Auch wenn es für Benutzer der API möglich wäre die Rechte auf das reine Anlegen von Belegen zu beschränken, würde das nicht verhindern, dass mit diesem Benutzer Belege für beliebige Kunden angelegt werden können. Ebenfalls würde nicht verhindert werden, dass Artikel und Belegdaten auf eine Art und Weise verändert werden, dass sie bspw. preislich oder steuerlich falsch wären. Die zu berücksichtigenden Punkte sind sehr komplex.

Andere API Anwender arbeiten bei ähnlichen Anforderungen mit eigens programmierten Anwendungen, die die Anfragen des Senders entgegen nehmen und nur Daten per API an die Warenwirtschaft weiterleiten, die wirklich gewünscht sind. Im Fall eines Onlineshops übernimmt diese Funktion beispielsweise die Shopschnittstelle. Die Kunden im Shop werden ja auch nicht als Wawi-Nutzer geführt, damit sie ihre Bestellungen direkt anlegen können.
