### ISSUE TITLE
undokumentierter Statuscode { "StatusCode": "BadRequest", "ResponseCode": "02-008", "Message": "BadRequest", "Details": null }

### ISSUE THREAD

**Issue by martinprenninger** [selectline-software/selectline-api#67]
Wir bekommen nach dem Login einen undokumentierten Fehler zurück. Der Login scheint zu klappen, da eine andere Fehlermeldung kommt, wen wir das Kennwort bewusst falsch hinterlegen. Ebenfalls eine andere Meldung, wenn wir den APPKEY falsch hinterlegen. Daher diese Paramenter stimmen.

Was bedeutet daher nach dem Login folgende Meldung:

> { "StatusCode": "BadRequest", "ResponseCode": "02-008", "Message": "BadRequest", "Details": null }
> 
> access-control-allow-origin: * cache-control: no-cache content-length: 111 content-type: application/json; 
> charset=utf-8 date: Thu, 10 Dec 2020 21:41:21 GMT expires: -1 pragma: no-cache server: Microsoft-IIS/10.0 x-
> aspnet-version: 4.0.30319 x-firefox-spdy: h2 x-powered-by: ASP.NET
> https://crm.eska.at:444/slmobileApi/swagger/ui/index#/Account/Account_Login
> 
> curl -X POST "https://crm.eska.at:444/slmobileApi/Login" -H "accept: application/json" -H "Content-Type: 
> application/json" -d "{ \"UserName\": \"shop\", \"Password\": \"vVyaAMs5PWff!\", \"LoginKind\": \"MobileApi\", 
> \"AppKey\": \"TEST\"}"

**Comment by VivienSchuboth** [comment]
Guten Tag,
welche Version haben Sie bei sich im Einsatz?

Mit freundlichen Grüßen,
Vivien Schuboth

**Comment by VivienSchuboth** [comment]
Guten Tag,

ich wollte Ihnen mitteilen, dass der Fehler zur Version 20.3.8 behoben wurde.
Die 20.3.8 wird als Hotfix voraussichtlich Anfang nächsten Jahres ausgeliefert werden.
Ein genaues Datum kann ich Ihnen noch nicht nennen.

Danke noch einmal für Ihre Hilfe bei der Suche nach diesem Fehler.

Ein frohes Fest und einen gesunden Rutsch in das neue Jahr 2021.

Beste Grüße,
Vivien Schuboth
