### ISSUE TITLE
Lagerplatz ändern

### ISSUE THREAD

**Issue by Grewamor** [selectline-software/selectline-api#68]
Lagerplatz kann per API nicht geändert werden.

Im Swagger gibt es das Beispiel zur Änderung des Lagerplatzes:

![image](https://user-images.githubusercontent.com/18594343/102067430-5d84c500-3dfb-11eb-8055-7f62359a184d.png)

Wenn dies ausgeführt wird, kommt leider die Meldung, dass der Lagerplatz nicht geändert werden darf.

```
{
  "StatusCode": "BadRequest",
  "ResponseCode": "42-031",
  "Message": "UpdateDocumentErrorException",
  "Details": {
    "ResponseDetails": "Das Feld [LagerplatzID] darf nicht geändert werden.",
    "ResponseType": "UpdateDocumentError",
    "ErrorCode": -1
  }
}
```

Ist das so gewollt, oder ein Fehler?

**Comment by ThorstenPoppe** [comment]
Wir haben ein ähnliches Problem und möchten in einem Packzettel die Lagerdaten bearbeiten.

Der PUT Request geht an /Documents/PPZ072/Positions/D42F8D49-F556-480F-AFB5-6CEC660E62F7 mit den Daten
`{
    "StoreInformation": [
        {
            "Identifier": "D42F8D49-F556-480F-AFB5-6CEC660E62F7",
            "Quantity": 6,
            "ArticleNumber": "lg-1_22",
            "Warehouse": "200"
        },
        {
            "Identifier": "D42F8D49-F556-480F-AFB5-6CEC660E62F7",
            "Quantity": 14,
            "ArticleNumber": "lg-1_22",
            "Warehouse": "1007,1,1,1"
        }
    ]
}`

Damit sollen im Packzettel die 20 Stück des Artikels mit 14 Stück aus dem Lagerplatz 1,1,1 des Lagers 1007 und 6 Stück au dem Lager 200 (Standard Lager) gebucht werden.
Als Response kommt
`{
    "StatusCode": "BadRequest",
    "ResponseCode": "42-031",
    "Message": "UpdateDocumentErrorException",
    "Details": {
        "ResponseDetails": "Fehler beim Update der Belegposition",
        "ResponseType": "UpdateDocumentError",
        "ErrorCode": -1
    }
}`

In der SelectLine können wir die Aktion über den Menüpunkt "Lagerdaten bearbeiten" durchführen.

Kann jemand helfen?

**Comment by ThorstenPoppe** [comment]
Guten Morgen,

ich muss hier einmal pushen, wir sind in der Angebotsphase eines größeren Projekts und benötigen diese Funktion.
In der COM Schnittstelle sollte das Pendant dazu die Methode SpeichernMitLagerinformation() auf dem Positions-Objekt sein.
Das benötigen wir in der API.

Viele Grüße,
Thorsten Poppe

**Comment by ThorstenPoppe** [comment]
Ich habe selbst noch einiges probiert und habe die funktionsweise des Aufrufs nun herausbekommen.
Man muss beim Request immer die CalculatedQuantityValue (Menge) ändern und die StoreInformation dann als Differenzbuchung angeben. 
Die Differenzbuchung kann ich noch verstehen, aber warum muss die Menge geändert werden, damit die Funktion überhaupt ausgeführt wird und keine Exception kommt?

Viele Grüße,
Thorsten Poppe

**Comment by VivienSchuboth** [comment]
Guten Tag @ThorstenPoppe,

Sie haben Recht. Es muss sowohl die Differenzbuchung, als auch die neue Gesamtmenge einer Position angegeben werden. 
In der Liste von Lagerinformationen muss jeweils die aus- bzw. einzulagernde Menge für ein Lager angegeben werden.
`CalculatedQuantityValue` stellt die neue Gesamtmenge der Position dar, welche für interne Berechnungen (Preise) benötigt und als neuer Wert der Positionsmenge gesetzt wird.

Viele Grüße,
Vivien Schuboth

**Comment by VivienSchuboth** [comment]
Ebenfalls an Sie @Grewamor einen guten Tag,

danke für diese Information! Die Rückgabe dieser Fehlermeldung ist Absicht. 
Das Feld darf nicht verändert werden. Das ist uns wohl "durch die Lappen gegangen". :-)
Das fehlerhafte Beispiel (& Model) werden wir demnächst überarbeiten.

Zur Bearbeitung des Lagers nutzen Sie bitte das Property "WarehouseId" oder innerhalb der Lagerinformationen das Property "Warehouse". Diese stellen die Nummer des Lagers dar. [BELEGP].[Lager]
Beispiel, um einen Lagerplatz anzugeben: 
`{ "CalculatedQuantityValue": 12, "StoreInformation": [{ "ArticleNumber": "130003", "Warehouse": "1000,1,1,1", "Quantity": 2 }]}`

Viele Grüße,
Vivien Schuboth

**Comment by Grewamor** [comment]
Ok, danke.
