### ISSUE TITLE
Get Documents and Filter

### ISSUE THREAD

**Issue by diekloope** [selectline-software/selectline-api#69]
Moin zusammen,
ich würde gerne die Filterfunktion nutzen und alle Belege laden, die das FeieKennzeichen 4 = true haben.
Ich habe es mit url := getConfig.Url+"slmobileApi/Documents?Filter=CustomField.Flag4 EQ 1" versucht und bekomme die Meldung: Error 400. The request is badly formed.
Muss ich die Anfrage in Version 20.3.6 anders formulieren?

**Comment by diekloope** [comment]
Hat sih erledigt,

**Comment by babicsal4u** [comment]
> Hat sih erledigt,
Hi
ich hätte das gleiche Problem. Ich habe es z.B. mit Articles?filter=IsInactive EQ false versucht aber ich kriege als output immer eine leere String. Wie hast du den URL aufgebaut, sodass es funktioniert? Danke

**Comment by babicsal4u** [comment]
Hab es gefunden: einfach die Leerstellen mit "%20" ersetzen.
z.B. Articles?filter=IsInactive%20EQ%20true%20AND%20IsShopActive%20EQ%20True
