### ISSUE TITLE
Error responses while using POST.../Documents

### ISSUE THREAD

**Issue by aameyer** [selectline-software/selectline-api#7]
I'm trying to create several Vouchers in parallel using multiple POST.../Documents requests. This does work if I'm only using one request at a time, but using multiple requests often returns several different error codes:

first try I get
Error: Request failed with status code 400|{"StatusCode":"BadRequest","ResponseCode":"42-036","Message":"CreateDocumentErrorException","Details":{"ResponseDetails":"Die Aktion wurde abgebrochen, weil versucht wurde ein Fenster zu öffnen.","ResponseType":"CreateDocumentError","ErrorCode":-1}}

If I post the same request a minute later, I get instead
Error: Request failed with status code 400|{"StatusCode":"BadRequest","ResponseCode":"42-036","Message":"CreateDocumentErrorException","Details":{"ResponseDetails":"XXXTABLELA: Das Feld 'Lager' wurde nicht gefunden","ResponseType":"CreateDocumentError","ErrorCode":-1}}

If I include the field "WarehouseNumber", instead I get several different error messages, for example:
Error: Request failed with status code 400|{"StatusCode":"BadRequest","ResponseCode":"42-036","Message":"CreateDocumentErrorException","Details":{"ResponseDetails":"Das Feld 'ArtBezGefunden' wurde nicht gefunden","ResponseType":"CreateDocumentError","ErrorCode":-1}}

Error: Request failed with status code 400|{"StatusCode":"BadRequest","ResponseCode":"42-036","Message":"CreateDocumentErrorException","Details":{"ResponseDetails":"Operation bei geöffneter Datenmenge nicht ausführbar","ResponseType":"CreateDocumentError","ErrorCode":-1}}

Error: Request failed with status code 400|{"StatusCode":"BadRequest","ResponseCode":"42-031","Message":"UpdateDocumentErrorException","Details":{"ResponseDetails":"Unterschiedliche Typen für Feld 'SonderRabatt'; erwartet: Float, gefunden: Integer","ResponseType":"UpdateDocumentError","ErrorCode":-1}}

Also, I sometimes get the following response while using POST.../documents/<documentkey>/ArticleItem
Error: Request failed with status code 400|{"StatusCode":"BadRequest","ResponseCode":"42-036","Message":"CreateDocumentErrorException","Details":{"ResponseDetails":"Falscher Parameter.","ResponseType":"CreateDocumentError","ErrorCode":-1}}

After several further requests using the exact same data, sometimes the Vouchers do get created without any errors, so I'm pretty sure the problem is not my data. Also, I do not get any errors when I post these requests one after the other. It seems the errors result from posting multiple requests at the same time using the same login.

**Comment by VivienSchuboth** [comment]
Hello,
thanks for writing us. I know it’s stressful when you’ve got work to do and you’re stuck like this.
As soon as we inspect the problem we will give you further information.

Best regards,
Vivien

**Comment by aameyer** [comment]
Something that just occured to me - would you like the issues to be written in english or german?

**Comment by VivienSchuboth** [comment]
I speak german as well. 
You can also write in german if you like to.

Best regards,
Vivien

**Comment by VivienSchuboth** [comment]
Good afternoon,
it may be helpful for us if you can provide us the following information:

1. your data backup 
2. a step-by-step-description about your requests and their data which raised different error codes.

It will help us to track down what’s happening and figure out the best way forward!
Please send the information **with your login information of your FTP server** to our support with a note of our conversation on GitHub. 
If you don't have a FTP server our support will organize it for you.
_support@selectline.de_

As soon as you reply, I can start investigating for you.

If you have any questions, please let me know.

Best regards,
Vivien

**Comment by aameyer** [comment]
Ich habe das Problem nicht selbst reproduzieren können, es ist aber am 12.5. auf einer unserer VMs erneut aufgetreten. In diesem Fall hat es wieder einen Fehler beim Anlegen der Belege gegeben, über die API wurde ein Fehler zurückgegeben, es wurden jedoch trotzdem leere Belege angelegt. Die Requests werden dort automatisch über einen Dienst abgesetzt, der aufgrund des Fehlers die gleichen Requests in regelmäßigen Abständen wiederholt hat - immer mit dem gleichen Fehler. Nach einem Neustart des Backendmanagers wurden die gleichen Requests ohne Fehler verarbeitet. Ich habe Datensicherungen von Mandant und Programm bei Ihrem Support unter Servicenummer 109393 hochgeladen, im Mandant WUNDF sehen Sie dort u.a. diverse leere Ausgangsrechnungen.

Zusammen mit den Datensicherungen habe ich auch eine Logdatei aller Requests hochgeladen, diese enthält alle Requests einschließlich Responses aus einer "normalen" Verarbeitung, da ich den Fehler heute nicht wieder reproduzieren konnte. Der Ablauf sowie die Daten im Fehlerfall waren jedoch identisch mit Ausnahme der Belegnummern. Dann werden die oben genannten Fehlercodes auf die POST.../document - Requests zurückgegeben. Hier noch einmal der Hinweis: Auf identische Requests werden teilweise völlig unterschiedliche Fehler zurückgegeben (s.o.).

In diesem Zusammenhang hat ein Benutzer noch eine Beobachtung gemacht, die ggf. relevant sein könnte. Über die Requests legen wir Belege an, anschließend werden die Belegpositionen hinzugefügt. Die Adressnummer muss zwingend im ersten Schritt mit übergeben werden, da ja eine spätere Änderung der Adressnummer in einem Beleg mit Positionen über die API nicht möglich ist.
Während der Beleg durch einen Dienst angelegt wurde, hat der Benutzer mehrfach die Ansicht der entsprechenden Belege aktualisiert. Auch wenn der Import in diesem Fall vollständig ohne Fehler verlief, kommt mir der Screenshot im Anhang verdächtig vor. Dort wird ein Beleg mit bereits angelegten Positionen angezeigt, jedoch noch ohne Adressnummer. Nach einem weiteren Aktualisieren war diese ebenfalls eingetragen.
Wenn dies nicht nur ein Problem der Anzeige ist, bedeutet dies, dass die API beim Anlegen des Beleges bereits eine Response mit Status 201 und der Belegnummer zurückgibt, bevor der Beleg in der Datenbank vollständig angelegt ist. In der Folge setzen wir ggf. die nächsten Requests zum Anlegen der Belegpositionen ab, bevor der Beleg vollständig existiert - ist dies Möglicherweise die Ursache?
![Screenshot unvollst  Beleg](https://user-images.githubusercontent.com/53219563/82076168-b3668280-96dd-11ea-8145-a3901d66278d.png)

**Comment by VivienSchuboth** [comment]
Guten Tag,
danke für die Hinweise zu diesem Problem! Wir werden uns das genauer anschauen und geben Ihnen Bescheid, sobald wir weitere Informationen für Sie haben.

Mit freundlichen Grüßen,
Vivien

**Comment by aameyer** [comment]
Guten Tag,
gibt es hierzu inzwischen neue Informationen? Aktuell funktioniert das Anlegen von Belegen über die API so für uns nicht verlässlich genug, um dies in Produktivsystemen einzusetzen. Unsere Bestandskunden drängen jedoch inzwischen auf eine baldige Umsetzung, und ebenso können wir weiteren Interessenten derzeit keine konkrete Fertigstellung zusagen.
MfG
Alexander Meyer

**Comment by VivienSchuboth** [comment]
Guten Tag Herr Meyer,
wir verstehen Ihre Bedenken und haben die Recherche zu diesem Problem im Blick.
Derzeit arbeiten wir mit Hochdruck an der neuen Version und haben es daher noch nicht geschafft, uns Ihrer zugesandten Datensicherung zu widmen.
Wir werden uns dieser Recherche in den nächsten zwei Wochen annehmen und prüfen, inwieweit wir dieses nachvollziehen können.

Mit freundlichen Grüßen,
Vivien

**Comment by VivienSchuboth** [comment]
Guten Morgen Herr Meyer,
welche Version haben Sie im Einsatz, mit welcher die Probleme auftreten?

Mit freundlichen Grüßen,
Vivien

**Comment by aameyer** [comment]
Guten Tag,
der Fehler trat zuletzt in einer Version 20.1.1. Build 184521 auf.

**Comment by VivienSchuboth** [comment]
Guten Tag,
wir haben, wie Sie, die Fehler nicht reproduzieren können. Daher tappten wir bei der Recherche im Dunkeln, was das Finden der Ursache der o.g. Fehler betrifft.
Aus der Analyse ergaben sich jedoch Optimierungsmöglichkeiten, die wir zeitnah umsetzen wollen. Ob diese, Ihre Problematik betreffen und dabei helfen Sie zu lösen, können wir leider nicht sagen.

> In der Folge setzen wir ggf. die nächsten Requests zum Anlegen der Belegpositionen ab, bevor der Beleg vollständig existiert - ist dies Möglicherweise die Ursache?

Sobald die Response mit dem Belegtyp und der Belegnummer zurückgegeben wird, ist der Beleg angelegt und gespeichert. Sie würden keine Belegposition anlegen können ohne die Informationen, Belegtyp und Belegnummer, mitzuschicken.

Eine Idee unsererseits, die Sie ausprobieren könnten, um mit uns gemeinsam die Fehlerursache einzugrenzen, wäre Folgende:
- Schicken Sie den Befehl zur Beleganlage zunächst nur mit dem Belegtyp ab.
- Bearbeiten Sie den Beleg danach, d.h. Sie fügen den Kunden und weitere Beleginformationen erst im zweiten Schritt, separat, hinzu.
- Danach können Sie die Belegpositionen anlegen.

Bitte geben Sie uns dann Bescheid, ob Sie hierbei einen Unterschied feststellen.

Eine Bemerkung am Rande zu ihrer gesendeten Logdatei aller Requests: 
Sie können ebenfalls über die API einen Artikel anhand der EAN-Nummer suchen: 
`GET {{url}}/Articles/{EANNummer, Seriennr oder Referenznr}?considerReferenceAndSerial=true`
Diese Information werden wir zeitnah in der API-Hilfe ergänzen.

Mit freundlichen Grüßen,
Vivien

**Comment by aameyer** [comment]
Guten Tag,
ich habe heute eine neue Programmversion mit Anlegen eines neuen Belegs ohne Kopfdaten, ausschließlich mit Belegtyp mit der neuen SelectLine Version 20.2.3 getestet, auch dort treten Fehler direkt bei der Belegerstellung auf.

Unten angehängt finden Sie einmal ein Log der abgesetzten Requests an die API mit den erhaltenen Responses. Zur Erläuterung: Es werden mehr oder minder zeitgleich zwei Prozesse gestartet, die sich mit jeweils eigenen Benutzern anmelden. Prozess1 (Benutzer DataFormAPIUser01, LoginId 61cce393-78e2-469f-ab97-feb216a0e4e7) soll eine Eingangsrechnung anlegen. Prozess2 (Benutzer DataFormAPIUser02, LoginId 4646d422-144d-4db6-8df9-fcf9a008008e) soll nacheinander mehrere Ausgangsrechnungen anlegen, dazu wird zuerst per API-Makro ein zugehöriger Wartungsvertrag ausgelesen, anschließend wird der Beleg angelegt.

Was tatsächlich passiert, ist folgendes: Prozess2 und Prozess1 erhalten auf das Anlegen des ersten Belegs eine Fehlermeldung "Zugriffsverletzung bei Adresse 00A01721 in Modul \'SelectLine.API.Backend.exe\'. Lesen von Adresse 00000000" zurück. Prozess2 versucht anschließend, einen zweiten Beleg anzulegen, und erhält als Fehlermeldung einen Bad Request ohne weiteren Fehlertext. Direkt im Anschluss legt Prozess2 noch zwei weitere Belege ohne Fehler an. Nach einer Minute Wartezeit starten Prozess1 und Prozess2 erneut und legen die fehlgeschlagenen Belege diesmal ohne Fehler an.

Die Logs der Requests und Responses:
16:56:52.309 | REQUEST | POST.../Login
  Request Data: {"UserName":"DataFormAPIUser01","Password":"*****","AppKey":"Sartissohn DataForm"}
16:56:52.486 | REQUEST | POST.../Login
  Request Data: {"UserName":"DataFormAPIUser02","Password":"*****","AppKey":"Sartissohn DataForm"}
16:56:52.983 | RESPONSE | POST.../Login
  Response Status: 200 "OK"
  Response Data: {"AccessToken":"4646d422-144d-4db6-8df9-fcf9a008008e","TokenType":"LoginId"}
16:56:53.003 | REQUEST | POST.../Macros/DataFormSelectMaintenanceContract
  Request Headers: {"AUTHORIZATION":"LoginId 4646d422-144d-4db6-8df9-fcf9a008008e"}
  Request Data: [{"Name":"CustomerNumber","Value":"10004"},{"Name":"Type","Value":"O365"}]
16:56:53.012 | RESPONSE | POST.../Login
  Response Status: 200 "OK"
  Response Data: {"AccessToken":"61cce393-78e2-469f-ab97-feb216a0e4e7","TokenType":"LoginId"}
16:56:53.014 | REQUEST | POST.../Documents
  Request Headers: {"AUTHORIZATION":"LoginId 61cce393-78e2-469f-ab97-feb216a0e4e7"}
  Request Data: {"KindFlag":"E"}
16:56:53.261 | RESPONSE | POST.../Macros/DataFormSelectMaintenanceContract
  Response Status: 200 "OK"
  Response Data: {<Makro-Ergebnisse, hier irrelevant>}
16:56:53.263 | REQUEST | POST.../Documents
  Request Headers: {"AUTHORIZATION":"LoginId 4646d422-144d-4db6-8df9-fcf9a008008e"}
  Request Data: {"KindFlag":"R"}
16:56:54.445 | RESPONSE ERROR | POST.../Documents
  Response Error: Request failed with status code 400
  Request Header: {"AUTHORIZATION":"LoginId 4646d422-144d-4db6-8df9-fcf9a008008e"}
  Response Data:
      { StatusCode: 'BadRequest',
        ResponseCode: '42-036',
        Message: 'CreateDocumentErrorException',
        Details:
         { ResponseDetails:
            'Zugriffsverletzung bei Adresse 00A01721 in Modul \'SelectLine.API.Backend.exe\'. Lesen von Adresse 00000000',
           ResponseType: 'CreateDocumentError',
           ErrorCode: -1 } }
16:56:54.484 | REQUEST | POST.../Macros/DataFormSelectMaintenanceContract
  Request Headers: {"AUTHORIZATION":"LoginId 4646d422-144d-4db6-8df9-fcf9a008008e"}
  Request Data: [{"Name":"CustomerNumber","Value":"10009"},{"Name":"Type","Value":"O365"}]
16:56:54.501 | RESPONSE ERROR | POST.../Documents
  Response Error: Request failed with status code 400
  Request Header: {"AUTHORIZATION":"LoginId 61cce393-78e2-469f-ab97-feb216a0e4e7"}
  Response Data:
      { StatusCode: 'BadRequest',
        ResponseCode: '42-036',
        Message: 'CreateDocumentErrorException',
        Details:
         { ResponseDetails:
            'Zugriffsverletzung bei Adresse 00A01721 in Modul \'SelectLine.API.Backend.exe\'. Lesen von Adresse 00000000',
           ResponseType: 'CreateDocumentError',
           ErrorCode: -1 } }
16:56:54.538 | REQUEST | POST.../Logout
  Request Headers: {"AUTHORIZATION":"LoginId 61cce393-78e2-469f-ab97-feb216a0e4e7"}
  Request Data: {}
16:56:54.859 | RESPONSE | POST.../Logout
  Response Status: 200 "OK"
  Response Data: ""
16:56:54.889 | RESPONSE | POST.../Macros/DataFormSelectMaintenanceContract
  Response Status: 200 "OK"
  Response Data: {<Makro-Ergebnisse, hier irrelevant>}
16:56:54.890 | REQUEST | POST.../Documents
  Request Headers: {"AUTHORIZATION":"LoginId 4646d422-144d-4db6-8df9-fcf9a008008e"}
  Request Data: {"KindFlag":"R"}
16:57:25.106 | RESPONSE ERROR | POST.../Documents
  Response Error: Request failed with status code 500
  Request Header: {"AUTHORIZATION":"LoginId 4646d422-144d-4db6-8df9-fcf9a008008e"}
  Response Data:
      { StatusCode: 'InternalServerError',
        ResponseCode: '42-000',
        Message: 'Client.Send failed. See InnerException',
        Details: null }

Ab hier treten keine weiteren Fehler auf. In der SelectLine finden sich jetzt zwei leere Belege, eine Eingangsrechnung und eine Ausgangsrechnung. D.h., die Fehler mit Zugriffsverletzung haben trotz alledem erfolgreich einen beleg angelegt. Der folgende Fehler mit dem Bad Request hat dagegen keinen weiteren Beleg angelegt.

Bitte prüfen Sie dies noch einmal, denn ich kann hier keine weiteren Änderungen mehr vornehmen. Der einzige verbliebene Workaround für uns wäre, vor und nach der Belegerstellung über die API die höchste Belegnummer auszulesen und, falls sich diese geändert hat, davon auszugehen, dass dieser Beleg trotz Fehlermeldung durch die API angelegt wurde. Dies öffnet jedoch die Tür für Timingprobleme mit anderen Importstrecken oder zeitgleich durch Benutzer angelegte Belege.

Mit freundlichen Grüßen
Alexander Meyer

**Comment by jprause1234** [comment]
Hallo Herr Meyer,

eine Nachfrage habe ich noch. Haben die beiden API Benutzer jeweils ein eigenes Wawi Kürzel zugeordnet oder verwenden beide das selbe Kürzel?

Viele Grüße
Jan Prause

**Comment by aameyer** [comment]
Hallo Herr Prause,
für beide API-Benutzer ist der selbe WaWi-Benutzer hinterlegt.

**Comment by jprause1234** [comment]
Hallo Herr Meyer,

können Sie bitte jedem API Benutzer ein eignes Wawi Kürzel zuweisen. Der Hintergrund ist, dass dann jeder API Benutzer einen eigenen Backend Prozess bekommt und ich vermute, dass dann dieses Problem nicht mehr auftritt. Unabhängig davon werden wir dieses Szenario intern bei uns nachstellen und Lösungen erarbeiten.

Viele Grüße
Jan Prause

**Comment by VivienSchuboth** [comment]
Guten Tag Herr Meyer,

wir können die Probleme, die Sie beschreiben, mittlerweile nachvollziehen und arbeiten an einer Lösung.

Mit freundlichen Grüßen,
Vivien Schuboth

**Comment by VivienSchuboth** [comment]
Guten Tag,
wir haben das Handling paralleler Anfragen an die SelectLine API optimiert. 
Damit lösen sich hoffentlich auch die Probleme in #8, #14 und #22.
Die Fehlerbehebung steht Ihnen mit der V21.1 zur Verfügung.

Mit freundlichen Grüßen,
Vivien Schuboth
