### ISSUE TITLE
Fehlende Infos in der Fehlermeldung

### ISSUE THREAD

**Issue by Logic-Bits** [selectline-software/selectline-api#70]
Hallo!

```
{
    "StatusCode": "BadRequest",
    "ResponseCode": "42-030",
    "Message": "WindowOnTheServerWasOpenedException",
    "Details": {
        "ResponseDetails": "Die Aktion wurde abgebrochen, weil versucht wurde ein Fenster zu öffnen.",
        "ResponseType": "WindowWasOpened",
        "ErrorCode": 402
    }
}
```

kann man hier noch Infos bekommen warum das passiert?

Danke!

**Comment by VivienSchuboth** [comment]
Guten Tag,

in der SelectLine API Hilfe steht Ihnen eine Seite für die Response/Error-Codes zur Verfügung.
https://demo.slmobile.de/demoApi/Help/ResponseCodes

![image](https://user-images.githubusercontent.com/34538107/102620507-64367380-413e-11eb-88d0-5d9f3cf4d9e1.png)

Mit freundlichen Grüßen,
Vivien Schuboth

**Comment by Logic-Bits** [comment]
Danke
