### ISSUE TITLE
Kunden aus Mobiel API lesen schlägt fehl.

### ISSUE THREAD

**Issue by Torchok19081986** [selectline-software/selectline-api#71]
Hallo, ich habe ein Problem mit CustomerAPI und SupplierAPI. 
Wenn man nach erfolgreiche Login versucht z.B. für Kunden einer der foglenden Methoden zu verwedenen (CustomerApi.CustomerReadCustomersAsync oder CustomerApi.CustomerReadCustomerByNumberAsync ), erscheint Fehlermeldung, dass man sich vorher authentifizieren soll.  Für das Login verwende ich folgende Method und es kommt Statuscode 200 -> erfolgreich.
 ```csharp
string url = "https://localhost:443/slmobile/";
url += "Login"; 
var client = new ApiClient(url);
Configuration.Default.ApiClient.RestClient = client.RestClient;
  Configuration.Default.ApiClient.RestClient.Authenticator = new NtlmAuthenticator(username, pwd);
 client.RestClient.Encoding = Encoding.UTF8;
 RestRequest request = new RestRequest(Method.POST);
request.AddHeader("Accept", "application/json");
var response = client.RestClient.Execute(request);
if (response.StatusCode == HttpStatusCode.OK)
 {
     var liste = CustomerApi.CustomerReadCustomersAsync() //<-- hier erscheint die Meldung
}
 else
 {
      MessageBox.Show("Fehlgeschlagen mit " + response.StatusCode.ToString());
}
```
Wie lese ich einen oder die Liste von alle verfügbaren Kunden nach dem Login ?

**Comment by VivienSchuboth** [comment]
Guten Tag,
für einen Login an der SelectLine API benötigen Sie die folgenden Informationen:

```
POST {{url}}/Login
{
  "UserName": "string",
  "Password": "string",
  "LoginKind": "MobileApi",
  "AppKey": "string"
}

```
Sobald diese Anfrage einen Erfolg (StatusCode = 200) zurückliefert, wird Ihnen ebenfalls eine LoginId zur Verfügung gestellt.
Diese müssen Sie nun in jeder Anfrage an die SelectLine API mitschicken.

Wenn Sie sich mit der SelectLine API erst einmal vertraut machen wollen, würde ich Ihnen die nachfolgenden Links oder auch gerne unsere SelectLine API-Schulung empfehlen.

- https://demo.slmobile.de/demoApi/swagger/ui/index 
- https://demo.slmobile.de/demoApi/Help
- https://demo.slmobile.de/demoApi/Help/ApiFunctions 

Mit freundlichen Grüßen,
Vivien Schuboth

**Comment by Torchok19081986** [comment]
Hallo, Vielen Dank für die Antwort. Könnte ich vllt noch eine Erklärung bekommen, was die Appkey für eine Bedeutung hat? Leider kann ich mir darunter etwas anderes vorstellen als Sie vermutlich es meinen. Ist das AppKey eine webseite wo das App liegt, wie https;//.../Login oder hat Appkey andere Bedeutung ? bis jetzt haben wir das Login und die Daten nur mit HttpClient und HttpResponse behandelt. Aber mit OpenAPI von Swagger geht einfacher.

**Comment by VivienSchuboth** [comment]
Guten Tag,

um auf die Funktionen der SelectLine API zugreifen zu können, benötigen Sie eine Lizenz.
Diese Lizenz stellt Ihnen einen AppKey bereit, der Ihnen den Zugriff auf die SelectLine API gewährt.
Der AppKey ist sozusagen der Schlüssel, um überhaupt mit der SelectLine API arbeiten zu können.

Bei Fragen zu dem Erwerb einer Lizenz und des AppKeys wenden Sie sich bitte an Ihren Vertriebspartner oder an unser Partnermanagement der SelectLine Software GmbH.

Beste Grüße,
Vivien Schuboth
