### ISSUE TITLE
Wawi Makro Funktioniert nicht (wie in Postman Beschreibung)

### ISSUE THREAD

**Issue by Logic-Bits** [selectline-software/selectline-api#72]
Version 20.3.0

Hallo,

https://demo.slmobile.de/demoApi/swagger/ui/index#/Macro/Macro_ExecuteWawiMacroPerPipe

Bei dem Beispiel ein Wawi Makro auszuführen kommt immer der gleiche Response mit, egal ob es die Parameter gibt, oder gar des Makro existiert.
Auch sagt die Doku dass hier ein bool zurück kommt.
Example und Model unterscheiden sich auch (Groß / Kleinschreibung).

```
{
    "ResponseDetails": "Betroffene Zeilen: 8611596",
    "ResponseType": "Ok",
    "ErrorCode": 0
}
```

Gibt es hier ein Beispiel auf beide Seiten? Nur das Postman Beispiel funktioniert so nicht (update sowie select).

Danke für die Rückmeldung.

**Comment by VivienSchuboth** [comment]
Guten Tag,
intern konnten wir dieses Problem noch nicht nachstellen. 

Könnten Sie uns bitte verraten, wie sie den Aufruf abschicken und welche Aufgabe das Makro übernimmt (Lesen, Schreiben, Aktualisieren oder Löschen von Daten?) . 

Wurde nach dem Anlegen des Makros der Backendmanager-Prozess noch einmal neugestartet? Wenn nein, könnte es sein, dass dem Backend-Prozess das Makro noch gar nicht bekannt ist.

Beste Grüße,
Vivien Schuboth

**Comment by Logic-Bits** [comment]
Vielen Dank für den Tipp mit dem Neustarten des Backendmanagers - habe ich nicht in der Swagger Beschreibung gefunden. Evtl könnte man dem nächsten das mit einem Kommentar ersparen.

**Comment by Logic-Bits** [comment]
Nächster Fehler => Doku sagt es kommt Boolean zurück, aber in echt ein String / Json ....

**Comment by VivienSchuboth** [comment]
Danke, das werden wir mit der nächsten Version korrigieren.

Beste Grüße,
Vivien Schuboth
