### ISSUE TITLE
Ändern der zweiten Benutzer Datenbankname gibt das Forbidden Code zurück.

### ISSUE THREAD

**Issue by Torchok19081986** [selectline-software/selectline-api#74]
Hallo , ich verändere einer unseren Plugin basierend auf Mobile API und habe ein Problem, dass ich nach dem Einloggen von zwei Benutzer , die erlaubte Mandanten Db´s für den 2. Benutzer nicht abgreifen. 
Unsere Tool übergibt nur Stammdaten aus einem Mandanten in das Ausgewählten mandanten , welche im Combobox geladen wird. Es wird folgende Methode in C# und WPF verwendet. 

```csharp

 public void ChangeTetant(int User) //für den zweiten User.
 {
        using (var client = new HttpClient())
        {
            requestUri = string.Format("{0}Users/Current", Url.Text);
          
            SetClientDefaults(client, requestUri);
            SetClientAuthorization(client, User);

            var user = new
            {
                TenantDatabaseName = Combobox.SelectedItem.ToString()
            };

           var response = client.PutAsJsonAsync(requestUri, user).Result;

    
        }
}

```` 
Es kommt beim response ein Forbidden Code zurück, obwohl der Benutzer die Recht hat , das Mandantwechsel.

**Comment by MatthiasGuse** [comment]
Hallo,
welcher code wird genau zurückgegeben?
Hat der angemeldete Benutzer auch das Recht den Mandanten zu bearbeiten?

Eine alternative wäre es dem zweiten Benutzer in der Mobile-Passwortverwaltung gleich den gewünschten Mandanten zuzuweisen. So kann man sich den Mandtantenwechsel ja ersparen, wenn es nur zwei Mandanten gibt.

**Comment by Torchok19081986** [comment]
Hallo, danke für die Info. Es wird ein 403, also Forbidden zurückgegeben. Jap, das Recht für Mandantenwechsel besitzt der zweite Benutzer. In der Rechteverwaltung in Mobilemanager ist der grüne häkchen an. Propblem ist, dass es 14 Mandaten sind. Genau hier ist das Problem. Es ist immer selber Quelle, aber immer unterscheidlicher Zielmandant

**Comment by MatthiasGuse** [comment]
Hallo,
API Benutzer haben in der Benutzerverwaltung von Mobile gar keine Möglichkeit Rechte einzustellen. Seit geraumer Zeit sind diese Einstellungsmöglichkeiten entfert wurden. Kann es sein, dass Sie eine sehr alte Version einsetzen oder versuchen einen Benutzer in der API zu verwenden, der gar kein API-Nutzer ist?

Ebenfalls ist es nötig, dass der gewählte Benutzer in der Rechteverwaltung der **Warenwirtschaft** auch das Recht auf den jeweiligen Mandanten besitzt. Sie können die erlaubten Mandanten auch per API über GET/Users/Current abfragen.

**Comment by Torchok19081986** [comment]
Guten Morgen, die Version ist die 20.3.7 und dazu passender SL Mobile Version. Der Benutzer ist im SL Mobile Manager als API Benutzer angelegt und heißt Ziel. Dieser Benutzer hat das Recht auf alle Mandanten sowohl im SQL Server als auch im Warenwirtschaft. Bis zu Version 20.3.X hat die oben gepostet Code einwandfrei funktioniert und jetzt nach dem Update kommt das 403 - Forbidden zurück, wenn man das Ändern des Zielmandanten zu ändern versucht. Es wird das von dem angemeldeten Benutzer, die List alle erlaubeten Mandaten abgegegriffen und diese Property ist AllowedTenantList als HashSet<T>.  
Hier wird das combobox auch gefüllt. die Daten erscheinen auch korrekt. Wenn man veruscht, dann aber Customer / Supplier nach gewählten Db zu übertragen mit POST / PUT, dann kommt Forbidden.

**Comment by MatthiasGuse** [comment]
Übergeben Sie den neuen "TenantDatabaseName" beginnend mit "SL_M"?

Bitte prüfen Sie ob bei dem Benutzer dessen Mandanten Sie ändern möchten, ob in der Mobile Benutzerverwaltung ein Mandant zugewiesen ist. Wenn nein weisen Sie bitte einen zu und testen es erneut. 

Meine Vermutung ist, dass beim Mandantenwechsel die Angabe eines Mandanten der nicht existiert (flasche Name oder Schreibweise) zu diesem Effekt führt, dass der zugewiesene Mandant rausfliegt und man sich danach nicht mehr korrekt einloggen kann.

**Comment by Torchok19081986** [comment]
Hallo, Vielen Dank für die Info. Das werde ich dann überprüfen. 
Die Namen der Mandaten erscheinen alle mit SL_M<Number> und hier dann zwischen M10 und M99, sind 14 Stück belegt (etwas durcheinander) , In dem Mobile Manager nachdem man das 2 Benutzer anlegt oder dieser angelegt worden, wird IMMER irgendeinen Mandant zugewiesen, weil es sowieso gewechselt wird, AFAIK ist die Schreibweise der Mandanten ist nicht beeinflussbar. 
Ich konnte auch das code soweit bis zum 
 var response = client.PutAsJsonAsync(requestUri, user).Result;
verfolgen. Hier kommt als Response Forbidden zurück. 
Muss ich vllt. das SelectedItem von Combobox als Tenant object aus Selectline.Erp.TenantModule casten?

**Comment by MatthiasGuse** [comment]
Wie geschrieben. Bitte erstmal prüfen ob beim Benutzer in der Mobile Benutzerverwaltung ein Mandant eingetragen ist oder nicht. Ich bekommen ebenfalls "Forbidden" wenn der Mandant leer ist. Solange der Mandant gefüllt ist, funktioniert es bei mir.

**Comment by Torchok19081986** [comment]
Morgen. Ich habe gerade geprüft. Folgende Eingaben stehen bei mit im Benutzerverwaltung: Name ist User1, Type : API, Kürzel 1, Mandanten WAWI, und als zugewiesene Mandant ist Muster Warenwirtschaft . Als Name der Tenant kommt SL_MWAWI für diesen Benutzer zurück.

**Comment by MatthiasGuse** [comment]
Bitte stellen Sie mir einen Screenshot der Benutzerverwatung zur Verfügung, wenn diese keine sensiblen Daten enthalten.
![grafik](https://user-images.githubusercontent.com/31447000/105331618-f4e7ef80-5bd3-11eb-9a9e-c62bcfccf6c9.png)

**Comment by Torchok19081986** [comment]
Ok. Mache ich.  Sollte jetzt dann sichtbar sein.
![SL Mobile Übersicht](https://user-images.githubusercontent.com/25432729/105332458-ef3ed980-5bd4-11eb-8eda-0d946f1523e4.JPG)

**Comment by Torchok19081986** [comment]
Alle Tests sind grün. Und Mobile Manager beklagt nicht die Version. Bis jetzt habe ich das Mandantenwechsel immer im Code C# gemacht. Könnten Sie mit evtl. die Anleitung oder link senden, wie ich es per Swagger Mandantenwechsel durchführen kann ?
Aufgrund von der neuen geänderten Lizenz und evtl. auch da Benötigen von AppKey ist noch keine gültige Lizenz eingetragen. 
Könnte es vllt. die Ursache sein ? 
Folgende Info kann ich geben: bis jetzt wurde immer beide Benutzer gleichzeitig eingeloggt und dann fand mandatnwechsel statt. Jetzt aber in der neuen Version des Tools wird der Zweite Mandant erst eingeloggt, wenn es zum Datenübertrag kommt. 
Kann es daran liegen, dass der Benutzer aus gerade unerklärlichen Gründen das Mandantwechsel verweigert wurde? AccessToken wird aber den 2. Benutzer zugewiesen, also, bin ich davon ausgegangen, dass der o.g. C# Code auch gehen wird. Sonst muss ich in der Tat das ganze mühseelig anschauen. Gibt es evtl. Log für das Verhalten des Momobile Manager. Leider habe ich dazu nichts gefunden.

**Comment by MatthiasGuse** [comment]
Ist in Ihrer Anwendung neben dem Error 403 auch der ResponseCode zu bekommen? Vielleicht kommen wir da eher auf einen Nenner.

Grundsätzlich kann ein Nutzer nur, wenn er selbst angemeldet ist den Mandanten für sich selbst ändern. Meine Empfehlung wäre es für jeden Mandanten einen Nutzer anzulegen und das so zu verwalten, dass die Anmeldung am jeweiligen Zielmandanten einfach durch die Anmeldung eines bestimmten Nutzers gesteuert wird. Somit wird sich die jeweilige Mandantenänderung erspart.

Neben Swagger ginge natürlich auch Postman. Beschreibung für Swagger:

- Im Mobile Manager --> Seite Webseite die Hilfe aufrufen - "...api/help"
- Unter Grundlagen - Swagger wählen --> "Swagger Dokumentation und Testumgebung" auswählen
- Dann "Account" --> "Login" öffnen und oben rechts "Try it out" klicken
- Benutzeranmeldung eingeben ("Appkey" entfernen, wenn nicht vorhanden) --> Excecute
- Wenn erfolgreich "AccessToken" aus Response kopieren, nach ganz oben scrollen --> "Authorize" klicken und Token einfügen --> "Authorize" klicken
- Dann unter User die Mandantenänderung durchführen (wieder "Try it out"...)
![grafik](https://user-images.githubusercontent.com/31447000/105358455-7a7c9700-5bf6-11eb-94b4-7305cb251eb0.png)
- Was kommt unter ResponseCode und Message zurück?

**Comment by Torchok19081986** [comment]
Ok. Das scheint es wohl die Ursache zu sein.  Es kommt genau hier als Responses 204 und doe 403 . In der Description: No Content und Forbidden.

**Comment by VivienSchuboth** [comment]
Guten Abend,

ich vermute hier liegt noch ein Verständnisproblem vor.
Auf Ihrem Screenshot erkennt man, das alles geklappt hat. Die Rückgabe bei einem PUT ist, wenn alles funktioniert, die Response 204. 
Unter "Server responses" sehen wir die Rückgabe zu Ihrer Anfrage: 204.
Es sollte also alles geklappt haben.

In Swagger finden Sie unter "Responses" alle möglichen Rückgabecodes für diese Funktion aufgelistet - unabhängig von ihrer Anfrage.
Dies dient lediglich der Dokumentation der API. Sie als Anwender können so für diese Codes in Ihrem Programm Weichen einstellen.

Als Beispiel:

if (response == 204) {
  console.log("alles super");
} else if (response == 403) {
  console.log("kein zugriff");
} else {
 console.log("unbekannter fehler");
}

Ich hoffe, es hilft Ihnen ein wenig.

Beste Grüße,
Vivien Schuboth

**Comment by Torchok19081986** [comment]
Hallo, vielen Dank für die Info.  Ich habe gerade mir die Rechte im SQL Server vergliechen, Kann es sein, dass dem Benutzer die Rechte im SQL Server fehlen ? Einer Benutzer ist mit Window Anmeldunge verknüpft und der zweiter ist mit einem SQL Benutzer angelegt. BEIDE sind aber im WaWi erstellt worden. Gibt es da eine Richtlinie, wie man die Benutzer für das Mobile API anlegt ? Ein Link oder Hilfestellung wäre gut.

**Comment by MatthiasGuse** [comment]
Unserer Meinung nach hat das keine Rechteproblem zu Grunde zu liegen. Per Swagger funktioniert es ja bei Ihnen. Das würde bei fehlenden Rechten fehlschlagen.

Die API gibt neben dem Error Code auch einen ResponseCode und eine Message aus. Um hier weiterzukommen benötigen wir diese Informationen, die im Falle des 403 Fehlers Ihrer Anwendung zurückgemeldet werden. 

Beispiel: 
![grafik](https://user-images.githubusercontent.com/31447000/105454531-56ff2e00-5c82-11eb-8638-942eb5362e84.png)

**Comment by Torchok19081986** [comment]
Guten Morgen, Vielen Dank für weitere Hilfe.  Als Response erscheint, wie die vorher gesagt wurde, eine 204 Message und unter der Response ist keine weitere Info. Nach dem ich die Kiste neu gestartet habe und auch gleichzeitig ein paar Windows Updates mit Windows Defender installiert habe, so erscheint nun das gewechselte Db im dafür vorgesehen Combobox.  Es ist Windows Server 2019. IIS in der Version 10.0.17763.1. Gibt es die Möglichkeit nun im Swagger abzuprüfen, in welchen Db der Benutzer gewechselt wurde?

**Comment by MatthiasGuse** [comment]
GET​/Users​/Current - Liest den angemeldeten Benutzer
Unter "TenantDatabaseName" sehen Sie den aktuellen Mandanten.
