### ISSUE TITLE
Status einzelner Positionen

### ISSUE THREAD

**Issue by mbuhl11** [selectline-software/selectline-api#75]
Ist es möglich den Status einzelner Positionen eines Beleges auf erledigt zu setzen bzw. zu ändern oder ist dies über die API nur für komplette Belege möglich?

**Comment by VivienSchuboth** [comment]
Guten Tag,

das Setzen des Status ist nur für den Beleg und nicht für dessen Positionen möglich.
Falls Sie sich diese Funktionalität wünschen, können Sie gerne einen Eintrag im UserVoice-Forum der SelectLine einstellen.

Beste Grüße,
Vivien Schuboth
