### ISSUE TITLE
Swagger Authentifizierung Credentials c#

### ISSUE THREAD

**Issue by git828** [selectline-software/selectline-api#76]
Hallo, Ich probiere momentan eine Einbindung mit IO.Swagger in c# Net Core 5.
IO.Swagger.Api.InfoApi() funktioniert.
Leider habe Ich Probleme mich anzumelden.
Alle versuche enden immer mit 
..."Message": "Sie müssen sich einloggen, um diese Funktion zu nutzen.",

Im README.md der generierten Swagger c# steht nur:
// Configure API key authorization: LoginId
 Configuration.Default.ApiKey.Add("Authorization", "YOUR_API_KEY");
// Uncomment below to setup prefix (e.g. Bearer) for API key, if needed
// Configuration.Default.ApiKeyPrefix.Add("Authorization", "Bearer");

Hat jemand ein Beispiel wie Ich die Credentials mit Username password hin bekomme?

Danke

**Comment by Torchok19081986** [comment]
Hallo, ich habe selben Problem. Weder über Postman noch über eigens Programm, in C#, konnte ich mich am anmelden. 
Nach einer Zeit und ewig ausprobieren, habe ich folgende Methode ausgearbeitet.
```charp


private bool MethodeLogin()
        {
            try
            {
                using (var client = new HttpClient())
                {
                    var cred = new Credentials { UserName = Txtusername.Text, Password = TxtPassword.Password };
                    HttpContent content = new StringContent(JsonConvert.SerializeObject(cred));
                    content.Headers.ContentType = new MediaTypeWithQualityHeaderValue("application/json");  
                    string loginuri = Targeturi.Text.EndsWith("/") ? Targeturi.Text : string.Concat(Targeturi.Text, "/");           
                    Targeturi.Text = loginuri;
                    loginuri += "Login";
                    var response = client.PostAsync(loginuri, content).Result;
           
                    if (response.IsSuccessStatusCode)
                    {
                        var tokenModel = response.Content.ReadAsAsync<Token>().Result;

                        if (tokenModel != null)
                        {
                            AccessToken1 = tokenModel.AccessToken;b //accesstoken ist eine Property
                        }

                        var mainwindow = new MainWindow(Targeturi.Text, AccessToken1)
                        {
                            ShowInTaskbar = true
                        };
                        mainwindow.Show();
                        this.Close();
                    }

                    if (response.StatusCode == HttpStatusCode.OK)
                    {
                        loginsuccess1 = true;

                        return true;
                    }
                    else
                    {
                        loginsuccess1 = false;
                        var apiResponse = response.Content.ReadAsAsync<ApiResponse>().Result;
                        MessageBox.Show(apiResponse.StatusCode.ToString() + "\n" + apiResponse.ResponseCode + "\n" + apiResponse.Message, "Webresponse from Server", MessageBoxButton.OK, MessageBoxImage.Warning);
                        return false;
                    }
                }
            }
            catch (NullReferenceException nullref)
            {
                MessageBox.Show(nullref.ToString());
                return false;
            }
            catch (Exception exc)
            {
                MessageBox.Show(exc.ToString());
                return false;
            }
        }

``` 
das ganze ist im WPF gemacht, aber probieren Sie es selbst aus.

**Comment by ThePholph** [comment]
Hallo,

findet ihr alles unter https://ServerIP:Port/slmobileApi/Help/HowToUse

Hier ein Beispiel:

Url: https://ServerIP:Port/slmobileapi/login
Content-Type: application/json
Method: POST
Body:
````
{
    "username": "user",
    "password": "pw",
    "AppKey": "optional wenn vorhanden"
}
````
Beispiel mit curl:

````
curl -X POST -k -H 'Content-Type: application/json' -i 'https://ServerIP:Port/slmobileapi/login' --data '{ "username":"user", "password":"password", "AppKey":"optional wenn vorhanden" }'
````

**Comment by git828** [comment]
Vielen Dank für die Hinweise.
Ich meinte mit Swagger kann man so was wie die IO.Swagger.Model.Credentials anpassen. 
Und das sollte es sein. 
Versteh Ich da was falsch?

**Comment by Torchok19081986** [comment]
nach meinen Tests, kann ich nur eins sagen, dass man die Swagger.IO Models von mitgelieferten json Datei im Mobile, nicht ohne gültigen AppKey verwendet werden, somit auch keine APPKEY für das Anmelden. Das mobile Manager akzeptiert einfach das Anmeldenvorgang , trotz den gültigen Daten.

**Comment by git828** [comment]
Beispiel bringt 
Error System.IO.InvalidDataException: userName is a required property for Credentials and cannot be null
   at **IO.Swagger.Model.Credentials**..ctor(String userName, String password, Nullable`1 loginKind, String appKey)
an dieser Stelle: 
var cred = new Credentials { UserName = "APIUser", Password = "Ichverzweifle1000%" };

**Comment by Torchok19081986** [comment]
Guten abend. Wie senden Sie die credentials ans Zielurl ? Diese müssen zuerst als Stringcontent und Jsonconvert serialisiert werden, erst dann können die Daten ans Zielurl übergeben werden. Vermutlich ist hier bei Ihnen nichts oder NULL, darum fehlermeldung,
in etwas so:
    HttpContent content = new StringContent(JsonConvert.SerializeObject(cred));
                    content.Headers.ContentType = new MediaTypeWithQualityHeaderValue("application/json");  
Auch in Beispiel APP für WPF und C# ist auch dargestellt. Probieren Sie es aus.

**Comment by MatthiasGuse** [comment]
Seit der Version 19.3 braucht man einen AppKey mit dem die Anmeldung der Anwendung bei der SelectLine API erfolgen muss. Ohne gültigen AppKey, der auch in der Lizenz der dahinterliegenden Installation hinterlegt ist, kann man sich nicht anlmelden.

**Comment by git828** [comment]
Bitte versteht mich nicht falsch. Das einloggen funktioniert AppKey habe Ich. Das Console Demo von Seleceltine funktioniert wunderbar.
Nur das kann Ich nicht gebrauchen wenn Ich Swagger benutzen will.
Ein Aufruf zum Beispiel von:
```
List<Article> result = apiInstance.AccessoryArticleReadArticlesWhereArticleIsAccessoryArticle(accessoryArticleNumber, .....)
Console.WriteLine(result);
```
endet immer in 
```
Exception when calling AccessoryArticleApi.AccessoryArticleReadArticlesWhereArticleIsAccessoryArticle: Error calling AccessoryArticleReadArticlesWhereArticleIsAccessoryArticle: {
  "StatusCode": "Forbidden",
  "ResponseCode": "22-002",
  "Message": "Sie müssen sich einloggen, um diese Funktion zu nutzen.",
  "Details": null
}
```
Ich kriege einfach die IO.Swagger.Model.Credentials nicht hin.
Oder Ich denke da falsch.
Wie Authentifiziert man sich bei Swagger per c#?

**Comment by Torchok19081986** [comment]
Abend. Leider kann ich Ihnen hier nicht weiterhelfen. Nur die SL Mobile Profil wissen evtl. Antwort drauf. Ich arbeite auch auf dem anderen Project, wo ich das auch Swagger OpenAPI nutzen, nach dem man das Client generiert hat und , im meinem Fall, dies im Visual Studio geöffnet hat, so erscheint zusätzlich das RestSharpClient dll (oder wird von dem Nuger Package Manager wiederhergestellt.) Da kann ich OpenAPI verwenden und hier gibt es keine Probleme, um die Daten zu bekommen .

**Comment by git828** [comment]
Ich hab es Geschafft ! Hier mein Gebastel. 
Ich bin überzeugt das es auch eleganter klappt. Da wissen die SL MobileAPI  Pros sicher mehr.
```
var credentials = new Credentials(
                userName: APIUsername,
                password: APIPassword,
                appKey: apiKey
                );
```
Login Authorize: (Da Ich nicht weiss wie das wirklich funktioniert habe Ich den Header selber geändert)
 ```
var apiLogin = new IO.Swagger.Api.AccountApi();
            try
            {
                // Logs user into the system
                Token token = apiLogin.AccountLogin(credentials);
                Configuration.Default.DefaultHeader.Add("accept", "application / json");
                Configuration.Default.DefaultHeader.Add("Authorization", "LoginId " + token.AccessToken.ToString());

            }
            catch (Exception e)
            {
                Console.WriteLine("Exception when calling UserApi.LoginUser: " + e.Message);
            }
```
Nun kann klappt es auch mit so etwas
```
                var cust = apiKunde.CustomerReadCustomerByNumberAsync("123456");
                Console.WriteLine(cust.LastName);
```
Vielen Dank
