### ISSUE TITLE
Route ExtraTable

### ISSUE THREAD

**Issue by ThorstenPoppe** [selectline-software/selectline-api#78]
Guten Morgen,

die Route ExtraTable wird in https://apiupdate.selectline.de/ als Obsolete gekennzeichnet und soll mit Version 21.1 entfernt werden?!
Oder verstehe ich das falsch und es bezieht sich lediglich auf den genutzte Model dahinter (InsertExtraTable is deprecated and will be revised next version.)

**Comment by VivienSchuboth** [comment]
Guten Morgen,

ja, die dort gelistete Route wird entfernt. Trotz dessen können Sie Ihre Daten weiterhin in Extratabellen einpflegen.
Dafür steht Ihnen die Route POST ExtraTable/{tableName} zur Verfügung. Hier werden wir die Beschreibungen zu den Properties bis zur V21.1 ordentlich nachpflegen.

Beste Grüße,
Vivien Schuboth

**Comment by ThorstenPoppe** [comment]
Hallo Vivien,

danke für die Info!
Wir benötigen das für ei kommendes Projekt, dann können wir es doch weiter angehen.

Viele Grüße,
Thorsten Poppe
