### ISSUE TITLE
UpdateDocumentErrorException beim Aktualisieren einer Belegposition

### ISSUE THREAD

**Issue by chucky2002** [selectline-software/selectline-api#79]
Version: SelectLine 20.3.8, SL.Mobile 20.3.8
Bereich: Aktualisierung Belegposition

Problem: 
Das Aktualisieren einer Belegposition schlägt fehl, wenn der Wert bereits eingetragen ist.
Das Problem lässt sich mit der SwaggerUI reproduzieren. Dazu ist wie folgt vorzugehen:
- im SelectLine  Auftrag anlegen und Belegposition mit Artikel anlegen. Zeilentyp A
- Über die Swagger UI und den CALL /Documents/{documentKey}/Positions/{documentPositionIdentifier} die Bezeichnung der Belegposition mit dem Text "Foobar123" aktualisieren.

Ergebnis:
- die erste Aktualisierung ist erfolgreich
- die zweite Aktualisierung schlägt fehl, da der Wert für das Update nicht geändert wurde
- wird der Text auf "Foobar456" geändert, ist die Aktualisierung erfolgreich. die Zweite Aktualisierung mit dem gleichen Wert schlägt fehl

Erwartet:
- der Text einer Belegposition sollte sich beliebig oft aktualisieren lassen, auch wenn sich dadurch kein Wert in der Position ändert.

**Request**
<img width="971" alt="Swagger Request" src="https://user-images.githubusercontent.com/3708455/105771936-afc01680-5f61-11eb-832a-b03c176592b0.png">

**Response des ersten Request - erfolgreich**
<img width="978" alt="Swagger Response 1 - OK" src="https://user-images.githubusercontent.com/3708455/105771945-b3ec3400-5f61-11eb-9831-96971790212c.png">

**Response des zweiten Request ohne Änderung des Wert- Fehler**
<img width="979" alt="Swagger Response 2 - ERROR" src="https://user-images.githubusercontent.com/3708455/105771950-b77fbb00-5f61-11eb-9bc4-d57945ccf401.png">

**Comment by VivienSchuboth** [comment]
Guten Morgen,

danke für den Hinweis! 
Wir werden uns diesen Fehler anschauen und uns bei Ihnen melden, wenn wir wissen, zu welcher Version Ihnen die Korrektur zur Verfügung steht.

Beste Grüße,
Vivien Schuboth

**Comment by VivienSchuboth** [comment]
Hallo noch einmal,
die Korrektur steht Ihnen mit der V21.1 zur Verfügung, die im Laufe des 1. Quartals diesen Jahres ausgeliefert wird.

Beste Grüße,
Vivien Schuboth
