### ISSUE TITLE
ResponseCodes Dokumentation falsch

### ISSUE THREAD

**Issue by Largo** [selectline-software/selectline-api#80]
In der Dokumentation sollte anstatt ein Doppelpunkt ein Bindestrich stehen:

falsch:
`[ModulCode]:[ErrorCode]
`
richtig
`[ModulCode]-[ErrorCode]
`

[AntwortCodes](https://demo.slmobile.de/demoApi/Help/ResponseCodes)

Beispiel aus API 20.3.6

```
/Login POST
{ "StatusCode": "InternalServerError", "ResponseCode": "02-000", "Message": "Es konnte eine Verbindung mit dem Server hergestellt werden, doch während des Handshakes vor der Anmeldung trat ein Fehler auf. (provider: SSL Provider, error: 0 - Der Wartevorgang wurde abgebrochen.)", "Details": null }
```

Beispiel aus der API 20.2

```
/Users/Current GET
}
  "Details": null
  "Message": "User (LoginId: xyz) not found.",
  "ResponseCode": "04-003",
  "StatusCode": "Forbidden",
{
```

**Comment by VivienSchuboth** [comment]
Danke für den Hinweis!
Den Fehler werden wir mit der nächsten Version korrigieren.

Beste Grüße,
Vivien Schuboth
