### ISSUE TITLE
Apimakro ausführen endet in Timeout

### ISSUE THREAD

**Issue by dbu828** [selectline-software/selectline-api#81]
Beim Ausführen eines Makros
https://hostname:444/slmobileApi/Macros/test 
( das auch im SQLManagement ca. 2min läuft) erhalte Ich nach exakt 30 Sekunden ein timeout.
```
{
  "StatusCode": "InternalServerError",
  "ResponseCode": "70-000",
  "Message": "Das Ausführungstimeout ist abgelaufen. Der Timeoutzeitraum wurde überschritten, bevor der Vorgang beendet wurde, oder der Server antwortet nicht.",
  "Details": null
}
```
SelectLine.Erp.WebApi.WebHost zeigt:
`{ "Name": "SelectLine.Erp.WebApi.WebHost", "TimeStamp": "2021-01-26T06:56:32.9621554Z", "ServerTimeStamp": "2021-01-26T06:56:32.9621554Z", "Host": {"Name":"API","Version":"Microsoft Windows NT 10.0.14393.0","UserName":"SelectLine","64bit":true}, "Process": {"FileName":"c:\\windows\\system32\\inetsrv\\w3wp.exe","Name":"w3wp","64bit":true,"ProcessId":2748,"ThreadId":30,"Runtime":"0:08:40:42.8127886","PrivateBytes":136671232}, "LogLevel": "Error", "Message": "Das Ausführungstimeout ist abgelaufen. Der Timeoutzeitraum wurde überschritten, bevor der Vorgang beendet wurde, oder der Server antwortet nicht.", "Exception": {"Message":"Das Ausführungstimeout ist abgelaufen. Der Timeoutzeitraum wurde überschritten, bevor der Vorgang beendet wurde, oder der Server antwortet nicht.","Data":{"HelpLink.ProdName":"Microsoft SQL Server","HelpLink.ProdVer":"14.00.2027","HelpLink.EvtSrc":"MSSQLServer","HelpLink.EvtID":"-2","HelpLink.BaseHelpUrl":"http:\/\/go.microsoft.com\/fwlink","HelpLink.LinkId":"20476"},"InnerException":{"Message":"Der Wartevorgang wurde abgebrochen","StackTrace":null}}, "CallerStack": ["SelectLine.Erp.WebApi.Controllers.Attributes.CatchExceptionAttribute.OnException(System.Web.Http.Filters.HttpActionExecutedContext context)","System.Web.Http.Filters.ExceptionFilterAttribute.OnExceptionAsync(System.Web.Http.Filters.HttpActionExecutedContext actionExecutedContext,System.Threading.CancellationToken cancellationToken)","System.Web.Http.Filters.ExceptionFilterAttribute.ExecuteExceptionFilterAsyncCore(System.Web.Http.Filters.HttpActionExecutedContext actionExecutedContext,System.Threading.CancellationToken cancellationToken)"] }
`

Wo kann man das timeout einstellen?

**Comment by VivienSchuboth** [comment]
Guten Tag,
diese Einstellung ist bisher nicht konfigurierbar. Dieses Feature erwartet Sie jedoch in der V21.1!
Das Timeout wird zukünftig über die Konfigurationsdatei der SelectLine API bestimmt. 

Mehr dazu finden Sie in dem Einrichtungsdokument der SelectLine API, MDE und BDE für die Version 21.1, welches Ihnen mit der Auslieferung der Produkte im Laufe des 1. Quartals 2021 zur Verfügung stehen wird.

Beste Grüße,
Vivien Schuboth

**Comment by dbu828** [comment]
Vieln Dank für die Info.
