### ISSUE TITLE
SerieCharge buchen

### ISSUE THREAD

**Issue by Lars-Mue** [selectline-software/selectline-api#82]
Hallo zusammen, 

mir ist gerade aufgefallen, dass bei  Übergeben eines Auftrags in die Rechnung/Lieferschein in der Tabelle SerieCharge
zu der Ausgewählten Serie kein Abgang bebucht wird. 
Weder über MDE noch über API /Successors wird hier etwas reingeschrieben, die Übergabe an sich an funktioniert aber.
Übergebe ich den Beleg händisch in der SelectLine , wird ein Eintrag in der Tabelle SerieCharge gebucht, und ich sehe genau wo 
der Abgang statt gefunden hat. 
Dieses Thema brennt uns extrem unter dem Nagel, da ein Kunde demnächst damit arbeiten muss. 

Json API: 
{
	"documentKindDestination":"R",
	"positions":[
		{
			"identifier":"cedcb25e-8205-4abd-b3bd-ca7ab7ef0076",
			"quantity":1.0,
			"articleNumber":"000088",
			"warehouse":"1",
			"serialNumber":"34308374"
		}
	]
}
Grüße 
Lars

**Comment by MatthiasGuse** [comment]
Das Problem lässt sich bei mir weder per MDE noch direkt per API (Swagger) nachvollziehen (Version 20.3.8). Die Tabelle der Serien/Charge wird immer um den jew. Abgang erweitert.

Welche Version setzen Sie ein?
