### ISSUE TITLE
Feldvorgaben - Kunde

### ISSUE THREAD

**Issue by Logic-Bits** [selectline-software/selectline-api#83]
Hallo,

warum werden die Benutzter Feldvorgaben beim anlegen des Kunden nicht berücksichtigt?

Danke!

**Comment by VivienSchuboth** [comment]
Guten Tag,
da diese Funktionalität schon sehr lange, vielleicht sogar seit Anbeginn der SelectLine API, existiert, kann ich Ihnen dafür auch keinen genauen Grund nennen. 
Anzumerken ist jedoch, dass die Funktionalität direkt an die Datenbank angebunden ist und damit nicht die vorhandene Funktionalität aus der Warenwirtschaft nutzt. Die Möglichkeit letztere zu nutzen, gab es damals noch nicht.

Beste Grüße,
Vivien Schuboth
