### ISSUE TITLE
Problem bei der Belegübergabe mit Teillieferungen

### ISSUE THREAD

**Issue by LukWlbr** [selectline-software/selectline-api#84]
Hallo zusammen,

bei der Belegübergabe (_/Documents/{documentKey}/Successors_) von einem Packauftrag (selbst definierter Belegtyp) zu einem Lieferschein übergebe ich nur eine Position von vielen, da ich eine Teillieferung anstrebe.

Mein Array aus _DocumentPositionStoreInformationUpdate_ enthält lediglich diese eine Position.
```
{
  "DocumentKindDestination": "0",
  "Positions": [
    {
      "Identifier": "11CC9CC6-EAEA-487F-9164-D8E08AACE914",
      "Quantity": 2.0,
      "ArticleNumber": "8011",
      "Warehouse": "100",
      "SerialNumber": "20277",
      "ExpirationDate": "2023-12-31T00:00:00.000+01:00",
    }
  ]
}
```

Dennoch werden in meinen Lieferschein alle anderen Positionen mit einer Menge von 0 übergeben.

Dies würde also bedeuten, wenn ich die 20 Positionen meines Packauftrag theoretisch einzeln übergeben würde, da ich mehrere Teillieferungen durchführe, wäre die letzte Position in 20 Lieferscheinen enthalten und das will ich natürlich nicht...

In der Dokumentation steht:
> Wird diese Eigenschaft als Array mit der Angabe von Positionsdaten angegeben, so wird eine Übergabe mit den im Array angegebenen Positionen und deren Menge durchgeführt.

In den Belegübernahmeoptionen im SelectLine habe ich auch bereits nachgeschaut, bin aber auch hier nicht fündig geworden.

Ich verwende SelectLine V20.3.6.

Beste Grüße und Vielen Dank im Voraus!

**Comment by VivienSchuboth** [comment]
Guten Tag,
diese Arbeitsweise ist uns bekannt und wird derzeit hinterfragt. Ich werde Sie benachrichtigen, wenn sich hieraus etwas ergibt.

Bis dahin kann ich Ihnen empfehlen, die nicht-angegebenen Positionen, die in diesem Beleg mit Menge 0 angelegt werden, über die SelectLine API wieder zu löschen. So sieht aktuell auch der Workflow für die SelectLine MDE aus.

Beste Grüße

**Comment by LukWlbr** [comment]
Guten Morgen,
vielen Dank für die Rückmeldung, ich hatte schon vermutet, dass ich mir einen Workaround bauen muss.

Soll ich das Ticket schließen oder wollen Sie dies offen lassen für eine eventuell spätere Rückmeldung?

Beste Grüße und ein schönes Wochenende!

**Comment by VivienSchuboth** [comment]
Wenn Sie mögen, lassen wir das Ticket erst einmal offen. Ich werde mich dann zurückmelden.

Beste Grüße und ebenfalls ein schönes Wochenende!

**Comment by VivienSchuboth** [comment]
Guten Tag,

wir haben die Problematik bei uns aufgenommen. 
Jedoch kann ich Ihnen leider noch nicht sagen, mit welcher Version hierfür eine Lösung bereitstehen wird.

Beste Grüße,
Vivien Schuboth

**Comment by VivienSchuboth** [comment]
Guten Tag,
mit der zukünftigen Version der 21.2 werden nur noch die Belegpositionen übernommen, die explizit angegeben wurden sind.

Beste Grüße,
Vivien Schuboth
