### ISSUE TITLE
Tech. Frage: SL API und Blazor

### ISSUE THREAD

**Issue by Torchok19081986** [selectline-software/selectline-api#85]
Hallo, ich habe ein Verständnisproblem . Würde den Blazor Application in C# mit der OpenAPI und SL Mobile gehen oder is es aus irgendwelchen Einschränkungen bzgl. der Umsetzung des Programms nicht möglich ?

**Comment by konrad79** [comment]
Ich wüsste nicht, was dagegen sprechen würde. Die SelectLine API ist eine normale API, von wo und mit welcher Programmiersprache oder Technologie man sie anspricht, ist eigentlich egal.

**Comment by Torchok19081986** [comment]
Ok. vielen Dank an der Stelle. Ich fragte nur deshalb nach, weil es mit Net Core bzw. Net 5.0 und der Injection von Javascript zu tun hat. Dann muss ich lediglich nur ausprobieren. 👍👍👍

**Comment by konrad79** [comment]
Sie können ja mal schreiben, ob der Versuch erfolgreich war :-)

**Comment by Torchok19081986** [comment]
kann ich mal machen, sobald ich fertig bin. letzte Frage: muss ich etwas im der IIS wegen JavaScript umstellen, sprich irgendwelche Einstellungen wie WebDAV usw?

**Comment by VivienSchuboth** [comment]
Nicht, dass wir wüssten.

Beste Grüße,
Vivien Schuboth

**Comment by VivienSchuboth** [comment]
Kleine Anmerkung: WebDAV blockiert standardmäßig alle PUT-Anfragen.
