### ISSUE TITLE
Steuer bei Belegübergabe

### ISSUE THREAD

**Issue by Lars-Mue** [selectline-software/selectline-api#86]
Hallo zusammen, 

wir haben bei einem Kunden das Problem , dass bei der Belegübergabe weiterhin der Steuerschlüssel 5% gezogen wird, obwohl im Auftrag 7 % hinterlegt sind. 
Das Problem Bestand schon einmal, da hat Sich ein Kollege von Ihnen aufgeschalten und an einer Config Datei etwas geändert. 
Das Problem ist relativ dringend, da bei unserem Kunde die Steuerschlüssel falsch kommen . 
Json
```
{
	"DocumentKindDestination":"P",
	"Positions":[
		{
			"Identifier":"FFCC62DC-78E2-4EF6-BBF2-868E3D7C3632",
			"ArticleNumber":"Artikelnummer1",
			"Quantity":10.0
		},
		{
			"Identifier":"6454EBA8-5D6D-4E98-BD81-FE59CB70A502",
			"ArticleNumber":"Artikelnummer2",
			"Quantity":1.0
		},
		{
			"Identifier":"C1A22BA8-815B-4AC1-B649-5D4EE05C340D",
			"ArticleNumber":"Artikelnumme3",
			"Quantity":1.0
		}
	]
}
```

Viele Grüße 
Lars

**Comment by ThorstenPoppe** [comment]
Hallo Lars,

wir hatten ein ähnliches Problem beim Jahreswechsel.
Die Steueranpassungen wurden im Dezember in der WaWi vorgenommen, aber die API hat im Januar immer noch den alten Steuersatz genutzt. Wir mussten den Backendmanager neu starten, damit auch der die neuen Steuersätze anwendet.
Einfach mal versuchen, ob es das Problem löst.

Viele Grüße,
Thorsten
