### ISSUE TITLE
Verständnisproblem Journal

### ISSUE THREAD

**Issue by blex97** [selectline-software/selectline-api#87]
Hallo zusammen,

ich versuche über die API die Journal-Einträge bestehender Aufträge zu ändern.

Änderungen von Journal-Einträgen an sich sind nicht das Problem, Problem ist es die richtigen Einträge bzw. die identifier zu finden.

Der Plan wäre etwa über ein Kriterium einen Auftrag zu finden, und darüber damit verknüpfte Journal-Einträge. 
Es ist unklar wie man vom Auftrag (oder einem anderen 'Document') zum Journal-Eintrag, oder auch andersrum kommt.

Aus der verfügbaren Doku, etwa https://demo.slmobile.de/demoApi/swagger/ui/index#/ und https://demo.slmobile.de/demoapi/help oder https://github.com/selectline-software/selectline-api lässt sich das bislang nicht erschliessen.

Es muss irgendwie mit JournalLinkInformationList zu tun haben, aber wie?

Vielen Dank schon mal :)

**Comment by VivienSchuboth** [comment]
Guten Morgen,
um die Journale hinsichtlich der Belegtypen und des Belegschlüssels einzuschränken, können Sie die Filtermöglichkeit an der Route zum Abfragen von Journalen nutzen. 

[Journale lesen über Swagger](https://localhost/slmobileApi/swagger/ui/index#/Journal/Journal_GetJournalList)

Für das Property "ForeignKey" steht die Record_ID des jeweiligen Datensatzes.
Im Property "Blobkey" tragen Sie bitte "QF" ein, um Journale zu einem Auftrag abzurufen.

Beste Grüße,
Vivien Schuboth
