### ISSUE TITLE
Semantic error in SelectLine.API.json

### ISSUE THREAD

**Issue by kagithd** [selectline-software/selectline-api#88]
SelectLine API 20.3.10.0

https://editor.swagger.io/

bringt folgenden fehler für die SelectLine.API.json
 
Semantic error at paths./ManualStorages/{documentNumber}
Equivalent paths are not allowed.
Jump to line 5032
Semantic error at definitions.UserRightModel.required.0
Read only properties cannot be marked as required by a schema.
Jump to line 19322
Semantic error at definitions.UserRightModel.required.1
Read only properties cannot be marked as required by a schema.
Jump to line 19323

**Comment by MatthiasGuse** [comment]
Hallo,

was versuchen Sie hier zu erreichen?

Swagger ist bereits mit der API installiert. Dazu gehen Sie in die installiert API Hilfe:

- Im Mobile Manager --> Seite Webseite die Hilfe aufrufen - "...api/help"

- Unter Grundlagen - Swagger wählen --> "Swagger Dokumentation und Testumgebung" auswählen

Das hat nichts mit der von Ihnen genannten Websiete zu tun.

Beste Grüße

**Comment by Grewamor** [comment]
Auf der Seite kann man automatisch clients für die API erstellen. Das ist schon praktisch... 😉

**Comment by kagithd** [comment]
es gibt noch einen weiteren fehler ... im Login fehlt für die  response 200 das schema,  das sollte eigentlich so wie hier aussehen 

        "/Login": {
            "post": {
                "tags": [
                    "Account"
                ],
                "summary": "Anmelden bei der API.",
                "operationId": "Account_Login",
                "consumes": [
                    "application/json",
                    "text/json",
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json",
                    "text/json"
                ],
                "parameters": [
                    {
                        "name": "model",
                        "in": "body",
                        "description": "Username und Passwort sind erforderlich",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/SelectLine.Erp.AdministrationModule.Models.Credentials"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        **"schema": {
                            "$ref": "#/definitions/SelectLine.Erp.AdministrationModule.Models.AccessTokenModel"
                        }**
                    },
                    "400": {
                        "description": "BadRequest"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "409": {
                        "description": "Conflict"
                    }

**Comment by pietzschke** [comment]
Beim openapi-generator wird folgende Fehlermeldung bei der Generierung ausgegeben:
`Validation failed. Duplicate operation id 'SerialNumber_GetSerialNumbers'

Error: Validation failed. Duplicate operation id 'SerialNumber_GetSerialNumbers'
    at o (https://apitools.dev/swagger-parser/online/js/bundle.min.js:1:79834)
    at https://apitools.dev/swagger-parser/online/js/bundle.min.js:17:231669

SyntaxError: Validation failed. Duplicate operation id 'SerialNumber_GetSerialNumbers'
    at Function.o [as syntax] (https://apitools.dev/swagger-parser/online/js/bundle.min.js:1:79834)
    at validatePath (https://apitools.dev/swagger-parser/online/js/bundle.min.js:1:6287)
    at validateSpec (https://apitools.dev/swagger-parser/online/js/bundle.min.js:1:5999)
    at SwaggerParser.validate (https://apitools.dev/swagger-parser/online/js/bundle.min.js:1:3318)
`
<img width="681" alt="Chargen," src="https://user-images.githubusercontent.com/7756693/152784304-e5f1ab7c-562f-4db2-86ba-b75e1513a1d4.png">
In der .json müsste nur von "SerialNumber_GetSerialNumbers" auf "SerialNumber_GetSerialNumber" geändert werden.

Wenn die Datei manuell erstellt wurde/aktualisiert wird, kann ich gerne dazu einen PR aufmachen.

**Comment by MatthiasGuse** [comment]
Hallo,
zur Version 22.1 werden wir eine aktualisierte Datei mit der Installation bereitstellen. 
Bitte zukünftig ein eigenes Ticket pro Problem öffnen.

Viele Grüße
