### ISSUE TITLE
Error message when creating a document position with document key = "M"

### ISSUE THREAD

**Issue by diekloope** [selectline-software/selectline-api#9]
I'm using the post Documents/M"+documentnumber+"/Positions and i got following error response:
{
  "StatusCode": "BadRequest",
  "ResponseCode": "42-036",
  "Message": "CreateDocumentErrorException",
  "Details": {
    "ResponseDetails": "Fehler beim Lagern. Offene Menge: 1",
    "ResponseType": "CreateDocumentError",
    "ErrorCode": -1
  }

I'm think that i have to send the "StoreInformation". My question regarding the storeinformation ist:
1. How can i use the storeinformation?
2. Do you have a sample for post a document position with storeinformation?

I hope you an info for me. Thanks a lot.

**Comment by VivienSchuboth** [comment]
Hello,
thanks for letting us know about your situation!
I'd love to help you, but I'm afraid this route is obsolete. 
We moved the functionality into the following route: `POST ../Documents/{documentKey}/ArticleItem`. The functionality is exactly the same.

As a result of this separation you are able to create article and shipping items as a document position.

If you need further information please visit: https://demo.slmobile.de/demoApi/Help/ApiGroup?controllerName=Document

But even this route needs store information.
Here is a simple example how you could fill the body:
```
{
  "ArticleNumber": "130004",
  "StoreInformation": [
   {
      "ArticleNumber": "130004",
      "Warehouse": "200",
      "Quantity": 3,
    }
  ]
}
```

If anything is still unclear, let me know. I’m happy to explain further.

Best regards,
Vivien

**Comment by diekloope** [comment]
Thanks for your help. 
Best regards
diekloope
