### ISSUE TITLE
Auslagerung Manuelle Lagerrung Belegtyp M

### ISSUE THREAD

**Issue by pd167** [selectline-software/selectline-api#90]
Moin zusammen,

in SelectLine selber ist die Einstellung true, dass negative Lagerungen vorgenommen werden können.
Versuche ich dieses über /ManualStorages/{manualStorageNumber}/Positions/Store bekomme ich folgende Fehlermeldung

`{
  "StatusCode": "BadRequest",
  "ResponseCode": "42-032",
  "Message": "StoreError",
  "Details": [
    {
      "Key": "00000000-0000-0000-0000-000000000000",
      "ErrorCode": 102027,
      "Detail": "Die Lagerungsmenge ist größer als der verfügbare Bestand."
    }
  ]
}`

ist es möglich dem noch einen Paramter mitzugeben oder ist es generell nicht möglich über /ManualStorages/{manualStorageNumber}/Positions/Store einen Negativen Lagerbestant zu generieren?
Sobald Bestand vorhanden ist, würde dies alles ohne Probleme funktionieren.

Viele Grüße

**Comment by MatthiasGuse** [comment]
Hallo,

die API orientiert sich hier am Funktionsumfang der Warenwirtschaft. Da in der Warenwitschaft in manuellen Lagerungen nicht in den negativen Bereich gelagert werden kann, ist das über die API auch nicht möglich.

Beste Grüße
