### ISSUE TITLE
GET ​/Articles articleListFilter.searchIn Referenzen

### ISSUE THREAD

**Issue by Grewamor** [selectline-software/selectline-api#91]
Hallo,

gibt es eine Möglichkeit, dass bei der Methode "GET​ /Articles Liest eine Liste von Artikeln" auch nach Referenzen mit dem Parameter searchIn gesucht werden kann?

![image](https://user-images.githubusercontent.com/18594343/110313719-20e5f580-8007-11eb-9a37-a270b70642c8.png)

**Comment by VivienSchuboth** [comment]
Guten Morgen,

das ist aktuell noch nicht möglich.
Es liegt vor allem daran, dass die Referenzen in einer anderen Tabelle gespeichert werden, als die Daten zu einem Artikel.

Beste Grüße,
Vivien Schuboth

**Comment by pd167** [comment]
Hallo,

ist dies mittlerweile in der neusten Version möglich?
Ich würde **ungern** 2 API Requests machen um zu filtern, ob der gesuchte Wert entweder in der Referenz oder in ManufacturerArticleNumber ist

Referenz nur via `.../slmobileApi/Articles/@SEARCHVALUE/?considerReferenceAndSerial=true`
Hst. Artikelnummer `.../slmobileApi/Articles?articleListFilter.filter=ManufacturerArticleNumber%20EQ%20@SEARCHVALUE`

**Comment by MatthiasGuse** [comment]
Hallo,

die Funktion wurde dahingehend nicht erweitert. 

Viele Grüße
