### ISSUE TITLE
Belegübergabe Datum

### ISSUE THREAD

**Issue by Lars-Mue** [selectline-software/selectline-api#92]
Hallo zusammen, 

ich habe das Problem ,dass wir bei einem Kunden Belege übergeben, welche teilweise noch 14% Mwst haben. 
Über den Endpunkt /Documents/{documentKey}/Successors
ist es leider nicht möglich, zu steuern, ob ein neues Datum vergeben wird oder nicht.
Dementsprechend erfolgt die automatische Anpassung der Steuer auf dass aktuelle Datum.

Haben wir eine Möglichkeit dass zu umgehen?
Grüße Lars

**Comment by MatthiasGuse** [comment]
Hallo,

welchen Belegtypen übergeben Sie denn hier konkret? Vielleicht können Sie ein kurzes Beispiel nennen.

Haben Sie die Handlungsempfehlungen für die Handlungsempfehlungen zum Konjunkturpaket entsprechend umgesetzt?
[https://www.selectline.de/mehrwertsteueraenderung2021/](url)

Beste Grüße

**Comment by Lars-Mue** [comment]
Hallo, 

ich übergebe einen Auftrag in einen Lieferschein. 
Der Auftrag hat das Datum 04.04.1999 und dementsprechend keine 19% Steuer. 

Übergebe ich den Beleg über den oben genannten Endpunkt in einen Lieferschein, so wird das Datum und der Steuerschlüssel automatisch angepasst und die Belegsumme stimmt logischerweise nicht mehr. 
Ich habe in Ihrer Dokumentation bis jetzt keine Möglichkeit gefunden, bei dem Endpunkt ein Belegdatum, oder Steuerprozent der Position mitzugeben.

Grüße

**Comment by MatthiasGuse** [comment]
Bei welchem Geschäftsvorfall die urprüngliche Steuer beibehalten werden darf, soll an dieser Stelle nicht beurteilt werden. 

Sie haben die Möglichkeit die Belegpositionen nach der Belegübergabe einzeln anzupassen

--- oder ---

die API generell so zu konfigurieren, dass bei einer Belegübergabe keine Anpassung der Steuer geschieht.

Dazu schauen Sie bitte in der API-Hilfe unter "Vorgabewerte für Dialoge" (ganz unten auf der Hilfeseite) und beachten den letzten Eintrag: "SteuersatzAutomatischAnpassen". Wo die Einstellung vorzunehmen ist, ist ebenfalls auf der Seite beschrieben. Bitte nach der Änderung alle Nutzer abmelden und erneut anmelden, sodass der Backenprozess neu gestartet wird.

Viel Erfolg!

**Comment by Lars-Mue** [comment]
Die Einstellungen sind dementsprechend angepasst und trotzdem wird die Steuer/das Belegdatum automatisch angepasst. 
Wir haben den Backend Manager sogar neu gestartet. 
Woran kann das noch liegen?

**Comment by MatthiasGuse** [comment]
Hallo,

da es bei mir so funktioniert, nur nochmal zur Vollständigkeit. Wichtig ist, dass alle 'SelectLine.API.Backend.exe' beendet wurden. Sie haben im Datenverzeichnis der Installation die Datei "api_standardwerte_vorgabe.json" kopiert, in "api_standardwerte.json" umbenannt und den Wert von "SteuersatzAutomatischAnpassen" aus 'false' gesetzt?
Welche Version setzen Sie ein?

**Comment by Lars-Mue** [comment]
Hallo, 

konnte das Problem nun Lösen. Trotzdem vielen Dank
