### ISSUE TITLE
Probleme bei Journal-Anhängen

### ISSUE THREAD

**Issue by davidhommel** [selectline-software/selectline-api#95]
Hallo zusammen,

Wir möchten eine Datei an einen Journaleintrag anhängen und bekommen immer
den Fehler 80-042 „Fehlerhafte Datei. Mögliche Ursache: Maximale Dateigröße überschritten „
als Antwort von der API. 
Wir haben die unterschiedlichsten Dateiformate / Content-Type Kombinationen getestet leider ohne Erfolg, weiterhin ist die maximale Dateigröße auf dem Defaultwert von 30MiB festgelegt, die zu übertragende Datei allerdings ,,nur'' 4MiB groß.
In der Dokumentation ist hier leider nichts angegeben und der Swagger bietet auch keine Beispiele bzw. einen zum Modell passenden Aufruf. 

Können Sie uns hier einen Tip geben?

**API-Antwort auf die Anfrage:**
[SLAPI_Journalfehler.txt](https://github.com/selectline-software/selectline-api/files/6121370/SLAPI_Journalfehler.txt)

**Comment by SteveSteglitz** [comment]
Hallo, 

ich habe das Ganze gerade noch mal erfolgreich mit Postman gegen die ausgelieferten Version probiert. Was mich an Ihrer Anfrage wundert, ist, dass der Content-Type im Body "application/octet-stream" ist. Hier müsste meiner Meinung nach z.B. image/png stehen. 

Probieren Sie bitte einmal den Fall mit Postman. Hier in GitHub finden Sie auch eine Postman-Collection mit allen SelectLine API Routen, die Sie importieren und verwenden können. Über Swagger-Testumgebung lassen sich keine form-data Geschichten realisieren, darum gibt es auch keine Möglichkeit Journalanhänge darüber hinzuzufügen.

Viele Grüße

**Comment by MatthiasGuse** [comment]
Problem konnte mit der Postman Collection gelöst werden.
