### ISSUE TITLE
Verständnisproblem Journal, Beziehung zu Auftrag

### ISSUE THREAD

**Issue by blex97** [selectline-software/selectline-api#96]
Hallo zusammen,

ich versuche weiter über die API die Journal-Einträge bestehender Aufträge zu ändern.

Mit der Info "QF" als Blobkey zu verwenden bekomme ich schon mal eine Teilmenge der Journale die soweit gut aussieht.

Vivien Schuboth: "Für das Property "ForeignKey" steht die Record_ID des jeweiligen Datensatzes."

Leider finde "Record_ID" nicht, nichts was so oder ähnlich heisst wenn ich mir etwa die JSON-Daten aller Aufträge ansehe.

Meine einzige Referenz ist was im Auftrag unter "Number" aufgeführt wird, also etwas wie "AU170001".

Es scheint nicht dem Inhalt von "BELEG_ID" zu entsprechen was in der UI beim Auftrag zu sehen ist, aber wieder nicht in den JSON Daten enthalten.

Wie kann ich mit "Number" (oder einem anderen in der UI ablesbaren) Identifier zur Record_ID kommen?

Wo könnte ich die Info "QF" als "Blobkey" zu verwenden finden und generell mehr Doku?

Vielen Dank schon mal :)

**Comment by VivienSchuboth** [comment]
Guten Morgen,

Sie haben Recht. Die Record_ID wird für einen Beleg nicht zur Verfügung gestellt.
Dadurch ist die Abfrage von Journalen zu einem Beleg nicht möglich.

Daher haben wir beschlossen, die SelectLine API, um die Abfrage von Journalen zu einem Beleg, zu erweitern.
Sobald ich weiß, zu wann Sie mit der Funktionalität rechnen können, melde ich mich noch einmal.

Beste Grüße,
Vivien Schuboth

**Comment by VivienSchuboth** [comment]
Guten Tag,
mit der Hotfix-Version 21.1.1 steht Ihnen eine Funktionalität im Bereich der Belege zur Verfügung, die Ihnen mithilfe des Belegtypen und der Belegnummer Ihre Journale abruft.

Beste Grüße,
Vivien Schuboth

**Comment by blex97** [comment]
Hallo Frau Schuboth,

vielen Dank für die Rückmeldung und den schnellen Fix. Wir haben den Dienstleister gebeten die Version einzuspielen, können daher im Moment noch nicht testen.

Wäre weiterhin dankbar für Hinweise zu
"Wo könnte ich die Info "QF" als "Blobkey" zu verwenden finden und generell mehr Doku?"
und weitere Quellen zur API-Nutzung.

Vielen Dank für Ihre Unterstützung

**Comment by MatthiasGuse** [comment]
Hallo,

die Version 21.1.1 wird voraussichtlich erst in dieser Woche zur Verfügung gestellt.

Der Blobkey ist für Ihren Zweck dann nicht mehr relevant. Blobkeys stehen nicht als Information in der API bereit. Der jeweilige Blobkey zu einer Tabelle kann bei Bedarf in den Vorgabewerten der Warenwirtschaft abgelesen werden ("Kürzel"). 

Neben der API Dokumentation und den Codebeispielen hier im Github, stehen Ihnen Swagger und eine Postman Collection zur Verfügung. Alternativ dazu haben Sie die Möglichkeit den kostenpflichtigen Support zu nutzen oder unser Webinar zu besuchen:
[https://www.selectline.de/veranstaltungen/api-grundlagenkurs-4/](url)

Viele Grüße

**Comment by blex97** [comment]
Hallo,

die Version  21.1.1 steht jetzt zur Verfügung, leider kann ich die Verwendung der API-Doku https://demo.slmobile.de/demoapi/help mit Stand 21.1. nicht entnehmen.

Können Sie mir die Verwendung hier beschreiben bzw. mitteilen wann die Doku die Änderungen enthalten wird?

Vielen Dank für ihre Unterstützung.
