### ISSUE TITLE
Spaltenname aus Customer 

### ISSUE THREAD

**Issue by Torchok19081986** [selectline-software/selectline-api#97]
Hallo, ich entwickle gerade ein app auf Basis der Mobile API und würde gern wissen , wo ich nachschauen , wie die Spalten im Db bzw. im Swagger heißen ? Ich versuche die Daten aus API für customer / supplier mit MVVM ans Ausgangsfenster zu binden, aber die Daten für die Spalten weichen  von der Anzegeinnamen im WaWi wie z.B.  nummer und Number für Kudnenummer.

**Comment by MatthiasGuse** [comment]
Hallo,

Sie finden die Informationen in der installierten API Hilfe unter der jeweiligen Route. Die Feldnamen der Datenbank sind hier in eckigen Klammern genannt. Hierzu sollte man wissen, dass die Ansichten in der Warenwirtschaft ebenfalls aus mehreren Tabellen zusammengesetzt sind. Im ebenfalls installierten Swagger finden Sie in der Regel die Namen im gezeigten Beispiel. Hier allerdings nur den englischen Feldnamen der API über den nicht unbedingt ein Bezug zum Feldnamen der Warenwirtschaft erkennbar sein muss.
Beste Grüße

**Comment by Torchok19081986** [comment]
Hallo Herr Guse, vielen Dank für die Hilfe und Info.  Ich weiß leider nicht, ob es dazu gehört, aber ich frage trotzdem. 
Laut der Beschreibung inheriten Customer class aus BussinesPerson und diese wiederrum von den Person. Ich kann aber nur die customer or Supplier via Request deserliaiseren (mit JSON). Wie bekomme die Daten aus Person, um z.B. diese in einem neuen Fenster anzuzeigen ? Die Idee ist , wichtige Stammdaten wie Email, Strasse, PLZ usw ., mit der Kundendaten darzustellen.

**Comment by MatthiasGuse** [comment]
Die Routen zum Customer / Supplier liefern bereits die Adressdaten ("Address") und die Kontaktdaten ("Contact"). Die Beispiele und die Dokumentation sollten Ihnen hier genügen um diese Informationen verwenden zu können.

Alles Weitere müsste man im Rahmen des kostenpflichtigen Supports oder eines Webinars [(klick)](https://www.selectline.de/veranstaltungen/api-grundlagenkurs-4/) klären.
