### ISSUE TITLE
Belegübergabe 

### ISSUE THREAD

**Issue by Lars-Mue** [selectline-software/selectline-api#98]
Hallo zusammen,

mir macht die Belegübergabe erneut Probleme. 
Ich möchte hierbei betonen, das jede händische Übergabe in der SelectLine oder Probleme funktioniert. 
Beispiel 1 : 
In der ersten Situation sind immer die gleiche Artikelnummer( nur unterschiedliche Menge) als Menge vorhanden, und ansonsten unterscheidet nur die Bezeichnung die einzelnen Positionen. Zwei Positionen sind allerdings auch was die Bezeichnung angeht komplett gleich. (Pos 1,7)
Hier führt die API beide Positionen beim Übergeben zusammen, und lässt den Ausgangsbeleg ( Beleg Typ F) offen stehen da eine der beiden gleichen Positionen nun mit der Menge 0 im Lieferschein geführt werden. 
Anbei eine Beispiel JSON : 
`{
  "documentKindDestination": "L",
  "positions": [
    {
      "identifier": "f584c5ef-4282-466d-ae93-2187e5356019",
      "quantity": 3,
      "articleNumber": "DIV",
      "warehouse": "WW-Laden",
      "serialNumber": ""
    },
    {
      "identifier": "44417d22-f146-4d5f-8494-c2901d14727c",
      "quantity": 1,
      "articleNumber": "DIV",
      "warehouse": "Laden",
      "serialNumber": ""
    },
    {
      "identifier": "167a12c1-8163-48a3-8462-37eced4a833d",
      "quantity": 3,
      "articleNumber": "DIV",
      "warehouse": "Laden",
      "serialNumber": ""
    },
    {
      "identifier": "47580d43-b3eb-4ee7-ad93-a991b7fefa26",
      "quantity": 1,
      "articleNumber": "DIV",
      "warehouse": "Laden",
      "serialNumber": ""
    },
    {
      "identifier": "f584c5ef-4282-466d-ae93-2187e5356019",
      "quantity": 3,
      "articleNumber": "DIV",
      "warehouse": "Laden",
      "serialNumber": ""
    },
    {
      "identifier": "3683828d-de8a-424b-a02a-0e255bbadf91",
      "quantity": 2,
      "articleNumber": "DIV",
      "warehouse": "Laden",
      "serialNumber": ""
    },
    {
      "identifier": "10e64c53-d20e-4e51-b98b-4a0a670f8233",
      "quantity": 3,
      "articleNumber": "DIV",
      "warehouse": "Laden",
      "serialNumber": ""
    }
  ]
}
`
 Beispiel 2  : 

Ist in dem Ausgangsbeleg eine Positionen mit einem Negativen Wert vorhanden, so wird diese Übergeben allerdings ohne Menge. 
Auch hier bleibt der Beleg offen stehen, da die Position nicht sauber übergeben worden ist, 

Ich bekomme bei beiden Beispielen keine Fehlermeldung zurückgegeben,

Version : 20.3.10

Vielen Dank im Voraus

Grüße

**Comment by Lars-Mue** [comment]
Hallo zusammen, 

konnten Sie diesbezüglich schon etwas herausfinden? 
Grüße

**Comment by MatthiasGuse** [comment]
Hallo,

leider lässt sich das mit dem abgebildeten Beispiel nicht verständlich nachbilden. Könnten Sie ein einfaches Beispiel schildern? Prinzipiell reichen der Belegtyp und ein beispielhafter Inhalt des Ausgangsbelegs.

Viele Grüße

**Comment by Lars-Mue** [comment]
Hallo, 

ich probiere das nochmal genauer auszuführen.
In meinem Beleg sind 6 Positionen vorhanden von denen 2 exakt identisch sind. 
 1 -  Bildschirm 
 1 -  Kabel
 1 -  Maus 
 1 - Tastatur
 1 - Rechner 
 1 - Bildschirm

Die API übergibt alle Positionen sauber, bis auf die welche exakt übereinstimmen. Diese werden entweder zusammengefasst 
sieht dann übergeben im Lieferschein so aus : 
 2 -  Bildschirm 
 1 -  Kabel
 1 -  Maus 
 1 - Tastatur
 1 - Rechner 
 0 - Bildschirm
 
oder so : 

 1 -  Bildschirm 
 1 -  Kabel
 1 -  Maus 
 1 - Tastatur
 1 - Rechner 
 0 - Bildschirm

Problem ist nun, dass die zweite Position ( Bildschirm) jeweils mit Menge 0 geführt wird und daher der Ausgangsbeleg als noch offen dasteht weil eine Position nicht erledigt ist. 

Der zweite Punkt ist eine Position mit einem negativen Wert. 
Das ist zum Beispiel so : 

1 - Bildschirm 14,99€
1 - TreueRabatt - 5.99€

die -5.99 werden ohne Menge übergeben, und so bleibt auch dieser Beleg offen stehen. 

Ich hoffe ich konnte das Ihnen etwas besser erklären nun. 

Grüße

**Comment by MatthiasGuse** [comment]
So war es verständlich. Danke!

Ich habe das mit der Version 21.1.1 nachgestellt und konnte keines der beschriebenen Verhalten nachvollziehen.

Belege:
![07-04-_2021_08-54-02](https://user-images.githubusercontent.com/31447000/113823599-2148ec00-977f-11eb-9dc6-7a73da339f75.png)
API JSON:
`{
	"documentKindDestination": "L",
	"positions": [
		{
			"identifier": "E900ACE7-A0C0-4D23-B71A-B20161796906",
			"quantity": 1,
			"articleNumber": "100001",
			"warehouse": "100"
		},
		{
			"identifier": "EE357F49-EAEE-41C0-938E-29C01B60F905",
			"quantity": 1,
			"articleNumber": "100005",
			"warehouse": "100"
		},
		{
			"identifier": "C75CD37E-9D02-4CAD-82DD-738BBEDC3AEB",
			"quantity": 1,
			"articleNumber": "100003",
			"warehouse": "100"
		},
		{
			"identifier": "0EC6C8D3-76FC-45A8-B26A-2A739AE843A6",
			"quantity": 1,
			"articleNumber": "100002",
			"warehouse": "100"
		},
		{
			"identifier": "7E9D867F-9E8E-49AD-BC05-D21EACA1622C",
			"quantity": 1,
			"articleNumber": "100006",
			"warehouse": "100"
		},
		{
			"identifier": "{40E36964-F9D0-4ECE-AE8E-B0BEF9CAF6F6}",
			"quantity": 1,
			"articleNumber": "100001",
			"warehouse": "100"
		}
	]
}`

Ebenfalls wird eine Position mit einem negativen Preis korrekt übergeben.

Evtl. testen Sie das Verhalten mit der Version 21.1 erneut. (Konkrete Fehlerbehebungen sind mir hierzu allerdings nicht bekannt.) Falls Sie das nachvollziehbar reproduzieren können, melden Sie sich bitte nocheinmal. 

Viele Grüße
